### ISSUE TITLE
Cloud, VPS, and dedicated server providers

### ISSUE THREAD

**Issue by djzort** [nylira/prism-break#100]
_title edited by @nylira 2013-08-15_

I think, personally, that the assumption that AWS, Rackspace, HP Cloud etc are in any way 'safe' is a dangerous assumption. Who has access to the live systems of my business or personal software running on these services? Who has access to snooping data in transit? Who has access to whats in RAM or on HDD?

Are there alternatives that provide some or any assurance of data security both on disk, in memory and in transit?

**Comment by Atavic** [comment]
I see the *safe countries* question appearing in many issues. I think it's a false dilemma, as a connection isn't almost never direct to the server your browser is pointing to. On the net there are many hops (middle targets that the connection's request passes thru before reaching the queries server) and if one had to exclude USA, UK, CAN, AUS and NZ then most of the net will be unreachable. For this issue the best answer is an anonymous OS or a live iso with no persistence.

**Comment by Wolf480pl** [comment]
@Atavic you can make it harder for the countries in the middle to wiretap by using encryption, etc. 

However, when you rent a server somewhere, that country can (directly, or through your provider by legally pressuring them) obtain physical access to the server you're renting and dump all your keys from RAM, or mess around with the server in many other way. Defending against that would require use of equipping the server with physical intrusion sensors and/or using TPMs, etc. and there's little sense doing that unless you own the physical server. And they can still take your server down if they want.

So the list of safe countries would be more of a "places to safely store your data" than "places that won't tap on your connection".

**Comment by Hillside502** [comment]
Internet censorship and **surveillance** by country
https://en.wikipedia.org/wiki/Internet_censorship_and_surveillance_by_country

**Comment by Wolf480pl** [comment]
Some information about legal protections of personal data (including laws governing when and how such data can be seized) and about data retention policies would be helpful too.

**Comment by Hillside502** [comment]
Technological Sovereignty
Data Sovereignty
Information Sovereignty
https://en.wikipedia.org/wiki/Technological_Sovereignty

Information privacy law
https://en.wikipedia.org/wiki/Information_privacy_law

Privacy law
https://en.wikipedia.org/wiki/Privacy_law

Data retention
https://en.wikipedia.org/wiki/Data_retention

**Comment by strugee** [comment]
So, I admittedly have not read this entire thread, only the comments in the last couple days. My principal concern with this point is our limited resources. It seems to me that the primary question here is where the servers are hosted, but I don't know that this community has the resources to actually research and keep up with all the relevant laws, worldwide - especially since legal stuff can get pretty complex in ways that we (PRISM Break) as a technical community aren't skilled at dealing with. Plus you're always depending on the provider's good-faith respect of the law, anyway. So I feel like maybe we should just declare this out-of-scope, similar to how we declared hardware out-of-scope. Thoughts?

**Comment by Atavic** [comment]
The answer is to host a service for your own if possible. If not, we're dealing with privacy and encryption is a good measure (problem about which kind of encryption is another issue).
