### ISSUE TITLE
Remove or modify the inclusion of Cyanogenmod due to recent changes in the privacy policy that expand data collection.

### ISSUE THREAD

**Issue by gayse** [nylira/prism-break#1005]
I understand there has been discussion before on the inclusion of Cyanogenmod (#903, #726, #654), but I believe that this new development warrants a new issue to be created and falls in line with the project guidelines due to a significant change in the development of the software.

Cyanogenmod's privacy policy has been updated recently, and the new privacy policy contains troubling language that I believe goes against the site's mission to promote free and ethical software.

https://cyngn.com/legal/privacy-policy/

https://cyngn.com/blog/2014/06/privacy-policy-and-terms-of-use-update/

> "We may collect information such as occupation, language, zip code, area code, unique device identifier, location, and the time zone where your product or device is used so that we can better understand customer behavior and improve our products, services, and advertising."
> 
> "When you create an account (such as a CyanogenMod Account or a CyanogenMod Forum Account), register your devices or products, purchase a device or product, download a software update, contact us or participate in an online survey, we may collect a variety of information, including your name, mailing address, phone number, email address, contact preferences, and credit card information."
> 
> "Third Parties - As Cyanogen Inc. continues to expand, they enter agreements with the likes of Google and other parties for services seen on retail hardware. Language has been added to reflect both the Terms and Privacy Policy as it relates to third parties."
> 
> "Cyanogen websites, products, applications, and services may contain links to third-party websites, products, and services. Our products and services may also use or offer products or services from third parties. Information collected by third parties, which may include such things as location data or contact details, is governed by their privacy practices. We encourage you to learn about the privacy practices of those third parties."

The privacy policy does not contain any language allowing the user to drop-out of this monitoring, unlike earlier versions of the policy and software. A developmental shift away from privacy and security has been enough to get LMDE removed (#805), and as such I believe the precedent set in that issue should also be applied to this one as well.

Thanks everybody for their time and consideration of this issue, I understand pull requests are preferred here and I will try my hand at creating one shortly.

**Comment by alerque** [comment]
This issue is obsolete and can be closed. Cyanogen has been removed.
