### ISSUE TITLE
OS X File encryption - GPG Tools? 

### ISSUE THREAD

**Issue by goodc0re** [nylira/prism-break#1013]
Maybe people might be looking for truecrypt alternatives.  

Is there a reason for GPG Tools not being listed under file encryption for OS X? 
(GPG Tools is listed under email encryption for OS X)

**Comment by yegortimoshenko** [comment]
GPG Tools can't be used for volume encryption, only for single file encryption, and typically such files are encrypted using recipient's public key.

Using your own public key is also possible, but public key cryptography is significantly weaker than, say, AES, and more susceptible to brute force via a quantum computer, that applies both to RSA and ed25519.

Oh, and also it's terribly slow.

There are better options for file encryption, that don't leak metadata such as file names, or even existence of encrypted data (like plausible deniability provided by TrueCrypt).

**Comment by strugee** [comment]
> public key cryptography is significantly weaker than, say, AES

It is? Why? I agree with your comment, this is just a curiosity

**Comment by yegortimoshenko** [comment]
Because public key cryptography relies on mathematical concepts like factorization, or elliptic curves, that are more susceptible to analysis than shifts used by block ciphers.

It doesn't mean it's weak, it only means it's weaker, usually more complex in implementation, and much slower in practice to achieve the same security.

**Comment by alerque** [comment]
@strugee What @yegortimoshenko said is true, especially the bit about speed. The algorithms used in public key cryptography are typically several orders of magnitude slower to run than block and stream ciphers. In fact the former is rarely used to encrypt large amounts of data, and speed is a major part of the reason for that. Almost all pubic key encryption schemes in common use use the public key methods only to negotiate a safe key to use for the rest of the operation using a block or stream cipher.
