### ISSUE TITLE
Add Android App Pry-Fi

### ISSUE THREAD

**Issue by begleysm** [nylira/prism-break#1017]
After reading about the iOS8 update that randomizes the MAC during active network searches I did a little googling for an Android equivalent.  I downloaded and installed Pry-Fi which is very simple and appears to work as intended.

This program randomizes your MAC address while you search for Wi-Fi networks.  If desired, it can be configured to randomize your MAC while you are on a Wi-Fi network (and disabled for others).

Thoughts?

https://play.google.com/store/apps/details?id=eu.chainfire.pryfi

**Comment by yegortimoshenko** [comment]
Suggested app is proprietary, safe to close.
