### ISSUE TITLE
Add ReactOS / Windows 1st recommend

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1018]
Windows ----> Linux : Difficult (Windows software won't work, Can't read NTFS, Network issue, etc etc)
Windows ----> ReactOS (Easy! Windows Open Source Edition!!)

Hey guys, I can understand all of you want people to move into Linux. I agree.
However, seems like many people STILL using Windows XP, and Windows 8.

Linux is good for server, but not for desktop.
Please add ReactOS, people using xp will move into it.

(Me? 100% Linux.)
# 

WEBPAGES (thanks Draxler!)
http://www.reactos.org/
https://en.wikipedia.org/wiki/React_os

DOWNLOAD
http://sourceforge.net/projects/reactos/files/ReactOS/0.3.16/ReactOS-0.3.16-REL-iso.zip/download

Windows = Microsoft Backdoor installed
ReactOS = No backdoor, open source, stable(IMO)

**Comment by aleksandar-todorovic** [comment]
> ReactOS 0.3.17 is still under heavy development (alpha stage) and is not ready for everyday use.

I think that this point is pretty much enough to close this issue for now. There's no point of including an alpha version of something as important as an operating system.

**Comment by thomhastings** [comment]
+1
