### ISSUE TITLE
automated creation of translation stubs

### ISSUE THREAD

**Issue by ThomasWaldmann** [nylira/prism-break#1026]
if a new entry is added to en-projects.json it seems that currently there is no automated means to add the same new entry to all other languages, so translators can translate the new entries.

it would be nice to have a Makefile target that automatically updates a non-english file with entries from the english file - I guess the slug could be used as unique key to find missing ones easily.

also, the docs should be updated so if somebody adds a new project, he also runs the "make stubs".

**Comment by jeremyn** [comment]
After creating the translation entries for pull request #1526 manually, I agree with this issue.

**Comment by strugee** [comment]
See also #1627 for anther approach to this problem

**Comment by strugee** [comment]
Closing since #1627 has now landed.
