### ISSUE TITLE
Add Cyberfox instead of Firefox / Remove firefox

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1031]
Firefox make a connection to *.mozilla.com automatically(by default, without add-ons).
The data which Firefox send includes considerable amount of privacy information.

In version 30.0, Firefox start urging users to use "Firefox Sync", which is COMPLETELY proprietary system.
All data(history, bookmarks, settings, etc) goes to Mozilla's server.

3 REASONS WHY I HATE FOX:
1. Connect to .mozilla.com / .firefox.com AUTOMATICALLY
2. Even you choose not to help telemetary, healthreport, whatever, FIREFOX COLLECT YOUR ACTIVITY EVERYTIME.
3. They always enable some dangerous APIs.

> (profile directory)/
> minidumps
> startupCache
> sessionstore.js
> *.sqlite

at least... (too many to show me, do your own research)
>
browser.search.suggest.enabled
app.update.service.enabled
dom.gamepad.enabled
dom.battery.enabled
dom.network.enabled
dom.vibrator.enabled
dom.voicemail.enabled
dom.telephony.enabled
dom.storage.enabled
geo.enabled
geo.wifi.uri
network.websocket.enabled
network.http.spdy.enabled (SPDY is developed by GOOGLE)
places.history.enabled
social.remote-install.enabled
social.toast-notifications.enabled
device.sensors.enabled
device.storage.enabled
dom.idle-observers-api.enabled (Watch your screen when you're AFK lol)
full-screen-api.pointer-lock.enabled
>

Why prism-break doesn't have "text browser"(with Adblock add-on)? It's clean and simple :P

**Comment by GreenLunar** [comment]
I agree with @ghost.

Firefox, by default, also send data to Google* for every webpage (or, maybe, only domain) being visited by user, in order to "check" whether a website is "malicious".  This can be disabled in `about:config` after displaying to user a scary dialog.

*maybe provider has changed since the time I found out about this.

To me, they are:
Mozilla Firefox RAM Funker

**Comment by Zegnat** [comment]
> Firefox, by default, also send data to Google* for every webpage (or, maybe, only domain) being visited by user, in order to "check" whether a website is "malicious". 

Are you talking about safe browsing? That was [previously discussed](https://github.com/nylira/prism-break/issues/804#issuecomment-31606923) and no: Firefox does not send the URL for every webpage. (Seriously people, am I the only one who read the Safe Browsing protocol specification?!)

**Comment by GreenLunar** [comment]
Mozilla should prompt end-users about this, instead of hiding it in `about:config`.

**Comment by Zegnat** [comment]
Again, are you talking about safe browsing? Safe browsing can be turned off through the default settings panel, I even showed a screenshot of the options in #804. Nothing is hidden, it has just been made opt-out rather than opt-in.

If you are thinking of something else please set me right. But if it is safe browsing you are talking about read #804.

**Comment by GreenLunar** [comment]
> Again, are you talking about safe browsing?

Yes.

**Comment by Zegnat** [comment]
> Should we add a help page about thi kind of settings?

It was early on decided by @nylira that PRISM Break would not host help pages or guides. It is hard enough to keep the list semi-up-to-date with what’s going on with all the software, let alone guides. We will link to guides if they are found somewhere.

**Comment by nodiscc** [comment]
@Zegnat I originally intended to work on commenting my own Firefox `prefs.js` to explain what privacy-related options do, and let users choose if they want to edit theirs, but apparently https://github.com/pyllyukko/user.js already does a great job at this. Would you be ok to link to this project on the Firefox page?

Does this need a separate issue?

**Comment by Zegnat** [comment]
@nodiscc, that seems like something pretty new, so please do open a new issue.

I will close this one as it has been spinning out of control for a while. We will not be adding Cyberfox.
