### ISSUE TITLE
Add censurfridns.dk?

### ISSUE THREAD

**Issue by anthologist** [nylira/prism-break#1033]
Here is the DNS: http://www.censurfridns.dk/
FAQ says nothing is logged: http://blog.uncensoreddns.org/en/faq
What do you think about it?

**Comment by yegortimoshenko** [comment]
UncensoredDNS indeed does have DNSCrypt and even DNS over TLS.

Unlike OpenNIC, UncensoredDNS does not come with weird top-level domains, has strict no-logging policy, and supports every modern DNS protocol.

I think it's a very good option and would be great to have on PRISM Break.
