### ISSUE TITLE
Riseup Networks No Longer Accepting Requests

### ISSUE THREAD

**Issue by a6286224** [nylira/prism-break#1037]
Apparently Riseup Networks no longer allows signups. I tried signing up for an account about a month ago and the ticket was closed without explanation.

After asking a few times if the ticket had been denied (opening the ticket in the process) the ticket was subsequently closed each time without comment.

I got bounce emails in the ticket comments saying my message came from an invalid sender, but I used the web interface, so I don't know what they meant. Point being, I'm under the cynical impression they've been compromised.

**Comment by gigjaskula** [comment]
If anyone can send me an invite code on riseup I would be so thankful. I already have one but you need to have 2 codes. My email is gis10@hi.is

**Comment by nylira** [comment]
> Note that we are not allowed to give out invite codes to people we do not know. I would urge you to get active within existing communities that make use of Riseup if invites are the way to go.

This is not the right place to request Riseup invitations.

**Comment by SculMave** [comment]
Can you give me invite codes of Riseup ?

**Comment by SculMave** [comment]
@NationalSpyAgent  Can you give me invite codes of Riseup ?  this is my email 1004938062@qq.com
