### ISSUE TITLE
[Discussion] Why everyone still trust Google? Are you insane?

### ISSUE THREAD

**Issue by googlemustdie** [nylira/prism-break#1038]
Google just announce new devices:

Titanium collection
Android One
Android TV
Gear Live
LG G Watch
Moto 360

I never forgive Google. Until I die.
I can't believe WHY americans, who respect "freedom", are still trust and being a good google dog.

How about you? Do you still want to buy those privacy-invaders?

--------------------------
FYI, here's a google IP range. Kill them using ipset(iptables);
SOURCE CODE: http://pastebin.com/V5FVGwi8
	

    Research prefix for APNIC Labs(AS15169):1.0.0.0-1.0.0.255
    Research prefix for APNIC Labs(AS15169):1.1.1.0-1.1.1.255
    APNIC Debogon Project(AS15169):1.2.3.0-1.2.3.255
    Google Inc.(AS15169):8.8.4.0-8.8.4.255
    Google Inc.(AS15169):8.8.8.0-8.8.8.255
    Google Inc.(AS15169):8.15.202.0-8.15.202.255
    Google Inc.(AS15169):8.34.208.0-8.34.215.255
    Google Inc.(AS15169):8.34.216.0-8.34.223.255
    Google Inc.(AS15169):8.35.192.0-8.35.199.255
    Google Inc.(AS15169):8.35.200.0-8.35.207.255
    Google Inc.(AS15169):23.236.48.0-23.236.63.255
    Google Inc.(AS15169):23.251.128.0-23.251.159.255
    Google Inc.(AS15169):64.233.160.0-64.233.191.255
    Google Inc.(AS15169):64.233.160.0-64.233.160.255
    Google Inc.(AS15169):64.233.164.0-64.233.164.255
    Google Inc.(AS15169):64.233.165.0-64.233.165.255
    Google Inc.(AS15169):64.233.168.0-64.233.168.255
    Google Inc.(AS15169):64.233.171.0-64.233.171.255
    Google Inc.(AS15169):64.233.172.0-64.233.172.255
    (AS15169):64.233.173.0-64.233.173.255
    Google Inc.(AS15169):66.102.0.0-66.102.15.255
    Google Inc.(AS15169):66.102.2.0-66.102.2.255
    Google Inc.(AS15169):66.102.3.0-66.102.3.255
    Google Inc.(AS15169):66.102.4.0-66.102.4.255
    Google Inc.(AS15169):66.249.64.0-66.249.95.255
    Google Inc.(AS15169):66.249.64.0-66.249.64.255
    Google Inc.(AS15169):66.249.65.0-66.249.65.255
    Google Inc.(AS15169):66.249.66.0-66.249.66.255
    Google Inc.(AS15169):66.249.67.0-66.249.67.255
    Google Inc.(AS15169):66.249.69.0-66.249.69.255
    Google Inc.(AS15169):66.249.70.0-66.249.70.255
    Google Inc.(AS15169):66.249.72.0-66.249.72.255
    Google Inc.(AS15169):66.249.73.0-66.249.73.255
    Google Inc.(AS15169):66.249.74.0-66.249.74.255
    Google Inc.(AS15169):66.249.76.0-66.249.76.255
    Google Inc.(AS15169):66.249.77.0-66.249.77.255
    Google Inc.(AS15169):66.249.78.0-66.249.78.255
    Google Inc.(AS15169):66.249.79.0-66.249.79.255
    Google Inc.(AS15169):66.249.80.0-66.249.80.255
    Google Inc.(AS15169):66.249.81.0-66.249.81.255
    Google Inc.(AS15169):66.249.83.0-66.249.83.255
    Google Inc.(AS15169):66.249.84.0-66.249.84.255
    Google Inc.(AS15169):66.249.85.0-66.249.85.255
    Google Inc.(AS15169):66.249.88.0-66.249.88.255
    Google Inc.(AS15169):66.249.89.0-66.249.89.255
    Google Inc.(AS15169):66.249.90.0-66.249.90.255
    Google Inc.(AS15169):66.249.91.0-66.249.91.255
    Google Inc.(AS15169):66.249.92.0-66.249.92.255
    Google Inc.(AS15169):66.249.93.0-66.249.93.255
    Google Inc.(AS15169):70.32.128.0-70.32.159.255
    Google Inc.(AS15169):70.32.144.0-70.32.144.255
    Google Inc.(AS15169):70.32.148.0-70.32.149.255
    Google Inc.(AS15169):72.14.192.0-72.14.255.255
    Google Inc.(AS15169):72.14.208.0-72.14.209.255
    Google Incorporated(AS15169):72.14.225.0-72.14.225.255
    Google Incorporated(AS15169):72.14.228.0-72.14.228.255
    Google Inc.(AS15169):72.14.244.0-72.14.245.255
    Google Inc.(AS15169):74.125.0.0-74.125.255.255
    Google Inc.(AS15169):74.125.16.0-74.125.16.255
    Google Inc.(AS15169):74.125.17.0-74.125.17.255
    Google Inc.(AS15169):74.125.18.0-74.125.18.255
    Google Inc.(AS15169):74.125.19.0-74.125.19.255
    Google Inc.(AS15169):74.125.20.0-74.125.20.255
    Google Inc.(AS15169):74.125.21.0-74.125.21.255
    Google Inc.(AS15169):74.125.22.0-74.125.22.255
    Google Inc.(AS15169):74.125.23.0-74.125.23.255
    Google Inc.(AS15169):74.125.24.0-74.125.24.255
    Google Inc.(AS15169):74.125.25.0-74.125.25.255
    Google Inc.(AS15169):74.125.26.0-74.125.26.255
    Google Inc.(AS15169):74.125.28.0-74.125.28.255
    Google Inc.(AS15169):74.125.29.0-74.125.29.255
    Google Inc.(AS15169):74.125.30.0-74.125.30.255
    Google Inc.(AS15169):74.125.31.0-74.125.31.255
    Google Inc.(AS15169):74.125.36.0-74.125.36.255
    Google Inc.(AS15169):74.125.37.0-74.125.37.255
    Google Inc.(AS15169):74.125.40.0-74.125.40.255
    Google Inc.(AS15169):74.125.41.0-74.125.41.255
    Google Inc.(AS15169):74.125.42.0-74.125.42.255
    Google Inc.(AS15169):74.125.43.0-74.125.43.255
    Google Inc.(AS15169):74.125.45.0-74.125.45.255
    Google Inc.(AS15169):74.125.54.0-74.125.55.255
    Google Incorporated(AS15169):74.125.58.0-74.125.58.255
    Google Incorporated(AS15169):74.125.63.0-74.125.63.255
    Google Inc.(AS15169):74.125.68.0-74.125.68.255
    Google Inc.(AS15169):74.125.70.0-74.125.70.255
    Google Inc.(AS15169):74.125.72.0-74.125.72.255
    Google Inc.(AS15169):74.125.73.0-74.125.73.255
    Google Inc.(AS15169):74.125.74.0-74.125.74.255
    Google Inc.(AS15169):74.125.76.0-74.125.76.255
    Google Inc.(AS15169):74.125.88.0-74.125.89.255
    Google Inc.(AS15169):74.125.90.0-74.125.91.255
    Google Incorporated(AS15169):74.125.116.0-74.125.116.255
    Google Incorporated(AS15169):74.125.117.0-74.125.117.255
    Google Incorporated(AS15169):74.125.118.0-74.125.118.255
    Google Incorporated(AS15169):74.125.119.0-74.125.119.255
    Google Incorporated(AS15169):74.125.121.0-74.125.121.255
    Google Incorporated(AS15169):74.125.122.0-74.125.122.255
    Google Inc.(AS15169):74.125.128.0-74.125.128.255
    Google Inc.(AS15169):74.125.129.0-74.125.129.255
    Google Inc.(AS15169):74.125.130.0-74.125.130.255
    Google Inc.(AS15169):74.125.131.0-74.125.131.255
    Google Inc.(AS15169):74.125.132.0-74.125.132.255
    Google Inc.(AS15169):74.125.135.0-74.125.135.255
    Google Inc.(AS15169):74.125.136.0-74.125.136.255
    Google Inc.(AS15169):74.125.137.0-74.125.137.255
    Google Inc.(AS15169):74.125.138.0-74.125.138.255
    Google Inc.(AS15169):74.125.142.0-74.125.142.255
    Google Inc.(AS15169):74.125.143.0-74.125.143.255
    Google Inc.(AS15169):74.125.176.0-74.125.176.255
    Google Inc.(AS15169):74.125.177.0-74.125.177.255
    Google Inc.(AS15169):74.125.178.0-74.125.178.255
    Google Inc.(AS15169):74.125.180.0-74.125.180.255
    Google Inc.(AS15169):74.125.181.0-74.125.181.255
    Google Inc.(AS15169):74.125.182.0-74.125.182.255
    Google Inc.(AS15169):74.125.183.0-74.125.183.255
    Google Inc.(AS15169):74.125.184.0-74.125.184.255
    Google Inc.(AS15169):74.125.185.0-74.125.185.255
    Google Inc.(AS15169):74.125.186.0-74.125.186.255
    Google Inc.(AS15169):74.125.187.0-74.125.187.255
    Google Inc.(AS15169):74.125.188.0-74.125.188.255
    Google Inc.(AS15169):74.125.189.0-74.125.189.255
    Google Inc.(AS15169):74.125.190.0-74.125.190.255
    Google Inc.(AS15169):74.125.191.0-74.125.191.255
    Google Inc.(AS15169):74.125.192.0-74.125.192.255
    Google Inc.(AS15169):74.125.193.0-74.125.193.255
    Google Inc.(AS15169):74.125.194.0-74.125.194.255
    Google Inc.(AS15169):74.125.195.0-74.125.195.255
    Google Inc.(AS15169):74.125.196.0-74.125.196.255
    Google Inc.(AS15169):74.125.198.0-74.125.198.255
    Google Inc.(AS15169):74.125.200.0-74.125.200.255
    Google Inc.(AS15169):74.125.201.0-74.125.201.255
    Google Inc.(AS15169):74.125.203.0-74.125.203.255
    Google Inc.(AS15169):74.125.204.0-74.125.204.255
    Google Inc.(AS15169):74.125.205.0-74.125.205.255
    Google Inc.(AS15169):74.125.206.0-74.125.206.255
    Google Inc.(AS15169):74.125.207.0-74.125.207.255
    Google Inc.(AS15169):74.125.224.0-74.125.224.255
    Google Inc.(AS15169):74.125.225.0-74.125.225.255
    Google Inc.(AS15169):74.125.226.0-74.125.226.255
    Google Inc.(AS15169):74.125.227.0-74.125.227.255
    Google Inc.(AS15169):74.125.228.0-74.125.228.255
    Google Inc.(AS15169):74.125.229.0-74.125.229.255
    Google Inc.(AS15169):74.125.230.0-74.125.230.255
    Google Inc.(AS15169):74.125.231.0-74.125.231.255
    Google Inc.(AS15169):74.125.232.0-74.125.232.255
    Google Inc.(AS15169):74.125.233.0-74.125.233.255
    Google Inc.(AS15169):74.125.234.0-74.125.234.255
    Google Inc.(AS15169):74.125.235.0-74.125.235.255
    Google Inc.(AS15169):74.125.236.0-74.125.236.255
    Google Inc.(AS15169):74.125.237.0-74.125.237.255
    Google Inc.(AS15169):74.125.238.0-74.125.238.255
    Google Inc.(AS15169):74.125.239.0-74.125.239.255
    Google Inc.(AS15169):107.167.160.0-107.167.191.255
    Google Inc.(AS15169):107.178.192.0-107.178.255.255
    Google Inc.(AS15169):108.59.80.0-108.59.95.255
    Google Inc.(AS15169):108.170.192.0-108.170.255.255
    Google Inc.(AS15169):108.177.0.0-108.177.127.255
    Google Australia's Corporate Network(AS15169):113.197.106.0-113.197.106.255
    Google Inc.(AS15169):130.211.0.0-130.211.255.255
    Google Inc.(AS15169):142.250.0.0-142.250.511.255
    Google Inc.(AS15169):146.148.0.0-146.148.127.255
    Google Inc.(AS15169):162.216.148.0-162.216.151.255
    Google Inc.(AS15169):162.222.176.0-162.222.183.255
    Google Inc.(AS15169):172.217.0.0-172.217.255.255
    Google Inc.(AS15169):172.253.0.0-172.253.255.255
    Google Inc.(AS15169):173.194.0.0-173.194.255.255
    Google Inc.(AS15169):173.194.32.0-173.194.32.255
    Google Inc.(AS15169):173.194.33.0-173.194.33.255
    Google Inc.(AS15169):173.194.34.0-173.194.34.255
    Google Inc.(AS15169):173.194.35.0-173.194.35.255
    Google Inc.(AS15169):173.194.36.0-173.194.36.255
    Google Inc.(AS15169):173.194.37.0-173.194.37.255
    Google Inc.(AS15169):173.194.38.0-173.194.38.255
    Google Inc.(AS15169):173.194.39.0-173.194.39.255
    Google Inc.(AS15169):173.194.40.0-173.194.40.255
    Google Inc.(AS15169):173.194.41.0-173.194.41.255
    Google Inc.(AS15169):173.194.42.0-173.194.42.255
    Google Inc.(AS15169):173.194.43.0-173.194.43.255
    Google Inc.(AS15169):173.194.44.0-173.194.44.255
    Google Inc.(AS15169):173.194.45.0-173.194.45.255
    Google Inc.(AS15169):173.194.46.0-173.194.46.255
    Google Inc.(AS15169):173.194.64.0-173.194.64.255
    Google Inc.(AS15169):173.194.65.0-173.194.65.255
    Google Inc.(AS15169):173.194.66.0-173.194.66.255
    Google Inc.(AS15169):173.194.67.0-173.194.67.255
    Google Inc.(AS15169):173.194.68.0-173.194.68.255
    Google Inc.(AS15169):173.194.69.0-173.194.69.255
    Google Inc.(AS15169):173.194.70.0-173.194.70.255
    Google Inc.(AS15169):173.194.71.0-173.194.71.255
    Google Inc.(AS15169):173.194.72.0-173.194.72.255
    Google Inc.(AS15169):173.194.73.0-173.194.73.255
    Google Inc.(AS15169):173.194.75.0-173.194.75.255
    Google Inc.(AS15169):173.194.76.0-173.194.76.255
    Google Inc.(AS15169):173.194.77.0-173.194.77.255
    Google Inc.(AS15169):173.194.78.0-173.194.78.255
    Google Inc.(AS15169):173.194.79.0-173.194.79.255
    Google Inc.(AS15169):173.194.96.0-173.194.96.255
    Google Inc.(AS15169):173.194.97.0-173.194.97.255
    Google Inc.(AS15169):173.194.98.0-173.194.98.255
    Google Inc.(AS15169):173.194.99.0-173.194.99.255
    Google Inc.(AS15169):173.194.112.0-173.194.112.255
    Google Inc.(AS15169):173.194.113.0-173.194.113.255
    Google Inc.(AS15169):173.194.117.0-173.194.117.255
    Google Inc.(AS15169):173.194.118.0-173.194.118.255
    Google Inc.(AS15169):173.194.119.0-173.194.119.255
    Google Inc.(AS15169):173.194.120.0-173.194.120.255
    Google Inc.(AS15169):173.194.121.0-173.194.121.255
    Google Inc.(AS15169):173.194.124.0-173.194.124.255
    Google Inc.(AS15169):173.194.126.0-173.194.126.255
    Google Inc.(AS15169):173.194.127.0-173.194.127.255
    Google Inc.(AS15169):173.194.136.0-173.194.136.255
    Google Inc.(AS15169):173.194.140.0-173.194.140.255
    Google Inc.(AS15169):173.194.141.0-173.194.141.255
    Google Inc.(AS15169):173.194.142.0-173.194.142.255
    Google Inc.(AS15169):173.255.112.0-173.255.127.255
    Google Inc.(AS15169):192.158.28.0-192.158.31.255
    Google Inc.(AS15169):192.178.0.0-192.178.511.255
    Google Zurich(AS15169):193.142.125.0-193.142.125.255
    Google Inc.(AS15169):199.192.112.0-199.192.115.255
    Google Inc.(AS15169):199.223.232.0-199.223.239.255
    Google Inc.(AS15169):207.223.160.0-207.223.175.255
    Google Inc.(AS15169):209.85.128.0-209.85.255.255
    Google Inc.(AS15169):209.85.238.0-209.85.238.255
    Google Inc.(AS15169):216.58.192.0-216.58.223.255
    Google Inc.(AS15169):216.239.32.0-216.239.63.255
    Google Inc.(AS15169):216.239.32.0-216.239.32.255
    Google Incorporated(AS15169):216.239.33.0-216.239.33.255
    Google Inc.(AS15169):216.239.34.0-216.239.34.255
    Google Incorporated(AS15169):216.239.35.0-216.239.35.255
    Google Inc.(AS15169):216.239.36.0-216.239.36.255
    Google Inc.(AS15169):216.239.38.0-216.239.38.255
    Google Incorporated(AS15169):216.239.39.0-216.239.39.255
    Google Incorporated(AS15169):216.239.44.0-216.239.45.255
    Google Fiber Inc.(AS16591):23.228.128.0-23.228.191.255
    Google Fiber Inc.(AS16591):23.255.128.0-23.255.255.255
    Google Fiber Inc.(AS16591):107.188.128.0-107.188.255.255
    Google Fiber Inc.(AS16591):192.119.16.0-192.119.31.255
    Google Fiber Inc.(AS16591):192.200.224.0-192.200.255.255
    Google Fiber Inc.(AS16591):216.21.160.0-216.21.175.255
    Google Inc.(AS22577):70.32.130.0-70.32.130.255
    Google Inc.(AS22577):70.32.131.0-70.32.131.255
    Google Inc.(AS22577):70.32.132.0-70.32.132.255
    Google Inc.(AS22577):70.32.133.0-70.32.133.255
    Google Inc.(AS22577):70.32.158.0-70.32.158.255
    Admob(AS22577):165.193.245.0-165.193.245.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.32.0-203.208.63.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.36.0-203.208.36.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.37.0-203.208.37.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.40.0-203.208.40.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.41.0-203.208.41.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.46.0-203.208.46.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.47.0-203.208.47.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.48.0-203.208.48.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.49.0-203.208.49.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.56.0-203.208.56.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.60.0-203.208.60.255
    Beijing Gu Xiang Information Technology Co.,Ltd.(AS24424):203.208.61.0-203.208.61.255
    PLIXDC SP. Z O.O.(AS36040):46.28.246.0-46.28.246.255
    PLIXDC SP. Z O.O.(AS36040):46.28.247.0-46.28.247.255
    MCI Communications Services, Inc. d/b/a Verizon Business(AS36040):63.88.73.0-63.88.73.255
    VideoServer Inc.(AS36040):63.96.4.0-63.96.4.255
    P2S ENGINEERING(AS36040):63.110.67.0-63.110.67.255
    TWEEDY, BROWNE COMPANY LLC(AS36040):63.117.14.0-63.117.14.255
    ING FINANCIAL SERVICES LLC(AS36040):63.117.68.0-63.117.68.255
    MCI Communications Services, Inc. d/b/a Verizon Business(AS36040):63.117.215.0-63.117.215.255
    YouTube, LLC(AS36040):64.15.112.0-64.15.112.255
    YouTube, LLC(AS36040):64.15.113.0-64.15.113.255
    YouTube, LLC(AS36040):64.15.115.0-64.15.115.255
    YouTube, LLC(AS36040):64.15.117.0-64.15.117.255
    YouTube, LLC(AS36040):64.15.119.0-64.15.119.255
    YouTube, LLC(AS36040):64.15.124.0-64.15.124.255
    YouTube, LLC(AS36040):64.15.126.0-64.15.126.255
    ALM MEDIA, INC(AS36040):65.196.188.0-65.196.188.255
    ALTERNET PERFORMANCE(AS36040):65.199.32.0-65.199.32.255
    Google(AS36040):149.3.177.0-149.3.177.255
    TelecityGroup Poland Sp. z o.o.(AS36040):193.33.5.0-193.33.5.255
    Peering GmbH(AS36040):194.122.80.0-194.122.80.255
    YouTube, LLC(AS36040):208.117.224.0-208.117.224.255
    YouTube, LLC(AS36040):208.117.225.0-208.117.225.255
    YouTube, LLC(AS36040):208.117.229.0-208.117.229.255
    YouTube, LLC(AS36040):208.117.230.0-208.117.230.255
    YouTube, LLC(AS36040):208.117.231.0-208.117.231.255
    YouTube, LLC(AS36040):208.117.232.0-208.117.232.255
    YouTube, LLC(AS36040):208.117.244.0-208.117.244.255
    Google Incorporated(AS36384):216.239.44.0-216.239.45.255
    Google, Inc.(AS36492):8.6.48.0-8.6.55.255
    Google, Inc.(AS36492):64.9.224.0-64.9.255.255
    Google, Inc.(AS36492):64.9.224.0-64.9.239.255
    Google Australia Pty Limited(AS41264):103.246.187.0-103.246.187.255
    Google Ireland Limited(AS41264):193.186.4.0-193.186.4.255
    Google Australia's Corporate Network(AS45566):113.197.106.0-113.197.106.255
    YouTube, Inc.(AS36561):64.15.114.0-64.15.114.255
    (AS36561):64.15.120.0-64.15.123.255
    YouTube, Inc.(AS36561):64.15.125.0-64.15.125.255
    (AS36561):208.65.152.0-208.65.153.255
    YouTube, LLC(AS36561):208.117.236.0-208.117.236.255
    YouTube, LLC(AS36561):208.117.240.0-208.117.240.255
    YouTube, LLC(AS43515):64.15.112.0-64.15.127.255
    YouTube, LLC(AS43515):208.65.152.0-208.65.155.255
    YouTube, LLC(AS43515):208.117.224.0-208.117.255.255
    YouTube, LLC(AS43515):208.117.236.0-208.117.236.255
    YouTube, LLC(AS43515):208.117.238.0-208.117.238.255
    YouTube, LLC(AS43515):208.117.239.0-208.117.239.255
    YouTube, LLC(AS43515):208.117.240.0-208.117.240.255
    YouTube, LLC(AS43515):208.117.242.0-208.117.242.255
    YouTube, LLC(AS43515):208.117.248.0-208.117.248.255
    YouTube, LLC(AS43515):208.117.249.0-208.117.249.255
    YouTube, LLC(AS43515):208.117.250.0-208.117.250.255
    YouTube, LLC(AS43515):208.117.251.0-208.117.251.255
    YouTube, LLC(AS43515):208.117.252.0-208.117.252.255
    YouTube, LLC(AS43515):208.117.254.0-208.117.254.255
    YouTube, LLC(AS43515):208.117.255.0-208.117.255.255
    Google Inc.(AS43515):216.239.60.0-216.239.60.255

And this image for a top page:
http://si.wsj.net/public/resources/images/MK-CH388_COOKIE_G_20131028180025.jpg

-------------------------
Please consider adding:
"ipset" with above IP range -> Linux
"Peerblock" with above -> Windows

// No Catherine, I don't do it. YOU do it.

**Comment by strugee** [comment]
Can we close this issue? It's not going anywhere. /cc @nylira
