### ISSUE TITLE
ADD "KeePass 2.x" (Password Manager - F/OSS GPLv2, Multiplatform)

### ISSUE THREAD

**Issue by RanceJustice** [nylira/prism-break#1046]
I'm very pleased to see the new Password Manager category on Prism-Break! Alongside the existing Password Safe option, I'd like to suggest what seems to be one of the most comprehensive and viable password managers around - KeePass!  Specifically, the 2.x branch which  has a much greater feature set than the 1.x option and is better designed to run cross platform.

Websites :  www.keepass.info
Sourceforge - /www.sourceforge.net/projects/keepass/

KeePass 2.x is F/OSS  via GPLv2, hosted on SourceForge.   It is available to be compiled on all major platforms and there have been a number of 3rd party  (many of them, FOSS) ports for Android, iOS and other platforms - we can look into suggesting them for those versions of the site.   It also has a HUGE set of plugins  (again, many are FOSS, but users should be careful) and its source comes with documentation on how to build plugins.  There's a huge index of plugins by feature on the homepage and they extend its features way beyond its considerable built in kit. 

Let us consider adding KeePass 2.x to Prism-Break - it can greatly contribute to privacy and security not only because of its technical viability, but its extensible and easily usable feature set.  Thank you.

**Comment by adjustamat** [comment]
I agree with [RanceJustice's comment](https://github.com/nylira/prism-break/issues/1237#issuecomment-77468898) (written in the thread about KeePassX - #1237) - who commented [this ThomasWaldmann's comment](https://github.com/nylira/prism-break/issues/520#issuecomment-46120060) in #520.
But personally, I can't just [fork the repo, commit the edit to index.html and the .json language files and create a pull request.](https://github.com/nylira/prism-break/issues/520#issuecomment-30509760)
But somebody should! Somebody should also close #1036 so at least this discussion is kept in one place - here!

**Comment by wifiextender** [comment]
@emwa 

>The version label argument seems not a valid argument, "Password Save" has been published in the linux category of password software wich the linux version of this program it's still in beta

Bruce Schneier and amateur crypto doesn't go hand in hand

>if it works properly with no critical buggs I don't see any problem doing

Are you really that naive ?

>People should know this software because it's clearly one of the best solutions to save passwords secure.

I guess GPG and LUKS are less **secure** then. If you followed my blog you'll know how simple to work with LUKS is, dedicated entire post how to encrypt your entire drive and boot loader.
