### ISSUE TITLE
Recommended cheap vps or raspberry pi colocation

### ISSUE THREAD

**Issue by scastillobib** [nylira/prism-break#1052]
Hi!

I'm thinking about self hosting my own mail server at home

The problem is that I have dynamic IP. Many SMTP servers will reject mail coming from a server with dynamic ip.

One solution could be host a SMTP server in a VPS or colocated raspberry pi.

Any recommendation?

Thank you

**Comment by yegortimoshenko** [comment]
Not actionable, duplicate of #100.
