### ISSUE TITLE
Add gpg4usb

### ISSUE THREAD

**Issue by PositronicTomato** [nylira/prism-break#1054]
Uses GPG, has the ability to generate/export/import keys, sign/verify, encrypt/decrypt text and individual files.

It's free, open source, portable, and has versions for Linux and Windows.

It isn't as full-featured as Enigmail + Thunderbird + GPG (the GUI doesn't support creating revocation certificates or changing your passphrase) but I think it is far easier to set up and has a well designed and easy to use interface. 

http://gpg4usb.org/index.html

**Comment by yegortimoshenko** [comment]
Hasn''t been updated since 2016-01-05.
