### ISSUE TITLE
Open Source Routing Machine Security Notes

### ISSUE THREAD

**Issue by oLux** [nylira/prism-break#1058]
Dear All,

Please consider making the "Security Notes" on "Open Source Routing Machine" more realistic. To avoid any misunderstanding: OSRM is a phenomenal project and the goal of running a routing server on the LAN which does not constantly supply data to Google and their likes is fully convincing.

Currently, the security notes are: "OSRM should be installed and run locally on your PC to avoid potential data leaks from the unencrypted online service."

Please note that extracting and preparing the OSM data does take a machine with > 32 GB RAM available (not used for other activities, e.g., in a virtualization environment) plus large SSD-Swap unless the real RAM is >> 32 GB plus > 4 up to date CPU cores. Otherwise extracting and preparing are likely either to fail or at least take multiple days. Everyone may certainly try that or triangulate this from:

https://github.com/DennisOSRM/Project-OSRM/wiki/OSRM-data-processing-timings

The current security notes may raise the expectation that it would be possible to have OSRM "run locally on your PC". I think that most PCs of prism-break readers will be insufficient for that task. One does not get the sense, that a server worth more than the low end of four digit range will be required to run OSRM in production for a small office.

Please consider something like: "OSRM should be installed and run on an enterprise grade linux server to avoid potential data leaks from the unencrypted online service."

A small-scale proxy-type alternative - within reasonable limits probably OK with the operators of the demo server in Karlsruhe (http://map.project-osrm.org/) - might be to run just the web interface (https://github.com/DennisSchiefer/Project-OSRM-Web) on a LAMP server without logging and with https and share that publicly among multiple users so that it will be indistinguishable where the original querries came from.

Regards

oLux

**Comment by yegortimoshenko** [comment]
This text is not present in notes anymore: https://prism-break.org/en/subcategories/gnu-linux-world-maps/

**Comment by yegortimoshenko** [comment]
I was wrong, it's in project notes, not in category notes: https://prism-break.org/en/projects/open-source-routing-machine/
