### ISSUE TITLE
DuckDuckGo XMPP is not secure 

### ISSUE THREAD

**Issue by jemadux** [nylira/prism-break#1062]
Searching on[DuckDuckGo Fora I bump into that  [topic](https://duck.co/forum/thread/5205/merge-ejabberd-hosts-into-prosody) and I am wondering if that is true

**Comment by yegortimoshenko** [comment]
https://duck.co/blog/post/4/xmpp-servDuckDuckGo 

> UPDATE (May 19th, 2017)
>
> On Thursday May 18th, 2017 we shut down our dukgo.com XMPP service. Thanks for your continued support over the previous years.
>
> For alternative XMPP servers check out www.cryptoparty.in/connect/contact/jabber and gultsch.de/compliance_ranked.html
>
> The DuckDuckGo Team
