### ISSUE TITLE
Add bitwasp as alternative to paypal oriented shopping carts and marketplaces like eBay. 

### ISSUE THREAD

**Issue by CameronRuggles** [nylira/prism-break#1076]
Bitwasp is a completely open source multisig marketplace software that is friendly towards GPG encrypted messages, had RSA encryption and a few other features that if enabled ensure info is safe from the NSA.

**Comment by yegortimoshenko** [comment]
Not being developed since October 2014: https://github.com/Bit-Wasp/BitWasp/commits/master

Also, README says "BitWasp is not production ready".

Domain bit-wasp.org is now parked, seemingly by some reseller.
