### ISSUE TITLE
Signal - iPhone Encrypted calls from Open Whisper Systems - FOSS

### ISSUE THREAD

**Issue by annonman** [nylira/prism-break#1081]
Open Whisper Systems has released a RedPhone compatible app for iOS.

https://whispersystems.org/blog/signal/

Code:
https://github.com/WhisperSystems/Signal-iOS
>"The project even pays out a percentage of donated Bitcoin for every merged pull request."

I suggest inclusion with Prism Break.

**Comment by Klimmbimmel** [comment]
Discuss here: #1314 

and close this thread.
