### ISSUE TITLE
Mitro (password manager)

### ISSUE THREAD

**Issue by Zegnat** [nylira/prism-break#1082]
[Mitro](https://www.mitro.co) is [going open source](https://www.eff.org/deeplinks/2014/07/mitro-a-new-free-password-manager) (EFF).

Should this be considered for inclusion? I never heard of Mitro before the EFF blog post.

**Comment by yegortimoshenko** [comment]
Mitro is not being developed anymore: https://github.com/mitro-co/mitro/issues/133
