### ISSUE TITLE
Can we add some of these browsers to the list?

### ISSUE THREAD

**Issue by blurmonk** [nylira/prism-break#1084]
Hi

Couple of these are pretty good (I believe) 

https://en.wikipedia.org/wiki/Comparison_of_lightweight_web_browsers.

Midori and Qupzilla can be nice FF/Chrome alternatives

thanks

**Comment by yegortimoshenko** [comment]
Midori has been rejected (#88, #524), QupZilla has been rejected (#559, #1907).
