### ISSUE TITLE
Feedly and such replacement TinyTinyRss

### ISSUE THREAD

**Issue by blurmonk** [nylira/prism-break#1085]
Hi

This is a wonderful RSS and news sharing replacement. It is gorgeous and offers many features like multiple accounts/mobile support etc.

http://tt-rss.org/

http://github.com/gothfox/Tiny-Tiny-RSS

**Comment by yegortimoshenko** [comment]
I think RSS is a federated replacement for any aggregator site, Facebook, Google News, etc. Currently we don't have that category, but it should be added.

**Comment by beerisgood** [comment]
TTRSS is even now- 3,5 years later, the best

**Comment by Hillside502** [comment]
Tiny Tiny RSS is definitely the best, but here's a few more for interest:-

Open Source Tiny Tiny RSS Alternatives - AlternativeTo.net
https://alternativeto.net/software/tiny-tiny-rss/?license=opensource
