### ISSUE TITLE
Can we remove Firefox from the list?

### ISSUE THREAD

**Issue by blurmonk** [nylira/prism-break#1091]
I know that FF is generally considered safe at least that is the perception. But based on my test I see that FF and Iceweasel(on Debian) initiates alot of port connections back to Mozilla even after disabling the visible accesible settings like telemetry, updates etc. I personally do not trust Mozilla and their motivations. I do not think that they care about user privacy as much as they claim publicly.

thanks

**Comment by nodiscc** [comment]
> FF and Iceweasel(on Debian) initiates alot of port connections back to Mozilla even after disabling the visible accesible settings like telemetry, updates etc

Fixing https://github.com/nylira/prism-break/issues/1254 should fix this.

**Comment by karme** [comment]
nodiscc <notifications@github.com> writes:

> Fixing https://github.com/nylira/prism-break/issues/1254 should fix
> this.

to me looks more like an argument to stop recommending firefox:

Reading
https://github.com/pyllyukko/user.js/blob/master/user.js
i wonder how many settings will have to be added with the next firefox
release and how many settings might be pitfalls.

for example
user_pref("security.OCSP.enabled", true);
might be a bad idea

don't get me wrong:
great work

(wasted many hours trying to fix the defaults myself and only did have a
small subset yet!)

**Comment by Zegnat** [comment]
I am going to close this issue, hope that’s okey. But I think we can all agree that just “removing Firefox” is no answer for us. #1310 and #1254 really are the better discussions :smile:
