### ISSUE TITLE
Please add Mutt to the list.

### ISSUE THREAD

**Issue by blurmonk** [nylira/prism-break#1093]
IF anyone is worried about their privacy they better learn some hardcore tools. Mutt is one of the most robust email client. And adding accounts is not so convoluted. You just add couple lines to a text file. While it is not as streamlined as TB, it is still a good email client. It offers imap/pop with ssl connections and more.

**Comment by alerque** [comment]
DItto. I'm a daily `mutt` user but it doesn't fit this site very well. People that need a CLI mail client will know where to find it anyway.

**Comment by strugee** [comment]
I would also concur.

**Comment by yegortimoshenko** [comment]
Closing based on consensus.
