### ISSUE TITLE
gog instead of steam 

### ISSUE THREAD

**Issue by jemadux** [nylira/prism-break#1101]
GOG.com is site that provides non-free software but old time classic games without DRM . 
I suppose that is good idea ...

**Comment by yegortimoshenko** [comment]
Desura does not exist anymore, and GOG went even further down proprietary road with proprietary GOG Galaxy that is required for some games for online/co-op gaming. Access to integration of online/co-op with GOG requires a proprietary SDK which is only available if you sign contract with GOG.

The situation with games is very sad, but it is what it is. I think the issue can be closed, and perhaps one day there would be an option that doesn't require to make a compromise.

**Comment by yegortimoshenko** [comment]
Anyway, we don't list any gaming clients, there is no gaming category. Let's close this on that basis?

**Comment by yegortimoshenko** [comment]
Closed together with #775.
