### ISSUE TITLE
Adding Searx in Web Search and Server

### ISSUE THREAD

**Issue by laskameleonart** [nylira/prism-break#1102]
Hi ;

I love the prism break project and i think there's a great tool you could add : Searx.
It is a privacy-respecting, hackable metasearch engine. Here's the project page : https://github.com/asciimoo/searx

You can use another instance, or install your own on your server. It it present in YuNoHost (which only include FOSS).

Hope to see it in the prism break list soon ;-)

Regards
laskameleonart

**Comment by Zegnat** [comment]
Closing in favour of #1123.
