### ISSUE TITLE
Jitsi security issues

### ISSUE THREAD

**Issue by darkman088** [nylira/prism-break#1112]
Hello,

I would seriously propose to put warnings on Jitsi !! I have 2 objective reasons for that:

1) By an absolute chance, I have come across this 2 years-old post:

http://markmail.org/message/ciszy5z2cevs3ni3

This sounded pretty thrilling from security point of view, so I went
ahead and checked the situation on my Jitsi 2.4.4997, which I am
running on Windows 7. I was SHOCKED, that in the path:

C:\Users<myuser>\AppData\Roaming\Jitsi\history_ver1.0

there are .xml files, which contain the chat history in plain text !!!
And this hasn't been fixed already for 2 years !!!
And it is a huuuuge security hole !!! Why bother to implement
all those ultra-secure protocols and encryption ??? If someone is
using Jitsi on a Windows PC, as I do, then the encryption is as easy
to break, as it is easy to break into a Windows PC !!! And nowadays
even children can do that!
YES, this option can be turned off, but very often when talking about
security, the question comes up if logs are stored. And Jitsi, which claims
to be a secure program, stores logs by default !! In my opinion, it should
be reversed - by default - not store logs, and if the user desires, only
then he should be able to enable this option. And in the end - why are
those logs stored in a plain text format and are not encrypted !!! As
far as I know, even Skype encrypts its chat logs !!!

2) There is most probably a bug in the chat feature of Jitsi, I have 
already reported that - Although I have set the option to initiate
encrypted chat sessions with everybody, when I open a chat window
with a contact, that I have already verified by exchanging fingerprints,
the chat is by default not secured (the lock button shows open), and
I need to click that lock button every time! It is quite annoying and it is
VERY possible that somebody will forget clicking that lock sometimes...

Many thanks for paying attention to the issues I have pointed out here!
I am very concerned !!!

**Comment by yegortimoshenko** [comment]
Every chat software I know stores logs in plain text, this is to be expected. Labeling as "waiting for objections".
