### ISSUE TITLE
New Browser Addons

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1120]
https://code.google.com/p/https-finder/ (it works better with https-everywhere, tests https connections on sites, and if it works, and has a valid certification and everything, it goes to that site)
https://addons.mozilla.org/en-US/firefox/addon/cookie-controller/ (control third party cookies and what not)
https://www.mozilla.org/en-US/lightbeam/ (visualize third-parties, and block them)
https://addons.mozilla.org/En-us/firefox/addon/refcontrol/ (controls how websites see what website you came from)
https://addons.mozilla.org/en-us/firefox/addon/wappalyzer/ (see if the technologies for the site you are using are trusted/secure)
https://addons.mozilla.org/en-US/firefox/addon/flagfox/ (check to see if the site you are using is in a country you prefer, for example, you can use it to avoid US sites and find Swiss sites)

**Comment by Hillside502** [comment]
Flagfox is not fully open source
https://addons.mozilla.org/en-US/firefox/addon/flagfox/license/6.0.3
