### ISSUE TITLE
[XMPP] Conversations

### ISSUE THREAD

**Issue by ignitedPotato** [nylira/prism-break#1145]
https://github.com/siacs/Conversations

This app seems to be a great alternative for Xabber and ChatSecure.

Also available via F-Droid:
https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations

**Comment by iNPUTmice** [comment]
:+1:

besides offering a modern UI Conversations also makes use of more advanced XMPP technologies. Stream Management to survive small network outages, Carbon Copies to keep your messages in sync with your desktop client, optional server side history to catch up with messages that have been written while offline and much more (see [README.md](https://github.com/siacs/Conversations/blob/development/README.md))

**Comment by pravi** [comment]
Conversations is definitely the best XMPP app for android. I think this should be the recommended app. I heard lots of complaints about ChatSecure and only positive reviews about conversations.

**Comment by lobit0** [comment]
:+1: merge this, already! :)

**Comment by sedrubal** [comment]
I think I've missed the other translations... Maybe @nylira can merge this now?
