### ISSUE TITLE
Add Korora to the Operating Systems list

### ISSUE THREAD

**Issue by MrTrebleClef** [nylira/prism-break#1146]
I think we have to add Korora to the Operating System list. It's based on Fedora and their objectives are: "With a special blend of aesthetics and functionality, Korora aims to make Linux easier for new users, while still being useful for experts. We provide a complete, easy to use computing system that "just works" out of the box."
It's like a Linux Mint based on Fedora (Red Hat) (without any relationship with Canonical). I think this one will be the best option on the list for the beginners.
Site of the project: https://kororaproject.org/

**Comment by strugee** [comment]
Closing as there don't seem to be any compelling advantages to this suggestion, plus there are some definite disadvantages. In addition to that the OS section is already overloaded.
