### ISSUE TITLE
Add IPFire in routers section

### ISSUE THREAD

**Issue by use-gitorious** [nylira/prism-break#1147]
https://www.gnu.org/philosophy/open-source-misses-the-point.html

**Comment by yegortimoshenko** [comment]
Actual IPFire site: https://www.ipfire.org/

**Comment by Hillside502** [comment]
Source
https://wiki.ipfire.org/devel/sources

**Comment by yegortimoshenko** [comment]
Would like to close this given that IPFire doesn't seem to be a compelling privacy/security improvement over Openwrt, OpenBSD, and other options in Routers section. If anything, distributions we currently list are more popular, and thus, receive much more attention and patches.
