### ISSUE TITLE
Android web browsers discussion

### ISSUE THREAD

**Issue by anthologist** [nylira/prism-break#1148]
I see in the Android section there's only Firefox. The problem is, from v32 they dropped the support for Android 2.2 and for ARMv6 (thanks Mozilla), so personally I'm cut out and probably many other people. Are there any other alternatives?
I was looking at Orweb (https://guardianproject.info/apps/orweb/) based on Shadow Browser (http://www.cl.cam.ac.uk/research/dtg/android/tor/).
Ignoring the security advisory displayed in the orweb page, what do you think  about them?

**Comment by yegortimoshenko** [comment]
Given that ARMv6 build of Firefox on Android has been dropped almost four years ago, there seems to be no point in finding a browser that works on it.

**Comment by yegortimoshenko** [comment]
Closing, because it would be irresponsible of us security-wise to recommend using a device that only runs Android 2.x.
