### ISSUE TITLE
To add: other Public DNS Servers

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1150]
Hi, 
I found some other Public DNS Servers that maybe colud be ok (tha source is http://pcsupport.about.com/od/tipstricks/a/free-public-dns-servers.htm):
- FreeDNS : http://freedns.zone/en/why/  FreeDNS says that they "never log DNS queries." Their free DNS servers are located in Austria
- censurfridns http://blog.censurfridns.dk/en/faq  The censurfridns.dk DNS servers are uncensored, operated by a privately funded individual, and are physically located in Denmark
- DNS.Watch https://dns.watch/index , uncensored DNS (not sure aboout it), an uncensored DNS located in Germany

Also, there is PowerDNS to add, it's completely open-source  https://www.powerdns.com/

P.s: I've also a request: could someone give me more informations about OpenDNS (http://www.opendns.com/)? How much "open" are them? They are by private company, right?

**Comment by yegortimoshenko** [comment]
Split into three more actionable issues:

censurfridns.dk: #1033 
FreeDNS: #1917 
DNS.WATCH: #1918
