### ISSUE TITLE
APG vs. OpenKeychain

### ISSUE THREAD

**Issue by dschuermann** [nylira/prism-break#1156]
I read that you want to have quality over quantity, so I would propose removing APG as a suggested PGP app for Android. It has not been updated in a while. Sure I am biased because I am the maintainer of OpenKeychain, but also new versions of K-9 Mail will no longer contain the interface to APG (see https://github.com/k9mail/k-9/pull/499)

**Comment by Sephula909** [comment]
I've used both, and prefer OpenKeychain, myself. No advantage, but potential disadvantages with APG. OpenKeychain is definitely better from a user perspective, too.

**Comment by qw3ry** [comment]
Not sure why this is still open, as #1171 and #1581 have been merged; if this is still open for discussion, I just noticed that APG got updated again. Not sure about re-adding it as a recommendation though, as I don't use it myself.

**Comment by dschuermann** [comment]
I was able to close this as I am the original reporter.

@qw3ry where do you see an update to APG?

**Comment by qw3ry** [comment]
@dschuermann for me the Google play store page says 

> A fork of APG called OpenKeychain added most of the new features, which have now been merged back into APG.
APG development is active again and I'm mostly working on the implementation of PGP/MIME now.

I've not further investigated this, but I was told it would work with K9 again

**Comment by dschuermann** [comment]
@qw3ry Ah okay :) The text on the Google Play store page is very old. He never worked on PGP/MIME for APG.
