### ISSUE TITLE
[Android] Noscript Anywhere

### ISSUE THREAD

**Issue by fervi** [nylira/prism-break#1174]
Hello!

There is a Noscript version for Android (in Alpha release, but it works) [Firefox only]
http://noscript.net/nsa/

It is official site of Noscript, but I cannot find a source code; but it works

Fervi

**Comment by yegortimoshenko** [comment]
> On Firefox 57 and above there's only one NoScript, i.e. NoScript 10 "Quantum" which you can download here.

> NSA is now considered a "legacy" add-on, just like NoScript 5.x "Classic" on desktop, but now NoScript is in an even better position than before on Android, because of the finally unified code-base ensuring the same support level both on desktop and mobile devices :) 

NoScript distributed on addons.mozilla.org now runs on desktop and mobile versions of Firefox, so this add-on is deprecated. Safe to close.
