### ISSUE TITLE
Adding Martus

### ISSUE THREAD

**Issue by 5u11y** [nylira/prism-break#1182]
FLOSS software maintained for 10+ years, designed for secure documentation of human rights abuses. Client-side end-to-end crypto, 3072 RSA/256 AES hybrid system. Offers free always-encrypted online backup secure from server admins (keys & credentials are offline-only), secure data sharing with other users (offline or via secure server), ability to customize data forms and templates, etc. About to get a long-awaited facelift, among many other usability enhancements.

https://www.martus.org/

Built/maintained by Benetech https://www.benetech.org/

**Comment by yegortimoshenko** [comment]
Martus seems to be tailored to collect data about human rights abuses. It's very hard to figure out what software actually does, so not sure how we could incorporate this into PRISM Break.
