### ISSUE TITLE
EFF Secure Messaging Scorecard

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1183]
https://www.eff.org/secure-messaging-scorecard
Based on these scores, I think we should do the following:
* Note Jitsi, Adium, Pidgin with OTR have  not been audited
* Discuss possible additions of Subrosa, SureSpot, and Silent Phone/Text

**Comment by hasufell** [comment]
> Looks like as of 2014-11-14, Pidgin has been audited

link? The eff site is not really helpful.

**Comment by Zegnat** [comment]
Closing this. The EFF scorecard is great for what it is meant to do, and that is to get companies to compete with each other on security. The EFF scorecard is not so great for what PRISM Break is meant to do, pointing people at secure software.

For more of my view on this, see [this comment](https://github.com/nylira/prism-break/issues/1224#issuecomment-71324851).
