### ISSUE TITLE
"New tab" page ads in Firefox

### ISSUE THREAD

**Issue by RoseTheFlower** [nylira/prism-break#1184]
One of the main reasons Ubuntu is not recommended here and is criticized by people in other places, is the amazon ads enabled by default. How's Firefox different now if updating to its newest version automatically enables the new, "Enhanced" look of the "new tab" page that allows Mozilla to push ads to users?

**Comment by nodiscc** [comment]
> I guess we can recommend the same here as we do for safe browsing (see #804): disable it or take the calculated risk of possibly leaking (unidentifiable) information.

Fixing https://github.com/nylira/prism-break/issues/1254 should fix this issue.
