### ISSUE TITLE
Detekt

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1187]
https://www.resistsurveillance.org/
helps find government spyware on your computer.
[Backed by EFF](https://www.eff.org/deeplinks/2014/11/detekt-new-malware-detection-tool-can-expose-illegitimate-state-surveillance). [Open source](https://github.com/botherder/detekt).

**Comment by hasufell** [comment]
Seems like this is only relevant for Computers that have the Windows backdoor/virus already installed.

**Comment by mastercoms** [comment]
It will be helpful since people can find out if they are being tracked in that way, and do something about it.

**Comment by strugee** [comment]
@mastercoms where do you suggest we put this on the page?

**Comment by mastercoms** [comment]
Possibly in the operating system section notes.

**Comment by strugee** [comment]
The OS section notes is very overloaded already, and I'd prefer not to add anything else. Any objections to closing this? As I said a while ago, I don't think this really belongs on PRISM Break.

**Comment by alerque** [comment]
Agreed.
