### ISSUE TITLE
AntiPrism - anonymizing mediacenter software

### ISSUE THREAD

**Issue by antiprismca** [nylira/prism-break#1195]
This might be worth adding to the OS category or, perhaps, even a separated "HTPC software" category:

http://www.antiprism.ca/

AntiPrism is a tool for very secure web-browsing and communication. It is implemented as a set of extensions to the OpenELEC-derived media center software providing a universal and seamlessly integrated web privacy solution for home and small office. It runs from a read-only file system within a secure Linux operating environment bootable from a USB flash drive or installable on a HDD/SSD. AntiPrism is activated with a password used as an encryption key to a hidden file system. Once deactivated, it leaves no traces of its operations. The computer device running AntiPrism can serve as a media center for watching movies, streaming music and games, and general web surfing with the included basic web browser, because the basic XBMC/Kodi external plug-ins functionalities are preserved and acting as an anonymizing tool in the background.

The main differences between AntiPrism and other existing anonymizing Linux derivatives (Tails, Whonix, Liberte, etc) are dictated by its purpose. AntiPrism provides, basically, a “secure anonymizing media center”, a household device that would normally do little when not being used for entertainment, but is now loaded with new hidden powers. For example, you can anonymously search, download and watch your torrents right on the device, without a need to copy them elsewhere. It can run as an intermediate or entry node in the anonymous networks extending their strength and improving availability. It has a noticeably high performance, due to the fast Systemd Linux backend with close to real-time IRQ response and low network packets losses.

**Comment by yegortimoshenko** [comment]
We already list AntiPrism: https://prism-break.org/en/projects/antiprism/
