### ISSUE TITLE
Whiteout

### ISSUE THREAD

**Issue by andoruB** [nylira/prism-break#1196]
Could Whiteout.io be added as both e-mail client and e-mail provider/account?

**Comment by pravi** [comment]
I have used the web version on my laptop and its pretty nice. I think we should recommend it as mailvelop does not support attachments and people will get easily disappointed if they start using it (we should mention that as a note too).

Also I think they should be listed as email service provider too.

**Comment by yegortimoshenko** [comment]
https://whiteout.io/

> As of January 1st 2016 the Whiteout Mail service is no longer available.

Can be closed.
