### ISSUE TITLE
What about SecuGab Messenger?

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1203]
http://de.wikipedia.org/wiki/Liste_von_mobilen_Instant-Messengern#cite_note-10
Hier sieht man, dass SecureGab theoretisch am besten sein müsste.
Was ist mit KeePass und TextSecure?

Danke! Sry, ich kann nicht so gut Englisch.

http://de.wikipedia.org/wiki/Liste_von_mobilen_Instant-Messengern#cite_note-10
Here you can see, that SecureGab Messenger is theoretically the best.
What about TextSecure?
And what is with KeePass?

Thanks! Sorry for my bad English;-)

**Comment by iNPUTmice** [comment]
SecuGab is / was just a fork of [Conversations](https://github.com/siacs/Conversations) that changed around some colors and modified the title and in return didn't made the source code publicly available. If you want to add a XMPP client with a modern UI and OTR / PGP encryption you should add Conversations to the list.

**Comment by alerque** [comment]
What @iNPUTmice says about SecuGab seems to check-out. A separate issue might need to be opened for Conversations, but that would require a considerable higher level of input about why it's a good fit that what we have here.

Suggest closing this issue as all the programs mentioned have been dealt with here or elsewhere.

**Comment by vyp** [comment]
@alerque fyi there is one already #1145.
