### ISSUE TITLE
TrueCrypt is still OK in version 7.1a

### ISSUE THREAD

**Issue by alliquot** [nylira/prism-break#1213]
The old version (binaries and sources) is stored and maintained by https://truecrypt.ch/
They offer the last secure version, 7.1a

It's worth noting because it was (and is) one of the best encrypting software.

**Comment by vyp** [comment]
This should really be comment in #995, which is what @Zegnat requested literally just in the previous issue #1212.

**Comment by Zegnat** [comment]
Closing as per @vyp’s comment. See #995.
