### ISSUE TITLE
Disconnect has not published their latest source.

### ISSUE THREAD

**Issue by xenithorb** [nylira/prism-break#1214]
https://github.com/disconnectme/disconnect

The repository here hasn't been seriously updated here for 6-8 months, and the business has moved to a new "premium" model, removing some of the features that were actually present in the original version and including them only in: https://disconnect.me/premium

Im not sure this can be considered a useful or FOSS project any longer.

**Comment by hasufell** [comment]
The available code is technically still FOSS.

However, you could argue that main development takes place in a non-FOSS manner now and that disconnect as such isn't up2date anymore. I'd still rather wait for @byoogle to comment on this

**Comment by byoogle** [comment]
Hey, thanks for asking me. I’m not working on the project anymore, though, so I don’t know either if/how Disconnect dev is done now. Maybe you can find out the answer from support@disconnect.me.

**Comment by hasufell** [comment]
> I’m not working on the project anymore

why?

**Comment by byoogle** [comment]
@hasufell I started another company, am working on other projects.

**Comment by fabianlischka** [comment]
I've looked into Disconnect recently, and while their code might technically still be FOSS, it's pretty much impossible to find it on their website. 
They seem to be pushing freemium apps whose free version is not very useful (they tell you which and how many tracking bugs there are, for example, but don't do anything about them), while the pay version seems pretty comprehensive (includes a VPN, for example), but not free, not open as far as I could tell, and arguably overkill in terms of bundling (i.e., I might want to have a VPN from a different provider, and not place all my trust in this one company). 

So, I guess I support @xenithorb's (implicit) suggestion of moving them into the proprietary category.

**Comment by Zegnat** [comment]
Does anyone know what parts of Disconnect would still be open-source? The website still says they are open-source but I have a hard time tracking any of it down. The application itself seems to be a node-webkit set-up so most of the code is accessible to the end-user but that doesn’t qualify for PRISM Break.

I’ll send out an email to them tomorrow (GMT).

**Comment by hasufell** [comment]
you know.... love is for everyone... so we should sharee it!

**Comment by Zegnat** [comment]
Email sent:

> Hi Disconnect team!
>
> I am writing to you as a contributor to [the PRISM Break project](https://prism-break.org/). This week an issue was opened saying [Disconnect is no longer open-source](https://github.com/nylira/prism-break/issues/1214) and I would like to ask you about this.
> 
> It seems the old GitHub repository is out of date, but your website (both home page and FAQ) still boldly state Disconnect is open-source. Where can we find the latest source?
> 
> I hope you can tell us where to find the latest source, or clarify the company’s current directions.

**Comment by Draxler** [comment]
May i ask wich version of Disconnect would be described as most trustworthey and successful version when comes to good performence as ''Free Disconnect user'' ? Wich Disconnect version give user most performence as Free Disconnect..  Because latley you have to pay Premium Disconnect for a lot of things wich were free before in past Disconnect versions ..

**Comment by hasufell** [comment]
I recommend to not use disconnect for now, but use [Request Policy](https://prism-break.org/en/projects/request-policy/) instead. It needs more manual configuration but is generally also more powerful.

**Comment by nodiscc** [comment]
There is a continued fork of the original requestpolicy (development halted in 2012) at https://github.com/RequestPolicyContinued/requestpolicy/ https://requestpolicycontinued.github.io/, work in progress

**Comment by Zegnat** [comment]
We got an answer from the Disconnect team. Here we go:

> Thanks for writing us, and sorry for confusion. Disconnect's extensions are still open source, our small team has just been insanely busy with new products. We have a plan to open source the new app, but two of our developers have been on vacation out of the country and we ran into some legal complications and an issue with people abusing our VPN servers. We'll publish the source on our github as soon as those problems are worked out.
> 
> In the meantime, we'll put up a page mentioning what's going on and letting folks know we're relying on OpenVPN, except on iOS where we use the built-in OS VPN.
> 
> Thanks, and let us know if there are any other questions!
> Eason Goodale

**Comment by wolftune** [comment]
I'm glad I read through this whole page. Could someone please at least edit the title here or close this or otherwise make it clear that Disconnect is not specifically going proprietary (as far as we know, given that e-mail reply above)

**Comment by Zegnat** [comment]
Very few open-source licenses prevent you from selling anything. In fact, you could clone PRISM-Break and start selling access to your fork. They could easily open-source all their code and charge for VPN use or access to their support. I do agree that we can modify the title here, and Disconnect is a bit of a ‘pending’ project ’til this is cleared up.

[The last commit](https://github.com/disconnectme/disconnect/commit/dd58f23bdf85e98e27694beb2f7b3fc534aacf5f) was a week ago, after our discussion here, but didn't do anything except commenting out a feature.

**Comment by wolftune** [comment]
Indeed, there's no wrong in them charging for access to a fully free/open program, but it's not clear whether the premium features will actually be under free/open terms

**Comment by Zegnat** [comment]
I am going to close this issue now. The browser add-on PRISM Break links to is still [available as is](https://disconnect.me/disconnect) and matches (at least the download I checked) the latest GitHub commit.

The Disconnect website also makes it clear now that only the browser add-ons are currently open-source on their [open source page](https://disconnect.me/opensource). PRISM Break is **not** recommending people use any of the other Disconnect applications.

If it looks like Disconnect is no longer going to be working on open source add-ons at all (e.g. by not showing any activity the coming month either) I will remove them from PRISM Break for that reason. I hope that’s a suitable middle-ground for everyone.
