### ISSUE TITLE
ello social network

### ISSUE THREAD

**Issue by whooper2** [nylira/prism-break#1217]
What do you think about this social network? Should it be added to the social networks category?

www.ello.co

http://en.wikipedia.org/wiki/Ello_%28social_network%29

**Comment by strugee** [comment]
No, because Ello is not free and open source software and even if it was, it would need to support federation in order to be useful. Ello's goals are noble, but no matter what they do you're still handing over your data to a third party.

**Comment by Zegnat** [comment]
Closing this, basically because of what @strugee also wrote.
