### ISSUE TITLE
Add also Seamonkey and Palemoon (web browsers)

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1220]
Hi everybody,
I think that Palemoon and Seamonkey could be added to PRISM Break:
- Seamonkey is the continuation of the former Mozilla Application Suite, based on the same source code http://thelinuxrain.com/articles/seamonkey-more-than-a-web-browser
- Palemoon is a Firefox fork, that uses the old UI, it has some "unuseful" code removed and will NOT supports  DRMs: http://www.phoronix.com/scan.php?page=news_item&px=MTY5NzM   http://www.ghacks.net/2014/05/21/palemoon-author-confirms-browser-will-ship-eme-ads-australis/

Remeber that their developement process does not follow Firefox's one, so it's not the same thing as Iceweasel, that is a rebranded version of Firefox.

**Comment by Zegnat** [comment]
Note that PRISM Break is about quality and not quantity, as such we are trying not to accept to many duplicates and would rather recommend the one clear winner. Could you tell us why Seamonkey and Palemoon would replace Firefox on the list?

* [SeaMonkey](http://www.seamonkey-project.org/) is a great suite and picked up where Mozilla left off. I have nothing but respect for the people working on the project, however I also have a hard time seeing where it would fit in on PRISM Break. Can SeaMonkey’s email client win over Thunderbird? Does it have access to great GPG integration and TorBirdy? Why would you want to replace Thunderbird with SeaMonkey?
  
  And is its browser any better than the current Firefox browser? Is SeaMonkey running on their own fork of Gecko or just running the latest from Mozilla? Will it offer anything above and beyond what Firefox does, including the many addons PRISM Break recommends?

* [Pale Moon](http://www.palemoon.org/) (and its Thunderbird fork [FossaMail](http://www.fossamail.org/) to some extend) looks like an extremely opinionated fork of Firefox. There is nothing wrong with that, of course, it is one of the great things about open-source software. They loved the old interface and didn’t change it and instead focussed on cutting out unneeded cruft to speed up the browser.

  But I see no mention of them working to enhance security. Your link says they will not implement DRM and that may be good from a philosophical standpoint but doesn’t change security one bit.

It is getting late and I’m not extremely sharp, so maybe there is information on the respective profile pages that I have completely neglected to read. If that is the case, please point me at it!

**Comment by Zegnat** [comment]
Closing now for lack of activity, if someone has good and new points for the inclusion of SeaMonkey/Pale Moon please request for this issue to be reopened or open a pull request for the project you want to see included.
