### ISSUE TITLE
Social Network Category Broken

### ISSUE THREAD

**Issue by thomasrive** [nylira/prism-break#1221]
![prism](https://cloud.githubusercontent.com/assets/6116249/5840580/8f0bfc40-a164-11e4-9754-8c71bb308f05.png)
The social network category is broken. Clicking on the category social network does not cause the page to jump to the social network section. In addition it seems the title is also missing as compared to the visible title for SIP Servers.

**Comment by nylira** [comment]
It's broken for you because you have an adblock plugin of some sort installed, which deletes from the page if they're related to Social Networking. Try disabling the addon for prism-break.org and you should see the title and functionality will return.
