### ISSUE TITLE
[Productivity] TagSpaces

### ISSUE THREAD

**Issue by uggrock** [nylira/prism-break#1226]
[**TagSpaces**](http://www.tagspaces.org)
- [Source](https://github.com/tagspaces/tagspaces)
- [AGPLv3](https://github.com/tagspaces/tagspaces/blob/master/LICENSE)

---

TagSpaces is an open source project which can be used as a free alternative to Evernote. It is working completely locally on your computer,  currently offering packages for Window, Linux and Mac OS X available on http://tagspaces.org

**Comment by yegortimoshenko** [comment]
Domain is dead, source code has not been updated since July 15.

**Comment by uggrock** [comment]
Domain is not dead, there is a recent blog post https://www.tagspaces.org/blog/tagspaces-next/ , explaining that the team is working on a new version of the application.

**Comment by Hillside502** [comment]
@yegortimoshenko 

> Domain is dead, source code has not been updated since July 15.

Not only is the domain **not** dead, but nothing in the source matches "July 15"

https://github.com/tagspaces

**Comment by yegortimoshenko** [comment]
Well:

* https://github.com/tagspaces/tagspaces, last updated on July 15
* http://tagspaces.org does not respond, but https://www.tagspaces.org does

**Comment by Hillside502** [comment]
@yegortimoshenko 

Please re-open this issue, as it is **very** surprising that TagSpaces has not been properly considered in the last **3 years**.

PRISM Break has **indeed** been riddled with unanswered/ignored/not-followed-through suggestions for inclusion.

Thank You, Yegor --- for all the methodical pruning and updating thus far.

TagSpaces should be treated as "Watch this space" regarding their recent announcements.

**Comment by yegortimoshenko** [comment]
The only concern that remains is that there is no publicly available source code for the new version. @uggrock, is the new version free software?

**Comment by yegortimoshenko** [comment]
> Thank You, Yegor --- for all the methodical pruning and updating thus far.

Thanks! :-)

**Comment by Hillside502** [comment]
Why do we think the licence might have changed?
https://github.com/tagspaces/tagspaces/blob/master/LICENSE

**Comment by yegortimoshenko** [comment]
Because repository with the new version that uses React is not available.

**Comment by uggrock** [comment]
As soon as we have a stable version of the react app, we plan to publish it on Github under AGPL or similar license.

**Comment by alerque** [comment]
@uggrock Can we close this issue until such a  time as eligibility for inclusion could be considered? Right now there is nothing actionable for review here so I don't think having an open issue makes sense.

**Comment by uggrock** [comment]
The react version of the the app is already on Github, published under AGPL https://github.com/tagspaces/tagspaces/tree/develop
