### ISSUE TITLE
Languages don't work 

### ISSUE THREAD

**Issue by piks3l** [nylira/prism-break#1230]
When clicking on the links to change languages it ends up back on /en/

**Comment by vyp** [comment]
Can confirm. Even directly going to https://prism-break.org/ar/ ends up back to /en/.

**Comment by nylira** [comment]
Thanks for the report. I've fixed this for most languages by editing my nginx config.

Oddly though, /ar/, /eo/, and /es/ fail to work still. Any thoughts?

**Comment by Zegnat** [comment]
Looking at my last build locally eba821602e6b141eb3144107ae6143eb4e05fa78 doesn’t seem to show any problems, all those folders exist and have index.html files in them. Might be an nginx specific thing going on? Could the nginx configuration be included in the repo, maybe besides the Apache `.htaccess` file, so everyone can take a look?

**Comment by nylira** [comment]
It's really a server-specific thing so it doesn't belong in the repository. Here is mine though:

    server {
      listen [::]:80;
      listen 80;

      # listen on both hosts
      server_name prism-break.org www.prism-break.org;

      # and redirect to the https host (declared below)
      # avoiding http://www -> https://www -> https:// chain.
      return 301 https://prism-break.org$request_uri;
    }

    server {
      listen [::]:443 ssl spdy;
      listen 443 ssl spdy;

      # listen on the wrong host
      server_name www.prism-break.org;

      # prism-break ssl
      ssl_certificate /etc/nginx/ssl/prism-break.org/ssl.combined.crt;
      ssl_certificate_key /etc/nginx/ssl/prism-break.org/ssl.key;

      # and redirect to the non-www host (declared below)
      return 301 https://prism-break.org$request_uri;
    }

    server {
      listen [::]:443 ssl spdy;
      listen 443 ssl spdy;

      # The host name to respond to
      server_name prism-break.org;

      # prism-break ssl
      ssl_certificate /etc/nginx/ssl/prism-break.org/ssl.combined.crt;
      ssl_certificate_key /etc/nginx/ssl/prism-break.org/ssl.key;

      # Path for static files
      root /var/www/prism-break.org/public;

      location = / {
        try_files $uri $uri/ /index.html;
        return 301 http://prism-break.org/en;
      }

      #Specify a charset
      charset utf-8;

      # Custom 404 page
      error_page 404 /404.html;

      # Include the basic h5bp config set
      include h5bp/basic.conf;
    }

**Comment by vyp** [comment]
I believe this has been fixed. :)
