### ISSUE TITLE
File Storage & Sync addition

### ISSUE THREAD

**Issue by Oweoqi** [nylira/prism-break#1231]
In the File Storage & Sync section, please consider adding Syncthing (http://syncthing.net/)

**Comment by aleksandar-todorovic** [comment]
Seems like a pretty good thing to me.

**Comment by Zegnat** [comment]
Please see #937 for the discussion and #1131 for the pull request. Feel free to breath new life into those issues to get Syncthing accepted.

Closing this as a duplicate.
