### ISSUE TITLE
Where Seeks gone?

### ISSUE THREAD

**Issue by GreenLunar** [nylira/prism-break#1233]
Here https://prism-break.org/en/all/

But not here https://prism-break.org/en/protocols/ssl-tls/

**Comment by Zegnat** [comment]
How do Seeks nodes talk to each other? Is that communication SSL/TLS encrypted? I can’t say I know why Seeks doesn’t have the SSL/TLS protocol set, but I guess the original contributor had a reason for it.

If Seeks is using SSL/TLS for all its communications this is clearly an oversight, can you point to some article or anything that shows Seeks should have the SSL/TLS protocol set?

**Comment by GreenLunar** [comment]
I suggest to add another category (for example, see #1234) where search engines and, maybe, other online services be listed under, so that projects such as Seeks would not be somewhat hidden.

**Comment by Zegnat** [comment]
Closing this if it is just about Seeks being ‘on the list’. If Seeks is set-up to use SSL/TLS please make a pull request to add that tag to the project. Like I said in #1234, there is already a page for [web services](https://prism-break.org/en/categories/web-services/) as well as one for GNU/Linux compatible [web search](https://prism-break.org/en/subcategories/gnu-linux-web-search/) engines where Seeks is part of.

**Comment by GreenLunar** [comment]
https://seeks.ru/ (HTTPS)

Is it qualified to be listed under SSL/TLS?
