### ISSUE TITLE
Add /services/ for online services

### ISSUE THREAD

**Issue by GreenLunar** [nylira/prism-break#1234]
Add https://prism-break.org/en/services/

Categorizing services such as search engines under /protocols/ssl-tls/ is confusing.

**Comment by Zegnat** [comment]
This has existed for a long time, I guess it is just a bit hard to find: [/categories/web-services/](https://prism-break.org/en/categories/web-services/). The protocols section is more as a quick way to find applications supporting certain encryption systems, like quickly listing [everything that supports PGP](https://prism-break.org/en/protocols/gpg/) no matter their category.
