### ISSUE TITLE
[Instant Messaging] [Video and Voice] Signal 2.0 for iOS now supports text messaging.

### ISSUE THREAD

**Issue by annonman** [nylira/prism-break#1239]
Updated just today, Signal supports text AS WELL AS voice.

https://itunes.apple.com/us/app/signal-private-messenger/id874139669?mt=8

https://whispersystems.org/blog/the-new-signal/

Github:
https://github.com/WhisperSystems/Signal-iOS

Signal is FOSS by Open Whisper Systems.  It offers cross-platform text communication between Android (TextSecure) and voice via RedPhone on Android.

**Comment by annonman** [comment]
Is there any reason Signal is not included?

**Comment by strugee** [comment]
See #552

**Comment by yegortimoshenko** [comment]
Duplicate of #552, #896, #1314, #1667.
