### ISSUE TITLE
Add MediaGoblin

### ISSUE THREAD

**Issue by nicolasrpmaia** [nylira/prism-break#1242]
IMO MediaGoblin should be added to the Media Publishing section. Is there any reason not to?

**Comment by nodiscc** [comment]
I like mediagoblin but to be fair, the last time I _tried_ to install it, it was a nightmare. The install process and required environment are complex.

**Comment by nylira** [comment]
MediaGoblin is in the server section, because it requires self hosting. https://prism-break.org/en/projects/mediagoblin/
