### ISSUE TITLE
Add ProtonMail

### ISSUE THREAD

**Issue by marcostudios** [nylira/prism-break#1244]
protonmail.ch should be here :)

**Comment by mastercoms** [comment]
I don't think proton mail is open source.

**Comment by aleksandar-todorovic** [comment]
No code online -> Should not be included.
This is a proprietary service. I see no point of adding it to this project.

**Comment by jzakiya** [comment]
I have a Proton Mail account.
I emailed them this question and the response I received was they intend to be open source in the future, but currently don't know under what license.

**Comment by aleksandar-todorovic** [comment]
Well, then there's nothing we could do about it. Once they select their
license and publish their code, we could consider it to be a part of
prism-break. Right now, no way.

**Comment by mva1985** [comment]
It may not be open source but it certainly seems like proton mail & unseen.is have some good things going for them and I would encourage anyone to get an account with both

**Comment by mva1985** [comment]
I have a couple invite links to keybase.io if anyone wants one 

keybase.io/mva1985

**Comment by Zegnat** [comment]
The only email services PRISM Break is currently recommending have been around for years proving themselves (Riseup and A/I) or use open-source software in combination with clear guidelines (Kolab Now).

Services like Protonmail and Unseen might be good, but they are rolling their own unpublished encryption set-ups and that’s not for PRISM Break. Closing this.
