### ISSUE TITLE
[Add Category] Secure Video Chat/Conferencing

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1248]
I would like to request consideration for adding this category to list.
Here are two candidates.

https://talky.io/

https://jitsi.org/
https://meet.jit.si/

**Comment by Zegnat** [comment]
There is a category called Video & Voice, and Jitsi is in it.

It doesn’t look like Talky is open-source. PRISM Break limits itself to open-source solutions so I don’t think it will be added.
