### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by IordanIordanow** [nylira/prism-break#1252]
Hello there prism-break.org
l like your page and been a fan and follower for a long time.
However the website is not translated in my native language so l would like to translate it in it.

l would like to volunteer and do this as soon as possible :)
my email is iordaniordanovv@tutanota.de

l look forward for looking from you.
Peace

**Comment by Zegnat** [comment]
Hi @IordanIordanow, sorry for being late. Thanks for your interest! PRISM-Break is open to translations from anyone, [CONTRIBUTING.md](https://github.com/nylira/prism-break/blob/master/CONTRIBUTING.md#contribute-localizations) includes some tips on how to get started.

I am going to close this issue as it isn’t really an issue.
