### ISSUE TITLE
Include link to Firefox settings recommendations on Firefox's page

### ISSUE THREAD

**Issue by nodiscc** [nylira/prism-break#1254]
https://github.com/pyllyukko/user.js

> This is a user.js configuration file for Mozilla Firefox that's supposed to harden Firefox's settings and make it more secure.

I'd like if the `Security Notes` section on https://prism-break.org/en/projects/mozilla-firefox/ could point to this project with a text like:

> As they are optimized for a wide audience, usability and convenience, Firefox's default configuration settings are not always set to the most secure values, or do not enforce strong privacy. See https://github.com/pyllyukko/user.js for recommendations on how to make your Firefox setup more robust.

As you can see in https://github.com/pyllyukko/user.js/blob/master/user.js, each configuration setting is clearly documented so users have the choice to alter their config or stick with the defaults.

This was originally discussed at https://github.com/nylira/prism-break/issues/1031

**Comment by wifiextender** [comment]
I agree that further tweaks are needed. Here are my preferences that I have been collecting for a long time https://github.com/wifiextender/dotfiles/blob/master/archlinux-openbsd/usr/lib/firefox/browser/defaults/preferences/vendor.js

The online test provided by EFF at Panopticlick is really useful as it determines how distinctive is your firefox browser among the other users out there, any score above than 12 or 15 means you can be identified with approximate accuracy.

**Comment by wifiextender** [comment]
The default firefox configuration comes with "light theme" enabled, but there are 2 radio buttons that will allow you to choose between dark and light themes out of the box. To enable the dark theme in **about:config**, exchange `browser.devedition.theme.enabled` to **true**. Now press F12 and click over the gear icon that has a tooltip saying "Toolbox Options" and choose "Dark Theme".

![screenshot 29e5d8e81c11](https://cloud.githubusercontent.com/assets/4725121/7082606/330fa26e-df46-11e4-836b-22fd68380c72.jpg)

**Comment by nodiscc** [comment]
> The default firefox configuration comes with "light theme", but there are 2 gtk radio buttons that will allow you to choose between dark and light themes out of the box

I don't think this is relevant to this project, I was talking specifically about security/privacy related settings (as discussed in https://github.com/nylira/prism-break/issues/1310)

**Comment by wifiextender** [comment]
Hello @nodiscc ,

There is no way to predict what the different user cases will be. If you insist on the inclusion of such settings, the casual computer users may have hard time finding why the particular website is not working properly anymore.

That is why all of you should participate in much "heated" discussion and outline which lines of code should be included in prism-break. You can borrow code from my **vendor.js** that is not presented in the pyllyukko' project.

As for a user-friendly installtion, a dead simple addon should do the work, and it will be platform independent too.

I would like to dedicate more time on my wife and children, don't have the time to be a part of the prism-break society.

Cheers

**Comment by myrdd** [comment]
> edit: Or addon with different profiles targeting different user groups. Simple - casual users, Expert - power-users and so on. Or addon with checkboxes explaining what it will do if the user checked the particular checkbox.

Sounds good! maybe there is already an addon like that?
It would be great if there would be some high-level options, in order to abstract different use cases from the actual preferences; at the same time, giving the option to set each pref separately.

**Comment by nodiscc** [comment]
> As for a user-friendly installtion, a dead simple addon should do the work, and it will be platform independent too.

Yes.

> It would be great if there would be some high-level options, in order to abstract different use cases from the actual preferences; at the same time, giving the option to set each pref separately.

[Random Agent Spoofer](https://addons.mozilla.org/en-us/firefox/addon/random-agent-spoofer/) does some of this (check 8th screenshot)

> There is no way to predict what the different user cases will be. If you insist on the inclusion of such settings, the casual computer users may have hard time finding why the particular website is not working properly anymore.

Yes, pyllyuko's config needs to be tested, and some settings may be relaxed if it causes too much functionality to break (prism break compliant fork?)

> You can borrow code from my [vendor.js](https://github.com/wifiextender/dotfiles/blob/master/archlinux-openbsd/usr/lib/firefox/browser/defaults/preferences/vendor.js)

Some of your settings could be added to the user.js project, or to a possible fork.
