### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1255]
Since the prism-break community is already quite large, I'd say we should set up a small code of conduct and add it to the README, so that people are aware of what is expected of them when discussing on the issue tracker.

Examples include:
https://en.opensuse.org/openSUSE:Conference_code_of_conduct
https://wiki.gentoo.org/wiki/Project:Council/Code_of_conduct
https://www.debian.org/code_of_conduct

It probably shouldn't be that verbose, but short and expressive.

I am thinking of something along these lines:
* be helpful and collaborative
* respectfully disagree
* don't get personal, stick to the factual level
* don't unnecessarily incite drama or negativity

In my opinion strong and heated arguments are helpful, if they stay on the factual level and help moving the discussion forward. That's why I wouldn't add unnecessary "love each other" phrases (although people may do that if they want).

**Comment by Draxler** [comment]
:+1:

**Comment by strugee** [comment]
> That's why I wouldn't add unnecessary "love each other" phrases (although people may do that if they want).

IMHO, we should at least recommend this, even if we don't require it. Some people have a lower tolerance for language directed "against" them, and it'd be nice to try to help them, even if we don't bend over backwards.
