### ISSUE TITLE
Should PRISM Break talk about best use practices of / how to use the recommended software?

### ISSUE THREAD

**Issue by wifiextender** [nylira/prism-break#1256]
Hello everyone,

Do you think it is worth to note the people that full disk encryption with dm-crypt and LUKS is not enough, as they will have to move their **boot** partition to removable devices or CD/DVD, because that partition is [not encrypted](http://en.wikipedia.org/wiki/Full_disk_encryption#The_boot_key_problem) and everyone with real access to the their hardware (seized computer for example) can [pwn](https://twopointfouristan.wordpress.com/2011/04/17/pwning-past-whole-disk-encryption/) the encryption as the encryption keys are stored there.

Best regards,
Aaron Caffrey

**Comment by Zegnat** [comment]
I personally think this is outside of PRISM Break’s scope. PRISM Break was not set-up to tell people *how* to use software, only what alternative software they may consider using. Explaining how to encrypt your machine in a tamperproof way in case of theft etc is up to the projects themselves.

This applies to everything, even outside of drive encryption. Editing the title to reflect the core discussion.

**Comment by mastercoms** [comment]
Well, I think that it should added in as a note, since we already recommend to use dm-crypt + LUKS.

**Comment by wifiextender** [comment]
Hello Martijn,

You've made a good point that it is reasonable everyone to be aware
how-to do certain thing, but that would be far from the scope of the project.

Cheers
