### ISSUE TITLE
Broken links in /about/media page

### ISSUE THREAD

**Issue by smonff** [nylira/prism-break#1260]
Some links are broken because the target website don't exist anymore, or because of editing typos (looks like copy & paste things mostly :+1: ).
I'm a volunteer to fix this. 
Sometimes, backups exists at archive.org : is it ok to use it (I mean, is archive.org a prism-break-compatible infrastructure?) or should I remove the link if nothing else is available?

**Comment by vyp** [comment]
I cannot speak for nylira, but if you want to start doing something, it's highly likely nylira would accept archive.org links.

I'm not sure what nylira would want about the dead links though, so maybe note down which ones they are, but keep them there for now, until he responds.

**Comment by nylira** [comment]
archive.org links would be great.

On Mon, Mar 23, 2015 at 8:21 PM, RWS <notifications@github.com> wrote:

> I cannot speak for nylira, but if you want to start doing something, it's
> highly likely nylira would accept archive.org links.
>
> I'm not sure what nylira would want about the dead links though, so maybe
> note down which ones they are, but keep them there for now, until he
> responds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylira/prism-break/issues/1260#issuecomment-84970238>.
>



-- 
Peng Zhong
Interaction Designer & Developer

Designer at http://nylira.com
Curator at https://prism-break.org
GitHub: https://github.com/nylira
LinkedIn: https://www.linkedin.com/in/nylira

**Comment by strugee** [comment]
@vyp looks like this is resolved given the above PR, yes?

**Comment by smonff** [comment]
[Another 404](http://www.srf.ch/k.text-blocktur/im-fokus/weblese/surfen-ohne-dass-die-nsa-zuschaut). Should link to http://www.srf.ch/kultur/netzwelt/surfen-ohne-dass-die-nsa-zuschaut.

Ref. #1324

**Comment by vyp** [comment]
There are still some broken links on the page.. see #1324.

**Comment by smonff** [comment]
[Schieb, Jörg.“Wie bewege ich mich sicher im Netz?](http://www1.wdr.de/fernsehen/aks/rubriken/angeklickt/angeklicktsichersurfen100.html) can link to https://web.archive.org/web/20141003211621/http://www1.wdr.de/fernsehen/aks/rubriken/angeklickt/angeklicktsichererimnetz100.html

**Comment by smonff** [comment]
[Garcia, Oskar.“NSA Revelations Reframe Digital Life for Some.”ABC](http://www.slate.com/blogs/future_tense/2013/06/17/identi_ca_diaspora_and_friendica_are_more_secure_alternatives_to_facebook.html) links to the next Slate paper. Didn't  find the right paper on ABC or archive.org

**Comment by smonff** [comment]
[Luckerson, Victor.“The Anonymous Internet: Privacy Tools Grow in Pop.text-blockarity Following NSA Revelations](http://business.time.com/2013/06/20/the-anonymous-internet-privacy-tools-grow-in-pop.text-blockarity-following-nsa-revelations/) should link to http://business.time.com/2013/06/20/the-anonymous-internet-privacy-tools-grow-in-popularity-following-nsa-revelations/

**Comment by strugee** [comment]
Neat, let's leave it open then :P

**Comment by alerque** [comment]
@strugee Why leave it open when we can fix it ;-) (PR about to follow.)

@smonff That Oskar one looks like the Slate article might have changed names since original publishing, hence the URL slug miss-match. Perhaps there isn't an issue with that one?

**Comment by vyp** [comment]
Thank you everyone! :smiley: 

@alerque I think so to because the page does mention prism-break.org.

Closing thanks to #1610.
