### ISSUE TITLE
Recommend hardware (specifications)

### ISSUE THREAD

**Issue by Wurstertoast** [nylira/prism-break#1264]
What about recommending not only software but hardware. Thinking about buying a new laptop I am thinking not only about the hardware specifications for a fast system, but also how the hardware can be affected with security issues. I don't really have a clue what it all means, but heard something of Secure Boot, Bios Password, TPM and other things. What I have to think of buying new hardware, laptops or desktop PCs?

**Comment by hasufell** [comment]
https://github.com/nylira/prism-break/issues/611
https://github.com/nylira/prism-break/issues/788
https://github.com/nylira/prism-break/issues/989

**Comment by Wurstertoast** [comment]
Ok thank you for this hint. I am not used to github and apologize for the circumstances.

**Comment by mastercoms** [comment]
It's fine. I guess you can close the issue now.
