### ISSUE TITLE
uBlock changes

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1266]
uBlock's new website is https://chrismatic.io/ublock/.  
As signified by the newest update, https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.0, uBlock's main development has been transferred to chris.  
gorhill's ublock is now a fork of chris' ublock, and it has not been updated as fast as the main fork, nor will it be.

**Comment by wifiextender** [comment]
Hello mastercoms,

It would be nice if you propose a pull request with the exchanged link.

Cheers

**Comment by Zegnat** [comment]
There you go.
