### ISSUE TITLE
Add Orweb

### ISSUE THREAD

**Issue by sedrubal** [nylira/prism-break#1269]
Is there a reason why I can't find [Orweb](https://github.com/guardianproject/Orweb) on prism-break as suggestion under the Android Browsers?

**Comment by Zegnat** [comment]
There was a discussion about Android browsers in #1148, as I personally did not own a smartphone at all I couldn’t comment and was waiting for PRs to come out of that one.

I guess it comes down to wether we want to recommend Orbot + Firefox or Orweb. Other than that I don’t know any reason not to add Orweb.

**Comment by sedrubal** [comment]
Why not recommend both? I'll create a PR...

**Comment by wifiextender** [comment]
Hello sedrubal,

[Orbot](https://gitweb.torproject.org/orbot.git) + Firefox seems rock solid combination as both projects are in constant development, so my vote goes for those two projects.

On the other hand, the default firefox configuration will leak too many fingerprints that will identify you.

Cheers

**Comment by sedrubal** [comment]
but why should we only support one browser?

**Comment by mastercoms** [comment]
Because firefox is the only trusted one.

**Comment by sedrubal** [comment]
I trust [The Guardian Project](https://guardianproject.info/) too. Their slogan is "Mobile Apps and Code You Can Trust" :D

**Comment by strugee** [comment]
Orweb is on PRISM Break now.
