### ISSUE TITLE
add DNSChain to DNS Software

### ISSUE THREAD

**Issue by wemeetagain** [nylira/prism-break#1274]
DNSChain is a server middleware, to be used to serve blockchain-based domains (.bit, etc) over DNS and HTTPS.
It can act as a blockchain and traditional domain DNS server, as well as a web-served blockchain lookup. This lets users both access domains blockchain domains and conveniently look up blockchain-stored information.
https://github.com/okTurtles/dnschain

**Comment by juanito003** [comment]
Does it require okTurtles browser extension installed in firefox to navigate on https website and .bit, .p2p domains?

**Comment by WeMeetAgain** [comment]
No, to access .bit, etc. would only require adding a DNSChain as one of your computer's DNS resolvers.

Users are encouraged to run their own DNSChain or use one of a friend, though there are some publicly run servers listed [here](https://github.com/okTurtles/dnschain/blob/master/docs/How-do-I-use-it.md#free-public-dnschain-servers).

**Comment by yegortimoshenko** [comment]
Closing, given that it hasn't been updated since 1 April 2016.
