### ISSUE TITLE
Add devosi.org multi-platform

### ISSUE THREAD

**Issue by mario26** [nylira/prism-break#1280]
Devosi is a community promoting Free Software and Anonymity on the Internet. It offers several services, mail herbergement, jabber / XMPP, social network with Movim, Youtube clone with Cumulusclip and a wiki to self-help.

http://www.devosi.org

Thank you to add to selection Prism Break

**Comment by yegortimoshenko** [comment]
This one only has a French website, so wouldn't really work for most of PRISM Break's visitors.
