### ISSUE TITLE
Remove Open Source Routing Machine

### ISSUE THREAD

**Issue by eloydegen** [nylira/prism-break#1281]
I think that the Open Source Routing Machine can be removed from the website, since OSM.org itself does include routing since a while. OSM uses OSRM algorithm, I think, looking at the dropdown menu on the website.

**Comment by Zegnat** [comment]
@eloydegen, has OSRM been merged into the OSM source or is it just their website using it?

Although OSRM is used on the OSM website, I believe OSRM has not been merged into the project source. People who want to run their own instance of OSM will still need to obtain and install OSRM separately. That’s what it looks like to me at least.

**Comment by nodiscc** [comment]
@Zegnat you're correct.

**Comment by Zegnat** [comment]
Thanks for the second set of eyes @nodiscc. On your confirmation, I can say I will not be removing OSRM.
