### ISSUE TITLE
Update all Google Code repository links.

### ISSUE THREAD

**Issue by erdoukki** [nylira/prism-break#1282]
code.google.com is closing.

Cryptsetup links need update.
The main project is now on gitlab.

Old links :
1: https://code.google.com/p/cryptsetup/source/browse/
2: https://code.google.com/p/cryptsetup/source/browse/COPYING

New links:
Main project at: https://gitlab.com/cryptsetup/cryptsetup
Source : https://gitlab.com/cryptsetup/cryptsetup/tree/master

The license is now reffered in the FAQ
https://gitlab.com/cryptsetup/cryptsetup/blob/master/FAQ
https://gitlab.com/cryptsetup/cryptsetup/wikis/FrequentlyAskedQuestions#1-general-questions
http://creativecommons.org/licenses/by-sa/3.0

**Comment by Zegnat** [comment]
> code.google.com is closing.

I know, been planning to go over the links but haven’t had the time yet. There are several links to Google’s code repositories on PRISM Break and I would love to try and fix them all in one go.

Thanks!

**Comment by wifiextender** [comment]
Hello erdoukki and Martijn,

I have visited all the platforms and project links, exchanged the broken links, and others that have moved their developement almost a month ago - [1](https://github.com/nylira/prism-break/commit/496a1ec67893a6431a73fb720e805caa8729a40a), [2](https://github.com/nylira/prism-break/commit/82eea7bef006f456003676b2f30f129a5c6a144e) . Unfortunately I had enough free time to compare the their official website links.

erdoukki, it would be great if you can help us out by visiting all the platforms, project licenses and source code links and then propose a pull request with the exchanged links.

Cheers
