### ISSUE TITLE
password manager

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1284]
Hello,

This will be a simple 'howto' create LUKS encrypted file system **within** a single file that will act as password database, no need for remote applications or complicated compiling with gazillion dependencies.

Create the file with `dd if=/dev/urandom of=cryptdb bs=1MB count=25`

Next create cryptographic device mapper device in LUKS encryption mode `cryptsetup --verbose --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --use-random luksFormat cryptdb`

Unlock the database in order to create file system and then mount it:

```
cryptsetup open --type luks cryptdb database
mkfs.ext4 /dev/mapper/database
mount -t ext4 /dev/mapper/database /mnt
```

Now transfer your passwords in **/mnt**. Once done unmount the database and close the device:

```
umount /mnt
cryptsetup close database
```

If you want even greater security just GnuPG the database with:

```
# Copy the 'pub' one
gpg --keyid-format long --list-keys your@email.addr
gpg --hidden-recipient PUB_KEY_GOES_HERE --encrypt cryptdb
```

From now on just unlock the database, mount it, transfer the passwords, unmount and close it. If you want to automate this process, feel free to borrow the crypto functions from my [dotfiles repository](https://github.com/wifiextender/dotfiles/tree/master/archlinux-openbsd/home/frost/.config/zsh/functions)

Next month will post in my blog archlinux installation with full disk encryption.

edit: The blog post http://wifiextender.github.io/post/install_arch_with_full_disk_encryption/

Cheers

![this](https://cloud.githubusercontent.com/assets/4725121/7332282/18712eca-eb38-11e4-8d7d-aa93611366a7.png)

**Comment by yegortimoshenko** [comment]
This is not an application we can suggest, nor it's something approachable for most users, but rather a set of instructions that only few would be able to follow. Result is similar to [pass](https://prism-break.org/en/projects/pass/). Safe to close.

**Comment by strugee** [comment]
Agreed. This is not usable.

**Comment by strugee** [comment]
Btw @yegortimoshenko, thanks for going through looking for old issues. I've done that myself a couple times but have never had time to make a really thorough pass. This is great.
