### ISSUE TITLE
some suggestions/additions

### ISSUE THREAD

**Issue by gunnersson** [nylira/prism-break#1285]
Dear all,

I think it could be worth to have a look at:

https://github.com/gorhill/uBlock
uBlock Origin (or uBlock₀) is not an ad blocker; it's a general-purpose blocker. uBlock₀ blocks ads through its support of the Adblock Plus filter syntax. uBlock₀ extends the syntax and is designed to work with custom rules and filters.
That said, it's important to note that using a blocker is NOT theft. Don't fall for this creepy idea. The ultimate logical consequence of blocking = theft is the criminalisation of the inalienable right to privacy.
Ads, "unintrusive" or not, are just the visible portions of privacy-invading apparatus entering your browser when you visit most sites nowadays. uBlock₀'s main goal is to help users neutralize such privacy-invading apparatus — in a way that welcomes those users who don't wish to use more technical, involved means (such as µMatrix).

https://github.com/chrisaljoudi/uBlock
uBlock is a general-purpose blocker — not an ad blocker specifically.
uBlock blocks ads through its support of the Adblock Plus filter syntax. uBlock extends the syntax and is designed to work with custom rules and filters.
uBlock's main goal is to help users neutralize privacy-invading apparatus — ads being one example.

https://github.com/muzuiget/referrer_control
Referrer Control is Firefox extension to control HTTP request referrer.

https://github.com/CipherShed/CipherShed
Cross-platform on-the-fly encryption software.
For more information, please see our website at https://ciphershed.org.

https://github.com/veracrypt/VeraCrypt
This archive contains the source code of VeraCrypt. It is based on original TrueCrypt 7.1a with security enhancements and modifications.

https://github.com/lieser/dkim_verifier
This is an add-on for Mozilla Thunderbird that verifies DKIM signatures according to the RFC 6376.
More Information in the wiki at https://github.com/lieser/dkim_verifier/wiki

https://github.com/Neo23x0/Loki
Loki - Simple IOC Scanner
Scanner for Simple Indicators of Compromise
Detection is based on four detection methods:
1. File Name IOC
   Regex match on full file path/name
2. Yara Rule Check
   Yara signature match on file data and process memory
3. Hash check
   Compares known malicious hashes (MD5, SHA1, SHA256) with scanned files

https://github.com/E3V3A/Android-IMSI-Catcher-Detector
Detect and avoid IMSI-Catchers, StingRay and Silent SMS - with AIMSICD!
https://secupwn.github.io/Android-IMSI-Catcher-Detector/

https://github.com/E3V3A/snoopsnitch
This is the SnoopSnitch source repository. SnoopSnitch collects and analyzes
mobile radio data to make you aware of your mobile network security and to warn
you about threats like fake base stations (IMSI catchers), user tracking and
over-the-air updates.

Thank you,

Gunner

**Comment by gunnersson** [comment]
<http://www.adlice.com/softwares/roguekiller/>
RogueKiller is an anti-malware program written in C++ and able to detect and remove generic malwares and some advanced threats such as rootkits, rogues, worms, …
Based on generic ways to find malware by their behaviour (heuristics), on classic anti-malware analysis (signature finding) and on undocumented hacks, RogueKiller can find/remove most of the basic malware (rogues, trojans, …) and some advanced threats like ZeroAccess or TDSS that behave more like rootkits.
RogueKiller is an anti-malware maintained by a small team, and thus new detections are based on “most spread threats“. We react quickly to integrate detection and removal of what we think can be a global threat and affect a big amount of users across the world.

<https://www.powerfolder.com/de/>
<https://www.powerfolder.com/compare/>
Keep all your devices in sync and easily share documents with others
PowerFolder keeps all your devices automatically in Sync in any network, across multiple users. It ensures that you always have the latest documents right in your hand anywhere and on any device.
Send and Distribute documents and folders of any size, securely  to employees, customers and partners
With PowerFolder you can easily share your documents with others, independent from size, type or location. You   also  can send links to single files or even share complete directories within business network , while keeping all transfers encrypted and secure.
Adjust the level of Collaboration to your demands
Make the collaboration in your teams more efficient and enable your team members to easily work on information with your customers and partners . PowerFolder supports this in the cloud or on-premise to match your demands.
Automatically create a file archive and backup, to prevent data loss
There are many reasons why files can get lost, with PowerFolder you can always restore deleted files and previous versions of documents to ensure a continuous workflow. All files will be automatically secured as a backup in as many versions as you demand.
Centrally manage your permissions, devices and information
Business information needs protection, with PowerFolder you can control who has access to which document, and       with which permission. You can centrally configure devices, control the shares and remote wipe data.
Setup your own High Available, Load Balanced and Branded Sync and Share solution
Have your own collaboration suite branded to match your Cooperate Identity. Make it high available and integrate it seamlessly into your own It Infrastructure via LDAP/ Active Directory and API’s.

<https://addons.mozilla.org/de/firefox/addon/wallabag/>
This Add-on allows you to post URL to your Wallabag instance.
Wallabag is an open-source and self-hosted alternative to Pocket, Instapaper, etc.
More informations at http://wallabag.org

Best wishes,

Gunner

**Comment by Dostoi** [comment]
Hum did you search on the site and github before opening this issue ? (i don't mean to be offending, just asking). Because ublock, and IMSI are already on the site.
For some of the rest the name sound familiar so I think it must have already been spoken on github (like snoopsnitch, veracrypt #1273  and ciphershed)
For wallabag I don't know if it will be accepted as it isn't security related but I'm not speaking in the name of anyone related to the site so ^^

**Comment by mastercoms** [comment]
We have uBlock listed already. 
We already have a discussion on ref control addons #689 
CipherShed -> #995 
And one for VeraCrypt #1273 
GPG is preferrable to DKIM, although it can be considered
Loki does not seem to be prevention for surveillance
IMSI Catcher is already listed
Antivirus -> #727 
PowerFolder is not open source.
Wallabag is not relevant to prism break.

**Comment by gunnersson** [comment]
Well, I check prism-break just once in a while, haven't checked all details for my post...

CipherShed and VeraCrypt: to be seen in comparison...
uBlock Origin (or uBlock₀) and uBlock: to be seen in comparison...
LOKI and Roguekiller: no prevention, right, but great follow-up care
PowerFolder: well, the service is not, but the core is https://www.powerfolder.com/open-source/
Wallabag: why not relevant or related? This is not a security tool, of course. But it offers protection of data privacy.
dkim_verifier: well, it already works...

**Comment by wifiextender** [comment]
Hello Gunner,

1. We are familiar with the German court ruling that made it clear that ads blocking is LEGAL.

2.

```
# Source https://github.com/pyllyukko/user.js/blob/master/user.js
pref("network.http.sendRefererHeader", 1);
pref("network.http.referer.spoofSource", 1);
pref("network.http.sendSecureXSiteReferrer", false);
```

5. [GnuPG](https://en.wikipedia.org/wiki/GNU_Privacy_Guard)

6, 7 and .8 - http://arstechnica.com/information-technology/2015/04/this-machine-catches-stingrays-pwnie-express-demos-cellular-threat-detector/

9. RogueKiller - Throw a bunch of viruses or whatever pile of crap you want in [DeepFreeze](https://en.wikipedia.org/wiki/Deep_Freeze_%28software%29), reboot the computer and the crap will gone. No need for anti-virus software or malwarebytes alternatives or to cross your fingers ever.

Cheers

**Comment by vyp** [comment]
> Wallabag: why not relevant or related? This is not a security tool, of course. But it offers protection of data privacy.

How?

**Comment by mastercoms** [comment]
PowerFolder's message of openness is not expressed clearly and we don't know their mission or intentions.

**Comment by wifiextender** [comment]
It took me a while to find non 404 installation link regarding the PowerFolder open source edition.

What caught my attention is their **recommendation** to:

>Make sure to disable encrypted data transfer in your server preferences to allow unencrypted connections from open source clients.

link - https://wiki.powerfolder.com/display/PFC/Running+the+Open+Source+edition

They have invented their own cryptographic protocol and promote it over the usage of SSL - https://wiki.powerfolder.com/display/PFS/System+Requirements

**Comment by N-siege** [comment]
Hello to everyone,

I suggest the gpg4usb. The gpg4usb is a portable software, open-source, which makes it easy to create, manipulate, write, encrypt and decrypt GPG messages. Compatible with Windows and Linux.

Being portable, it would enable both the program and its data (the keys) can be stored in a container EncFS in other encryption software, or even the discontinued TrueCrypt.

Official site: http://www.gpg4usb.org/
Source Code: https://github.com/gpg4usb/gpg4usb

I hope this become useful.

**Comment by zhr0** [comment]
https://prosody.im/

**Comment by yegortimoshenko** [comment]
uBlock Origin is listed, Referrer Control does not support FF57, CipherShed is abandoned, VeraCrypt has been discussed in #995, #1273, #1612, #1693, by spec DKIM verification should be done at server, Loki is not applicable (no category, not directly privacy-related), Android-IMSI-Catcher-Detector is listed, snoopsnitch is abandoned, roguekiller is proprietary (and subscription-based), PowerFolder is proprietary, Wallabag is listed.

Please look for duplicates, and open one ticket for each software.
