### ISSUE TITLE
pomf.se file hosting

### ISSUE THREAD

**Issue by pejakm** [nylira/prism-break#1293]
https://pomf.se

[Open source](https://github.com/nokonoko/Pomf), user friendly and provides [additional tools](http://p.pomf.se). Blog: http://blog.pomf.se/

**Comment by Dostoi** [comment]
There's an android app for that on F-Droid:
https://f-droid.org/repository/browse/?fdid=science.itaintrocket.pomfshare

**Comment by pejakm** [comment]
> There's an android app for that on F-Droid:

I know, I submitted it. :)

**Comment by RanceJustice** [comment]
I concur this would be a great addition for file hosting! Very usable!

Oh, without creating another topic - MediaCrush's main public hosted server (www.mediacru.sh) has gone offline, but the FOSS project is still up and working. However, a new MediaCrush instance hosted at www.imgrush.com is now running!

**Comment by pejakm** [comment]
pomf.se is closing: http://blog.pomf.se/post/121058516206/shutting-down
Closing issue.

**Comment by contrapunctus-1** [comment]
There appears to be a(tleast one) new instance - https://pomf.cat/
(Complete with warrant canary.)

**Comment by hasufell** [comment]
> WARNING: Our servers are currently hosted in the United States.
