### ISSUE TITLE
Web Pizza - Oninon share like app

### ISSUE THREAD

**Issue by rpgeeganage** [nylira/prism-break#1294]
Hi,
I have created a nodejs based app which has functionality as Onion Share. The main feature is the particular file can be located in a remote location. 
In addition to the onion address, 32 char passcode is required for proper download. 
I like to add to the prism break projects.

**Comment by yegortimoshenko** [comment]
Last updated in May 2015, 17 commits, 1 contributor, safe to close: https://github.com/rpgeeganage/web-pizza-file-share
