### ISSUE TITLE
Mediacru.sh DOWN

### ISSUE THREAD

**Issue by TheMrMelc** [nylira/prism-break#1298]
The image host Mediacrush seems to be [down for everyone](http://www.isitdownrightnow.com/mediacru.sh.html).
Furthermore, their Twitter account confirms the site was [shut down last January](https://twitter.com/mediacru_sh/status/560522635306467328).

**Comment by vyp** [comment]
Mentioned before https://github.com/nylira/prism-break/issues/1293#issuecomment-102273745, but I do think a new issue for it is warranted anyway.

**Comment by Zegnat** [comment]
If someone wants to file a pull request removing it, I will accept it. I just haven’t had the time to go through and fix it yet 😟 Same goes for double checking all Google Code repository links. When the month ends I hope to be able to put some time in again.
