### ISSUE TITLE
Only Office

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1300]
http://www.onlyoffice.com/free-edition.aspx

Online self hostable productivity/office suite software

open source: https://github.com/ONLYOFFICE

**Comment by yegortimoshenko** [comment]
Open core, privately developed (no public commits, only syncs). Nextcloud seems to be better.

**Comment by mastercoms** [comment]
Yes, ownCloud/Nextcloud has improved a lot since 2015. I think I'll close this because I don't think Only Office makes sense as an alternative anymore.

**Comment by yegortimoshenko** [comment]
Agree.
