### ISSUE TITLE
TextSecure / RedPhone / Signal (Open Whisper Systems)

### ISSUE THREAD

**Issue by redtextapps** [nylira/prism-break#1305]
Is there a reason why mobile message encryption apps such as TextSecure and voice encryption apps such as Android's RedPhone and iOS' Signal by Open Whisper Systems (https://whispersystems.org/) are not listed?

TextSecure was tested by https://www.eff.org/secure-messaging-scorecard and received best grades...

**Comment by wifiextender** [comment]
Hello redtextapps,

>Is there a reason why mobile message encryption apps such as TextSecure and voice encryption apps such as Android's RedPhone and iOS' Signal by Open Whisper Systems (https://whispersystems.org/) are not listed?

Does the following [issues](https://github.com/nylira/prism-break/issues?utf8=%E2%9C%93&q=redphone) are still affecting those programs ?

Cheers

**Comment by strugee** [comment]
Duplicate of #896.

In the future, please search for duplicates before filing a new issue.
