### ISSUE TITLE
Firefox will start showing ads on new tab page based on browsing history 

### ISSUE THREAD

**Issue by vyp** [nylira/prism-break#1307]
https://blog.mozilla.org/futurereleases/2015/05/21/help-test-changes-to-new-tab-in-firefox-beta/

---

Random blog post:

http://www.geeksnack.com/2015/05/22/firefox-will-show-ads-based-on-your-browsing-history/

> In Mozilla’s defence, however, we do have plenty of reasons to trust that the nonprofit will keep their promise to not use our data for some nefarious purpose.

Doesn't matter in my opinion. Prism break should not need to trust words.

---

Possibly more information: https://www.reddit.com/r/linux/comments/36txe4/firefox_will_show_ads_based_on_your_browsing/crh4tus Copy pasted:

> Ok, I took a few minutes and reviewed a couple relevant Bugzilla bugs. I'm not a Firefox dev or anything, just someone that needed something to occupy time. From a cursory reading of a couple Bugzilla bugs (which if you follow a the right links from the OP, you will find. I won't link them here because then people will spam them. It took me less than 5 minutes to find them.), I found the following:

> Mozilla is not sending browsing history to the server. What they are doing is getting lists of "Suggested Tiles" along with a list of URLs from the server. If by some algorithm, your history matches that list well enough, they show the tile and notify Mozilla. (I'm not sure about this last part...someone correct me if I'm wrong)

> They prevent Mozilla from passing a list with one item and discovering history by requiring the lists to be long. If I'm reading correctly (I haven't looked at the code), there are a bunch of allowable lists hardcoded into Firefox. The list the server sends with the tiles must be one of those.

> So the only info Mozilla gets is (a) whether your browsing history matches one of the lists of URLs (seemingly hardcoded in Firefox) that shows a tile and (b) whether you clicked on it.

> Do I think this is a good idea? It seems like a step down the wrong path... but at least they considered privacy. That's better than all the other major players, and they still do need to make enough money to exist.

> There's a way to opt out, and it looks like they're automatically opting some people out if they have Do Not Track enabled (even though they point out that they aren't tracking anyone anyway).

But I cannot find the claimed sources for that comment, nor any other official discussion? Probably I just suck at searching.

---

Once some sources or more specific official details are retrieved, the question (obviously) becomes "should Firefox be removed because of this?". Or is this even harmless to privacy or not?

**Comment by Zegnat** [comment]
Duplicate of #1184. Though a lot might have changed since November. This will probably need some restudying again…

**Comment by vyp** [comment]
I thought this was different because "browsing history"?

**Comment by vyp** [comment]
Maybe not "different", but in terms of surveillance, it might have an effect if Mozilla does send browsing history, right? #1184 is just about "enhanced tiles" themselves. Although if you want, we can close this and talk about these new browsing history mechanisms to enhanced tiles at #1184 too.

**Comment by Raprp** [comment]
I believe that IceWeasel and IceCat wouldn't include these adds.

If IceWeasel is Debian only (is it?) shouldn't we also recommend IceCat as an alternative to non-debian platforms?

Apparently the issue #522 had (or has) a good argument of avoiding IceCat recommendation but I just checked that IceCat's latest version is (31.6.0) which is close to the current IceWeasel version (31.7.0). Latest update wa last month.

**Comment by mastercoms** [comment]
Iceweasel is on 38.0.1

**Comment by Raprp** [comment]
@mastercoms  you are right!

31.7.0 is the version o Debian stable, I added mozilla's repo to my sources and now I got the updated version of iceweasel and icedove. Thanks!

This means that IceCat still ain't able to keep up with the updates.

**Comment by wifiextender** [comment]
Hello guys,

I understand that they want to survive without Google's funding, but the whole story reminds me to the recent **RadioShack** theatre. Thank you Mozilla for your products, but I strongly disagree with enforcing policies, be it ads; DRM or self-signing 'features'. Bye mozilla, have a great backlash err time.

>This means that IceCat still ain't able to keep up with the updates.

[Those](http://directory.fsf.org/wiki/GNU) projects require a lot man power. 

Cheers

**Comment by Raprp** [comment]
I just noticed the new IceWeasel comes with this feature enabled by default and they give 3 options of tiles:

1 - Enhanced = Data collection and ads (default option)
2 - Classic = the way it was before
3 - None = no tiles

Switched to classic and looks like it was before. Still, in my opinion the fact that data collection and ads comes as default option makes Firefox and its variants be less respectful with the user's privacy and also creates a precedent to add data collection and ads in other places and projects.

What would be an alternative that also provides the privacy add-ons that Firefox does? Chromium?

**Comment by Raprp** [comment]
Scratch chromium (#169).

I think I will give Midori a try.

**Comment by vyp** [comment]
@Raprp Icecat targets firefox esr.

**Comment by wifiextender** [comment]
@Raprp Crashidori will dissapoint you, have a look at the alternatives https://wiki.archlinux.org/index.php/List_of_applications#Web_browsers instead.

Cheers

**Comment by excu** [comment]
How about Pale Moon as one of the replacement candidate for Firefox? It has no ads nor drm.

**Comment by vyp** [comment]
#1220, but if Firefox is removed because of this, I don't see why pale moon couldn't be considered (unless I'm missing something, because I've never used it). But I'd rather advocate for icecat, assuming they do not implement this (and that this is even a problem).

**Comment by nodiscc** [comment]
Firefox's anti-features can be disabled. The fact that they come enabled by default is still problematic, but the other options proposed here don't seem reasonable to me:

Switching to another browser or fork: can you name another browser with a dedicated/responsive security team, a feature set as large as Firefox's, active development (or if a Firefox fork, abitlity to keep up with upstream changes), and cross-platform?

 * Iceweasel fits the bill but is only available on Linux at the moment.
 * Midori is cool but lacks features (HTTPS everywhere? Noscript? no.) and is unstable.
 * uzbl, luakit etc are definitely for advanced users.
 * Does IceCat have active maintainers? OSX support? Full multilanguage?
 * Pale Moon is still based on Fx 25 and possibly has (?) unpatched security vulnerabilities
 * Chromium. No.

What I recommend instead ([it was proposed at the time](https://github.com/nylira/prism-break/issues/1031#issuecomment-69030089)) is to include settings recommendations to disable these anti-features in Firefox, clearly noted on the Firefox application page. https://github.com/pyllyukko/user.js/ make it mostly easy to configure Fx with decent privacy/security settings. Linking to it or providing an automated config tool/addon would be a good step forward.

Firefox is still the best general-purpose FOSS web browser, though Mozilla's current direction is questionable. Replacing it with niche browsers or low-maintenance forks will not help prism-break doing it's job.

**Comment by wifiextender** [comment]
@nodiscc I think you need to read all of the 330 reddit comments more carefully and understand the core issue. Take your time and stay calm.

Cheers

**Comment by Raprp** [comment]
> Iceweasel fits the bill but is only available on Linux at the moment.

I'm using IceWeasel and this tiles crap is shipped on it too. I was hoping they would leave it out.

Tried for a couple of hours Midori, IceCat and SeaMonkey. The closest one was IceCat. It worked with noscript, ublock, https eveywhere, firebug and disconnect.

However it's not working with KeeFox.... this is kinda of a blocker because I don't even know most of my passwords anymore, I just tell KeePass to generate them.

**Comment by aleksandar-todorovic** [comment]
Come on guys, there was like 10 or 15 discussions inside of this repository to remove Mozilla products (Firefox and Thunderbird) and every time the result was the same: the products were not removed. Aren't you tired already?

Maintainers are aware that those products might have some flaws, but they are still way better than Chrome/IE/Safari/restofthecrap, easy to use, cross platform, they have a huge developer community backing them and they are popular enough to get some real traction.

Imagine Average Joe. Suggest him to use IceCat (or whatever) and he will freak out and he won't do it. Suggest him to switch to Firefox and he will consider it.

**Comment by Raprp** [comment]
> Maintainers are aware that those products might have some flaws, but they are still way better than Chrome/IE/Safari/restofthecrap, easy to use, cross platform, they have a huge developer community backing them and they are popular enough to get some real traction.

Agreed, and nobody is questioning that.

> Imagine Average Joe. Suggest him to use IceCat (or whatever) and he will freak out and he won't do it. Suggest him to switch to Firefox (and install some add-ons and tweak a thing or two on top of the default installation to boost his privacy) and he will consider it.

Will the average Joe remove Windows or OS X from his computer and install Linux / BSD? No, the average Joe does not care and won't change a thing, he has the "I do not have anything to hide" mentality.

I'm my opinion the suggestions should be done to people that care about privacy even if the only option is compile a browser from the sources.

I believe that after this move from Mozilla it's time to start looking and discussing another options.

**Comment by mastercoms** [comment]
Cyberfox is a great alternative for Windows.

**Comment by RoseTheFlower** [comment]
>Cyberfox is a great alternative for Windows.

You have to make an argument for it then.

**Comment by mastercoms** [comment]
It removes all the crap from Firefox.

**Comment by mastercoms** [comment]
Firefox will no longer be available on F-Droid. https://f-droid.org/repository/browse/?fdid=org.mozilla.firefox

**Comment by Raprp** [comment]
@mastercoms, good news!

>Note that this package is planned to be dropped from the F-Droid repo soon. Please consider using Fennec FDroid instead to be sure of continued update support.

> Non-Free Addons
This application promotes non-Free add-ons.

> Tracks You
This application tracks and reports your activity to somewhere.

Don't get me wrong, I love and donate money to Mozilla for ages and I really want them to be successful, but this negative feedback is important so they can realize that a lot of their users will leave (or are already leaving) them because of this crap they are including.

The only reason I do not stop using IceWeasel today is because I could not find a suitable alternative yet.

**Comment by mastercoms** [comment]
IceWeasel is at least better than using Firefox.

**Comment by vyp** [comment]
@nodiscc 

> Iceweasel fits the bill but is only available on Linux at the moment.

> Does IceCat have active maintainers? OSX support? Full multilanguage?

In my opinion, I don't see why prism break should care about OSX support. Prism break should only care about support on systems they suggest.

@Raprp 

> Will the average Joe remove Windows or OS X from his computer and install Linux / BSD? No, the average Joe does not care and won't change a thing [...]

They need to understand that Windows/OS X are fundamentally flawed because they are nonfree. So again, I don't see why prism break has to care if a visitor decides not to switch to Linux / BSD etc.

> Switching to another browser or fork: can you name another browser with a dedicated/responsive security team, a feature set as large as Firefox's, active development (or if a Firefox fork, abitlity to keep up with upstream changes), and cross-platform?

> What I recommend instead (it was proposed at the time) is to include settings recommendations to disable these anti-features in Firefox, clearly noted on the Firefox application page. https://github.com/pyllyukko/user.js/ make it mostly easy to configure Fx with decent privacy/security settings. Linking to it or providing an automated config tool/addon would be a good step forward.

That being said @nodiscc, I agree with this. Do we have official details on how to "opt out" of this. (link?) Because in that case, I do think firefox would be the better option compared to say icecat even though icecat still is a firefox derivative (not an outright fork, so it still receives some of the advantages of security backports to firefox esr). Simply because the latest (non-esr) version is more "directly tied" to updates from the security team.

@mastercoms 

> Firefox will no longer be available on F-Droid.

This is significant, so I suggest opening a new issue specifically for firefox for android? (Because prism break does not suggest play store anyway.) Is it simply that fennec is the replacement, or is a result of new antifeatures? link?

Also, cyberfox seems to be only for windows? In that case, in my opinion, I do not think prism break should support it. Prism break should not support applications which are not available on their suggested systems because it effectively prevents visitors from switching to a suggested system once/if they become familiar with the application. (They may not want to switch even more when they learn they have to switch applications yet again, even though they thought they already made a beneficial switch.)

**Comment by Raprp** [comment]
@vyp
> They need to understand that Windows/OS X are fundamentally flawed because they are nonfree. So again, I don't see why prism break has to care if a visitor decides not to switch to Linux / BSD etc.

Agreed 100%.

> Is it simply that fennec is the replacement, or is a result of new antifeatures? link?

Looks like Fennec Droid have the same problem as Firefox, so apparently it should not be a replacement:

https://f-droid.org/repository/browse/?fdid=org.mozilla.fennec_fdroid

>Tracks You
This application tracks and reports your activity to somewhere.

**Comment by vyp** [comment]
> Looks like Fennec Droid have the same problem as Firefox, so apparently it should not be a replacement:

Hmm, well I mean in that case why would they keep Fennec too?

**Comment by Raprp** [comment]
Yeah, its weird... maybe the tracking warning is not related to the tiles, ex: usage statistics. I will download and check.

**Comment by vyp** [comment]
I don't think it is either, I've seen the warnings (in both firefox and fennec) well before the introduction of enhanced tiles. I think it might be related to Mozilla collecting (anonymous) usage statistics, but I'm not sure.

**Comment by Raprp** [comment]
Just installed Fennec Droid and apparently the feature is there too. On the Home settings there is the same option as Firefox:

>Show site suggestions: display shortcuts on your home page that we think you might find interesting

And it's checked by default.

**Comment by vyp** [comment]
Well yes, Fennec *is* firefox for android if I understand correctly, it isn't a fork. But perhaps the "Fennec FDroid" app on f-droid is slightly different in that they remove some antifeature-like things such as features which require non-free libraries and drm/eme. 

> This is a developer build based on the latest Firefox release. It's focused on removing any proprietary binares used in the official builds.

However, they still have this ad feature as you described...? Anyhow, seeing as though firefox for android is being removed from f-droid, prism break may have to switch to recommending fennec instead (+ recommending to turn off that site suggestions option), or something else.

**Comment by Zegnat** [comment]
> On the Home settings there is the same option as Firefox:
> 
> > Show site suggestions: display shortcuts on your home page that we think you might find interesting

Is this ads or is it just the browser sorting through your history to auto populate the tiles with things you visit the most? Because the latter would be completely self contained and not leak any data.

A lot of confusing situations like this exist because software developers do not properly convey what features do. Compare it to people thinking that “Block reported attack sites” sends every URL you visit to Google. It doesn’t, but Mozilla never clearly explained to people how it does work.

---

I have not yet had the time to read the 300 comments on Reddit. Or read the Mozilla bug reports. Or read the Mozilla blog posts.

I became an active contributor to PRISM Break when I had time to read long TOS documents and evaluate these issues, lately this hasn’t been the case so I have been falling a bit silent. Hopefully I will find the time to figure out what stunt Mozilla is pulling this time around later during the week and get back with my real thoughts.

I will be following the discussion here closely until then. In the mean time, if you want to make an argument for Firefox’ removal, please point out how this new feature is going to leak browsing information. With links to outside documentation.

---

Also of interest, [the official extension signing blog post](https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/) talks about “special, unbranded builds of Release”. Does anyone know if this means Mozilla will be providing official unbranded builds? If those turn off extension signing and maybe these enhanced tiles while at the same time keeping up with Firefox’ official releases they may be the answer we are looking for.

**Comment by mastercoms** [comment]
> Also, cyberfox seems to be only for windows?
I was responding to concerns that IceCat was only for Linux, and was giving a Windows alternative. We shouldn't just recommend Cyberfox, but it should be our recommendation for Windows.

Relevant blog post: https://blog.mozilla.org/futurereleases/2015/05/21/help-test-changes-to-new-tab-in-firefox-beta/

It says that if you set do not track on, the tab features will be disabled.

**Comment by vyp** [comment]
> Also of interest, the official extension signing blog post talks about “special, unbranded builds of Release”. Does anyone know if this means Mozilla will be providing official unbranded builds? If those turn off extension signing and maybe these enhanced tiles while at the same time keeping up with Firefox’ official releases they may be the answer we are looking for.

Yes, it is my understanding that they will be providing the unbranded builds. Iirc there was a debate on whether they should even do that because malicious actors would just tell their users to download the unbranded builds instead, but I might be confusing things. Anyway, the unbranded builds are, supposed to be identical to the official build except you are allowed to installed unsigned extensions (again, iirc, I may be wrong, I will look up the actual scenario again when I close #1235, which should be in a couple of weeks or so when signed extensions become mandatory.), so I do not think they will remove enhanced tiles in it.

> I have not yet had the time to read the 300 comments on Reddit. Or read the Mozilla bug reports. Or read the Mozilla blog posts.

I am still unable to find the bug reports or whatever official detailed information about browsing history based enhanced tiles. By opening this issue, I was hoping to bring this some attention and that someone here might know where to read for more. Because without official information, this issue, and any action taken for it, is put on hold.

**Comment by vyp** [comment]
> Relevant blog post: https://blog.mozilla.org/futurereleases/2015/05/21/help-test-changes-to-new-tab-in-firefox-beta/

It says that if you set do not track on, the tab features will be disabled.

That's my very first link at the very top and why I created the issue. I swear they must have edited the page unless, how did I miss it? Did anyone else see the footnote part at the end?

For example, I didn't catch this:

> However, it’s important to understand that no tracking is involved in delivering Tiles.

And if I did, then I would not have opened this issue. Anyway, this is promising, I wish they would provide more technical details on how this all works. However, assuming what they say is true, I don't really see an issue here. I will likely close here soon, unless anyone else wants to say something.

> I was responding to concerns that IceCat was only for Linux, and was giving a Windows alternative. We shouldn't just recommend Cyberfox, but it should be our recommendation for Windows.

Ah I understand now. But even then, my response to that (above) was that 1) prism break should not worry about specifically suggesting applications for systems it does not recommend and 2) prism break should not recommend applications only available on systems they do not recommend because it gets in the way of visitors switching to those recommended systems, which is a much better switch compared to just switching an application in a nonfree/hostile system.

**Comment by mastercoms** [comment]
The technical details are on their wiki. https://wiki.mozilla.org/Tiles

**Comment by cozymozy** [comment]
http://www.zdnet.com/article/mozilla-abandons-firefox-tracking-protection-initiative/

http://monica-at-mozilla.blogspot.com/2015/05/tracking-protection-for-firefox-at-web.html

Quote "Privacy might be an abstract value that consumers prize, but they're not going to pay for the expensive ongoing development that effective tracking protection requires."

Another quote "Monica Chew, who demoed the Firefox tracking protection feature publicly for the first time last summer and was a co-author of that award-winning paper, left Mozilla in early April."

**Comment by Zegnat** [comment]
@cozymozy, maybe I am missing something, but how does Mozilla (apparently) choosing not to pursue a feature that was never publicly shipped relevant?

(Interesting to note: reading [the feature’s page](https://support.mozilla.org/en-US/kb/tracking-protection-firefox#w_what-is-tracking-protection) suggests they were simply blocking domains from the Disconnect blocklist. That’s just doing what every other ad and tracker blocking add-on has been doing for years.)

**Comment by GreenLunar** [comment]
[Raprp commented on May 24]#issuecomment-104975540)

> Don't get me wrong, I love and donate money to Mozilla for ages and I really want them to be successful, but this negative feedback is important so they can realize that a lot of their users will leave (or are already leaving) them because of this crap they are including.

You are correct.
