### ISSUE TITLE
Should a licence file be added to comply with used dependencies and logos?

### ISSUE THREAD

**Issue by Zegnat** [nylira/prism-break#132]
I’m putting this here for other who know more about it to comment on.

All work on the prism-break.org project is released to the public domain as per [CC0](http://creativecommons.org/publicdomain/zero/1.0/) (creativecommons.org). However it should be made clear that this is only applicable to the original code and the translations. (The list itself might not even be copyrightable.)

The non-original code is not released under CC0:
- `normalize.css` is used and is covered by a MIT licence: [LICENSE.md](https://github.com/necolas/normalize.css/blob/master/LICENSE.md) (GitHub.com). Honestly this file shouldn’t be needed as the few resets we need can be managed by prism-break.org’s own CSS file.
- `html5.js` is used and is covered by a dual MIT and GPL2 licence. Again, I wonder if this file is needed for the site. The only HTML5 that is used it the `footer`-element, so we could just add it with `document.createElement('footer');`.
- `jquery-1.10.1.min.js` and `jquery.color-2.1.2.min.js` are both covered by a MIT licence: [MIT-LICENSE.txt](https://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt) (GitHub.com). These are probably harder to stop using as it would require a complete rewrite of the scripting. To comply with the licence the file should be included, as per:
  
  > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

The project also includes logos of the software that is being mentioned. These logos cannot be licensed by prism-break.org to the public domain either.

As an example, [the Mozilla trademark policy](https://www.mozilla.org/en-US/foundation/trademarks/policy/) (Mozilla.org) makes the following two points:

> - Accompanying Symbol - The first or most prominent mention of a Mozilla trademark should be accompanied by a symbol indicating whether the mark is a registered trademark ("®") or an unregistered trademark ("™"). See our Trademark List for the correct symbol to use;
> - Notice - The following notice should appear somewhere nearby (at least on the same page or on the credits page) the first use of a Mozilla trademark: "[TRADEMARK] is a ["registered", if applicable] trademark of the Mozilla Foundation";

I might be interpreting this wrong – _IANAL_ – but it seems to say prism-break.org must write ‘Firefox®’ and include a notice at the bottom: ‘Firefox is a registered trademark of the Mozilla Foundation’.

Several other companies might hold trademarks on other names that are being used on the page. Logos might also be protected by different licenses and registrations. (The Firefox logo has [a special page on dos and don’ts](https://blog.mozilla.org/press/media-library/) (Mozilla.org).)

Adding a licence file containing all trademark notices and dependency licences will make it easier and safer for people to actually share and redistribute this list.
- Firefox logo is a registered trademark of the Mozilla Foundation.
- IceCat logo is released under a MPL/GPL/LGPL tri-license.
- _etc._

**Comment by vyp** [comment]
Because of the length of the list today, undertaking this task would be *immensely* time consuming I imagine (checking for each project whether or not they have a registered trademark...). And for what benefit? These past two years haven't seemed to cause any issues. I think this issue can be resolved, at least until someone with a trademark comes here to complain, in which case that specific situation can be fixed easily.

(And at least we have "Logos are copyrighted and trademarked by their respective companies." in `LICENSE.md`.)

I agree though that it would be preferable to have it, but it seems like this should have been done back then when the list was sort of in its infancy.

The only reasons I can think of for keeping it open would be if one of you think yoy will actually have the time to do this sometime, or if someone with a lot of time comes along in the future and finds this under the "pull request accepted" label, which they won't if this is closed.

**Comment by yegortimoshenko** [comment]
List of dependencies presented here is not up to date, we don't have any of that software listed by @Zegnat in the tree by now. On that basis, I think this issue can be closed.

> The project also includes logos of the software that is being mentioned. 

The context in which logos are used is covered by fair use.

> I might be interpreting this wrong – IANAL – but it seems to say prism-break.org must write ‘Firefox®’ and include a notice at the bottom: ‘Firefox is a registered trademark of the Mozilla Foundation’.

If that's indeed true, this is outrageous ad Mozilla should go take a hike.

**Comment by yegortimoshenko** [comment]
`LICENSE.md` now lists licenses of used dependencies, logos are under fair use, and list of dependencies in this issue is outdated. Closing.
