### ISSUE TITLE
[Add] Midori Browser

### ISSUE THREAD

**Issue by Doomineer** [nylira/prism-break#1332]
How about Midori Browser? http://www.midori-browser.org/
Midori is a web browser that aims to be lightweight and fast. It is also privacy-aware, and by default allows users to search via Small DuckDuckGo iconDuckDuckGo. It uses the WebKit rendering engine and the GTK+2 interface (or optionally GTK+3).

**Comment by hasufell** [comment]
midori is horribly buggy. We dropped it from stable branch completely in gentoo.

**Comment by Doomineer** [comment]
Yup I found this post later #524 
Sorry for the double post! :/
