### ISSUE TITLE
Add SMSSecure to Secure Instant Messengers

### ISSUE THREAD

**Issue by juanito003** [nylira/prism-break#1333]
**A new fork of TextSecure that supports encrypted SMS/MMS**
This is a fork of textsecure. The forks goals is to drop all Google service dependencies and drop all support for sending messages over the internet, it is only SMS and MMS. It can be found on Google play, and F-Droid. I am in no way associated with this project, I just thought that some of us would like to find a fork of Textsecure that is actively being updated and supports the old method of encrypting messages, and as always it is open source ;)
**Source**: http://www.reddit.com/r/privacy/comments/34jrk5/a_new_fork_of_textsecure_that_supports_encrypted/

I use it for encrypted SMS on paranoidandroid without gapps, since several month, and it does the job.

**SMSSecure website and repo:**
http://smssecure.org/
https://github.com/SMSSecure/SMSSecure

#1314 to read more about why not to use textsecure anymore.

**Comment by vyp** [comment]
I agree with you. But this is a dup of #1267.

**Comment by juanito003** [comment]
My bad, I didn't see the other opened one because after my searched I was in a hurry and saw no result. But it was no result on code. Sorry. How can we delete this entry now?

**Comment by vyp** [comment]
Not sure if you can delete, but closing should be fine (there should be a close button at the bottom).
