### ISSUE TITLE
LibreOffice

### ISSUE THREAD

**Issue by SnowGabe** [nylira/prism-break#1342]
Why isn't LibreOffice office suite recommended in the 'productivity' category? Are online solutions preferred?

https://www.libreoffice.org/

**Comment by Zegnat** [comment]
For the same reason as why PRISM Break does not discourage the use of Microsoft Office or Apple Productivity Apps (Pages, Numbers, and Keynote). There is no reason to believe any of these leak private data. Thus the productivity category is aimed at online collaboration tools.

OpenOffice (or any of its forks like LibreOffice and NeoOffice) cannot replace any of the services from the proprietary column, as they do not support online collaboration.

If any reason is found to add Microsoft Office or Apple Productivity Apps to PRISM Break as invasive software, than I do not doubt we will be adding OpenOffice or LibreOffice as recommendations!

I hope that answers your question :smile: Closing this issue. Feel free to reopen if you have new arguments to make!

**Comment by SnowGabe** [comment]
I now your stance, but I'm confused. Do you also believe that there's "no reason to believe" that Windows and OS X operating systems are harmful?

**Comment by Zegnat** [comment]
This is a separate issue from the operating systems.

PRISM Break is not a website that lists open-source software. It is a website that discourages the usage of proprietary applications to handle your private information. So while we discourage the use of “Microsoft Office Web Apps” and “Zoho Office Suite” (Google Documents should probably be added to that list), and recommend using EtherCalc and Etherpad, there is no reason to tell people not to use a 100% offline application like Microsoft Word.
