### ISSUE TITLE
Check this list for software recommendations

### ISSUE THREAD

**Issue by nodiscc** [nylira/prism-break#1354]
Hi, I've been working on https://github.com/Kickball/awesome-selfhosted which is a list of self-hostable alternatives to commercial/SaaS web services. Feel free to cherry-pick projects from the list.

Adding this because I just saw https://github.com/nylira/prism-break/issues/1349 - bookie is still available as a self-hosted platform.

**Comment by yegortimoshenko** [comment]
Thanks, I've reviewed it and added #1946 and #1947 based on that, and bookmarked several services not applicable to PRISM Break to my own collection :-) If you think I've missed something, you can always create a ticket with inclusion request.
