### ISSUE TITLE
Calendar, contacts & tasks 

### ISSUE THREAD

**Issue by SegiH** [nylira/prism-break#1356]
Can you guys review and add Fruux. They are open source and use encryption. Fruux.com

**Comment by strugee** [comment]
Can you provide references to them using encryption and their source code? From glancing at their homepage, I can't find either. I also can't find anything saying that you can self-host it, which is somewhat of a no-no on PRISM Break. Somewhat.

**Comment by mastercoms** [comment]
They aren't open source, they "love" open source. The open source component of fruux is http://sabre.io/, so we should review that instead.

**Comment by Zegnat** [comment]
There are a lot of calendar synchronisation tools. But I really don’t know if they fit on PRISM Break. Prior issues:

#65, #516,

**Comment by strugee** [comment]
Closing as Fruux isn't free software and can't be self-hosted.
