### ISSUE TITLE
Possibly misleading statement under 'Web Browser Addons' section

### ISSUE THREAD

**Issue by one23** [nylira/prism-break#1358]
Under the ['Web Browser Addons' section] (https://prism-break.org/en/all/#web-browser-addons), the final paragraph under 'Notes' heading reads: 
> Why is Adblock Plus not recommended? Adblock Plus shows “acceptable ads” by default, which works against the purpose of the add-on. Either disable acceptable ads or use the uBlock fork instead.

This last statement seems to imply that uBlock is a fork of Adblock Plus, which it is not. (This is repeated in a number of translations also.)

**Comment by vyp** [comment]
Yeah I noticed that whilst doing #1357. IIRC it used to say Adblock Edge, which I think was a fork of Adblock Plus, I guess that was changed to uBlock at some point.

**Comment by one23** [comment]
That was an incredibly quick fix!  By the way, a big thank you to all who work on this project - it is an invaluable resource!

**Comment by vyp** [comment]
Thanks! But to be fair, it was only deleting a few words, so small change. Important part was that you mentioned it so thanks a lot.

**Comment by vyp** [comment]
Also note that the (static) site is manually built and published so changes don't become live until at best a few hours, maybe a few days, at discretion of nylira.
