### ISSUE TITLE
"Social Networks"'s notes reference RetroShare, but it's not in the list.

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1370]
See https://prism-break.org/en/subcategories/servers-social-networks/. Not sure if RetroShare got removed or was just never there, but this is confusing.

**Comment by vyp** [comment]
It is: https://prism-break.org/en/all/#social-networks, just not under servers. Not sure if the notes section can be changed depending on category view though, don't think so.

**Comment by yegortimoshenko** [comment]
RetroShare is not meant to be run on a server, and we do not have capability to change notes according to specific category. I think that this reads fine: RetroShare does not require a server, but it's the easiest way to start a social network.

If I were to send a patch that makes RetroShare into an anchor link, would that resolve the issue?
