### ISSUE TITLE
Microsoft's new privacy policy

### ISSUE THREAD

**Issue by vyp** [nylira/prism-break#1377]
https://edri.org/microsofts-new-small-print-how-your-personal-data-abused/

Amidst all the talk about windows 10, this one month old article seems to have been swept under the radar, though I have seen a hacker news thread for it: https://news.ycombinator.com/item?id=9966236.

As you can see, the sections of this new privacy policy that the article quotes are *quite* concerning to say the least, especially with regard to mass surveillance.

Sometimes with articles like this, the claims made can be intentionally misleading to make the situation seem more dire than it actually is. And so even though to me this looks like the real deal, because of my inexperience with Windows (for quite some time now), I may still be wrong here.

It is my understanding that this affects only Microsoft-account enabled user accounts, but not the local user accounts, is that correct?

So I opened this issue to see if others here:

1. Know/have more sources on if this is really as bad as it seems.

2. Think that it would be helpful to put a warning on the site about this, if this is true.

And I believe it's still a huge deal even if it's only for Microsoft-account enabled user accounts because, by my understanding, this is by default opt *out*, meaning there will be many who will 'fall prey' to this unknowingly.

And that would only continue to enable more mass surveillance (at least in a much more economically viable manner), hence why I think it would be helpful if this is mentioned somewhere in the Windows warning.

Thoughts?

**Comment by Zegnat** [comment]
I am not a Microsoft user and not up-to-date on what is going on. I know that with the default installation of Windows 10 you will allow a lot of information to be shared with Microsoft, I saw this reported on the Dutch RTL News ([one such article (NL)](http://www.rtlnieuws.nl/economie/home/windows-10-installeren-let-op-je-privacygegevens)). Really nothing new, as it is much the same as the information that people are sharing with their mobile OS on a daily basis, but it is going to catch people off-guard.

**Comment by lucaspetter** [comment]
A lot of the same things in the article are happening with Macs too.

> By default, when signing into Windows with a Microsoft account, Windows syncs some of your settings and data with Microsoft servers, for example “web browser history, favorites, and websites you have open” as well as “saved app, website, mobile hotspot, and Wi-Fi network names and passwords”. Users can however deactivate this transfer to the Microsoft servers by changing their settings.

Basically all of the above is true on Macs with iCloud and iCloud Keychain, both of which Apple heavily encourages people to use.

> Also, when device encryption is on, Windows automatically encrypts the drive Windows is installed on and generates a recovery key. The BitLocker recovery key for the user’s device is automatically backed up online in the Microsoft OneDrive account.

Apple's FileVault similarly backs up the recovery keys to iCloud, but users can opt out.

> Users who chose to enable Microsoft’s personal assistant software “Cortana” have to live with the following invasion to their privacy: “To enable Cortana to provide personalized experiences and relevant suggestions, Microsoft collects and uses various types of data, such as your device location, data from your calendar, the apps you use, data from your emails and text messages, who you call, your contacts and how often you interact with them on your device. Cortana also learns about you by collecting data about how you use your device and other Microsoft services, such as your music, alarm settings, whether the lock screen is on, what you view and purchase, your browse and Bing search history, and more.” But this is not all, as this piece of software also analyses undefined “speech data”: “we collect your voice input, as well your name and nickname, your recent calendar events and the names of the people in your appointments, and information about your contacts including names and nicknames.”

Siri is currently only on iOS, sending this type of personal info to Apple, but it wouldn't be surprising to see Apple add Siri to Macs in the future. When/if that happens, Apple will be collecting the same data about its Mac OS users.

Macs also go a step further: unsaved drafts in the text editor or document apps are [automatically uploaded to iCloud](https://www.schneier.com/blog/archives/2014/10/apple_copies_yo.html), and only get removed from iCloud when users save the drafts to a local drive.

**Comment by Dovaa** [comment]
Neither OS X nor Windows are recommended in prism-break ( •᷄⌓•᷅ )

**Comment by strugee** [comment]
@vyp why was this closed?

**Comment by vyp** [comment]
@strugee Because it seems the answer to my second point in OP is "no". I'm still for putting a notice up about this because "android/ios/mac also does this" is not really a strong argument against this in my opinion. I believe the difference here, if any, at least compared to macs, is that it's opt-*out*, unlike with icloud which I think is opt-in right? Not sure about mobile OSes though, but I wouldn't be surprised if they are also opt-out with regard to "send a lot of things back 'home'".

But I can't justify the inclusion of some extra notice in a pr if no one else agrees with me, and it's been a week.
