### ISSUE TITLE
Add Kaiwa XMPP client

### ISSUE THREAD

**Issue by jerome-tgl** [nylira/prism-break#1378]
Add Kaiwa, an open-source XMPP Web client, as an alternative to [Slack](https://slack.com/).
It's based on Prosody, which is already listed under XMPP servers, and has an MIT license.

See the [official website](http://getkaiwa.com) for an introduction.
See the [kaiwai repo](https://github.com/digicoop/kaiwa) for more info

**Comment by yegortimoshenko** [comment]
Kaiwa is not maintained anymore: https://github.com/digicoop/kaiwa
