### ISSUE TITLE
Add Epirts.js

### ISSUE THREAD

**Issue by pizzamaker** [nylira/prism-break#1382]
http://pehjota.net/projects/epirts.js/

Epirts.js, a free software replacement for Stripe.js, a payment method.

**Comment by Zegnat** [comment]
Going to close this.

* There is no way for consumers to affect how they pay over the internet with this and it does not replace any software. It does not help anyone keep their data in their own hands.
* Even with this library in use, the consumer’s browser will always be exposed to the Stripe servers. No matter if you use “Stripe.js” or “Epirts.js”. So even for website owners it makes little sense to use this, especially considering the extra PCI DSS Compliance work you will have to go through.

Other than allowing [LibreJS](https://www.gnu.org/software/librejs/) users to do credit card payments online, I have a hard time understanding why this is a thing. (And PRISM Break rejected recommending LibreJS.)
