### ISSUE TITLE
Windows section is missing PDF readers , Microsoft office replacement 

### ISSUE THREAD

**Issue by theJaxon** [nylira/prism-break#1384]
I just want to know why free and open source PDF readers such as SumatraPDF , Evince are not listed as a replacement for adobe reader and foxit reader ? 
Also why there's no replacement for microsoft office i mean isn't LibreOffice supposed to be the replacement for it ?

**Comment by vyp** [comment]
https://github.com/nylira/prism-break/issues/1155

**Comment by yegortimoshenko** [comment]
Duplicate of #1155.
