### ISSUE TITLE
search engine: Qwant

### ISSUE THREAD

**Issue by gentilvirus** [nylira/prism-break#1387]
In the **Web Search** category, I propose to add **Qwant**.
In two words, Qwant is the European equivalent of DuckDuckGo : it has its own search engine, emphasizes [protecting searchers' privacy](https://www.qwant.com/privacy) and avoids the filter bubble. It recently introduced the [Qwick](https://www.qwant.com/qwick) which is just the same as the popular !bang functionnality of DuckDuckGo.

I am using it as my default search engine for 4 months.  Earlier, I tried to set other "alternative" search engine as default on my computer but everytime I gave up because the results were very poor compared to google for non-english searching.

**Comment by Zegnat** [comment]
I am confused. They seem to say the only personal data collected is whatever you write in a form when you create an account. But then when you get to “What measures does Qwant take to ensure the security and confidentiality of your personal data?” on the [privacy page](https://www.qwant.com/privacy) you read this:

> Thus, the IP address associated with your research is anonymised in accordance with the CNIL recommendations.

My IP is still being stored? Why? Associated with what “research” exactly? Is that every search I do?

Compare that to [DuckDuckGo’s extremely clear statement](https://duckduckgo.com/privacy#s4) about search analysis (emphasis mine):

> We also save searches, but again, not in a personally identifiable way, as **we do not store IP addresses or unique User agent strings**. We use aggregate, non-personal search data to improve things like misspellings.

Do we know anyone from Qwant we can ask to comment on this?

---

On a completely unrelated note, I love how they are [partnered with Huawei](https://blog.qwant.com/en/servers-by-huawei-2-2/) for their server infrastructure. A company that throughout the years has been criticised by the UK and Australian governments, and labelled a national security threat by an intelligence committee from the US’ House of Representatives. That is, of course, a lot of FUD and I do not remember ever reading anything concrete on the matter, but I still found it amusing.

**Comment by Sigmun** [comment]
You can contact privacy@qwant.com
from the new privacy page https://about.qwant.com/legal/privacy/

**Comment by yegortimoshenko** [comment]
It would be better to remove all proprietary search engines in favor of Searx, in my opinion: https://github.com/nylira/prism-break/pull/1890

This is also somewhat similar to https://github.com/nylira/prism-break/issues/1938.
