### ISSUE TITLE
Add StartMail email service

### ISSUE THREAD

**Issue by qwertychouskie** [nylira/prism-break#1389]
Could anyone add StartMail?  It is made by the same makers of Startpage and Ixquick.

**Comment by Zegnat** [comment]
StartMail can surely be considered. I am a bit occupied the coming week, but if anyone else would like to read and comment on [their privacy policy](https://www.startmail.com/privacy) and [white paper](https://www.startmail.com/documents/whitepaper/whitepaper.en_US.pdf) that would be much appreciated.

From glancing at it, the “User Vault” system is the part that needs the most scrutiny in the white paper. As it will be used to store your private PGP key on their servers (see page 13) and is a closed source system (see page 7) developed by them.

**Comment by espress0** [comment]
Sending 'private' PGP key to outside your computer is not okay.
If the data leaves your computer, it's not private anymore.

**Comment by alerque** [comment]
Private PGP keys in a closed source bit of the system? I think that's enough to put this out of the reconning without further examination.

**Comment by Zegnat** [comment]
You know what, I have no idea how occupied my mind was with other things when I wrote that comment. It looks like the “User Vault” is a LUKS-based partition of some sort. Using that to store your PGP key suggest to me that – as long as your User Vault is mounted – anyone with access to the server has access to your key. Which does not sound like something you want.

I think I’ll just close this until more of their encryption infrastructure is open-sourced, at the least.
