### ISSUE TITLE
Add SoftetherVPN

### ISSUE THREAD

**Issue by df1paw** [nylira/prism-break#1391]
I suggest adding SoftEther VPN project to the VPN section:
https://www.softether.org/

https://en.wikipedia.org/wiki/SoftEther_VPN

Regards,
   Andreas Weller

**Comment by espress0** [comment]
SoftEtherVPN devs doesn't care about your privacy. They ignore our security report a few months ago.

They send information on the client computer, such as computer name and license key, to VPN server without user authorization.
Also, they're still using SSL3 and RC4 for encryption method, and both are very weak.

If you don't believe me, feel free to read issues in github/SoftEtherVPN/SoftEtherVPN/issues .
Take my advise; use OpenVPN and stay away from SoftetherVPN and PacketixVPN.

**Comment by alerque** [comment]
This doesn't look like something PRISM-Break can recommend. Reliance on outdated encryption protocols is a huge red flag. This suggestion could be closed until that at least is dealt with.

**Comment by Zegnat** [comment]
> This suggestion could be closed until that at least is dealt with.

Yup.
