### ISSUE TITLE
Add ubuntu phone (Mobile Operating systems)

### ISSUE THREAD

**Issue by stakewinner00** [nylira/prism-break#1397]
What about ubuntu phone? It's not the same that ubuntu for desktop and may be a good alternative to android and windows phone.

**Comment by alerque** [comment]
It may be, but we really need somebody qualified that has dug through the nitty-gritty to comment on it's strengths and weaknesses in the encryption and privacy departments. So far I've heard kind of a mixed bag of stuff but most of the technical reviews I've seed are focused on other aspects. I don't think its really gotten a through enough shake out yet to say whether it will be a bane or a boon to people trying to avoid being caught in surveillance dragnets.

**Comment by hasufell** [comment]
> It's not the same that ubuntu for desktop

Yes, because it's for mobile phone. What makes you think that they suddenly apply a different workflow/philosophy here?

**Comment by stakewinner00** [comment]
It don't seems that Canonical will be more concerned about privacy than before. But i read an article, "Ubuntu's Unity 8 desktop will remove the Amazon search 'spyware'" ( http://www.pcworld.com/article/2840401/ubuntus-unity-8-desktop-removes-the-amazon-search-spyware.html ) that make me feel that the major issue with ubuntu is "fixed".

 I'm not up to update about Canonical for this reason I asked if this was a possible solution or there are some other issue that I don't know.

**Comment by vyp** [comment]
@stakewinner00 You may want to read #334 (as linked on the site) for more information about ubuntu/canonical. It's pretty unlikely that ubuntu phone will be accepted for more of the same reasons that @hasufell talks about there.

**Comment by haary** [comment]
Ubuntu Phone aka "Ubuntu for Devices" is not free software. The Disclaimer at https://developer.ubuntu.com/en/start/ubuntu-for-devices/installing-ubuntu-for-devices/ says:

""Ubuntu for devices" is released for free non-commercial use." 

The restriction to only non-commercial use makes this software clearly non-free.

**Comment by mpathy** [comment]
You cant do that! When you once start to have a point, no matter how far-fetched the reasons are, you have to stay true to it.. Come on, lets say its Ubuntu "there must be spyware somewhere, even if we dont see it.. its all open source and everyone could look, but.. well.. it is ubuntu there must be something, I read an article about that 4 years ago"..

So I vote for please exclude Ubuntu because of spyware data leaks and other pro expert reasoning.

**Comment by Zegnat** [comment]
Ubuntu is currently not being considered for inclusion on PRISM Break. If you have any new arguments, please create a new issue.
