### ISSUE TITLE
OpenJDK instead of Oracle JRE?

### ISSUE THREAD

**Issue by Raprp** [nylira/prism-break#1399]
Anyone thinks it's worth adding to the Linux/BSD section a recommendation of OpenJDK instead of Oracle's JRE for those who run Java applications on their computers?

**Comment by strugee** [comment]
Why? Does Oracle's JRE phone home or something? Recall that PRISM Break is not a general FOSS application directory.

**Comment by Raprp** [comment]
Microsoft never called me too, maybe Prism Break should start recommending the use of Windows 10.

**Comment by hasufell** [comment]
xD

The point is... we assume that by choosing the right distribution it won't be easy to install non-free software (java even requires EULA). In gentoo that is achieved by a license configuration that applies system-wide. Either your distro doesn't ship it at all, or it allows you to keep it out. We can't list all of those non-free dependencies here (java is not an end-user app). That's a distro-level problem.

**Comment by strugee** [comment]
@Raprp Windows 10 is an obvious and well-known privacy problem. Oracle Java is not. We're happy to listen if you provide links, but all I see here is FUD.

**Comment by Raprp** [comment]
@hasufell You are right. Thanks for the answer. I will close the issue.

@strugee You seriously need to get laid.

**Comment by alerque** [comment]
@Raprp That was uncalled for. If you have anything to add to the discussion that furthers the discussion of solutions listed on PRISM-Break based on their technical merits (or faults) by all means jump in, but personal disparaging remarks about contributors here is not appreciated.

**Comment by strugee** [comment]
@alerque thanks for saying this. \*wonders when someone will draft a Code of Conduct\*
