### ISSUE TITLE
Miranda IM

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1405]
Hi there,

I've been surprised to see that Miranda IM is not quoted in Instant Messaging clients.
Is there any reason to this ?
Here is the main page : http://www.miranda-im.org/

Thanks for answers or eventually for adding this program to Prism-Break :)

**Comment by alerque** [comment]
I don't this Miranda IM is an appropriate piece of software to list. @Marebul if you think differently please expand your request with specifics of why it would be appropriate for PRISM-Break, but consider these points:

* PRISM-Break is not a directory of free or alternate software. There are lots of open source projects out there, but the purpose of this recommendation list is to forward software alternatives that specifically address the privacy and security concerns raised by global surveillance operations such as PRISM.
* Miranda makes zero claims to address privacy or security. Reviewing their website shows nothing in the project purpose or feature list that is related to privacy or security and no suggestion is made that this is a priority.
* Miranda doesn't handle its own  messaging, it is just a client that connects to other messaging networks.
* The messaging networks it connects to **are proprietary and are known to be subject to surveillance**.

I conclude that this is not a suitable candidate for inclusion in PRISM-Break and suggest this issue be closed.

**Comment by vyp** [comment]
Agree with @alerque. There are networks/protocols it supports that are specifically *not* recommended by prism break. e.g. facebook and aim.

**Comment by Marebul** [comment]
I understand. This is very clear :) Thanks for your answers, you can close the issue.
