### ISSUE TITLE
I miss Kontalk as a secure mobilemessenger

### ISSUE THREAD

**Issue by webratte** [nylira/prism-break#1408]
Hi,
I hope I don't write a duplicate...

I miss on Prism break https://github.com/kontalk
They using XMPP and PGP. And the source code for client and server is open of course.

Thank you

**Comment by vyp** [comment]
It is a duplicate #276. I actually like kontalk as well, and I've been meaning to make a PR to add it recently (because the problems initially discussed in #276 have been more or less solved) but just haven't got around to it. I'm not sure but perhaps others here want to wait on https://github.com/kontalk/androidclient/issues/179, depending on how important they feel that feature is?

**Comment by alerque** [comment]
I've never heard of this platform before but it looks promising. As I recall there are a few protocol level issues with XMPP that leak privacy information even if you encrypt the messages themselves. It looks like they may have done some work with the protocol as well as from the client end, but I don't see any technical overview of how exactly their architecture works for review. If anybody knows of such documentation a link would be great, as well as if there happen to be any third party audits.

**Comment by webratte** [comment]
I don't know what exactly you looking for.
But maybe you can take a look on this (maybe I'm wrong):
https://github.com/kontalk/androidclient/wiki
or
https://github.com/kontalk/network/wiki

I think there no third party audits yet.

**Comment by timofonic** [comment]
I consider Tox more interesting, serverless...


https://github.com/irungentoo/toxcore

**Comment by hasufell** [comment]
tox is alpha and has not seen a single proper release yet

**Comment by timofonic** [comment]
I agree.

But they are progressing fastly and have implementations for all major
platforms, including Android and iOS.

It's the only FOSS equivalent of Threema too.

I think it's the only reasonable solution to censoring and network
dependence, with intention to even making it Internet dependent by mesh
network in case of an Internet outage (think of Jericho TV series!).

They just need more support to reach their goals: Advanced optimization and
have all features of similar messaging software implemented in all clients.

I did suggest them to use Codec2 for VoIP. It's an extremely low bandwidth
speech protocol engineered for Software-Defined Radios, but it needs some
improvements to make it usable for VoIP.

Servers are the weakest part of the chain in communications, removing them
gives new problems to solve but also remove a very dangerous vulnerability.

**Comment by strugee** [comment]
@timofonic please keep discussions on-topic. If you don't have anything to say about the inclusion of Kontalk, don't comment in this issue. Instead search the issue tracker for issues already open about Tox and comment there. Thanks.
