### ISSUE TITLE
Add Zulip - as alternative to Slack

### ISSUE THREAD

**Issue by mad73923** [nylira/prism-break#1410]
https://www.zulip.org/index.html
sounds promising!

**Comment by ayttew** [comment]
+
Looks like all sources (including clients) available [on GitHub](https://github.com/zulip).

**Comment by alerque** [comment]
This is not a viable system to recommend on PRISM-Break. Zulip is a very cool piece of software and having been open-sourced it is a very promising alternative to Slack (along with Mattermost). However this is not just a directory of open-source alternative software. This project is about recommending ways to stay out of surveillance dragnets. As such Zulip does not have the features we would expect to see to make such a recommendation. It does no additional encryption of messages either over the wire or at rest over and above whatever SSL link you might optionally host it on. This may be acceptable to you for everyday use in a non-privacy sensitive context but it does not keep you off the radar of programs like PRISM.

**Comment by mad73923** [comment]
I don't get the point. @alerque , you claim that all projects on prism-break are fully encrypted? What about Wordpress, Piwik, etc.? It's up to the user to secure these things.
Therefore using Zulip or Mattermost is way better than the centralized Slack, even if it's encrypted or not. As you say, makes easier to stay out of these dragnets.

**Comment by yegortimoshenko** [comment]
I think Zulip would be a valuable addition, in place of other online collaboration tools like Slack, HipChat and such. If we list Gogs, I can't come up with a good reason to not list Zulip.

**Comment by alerque** [comment]
I would re-consider this, especially if we start adding notes to all self-hosted project recommendations about needing to host them in SSL only modes.
