### ISSUE TITLE
Add Umbrella App  (Android)

### ISSUE THREAD

**Issue by securityfirst** [nylira/prism-break#1411]
Hi there,

Umbrella helps human rights defenders manage their physical and digital security on the move. 

It gives step-by-step advice and checklists for every situation from sending a secure email to emergency evacuation - Umbrella provides you with a one-stop-shop for all the latest tools and information on how to operate securely as and when you need it.

It would be awesome if you listed it in the ToolBox. You can find our more at www.secfirst.org or download the open source, free, app on the Google Play store (F-Droid will be available in the next few weeks):

https://play.google.com/store/apps/details?id=org.secfirst.umbrella

Thanks!

**Comment by yegortimoshenko** [comment]
Merged into #1518.
