### ISSUE TITLE
add umatrix

### ISSUE THREAD

**Issue by anarcat** [nylira/prism-break#1419]
umatrix seems like a nice alternative in the web browsers addon section that could replace:
- noscript
- privacy badger
- random agent spoofer
- request policy

... all in one! it's much faster and lighter than having all of those installed... and it works pretty transparently by default.

opinions?

**Comment by alerque** [comment]
This has already been discussed in #1299 which resulted in a decision to mention it as an alternative to the other options. This was merged in #1403.

**Comment by anarcat** [comment]
well, it doesn't appear at all right now.... 

oh well...

**Comment by alerque** [comment]
@anarcat Did you read the threads I linked to? The current status is [described in detail there](https://github.com/nylira/prism-break/pull/1403#issuecomment-141781330). Also if you use Github to search this project besides showing up in the issues I linked to it also shows up in the source code and you can confirm the wording of the note about it in various languages.

**Comment by vyp** [comment]
@anarcat It's mentioned in the "Notes" part for the "Web Browser Addons" section.

**Comment by anarcat** [comment]
i was hoping it would show up with an icon and everything... no biggie.

**Comment by strugee** [comment]
Closing as uMatrix is already listed in the browser addons "notes" section.

If anyone objects, comment and I'll reopen.
