### ISSUE TITLE
retroshare should also be in the file sharing section

### ISSUE THREAD

**Issue by anarcat** [nylira/prism-break#1420]
i didn't even expect to find it in messaging.. from what i understand from #433, it was one of the reasons the filesharing section was made in the first place!

**Comment by yegortimoshenko** [comment]
There is no File Sharing category on the site, at least not anymore. I think this can be closed.

**Comment by strugee** [comment]
Should this be File Storage & Sync? I've forgotten exactly what Retroshare is/does but it could be that that's what was meant here

**Comment by yegortimoshenko** [comment]
RetroShare is not really for file storage, more like for sharing :-) #433 is still open. We do need to list RetroShare and OnionShare in some category.
