### ISSUE TITLE
add Blink to 'Video and Voice'

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1422]
Homepage: http://icanblink.com/
License: GPL-3

Written in python and segfaults less than this buggy thing called linphone.

In case a packager cares for dependency information and stuff: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=57a0b02a89b8e902bf8c8e28cd5a71c015db4590

**Comment by yegortimoshenko** [comment]
I should note that they seem to go out of their way to make sure that no one can build Blink on macOS (which is the version they sell): https://gist.github.com/thunfischbrot/69ebf35bdc5b0f6dc1b0

For context, in many cases it is not trivial to build .dylib libraries on macOS and they probably have scripts and maybe patches to build systems of various dependencies to allow that.
