### ISSUE TITLE
Gigablast

### ISSUE THREAD

**Issue by txpower** [nylira/prism-break#1428]
Open-source search engine (not unlike YaCy)

website: http://gigablast.com
source code: https://github.com/gigablast/open-source-search-engine
Wikipedia: https://en.wikipedia.org/wiki/Gigablast
license: https://github.com/gigablast/open-source-search-engine/blob/master/LICENSE (Apache 2.0)
OS: any (web service) / GNU/Linux (own server)

**Comment by yegortimoshenko** [comment]
Has not been updated for the last year, search quality is seemingly worse than YaCy (which is on its own so low that warrants removal: #1888). Should be closed unless there are objections.

**Comment by yegortimoshenko** [comment]
Closing this because it's not maintained and search quality is bad.
