### ISSUE TITLE
Duckduckgo may be unreliable

### ISSUE THREAD

**Issue by Zaukaj** [nylira/prism-break#1429]
Sorry for probably bad title.

This link explains it: https://8ch.net/tech/ddg.html

Like it says, there's no proof Duckduckgo really does anything (or doesn't do anything) that violates privacy, but I don't trust it as much anymore.

**Comment by Zegnat** [comment]
searx will probably be included, though I haven’t gotten around to really revising the search category yet. The other alternative that 8ch.net seems to offer is Startpage, but Startpage’s inclusion on PRISM Break has also had a lot of criticism. As with DDG, there is never any real proof with these allegations. Just a whole lot of FUD.

Going to close this.

**Comment by alerque** [comment]
Concur. There are some valid concerns with using any centralised service like this and what we are recommending should get a work over. But this particular article is so full of FUD it's useless.
