### ISSUE TITLE
add IRSSI to IM/IRC-Section

### ISSUE THREAD

**Issue by silentalison** [nylira/prism-break#1430]
hi irssi is by many regarded as probably the most rock-solid irc-client there is and should therefore be added to the list.

**Comment by hasufell** [comment]
Does it add anything special wrt security over the currently listed projects? prism-break is really not about listing _all_ alternatives to proprietary solutions. Otherwise the page would really be bloated.

**Comment by strugee** [comment]
Since irssi is a commandline application, I'd also question its user experience.

**Comment by hasufell** [comment]
It's an ncurses client, so it is practically terminal-GUI.

**Comment by vyp** [comment]
Correct, it's not a cli client afaik.

**Comment by hasufell** [comment]
It would be interesting to have it in case this https://github.com/cryptodotis/irssi-otr/issues/14 gets resolved... then it would probably have an advantage over many of the already listed solutions. But until then, I don't see a strong argument either for or against, so I'd just do nothing.

**Comment by strugee** [comment]
I know it's ncurses-based, but still... *shrugs*

It doesn't seem like a good idea to me, but I don't feel strongly about the matter.

**Comment by Zegnat** [comment]
I agree with @hasufell on this one. If IRSSI came with build-in encryption options it should clearly be listed, but as of now it doesn’t really have anything it does better or worse than listed alternatives.

**Comment by GreenLunar** [comment]
I think we should aspire to avoid including programs for use in terminal emulators.  We may, however, add a link to an advanced index with any other type of interface (cli, ncurses etc.)

**Comment by strugee** [comment]
@Zegnat in that case, can we close this issue?
