### ISSUE TITLE
DNSCrypt-Proxy

### ISSUE THREAD

**Issue by SINE** [nylira/prism-break#1432]
Hello,

does the DNSCRYPT protocol (not the OpenDNS one) https://github.com/jedisct1/dnscrypt-proxy
look like something that fits into your concept? It's OpenSource client- and serverside and also features a pre-defined list of resolver-servers.

A little quote:
The daemon is known to work on recent versions of OSX, OpenBSD, Bitrig, NetBSD, Dragonfly BSD, FreeBSD, Linux, iOS (requires a jailbroken device), Android (requires a rooted device), and Windows (requires MingW).

**Comment by mastercoms** [comment]
This is already on here.

**Comment by hasufell** [comment]
https://prism-break.org/en/projects/dnscrypt/

**Comment by Zegnat** [comment]
Closing as per the previous comments.
