### ISSUE TITLE
Add Raccoon to Appstores

### ISSUE THREAD

**Issue by onyxbits** [nylira/prism-break#1433]
http://www.onyxbits.de/raccoon
https://github.com/onyxbits/raccoon

Raccoon is a third party Google Play desktop client. While it doesn't allow you to go completely "off the records", it at least considerably improves the current situation:
- Use trash accounts to log into Google Play 
- Use a dedicated account to contact Play (prevent Google from tracking you cross service).
- Use a proxy connection to hide your IP address
- Avoid running the Play app on your device with elevated permissions and constantly staying in contact with Google servers.

**Comment by vyp** [comment]
Well prism break doesn't really recommend any apps that are on Google Play does it? So I don't think it would be useful to have this on the website.

**Comment by onyxbits** [comment]
> Well prism break doesn't really recommend any apps that are on Google Play does it? So I don't think it would be useful to have this on the website.

I would disagree. Most Android apps are only available via Google Play, but being on Play doesn't automatically mean that they are a privacy concern themselves (only the means of obtaining them is). 

Of course, in an ideal world, we would only use open source software that is either self compiled or distributed via a store like F-Droid, but the reality, for most users, is that there is no way around Play. So this boils down to the question: Ivory tower? Do only those who fully subscribe to OSS ideals deserve privacy protection?

**Comment by vyp** [comment]
Good point. Personally, I'd go with the ivory tower (f-droid) because even basic (play store) apps like a compass app (iirc) seem to spy on you, but I agree in that the average privacy minded android user would probably still want to use some apps only available on the play store (despite all the progress f-droid has made in recent years). Basically what Zegnat already said here: https://github.com/nylira/prism-break/issues/1414#issuecomment-144722237

Maybe we could say to prefer f-droid, but if you really need it, don't install the GAPPS, but use this client instead as it minimises risk to your phone.. ?

**Comment by onyxbits** [comment]
> Maybe we could say to prefer f-droid, but if you really need it, don't install the GAPPS, but use this client instead as it minimises risk to your phone.. ?

I fully aggree.

**Comment by yegortimoshenko** [comment]
Raccoon can't even be installed on a phone, it is a desktop software. Yalp Store can be installed, but it's not a marketplace but rather an alternative client for Google Play.

**Comment by Hillside502** [comment]
Some doubt as to whether Raccoon is open-source:-
https://alternativeto.net/software/raccoon/#comments

**Comment by onyxbits** [comment]
> Some doubt as to whether Raccoon is open-source:-

That comment is wrong:
https://github.com/onyxbits/raccoon4

**Comment by Hillside502** [comment]
That commenter appears to think that premium versions of software are not open-source.

Raccoon Premium Features | Raccoon - The best APK Downloader
http://raccoon.onyxbits.de/premiumfeatures

**Comment by yegortimoshenko** [comment]
Closing in favor of #1924. Raccoon is not a phone app.
