### ISSUE TITLE
Tor Messenger Chat App

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1435]
It's still in beta, just presenting to track for future consideration.

https://arlolra.github.io/tor-messenger-website/
https://blog.torproject.org/blog/tor-messenger-beta-chat-over-tor-easily

**Comment by strugee** [comment]
That blog post is from a year and a half ago and AFAIK Tor Messenger hasn't had any major problems in that time (though I haven't researched extensively).

It's still in beta, but it seems to me that the risk of screwing up a proper Pidgin setup (not to mention all the libpurple bugs) far outweighs the risk of running this beta. Not to mention the UX improvement. So I think we should list this.

FWIW there's a lot of info here: https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger

**Comment by strugee** [comment]
From `#tor-dev`:

> \<strugee> hey, all! hope this isn't off-topic for this channel but I'm curious how close Tor Messenger is to being considered "stable"?
> \<strugee> context: https://github.com/nylira/prism-break/issues/1435#issuecomment-279256781
> \<armadev> i use tor messenger and it works. i think the main problem with calling it stable is that we don't have any full-time (or anywhere close to full time) developers on it.
> \<armadev> and yes, anything involving libpurple is bad news.
> \<strugee> ok, thanks
> \<strugee> mind if I quote you on GitHub?
> \<armadev> sure.
> \<armadev> i guess it depends what your other options are. i also use ricochet and am happy with it.
> \<strugee> Ricochet is already listed on PRISM Break
> \<strugee> although it kinda seems like it has the same problem
> \<strugee> and e.g. Tor Messenger's update mechanism is better than Ricochet's
> \<strugee> which has none
> \<armadev> yep
> \<strugee> cool. thx armadev
> \<armadev> and actually, arlo tells me that maintaining tor messenger is super easy, so long as tor browser stays maintained
> \<armadev> because most of the patches are the same
> \<strugee> ah. great
> \<strugee> right
> \<armadev> that said, if mozilla adds something harmful and crazy that impacts tor messenger but not tor browser.. who will be there to notice it?
> \<strugee> right
> \<strugee> though idk that Instantbird is super actively developed - is it?
> \<strugee> certainly not like Firefox
> \<strugee> so it seems like they'd make less changes to it and therefore there'd be less risk of something weird
> \<armadev> instantbird is essentially abandoned too
> \<armadev> if that makes you feel more comfortable, great :)
> \<strugee> exactly. mixed blessing, I suppose :P

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Endorsement from Roger is always a good thing.

The tradeoff against Pidgin that I see here is that Pidgin supports
stream isolation (though with setup difficulty) but has memory safety
isues, while Tor Messenger has better memory safety (though a lot of
C++ code is present) but no stream isolation.  To my knowledge CoyIM
is probably superior to both Pidgin and Tor Messenger on both of these
points (stream isolation is automatic, and the source code is in Go),
so I guess the question of whether to add Tor Messenger is somewhat
dependent on whether to add CoyIM.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzhYmAAoJELPy0WV4bWVw8twP/3pOPlmS6XI4wGOgvPD8t5Up
wX5Pkz10tHAoU1Ct5eWGoWUnqLk9MjmhgA0bxXStCXLEeR497hmigkVlU12xRAkq
uS/XgH9zUV5mLCKXFaME7Mfoe7oMdPjcsvbapDW16xm17zdjLc6zq1IHfQvw50HS
OQx6KNShe1mAJ5Yz87T5+ewsDUzjZBpwvDwAF0mgldub6ICCVniTzbu58UbGoo8x
Gz2Xu/CghCw+3b7jDYhBTDAM7X/D6QZmmDcmcHvSmJr3DPQWhPThhGzjGIJXca6w
wfAT6Jv1+Xyg2YYzbaRP7tzpxM5ORuNGhvRSAbNFM/Zl7B+epvylhVp9LPXQnk27
iGEuBM+xUbKpv6PQSnvabZY3YA2CU1u5byKD2JzNGe51eXvejXE5NNe5BPplLPIi
hXt2bTkPq03sh6uryRLtZcoeLC1U+eKcL0lm7o1Sr2riRKfX2ZEWaCCqtC/6itsY
0fO2bjU7B0yt9R4PTlBil0B4yRFAW3Z0oiX3EmxtbPbBFjOkQH2MEwWDgCAYHnNS
b7R5/ejbQScvJZx+Ns4jgW6H6B4imRi1eFKhPYYUF2eoapKc3iPl6kKxrKJt8dpp
3ex5vw7perfC4K858xbBVmd9bXJaW53RjgL0/pQ1mUrcY2ZOiUb5AdDMVrgYXxWe
2cXCDn4h3DJEtY38N6mk
=JpH4
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@JeremyRand let's not bring CoyIM into this - that's a separate discussions for us to have. We've gone down this road of conflating two decisions before and usually, it's not helpful (though there are of course exceptions - the Pidgin removal being a notable example, since it depends so heavily on whether we think there's a better alternative in terms of UX).

Speaking of which: setting stream isolation aside, I see no reason for Tor Messenger to not be listed. It's better than what we currently have. If no one objects, I'll mark this as accepting PRs, with the acceptance criteria being "add Tor Messenger with a note about using Pidgin if you need stream isolation."

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> @JeremyRand let's not bring CoyIM into this - that's a separate
> discussions for us to have. We've gone down this road of conflating
> two decisions before and usually, it's not helpful (though there
> are of course exceptions - the Pidgin removal being a notable
> example, since it depends so heavily on whether we think there's a
> better alternative in terms of UX).
> 
> Speaking of which: setting stream isolation aside, I see no reason
> for Tor Messenger to not be listed. It's better than what we
> currently have. If no one objects, I'll mark this as accepting PRs,
> with the acceptance criteria being "add Tor Messenger with a note
> about using Pidgin if you need stream isolation."

Sounds good to me.  (Although I'd suggest that any such note should
mention that both Pidgin and Gajim support stream isolation.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzitSAAoJELPy0WV4bWVw6i0QAIn/3czc7S/kHmrBKknWaWpj
siEHGeIDAb4949HXQY/EgX1UbOdW3uqJPw0AZ8FVe90eA3Y3kDCBOkFyOUezI/Fw
pIHe7i/J2l7d5rEMAkwtWtwSHjlilKG8oMwqAhDjT8ShSZk+W94zrXX1fYxUhM0d
ZjA3H5rD/VRIf9xmZQBtPQ/Fj79N7qYRPVMIBkQ3AQ0AiqJLPPy31Rz2HuOCvL7N
Bys8FLSn5uwdm3oSaAJAqQbs4h73874WDeV4TcSa2ZUAZrQioesaetXwteNRQ5vL
sVA49gOpiM3roVVGxpkPVXVr2UfMEPQQUYv5hc9yEatCPwxUXFLcDllVpP9Z9Ox2
VIEKTTJcLBSnce7M8PYXdGGLieAqo3o/0EJy+I0iUoNq0bYUvh6fGXEDxfvMw8vz
R2K8vOvyg9HyvV+GoW/ZR8mkRdH13p6TWjAfMvylapaKi0rUiWZtHPeOD8NAjuh0
J1S04xdm1lDyqggjrHTsxn4kCHfrzlpJ1Bp4Xbd4RDv2lOxLryV3ZO+L6OTV7adQ
Xeqnj7dCYJR2qWhXv/eAA/+8tahzb1G6wS21uXWRFGBcYrlaZ1xuPv5UBytBxKM9
zdsqhgVWAb0rNsT62NvRg6E117Y2OKGyCYYDI6cn+cwCCHepadVhmaA4j++8YzTG
29BC9sDAaZH0VveSd1X2
=uvCS
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
:thumbsup: for adding Gajim to the note.

**Comment by yegortimoshenko** [comment]
I would be against adding any new XMPP clients that do not support OMEMO

**Comment by yegortimoshenko** [comment]
Conversations 2.0 has been released, and it doesn't include OTR support.

**Comment by strugee** [comment]
Deprecated upstream. https://blog.torproject.org/sunsetting-tor-messenger
