### ISSUE TITLE
Add MySearch metasearch engine.

### ISSUE THREAD

**Issue by GreenLunar** [nylira/prism-break#1438]
Local search engine portal designed to anonymize your search requests and have a better display of search results
A public instance is available at https://search.jesuislibre.net/

For more information, see https://codingteam.net/project/mysearch

**Comment by Zegnat** [comment]
This is not a metasearch engine as normally described. They normally query multiple search engines an do their own ranking. MySearch looks like a basic proxy. I am not sure if there is any merit in including it on PRISM Break.

**Comment by alerque** [comment]
As far as I can see it is not even a proxy in the classic sense that would anonymise your internet connection. The program seems to be a pass through of sorts minimizes local meta data and tracking tidbits being processed in your browser, but it still connects to the upstream search engine from your computer (or wherever the instance is being run) and thus leaves you just as exposed as you were before to global eves-dropping programs. I don't see any reason to include this on PRISM-Break. If you want to search anonymously our recommendation would be to access a search service through Tor or even a real proxy—anything that actually protects your connection.

**Comment by Zegnat** [comment]
It is a proxy, just like Privoxy is a proxy. But yes, if you run it on your own computer then it is your IP that the proxy will use. The more I look at it, the more I think it isn’t for PRISM Break.

I am planning to set-up a single issue that pulls all the search-related issues together and see if we can revise the search section once and for all. I should have time for that tonight.

**Comment by GreenLunar** [comment]
@Tuxicoman, please explain why MySearch should or should not be listed on PRISM Break.

Assuming you are https://codingteam.net/users/show/Tuxicoman

**Comment by yegortimoshenko** [comment]
> Project not found.

Demo URL (search.jesuislibre.net) now uses searx (see #1890).
