### ISSUE TITLE
"PRISM Break empfiehlt die S/MIME E-Mail Verschlüsselung nicht, da es Drittanbieter-Zertifikate von zentralen Autoritäten benötigt. Mehr hier (Englisch)."

### ISSUE THREAD

**Issue by ForumSchlampe** [nylira/prism-break#1439]
Stimmt schlicht und ergreifend nicht

**Comment by Zegnat** [comment]
Hmm, yeah, I guess this is wrong as it isn’t impossible to self-sign. Just like with TLS. Although I have heard self-signing is tedious with all the different S/MIME implementations out there. As an example, Mozilla Thunderbird didn’t used to (and maybe still doesn’t?) support self-signed S/MIME certificates and requires a certificate authority ([source](http://www.extinguishedscholar.com/wpglob/?p=1018)).

See #330 for the discussion that birthed the note you quoted.

How would you like to see it solved?

**Comment by TraderStf** [comment]
www.Startssl.com provides free certifcates.
Use it since 2 y

**Comment by TraderStf** [comment]
More here:
https://github.com/ripienaar/free-for-dev#security-and-pki

**Comment by Zegnat** [comment]
@TraderStf, it isn’t about what CA you pick. The problem is that the whole idea of a centralised authority structure breaks down when our browsers trust hundreds of them. I believe this problem carries over to email. See [#233 (comment)](https://github.com/nylira/prism-break/issues/233#issuecomment-20551794) for a discussion on PKIs.

I don’t mind revising the S/MIME note if someone could explain why S/MIME can be recommended as secure.

**Comment by TraderStf** [comment]
Sorry, read this in hurrry
perhaps an anwser here, did not check, must leave
https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide

**Comment by TraderStf** [comment]
"That leaves the truly paranoid with no other option than GPG or MIME to ensure the confidentiality of the messages they send."

http://arstechnica.com/security/2015/10/dont-count-on-starttls-to-automatically-encrypt-your-sensitive-e-mails/

**Comment by Zegnat** [comment]
Ars Technica basically [makes the same argument](http://arstechnica.com/security/2013/06/encrypted-e-mail-how-much-annoyance-will-you-tolerate-to-keep-the-nsa-away/3/) that PRISM Break is already making:

> <i>[PGP’s]</i> major virtue compared to S/MIME is that it doesn't depend on certificate authorities. This eliminates one source of costs (no need to buy certificates) and protects against a certificate authority being compromised by hackers or government forces.

Please read #233 and #330 before commenting. @ForumSchlampe says there is something wrong with the current note PRISM Break has about S/MIME, if you also think it is wrong or should be rephrased, please come with new arguments.

**Comment by ForumSchlampe** [comment]
@Zegnat 
sorry for late reply
s/mime doesnt require an ca, self signed certificates works and the Standard doesnt requires it ...it just depends on the mail program you use, it depends on the implementation but in no case you need certificates from 3rd party authorities.
In most implementations just the certificates must be trusted (explicit) or the issuer (ca or yourself when self signing) must be in trust store.

Self signed certificates in MS Outlook 
- to encrypt, just create an contact, assign the untrusted pub certificate to it, mark this certificate explicit as trusted (you can do through properties in Outlook)...everything is fine,. Alternative you can Import the Pub cert to trust store (personal or Computer)
- to decrypt your self signed certificate must be in the windows trust store

Self signed certificates in Windows live mail
- encrypt/decrypt: just accept the warning, all fine

Self signed certificates in Thunderbird
- i have to look for this, never used but i am pretty sure if you import your self signed pub cert to trust store everything is fine, maybe you can assign 

and of course, the own pki is a solution, too.

At the end, with s/mime you can control by yourself who is trustfull and whos not....thats why i cant follow your recommendation and i dont think this is actual correct.
"PRISM Break empfiehlt die S/MIME E-Mail Verschlüsselung nicht, da es Drittanbieter-Zertifikate von zentralen Autoritäten benötigt. Mehr hier (Englisch)." (netherless i dont find where this was written again)

**Comment by yegortimoshenko** [comment]
We should not support broken systems when there is an alternative, and system where one of 200 privileged entities can pretend they are someone else is broken.

@Zegnat: I agree wholeheartedly and think this can be closed.

**Comment by strugee** [comment]
Agreed. No reason to use S/MIME.
