### ISSUE TITLE
iCloud appears to have hosted document editing

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1444]
Looking at icloud.com, it appears that Apple is now offering hosted versions of its iWork suite. If someone can confirm this, we should add it to the proprietary column of the [productivity section][1].

 [1]: https://prism-break.org/en/all/#productivity

**Comment by vyp** [comment]
Yes I think so, at https://www.apple.com/iwork-for-icloud/, it says "You’ve got a new place to work. Right in your browser.", with a screenshot labelled "iWork for iCloud" which has internet explorer open.

**Comment by strugee** [comment]
@vyp OK, great. Thanks for preparing a patch!

**Comment by vyp** [comment]
@strugee No problem!
