### ISSUE TITLE
Alternative to MeetUp.com

### ISSUE THREAD

**Issue by EugeneDebs** [nylira/prism-break#1447]
Hi. Does anyone know an alternative which is not for profit as well as privacy conscious?

**Comment by yegortimoshenko** [comment]
Sorry, but no. I've looked for some, but didn't found any: https://www.reddit.com/r/selfhosted/comments/5lpw7o/selfhosted_meetupcomlike_site/

If you find something, feel free to open an issue proposing to add it on the site.

**Comment by yegortimoshenko** [comment]
(There's https://github.com/phoet/on_ruby, but it's not a proper Meetup replacement.)

**Comment by Hillside502** [comment]
Open Source Meetup Alternatives - AlternativeTo.net
https://alternativeto.net/software/meetup/?license=opensource
