### ISSUE TITLE
Detection Of Language Preference

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1448]
If I visit https://prism-break.org/ it redirects me to https://prism-break.org/en/ even though my languages are set to <code>de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4</code>. The /de/ version looks complete to me so why not redirect there? Same with all the other languages. I don't know how to detect the Accept-Language header but shouldn't be too hard.

**Comment by Zegnat** [comment]
@nylira will have to look at that, as it goes together with the server configurations. Maybe use [Accept Language Module](https://www.nginx.com/resources/wiki/modules/accept_language/)?

For people that might be hosting a copy of PRISM Break on an Apache set-up (like I am) we probably need to figure out how [content negotiation](http://httpd.apache.org/docs/2.4/content-negotiation.html) works. Regular expression parsing of the `Accept-Language` in .htaccess seems very prone to mistakes.

PRISM Break made a choice to be static files only, so everyone can host it anywhere. (You can grab the files [here](https://github.com/nylira/prism-break-static) and do not even need to build it yourself.) It was also decided not to load any JavaScript. So our options are rally limited.
