### ISSUE TITLE
Keepass v1.x app for Android

### ISSUE THREAD

**Issue by go2null** [nylira/prism-break#1453]
Currently, there is no Android flavour of Keepass recommended.  (The [list](https://prism-break.org/en/subcategories/android-password-managers/) only has [PasswordSafe](https://prism-break.org/en/projects/passwdsafe).)

I have been using [KeepassDroid](https://github.com/bpellin/keepassdroid) on my Android and BlackBerry devices for several years now.  I do not use Keepass v2.x database as I do not want Mono dependencies. (I also use Keepass on my Windows and Linux boxes.)  It is available on [F-Droid](https://f-droid.org/repository/browse/?fdfilter=keepass&fdid=com.android.keepass) and on [Google Play](https://play.google.com/store/apps/details?id=com.android.keepass).

Other suggestions (for Keepass v1.x database) are welcome.

**Comment by yegortimoshenko** [comment]
Sorry, there are no Android clients that support KeePass 1.x. KeePass 2.x has first appeared 11 years ago, so perhaps time to upgrade. Try KeePassX if you don't like Mono: https://github.com/keepassx/keepassx, https://www.keepassx.org/
