### ISSUE TITLE
"Social networks" should include Friendica

### ISSUE THREAD

**Issue by PerigGouanvic** [nylira/prism-break#1455]
"The Friendica Project is a world-wide consortium of software developers creating decentralised social platforms and technology for the coming post-Facebook world. We aren't as flashy and well known as some of the other projects working on a decentralised/federated social web, but we've been quietly working behind the scenes to provide the most reliable, full-featured, and extensible alternative to the monolithic providers."

http://friendica.com/

**Comment by vyp** [comment]
It is, under the "Servers" platform: https://prism-break.org/en/all/#social-networks

**Comment by PerigGouanvic** [comment]
I checked all categories, and could not see what I had seen initially, that is: a presentation of open social networks that did not include Friendica. Dunno what happened. Anyways, "problem" solved.

**Comment by vyp** [comment]
No worries :+1:
