### ISSUE TITLE
Weather apps for Android

### ISSUE THREAD

**Issue by Fale** [nylira/prism-break#1459]
Please add a "weather app" section for android

**Comment by Zegnat** [comment]
A weather app will not only need to be open-source, but also download all weather reports for all locations within a country at once, if it would want to be on PRISM Break and be conscious of the user’s location. I don’t think such an app exists, neither would it be feasible. You are probably better off using Tor to browse your favourite local weather site.

I am closing this issue. If such an app does come into existence, please create an issue for the specific app.
