### ISSUE TITLE
Roundcube mail services

### ISSUE THREAD

**Issue by Maxiride** [nylira/prism-break#1460]
I'm not that techy and found the website behind this repo very helpful. I'd like to hear the opinion from someone more expert then me about this email provider https://ruggedinbox.com/ , if it's secure and how much, if it can be trusted or not.

I know the issue tracker is meant to, track issues xD, but I didn't knew a more appropriate place where to ask.

**Comment by IDKwhattoputhere** [comment]
Limited to 30 emails per day but that doesn't seem like a huge downside for most. The design is really terrible (I'm talking about the red font). Seems like they had a spam issue which was fixed.

**Comment by Zegnat** [comment]
We refer to [this list of services maintained by /r/privacy](http://www.prxbx.com/email/). RuggedInbox is not included there.

See also [/r/privacy’s general advice on choosing an email service](https://www.reddit.com/r/privacy/wiki/index#wiki_what_is_a_good_secure_email_service_that_respects_my_privacy.3F).

**Comment by IDKwhattoputhere** [comment]
Sorry for comming back so late but I found some more info: http://thesimplecomputer.info/free-webmail-for-better-privacy#ruggedinbox
Seems trustworthy to me if my opinion counts for anything.

**Comment by Zegnat** [comment]
Looks pretty good, but PRISM Break does not want to turn into a list of email providers. The /r/privacy list already has 24 of them. Adding RuggedInbox would make 25. We see no real reason to recommend all of those and would rather just link to the list.

I would recommend getting in touch with the guys behind the Privacy-Conscious Email Services list and get RuggedInbox on there though!
