### ISSUE TITLE
Wrong Differences For Platforms

### ISSUE THREAD

**Issue by IDKwhattoputhere** [nylira/prism-break#1461]
Depending on which platform you choose, PRISM Break hides certain projects not available for it. But some stuff is hidden for no good reason.
- Adblock Edge is hidden on https://prism-break.org/en/categories/windows/#web-browser-addons and from the OS X, the GNU/Linux and the BSD section.
- NoScript is hidden from the Android section (https://noscript.net/nsa/). Although I don't know if NoScript Anywhere is stable enough anyways.
- OpenNIC is hidden from the Routers section but one could use their DNS servers in their router's settings.
- Self-Destructing Cookies is hidden from the Android section.
- I2P is hidden from the Android section.

**Comment by IDKwhattoputhere** [comment]
Thanks a bunch. :+1:

**Comment by vyp** [comment]
Thank you for noticing these!
