### ISSUE TITLE
How about this firefox-tor project?

### ISSUE THREAD

**Issue by simonasd** [nylira/prism-break#1462]
I just discovered this project called firefox-tor: https://github.com/yeahwu/firefox-tor

It looks like a Tor-Firefox bundle specified for user in China. As you know, Tor can't be use directly in China, so this bundle put [Lantern](https://github.com/getlantern/lantern) or [Shadowsocks](https://github.com/shadowsocks/shadowsocks) (The developer of Shadowsocks [was forced](https://en.greatfire.org/blog/2015/aug/chinese-developers-forced-delete-softwares-police) to remove his code.) before Tor.

I know many people here are really expert about anonymous, so I come to ask for your advice: Is this project good enough for anonymous? If so, I think it will benefit many people from nation like China or Iran.

**Comment by strugee** [comment]
This seems like an extremely bad idea to me.

It is extremely difficult to use Tor in China because China is extremely good at censoring their network. Replacing Tor with something less-tested and less secure is a fool's errand and is likely to get someone killed. Note that Lantern, for example [explicitly does not try to deal with anonymity][1].

Also, the way that this project is set up is extremely concerning. Just in the root of the repository I count 12 precompiled binaries. PRISM Break requires that every project on our list can be built from source. Even if it didn't, only Windows binaries are provided, and those can't be run on a free operating system.

Unfortunately, I don't see how this project would ever end up on PRISM Break. Please close.

 [1]: https://twitter.com/strugee2/status/498360131076521984

**Comment by simonasd** [comment]
@strugee Thanks for your reply. But first of all, I'm sorry I don't make it clear. I open this issue not to suggest a new project to PRISM Break. I just want some advice about anonymous, for those people who want to use this project.

Precompiled binary is indeed a problem, I will talk to the developer. And I have a new question about Tor:

>Replacing Tor with something less-tested and less secure is a fool's errand

Tor offer two ways for those who can't use it directly: meek, or proxy before Tor. I know lantern and ShadowSocks are not anonymous tools. But I don't know why we can't use these tool **before** Tor? Especially, I think ShadowSocks might be a good way to setup a self-hosted socks proxy.

**Comment by strugee** [comment]
@simonasd I don't understand what you mean by "proxy before Tor." I think you have some misconceptions about how Tor is implemented - you may want to read up on [Tor Pluggable Transports][1]. Regardless of what you mean, why would you _want_ to use these tools in conjunction with Tor? What's the benefit?

 [1]: https://www.torproject.org/docs/pluggable-transports.html.en

**Comment by simonasd** [comment]
Maybe I should describe it as "double proxy"?

China block known bridges, and using DPI at the same time. So before Meek(Other pluggable transports doesn't work) comes out, Tor was almost dead here. The only way to establish Tor was [proxy](https://www.torproject.org/docs/faq.html.en#NeedToUseAProxy) (I don't know the term, so I said "proxy before tor").

In some cities, local ISP might use their own firewall which block almost all foreign IPs. In this case, Meek fail too. Proxy become the only option.

My ISP is that bad. I can't connect to google, amazon, Microsoft or GitHub. So Meek doesn't work for me, I have to use proxy to bypass local ISP's firewall and the Great Firewall, then use tor.

**Comment by strugee** [comment]
So if I understand correctly, some application generates traffic which then goes into the local Tor daemon. Then whatever encrypted, relay-bound traffic comes out of that Tor daemon goes over e.g. Lantern. Is this what you're proposing?

**Comment by simonasd** [comment]
@strugee

The normal way to use Tor: Browser → Tor → Tor network → Target.

The Way with proxy: Browser → Tor → proxy → Tor network → Target.

**Comment by strugee** [comment]
I can't find anything obviously wrong about that (although there might be), but there are a huge number of moving parts. I wouldn't recommend such a solution for that reason alone.

**Comment by Zegnat** [comment]
The Tor project developed meek & obfs3/obfs4 to establish Tor connections. If those are fully blocked, I guess there is little you can do. I cannot comment on Lantern or Shadowsocks as I haven’t looked into them.

I think (but don’t quote me on it) that you could run your Tor traffic through any third proxy you want without hurting your anonymity. I believe all data gets encrypted by Tor when it is sent and no proxy can eavesdrop. You might leak information about what entry nodes you are using though, and of course the proxy knows your connection comes from China. But as @strugee said, when you add extra steps you add way more extra complexity and possibilities to failure, and I have no time to look into any specific set-up.

You may want to look at [this email](https://lists.torproject.org/pipermail/tor-dev/2014-March/006356.html) and [its follow-up](https://lists.torproject.org/pipermail/tor-dev/2014-March/006363.html) for using Lantern as pluggable transport for Tor.

This discussion is probably better suited for a Tor mailing list than here, so I am going to close it.

**Comment by simonasd** [comment]
Thank you @Zegnat and @strugee for your advice, i think I have enough information now, I will keep an eye on it in the future :)
