### ISSUE TITLE
Add typed.pw?

### ISSUE THREAD

**Issue by xojoc** [nylira/prism-break#1465]
https://typed.pw maybe a useful addition to the list ☺.

**Comment by strugee** [comment]
@xojoc what category do you see this going in?

**Comment by xojoc** [comment]
Either "Productivity" or "Media Publishing" I guess.

**Comment by yegortimoshenko** [comment]
Repo (hasn't been updated for a year): https://github.com/xojoc/typed

When trying to connect to https://typed.pw, I get:

```
typed.pw uses an invalid security certificate. The certificate is only valid for xojoc.pw Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

https://xojoc.pw is @xojoc's personal web page.
