### ISSUE TITLE
Mailing, Filesharing, Instant Messaging

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1472]
I think "Kolab Now" is not very suitable for Prism Break. Private Mailing-Service should not cost so much money.

Free, secure and anonymous alternatives for Mailing-Service:
https://www.systemli.org

Free German Mail-Service (no english translation):
https://free.de
https://systemausfall.org
https://www.immerda.ch/
https://so63.net

Filesharing:
https://onionshare.org/

Instant Messaging:
https://www.whispersystems.org
https://rocket.chat

The list on prism break is for me very full and unclear. To make it clear, you could suggest and favour one service per category with a little reason why it is better then the other services. Or you could always shortly show differences between the services.

**Comment by mastercoms** [comment]
If you don't pay for a service, you are either the product, or the service will not last long.

Anything favoring one or showing differences would be biased in some way. It is up to you to research the differences between the services, as they are largely personal preference.

**Comment by 9203948** [comment]
There is a difference between buying a product or donating for a service.
Probably many people have no time to research the differences between services. Showing differences is not biased but rather facilitate the research. These would only be suggestions, no absolute information.

**Comment by mastercoms** [comment]
Then you have something like img.bi, great donation supported service, but it's down because of lack of donations, most likely.

**Comment by hasufell** [comment]
> you are either the product

That's not necessarily a bad thing, as long as that is transparent (e.g. advertisement). You can run an AGPL licensed service and still provide ads.

**Comment by GreenLunar** [comment]
> If you don't pay for a service, you are either the product, or the service will not last long.

You are correct.  But I, and even you, would prefer to have power decentralized.

Realization:
Assume are your own email provider, and you correspond exclusively with users of the provider *@prism-break.org*, there would not be any difference than yourself corresponding with an account on *@prism-break.org*.

**Comment by yegortimoshenko** [comment]
OnionShare: #1133
Signal: #552, #896, #1314 
Systemli: #1912 
Rocket.Chat: #1913 

https://free.de and https://so63.net are defunct, have not opened an issue for the other two because they do not have a page in English.
