### ISSUE TITLE
Add OMEMO to /protocols/omemo

### ISSUE THREAD

**Issue by GreenLunar** [nylira/prism-break#1476]
So far, two software support [OMEMO](http://conversations.im/omemo/) encryption, [Conversations](http://conversations.im/), [Cryptocat](https://crypto.cat/) and [Gajim](https://gajim.org/) (as plugin).

I suggest to add `/protocols/omemo` to raise awareness and receive more feedbacks on OMEMO, and to instigate its support on other software platforms.

**Comment by alerque** [comment]
I'm sympathetic to the cause of raising cryto awareness, but raising attention and review of protocols isn't the primary goal for PRISM-Break. The things we list are suggestions or recommendations. As such we can't list something just to get more feedback. That's what these Github discussions are for. Listing something on the site means we've received sufficient feedback to feel comfortable recommending something. I do think we should review OMEMO, but listing it won't be done for the reasons you list.

As far as considering it as something to recommend, has any third party review been done such as an audit on the protocol itself? Are there comments from academia that should be considered? Has anybody here dug into it?

**Comment by GreenLunar** [comment]
I agree with all that you wrote.  I do.

There was a [short discussions](http://mail.jabber.org/pipermail/standards/2015-November/030622.html) about OMEMO on XMPP Standards, and [ChatSecure](https://chatsecure.org/blog/chatsecure-conversations-zom/) is planned to have OMEMO support.

I have no other resources to refer to.

**Comment by GreenLunar** [comment]
Another case (a request in a bug tracker)

#17457 (Implement OMEMO) – Tor Bug Tracker & Wiki
https://trac.torproject.org/projects/tor/ticket/17457

**Comment by GreenLunar** [comment]
[Cryptocat - Security](https://crypto.cat/security.html) (supported) @iNPUTmice and @edhelas, if you know of more XMPP clients that support OMEMO, please list them here.

**Comment by GreenLunar** [comment]
New links (3):
[feature request for omemo · Issue #228 · jsxc/jsxc](https://github.com/jsxc/jsxc/issues/228) (open)
[XEP-xxxx: OMEMO Encryption · Issue #497 · jcbrand/converse.js](https://github.com/jcbrand/converse.js/issues/497) (open)
[XEP-xxxx: OMEMO Encryption · Issue #9 · anurodhp/Monal](https://github.com/anurodhp/Monal/issues/9) (open)

**Comment by participante0** [comment]
> As far as considering it as something to recommend, has any third party review been done such as an audit on the protocol itself?

Yes, on June 1, 2016: https://conversations.im/omemo/audit.pdf

**Comment by participante0** [comment]
> Are there comments from academia that should be considered?

Yes, on 25 August 2016:
https://link.springer.com/chapter/10.1007%2F978-3-319-45982-0_22
https://www.academia.edu/28117072/End-to-End_Encrypted_Messaging_Protocols_An_Overview

**Comment by iNPUTmice** [comment]
Since it has been audited and also implemented in three clients that are mentioned here, is there anything else that has to happen before this can be added to the protocols?

**Comment by strugee** [comment]
I don't have any objections. Security is pretty good and it seems like this is where most of the XMPP ecosystem will end up moving. The one concern I have is lack of client support - 3 is not a lot. But IMO it _is_ "good enough," so I say ship it.

Anyone disagree?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> I don't have any objections. Security is pretty good and it seems
> like this is where most of the XMPP ecosystem will end up moving.
> The one concern I have is lack of client support - 3 is not a lot.
> But IMO it _is_ "good enough," so I say ship it.
> 
> Anyone disagree?

I support adding OMEMO.  From my understanding it's held up reasonably
well to review, and my experience trying to get non-technical users to
use OTR suggests that OMEMO's improved usability is likely to attract
a lot of users who refuse to use OTR.

FWIW, last I heard, the CoyIM devs are declining to implement OMEMO
and are choosing to wait for the next version of OTR (which is planned
to have a similar, though not identical, feature set to OMEMO).  I
don't think the existence of a WIP spec for a future OTR version is a
good reason to exclude OMEMO now.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYjti8AAoJELPy0WV4bWVw/A4QAM2/X0CeW6dgx6G0tbTaIL/+
TTj92KU0eEQxr+xdWu8RgfJCG1X4BpjPtiy9CZjmCJlvlU3T6RilYvsT68wJtKCl
7HdZyI4nAyNnxnkvDFQWXMzgCGKfRrfPAqbkxH0DE3NO3GG+VQTz4eohXB7bN/Iz
r+VmvTJSQvwHp7U/lU3WZ8WaPv2waIisBiIyBxMBCMA7LBk0WH8TFEOCtt4PjYu9
mqxpqNa3HQD4kTnoY9okqm+Q1MSpel3cdxuAeUBHLeUkQbqcG5mBYcLEsfBH4xIC
KbbMCQumllJxdbBYT8wYh8kPdMb5OBo5AZGbGtQjEGZq0lOS8MXGGK0WQSycIt81
fAPiv2rO4CoI5R9Kx0Pky4pRcp8bSAnLWyoqAt0+7gT8Uih6gYSepbhzpTaXJ1bc
ei5lRfaeFoSaVNhnIrIGLFSmPknQJHgyP1VaoLOm30fIrgwo6cgwe5Cwtw811iEq
otzfMl3fa+V8A+Kwrn97UiwtECiNOQVwNAuSRjrtU3oDHxJBQYwcsqlEsFPYQNsL
qdMnI+obcBAk5o38TzLGCAapgNHoi+lRJVWwMOrLmdb2iNTVXk5/Ch0BNF96Oi6k
zhnfZhdOeVOHGYNPSMPorn/1ZDASCKyiFm0biZ84EXXSqkaNvRtwYeFaTgpK/8tO
C/yXWnXbB8BOMjmuIKpS
=LYRj
-----END PGP SIGNATURE-----

**Comment by mimi89999** [comment]
@strugee I made a PR some time ago. Can you give me any hints about what to change in it?
