### ISSUE TITLE
Add FreeOTP

### ISSUE THREAD

**Issue by quicklyandremember** [nylira/prism-break#1479]
Alternative to Google Authenticator / Authy

**Comment by Zegnat** [comment]
This is interesting, but can it replace Google’s Authenticator or Authy on websites that have implemented those? Otherwise it isn’t actually replacement software.

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-X-XX** [comment]
FreeOTP Utilizes TOPT and HOTP so It should. 
Taken from the Google Play store subscription: "FreeOTP works with many of the great online services you already use, including Google, Facebook, Evernote, GitHub and many more! FreeOTP also may work for your private corporate security if they implement the standardized TOTP or HOTP protocols. This includes great enterprise solutions like FreeIPA."

**Comment by GreenLunar** [comment]
Any links?

**Comment by GreenLunar** [comment]
Another case (a request in a bug tracker)

#17457 (Implement OMEMO) – Tor Bug Tracker & Wiki
https://trac.torproject.org/projects/tor/ticket/17457

**Comment by GreenLunar** [comment]
Please ignore my second comment. Wrong issue. Sorry

**Comment by Dostoi** [comment]
https://f-droid.org/repository/browse/?fdfilter=otp&fdid=org.fedorahosted.freeotp
https://fedorahosted.org/freeotp/

**Comment by GreenLunar** [comment]
Thanks.

**Comment by 1029chris** [comment]
This seems like a good idea. Using authentication apps is a very good idea for security, and recommending an open source one rather than the default google one would be a great idea. It even looks better than the Google one.
