### ISSUE TITLE
Servers:OS:Debian: Add note that DNS must be explicitly set, else uses Google DNS

### ISSUE THREAD

**Issue by go2null** [nylira/prism-break#1481]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658

---

From: md@Linux.IT (Marco d'Itri)
To: martin f krafft madduck@debian.org, 761658-done@bugs.debian.org
Subject: Re: Bug#761658: Please do not default to using Google nameservers
Date: Sun, 29 Mar 2015 05:57:22 +0200

On Sep 15, martin f krafft madduck@debian.org wrote:

> From a cursory look over the sources, I am led to believe that
> resolved defaults to using Google nameservers.
> From resolved.conf(5):

```
Any per-interface DNS servers obtained from 
systemd-networkd.service(8) take precedence over this setting, as do 
any servers set via DNS= above or /etc/resolv.conf. This setting is 
hence only used if no other DNS server information is known.
```

---

From: Martin Steigerwald martin@lichtvoll.de
To: 761658@bugs.debian.org, Christoph Anton Mitterer calestyo@scientia.net
Subject: Re: Bug#761658: Please do not default to using Google nameservers
Date: Sun, 29 Mar 2015 11:59:10 +0200

I highly appreciate if the default of using google name server if nothing 
else is configured is removed from Debian´s systemd.

I had a similar issue with Debian packaged Wordpress which appears to try 
to download fonts from Google unless I install a plugin to disable this, 
which I didn´t yet report. But really, if there is no DNS server 
configured I expect name resolution to _fail_, instead of the system 
asking any DNS server of choice by some who was not me. At least unless 
there is a DNS service that provably doesn´t track and save queries of 
users of it. As thats near to impossible to prove.

And no, I do not want to have to configure the system for basic privacy. I 
do want this to be the default. This is Debian, no Google Play enabled 
Android device

**Comment by Atavic** [comment]
Google DNS servers temporarily store your IP, as per privacy rules.

**Comment by strugee** [comment]
Yes, we're all aware of problems with Google's DNS - that's why it's in the proprietary column.

The real question is if this is still an issue.

**Comment by yegortimoshenko** [comment]
I don't think this is an issue, at least not anymore: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658#216

If it were, Google Public DNS is only used if there are no any other alternatives, in which case it would otherwise result in no resolving at all. On scale of Debian, there isn't much choice but to default to Google Public DNS. I'm against this note because it practically never happens.
