### ISSUE TITLE
Decentraleyes?

### ISSUE THREAD

**Issue by Nudin** [nylira/prism-break#1483]
A quite new Browser-Addon to improve privacy is [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/). It's free software (MPL 2.0).
The concept seems valid, but I'm not sure how effective it is. I'm interested in your thoughts…

**Comment by Zegnat** [comment]
Really interesting add-on. The concept is definitely valid. We should probably consider this one for PRISM Break!
