### ISSUE TITLE
Esperanto translations

### ISSUE THREAD

**Issue by Riamse** [nylira/prism-break#1484]
The esperantaj traduktoj are incomplete. This must be fixed.

**Comment by Riamse** [comment]
I'm working on it.

**Comment by Grossdm** [comment]
May I ask why?
How many people are fluent in Esperanto? A dozen or so?
Perhaps I have a misunderstanding re: Esperanto.

**Comment by alerque** [comment]
More importantly, how many people are fluent in Esperanto and also _not_ fluent in any of the other translations provided already.

I would say this issue can be closed as not being an _issue_ with the project (i.e. I disagree with the "must be fixed" statement). If anybody wants to do this they are welcome to do so and submit a PR for consideration, but until such a time this doesn't need to clutter up the open issue list.

**Comment by hasufell** [comment]
It's fine to have this issue as a starting and coordination point for people who want to contribute to the esperanto translation.

**Comment by Grossdm** [comment]
But @hasufell , what **language** should be used for the [Issue](https://github.com/nylira/prism-break/issues/1484):question: :grin: :smirk: :wink:

**Comment by hasufell** [comment]
@Grossdm english.

**Comment by yegortimoshenko** [comment]
Ĉu vi ankoraŭ volas traduki?

**Comment by yegortimoshenko** [comment]
Apparently not :-) It is the case that Esperanto translations are not complete, but that also applies to most of the translations. Feel free to open a pull request.
