### ISSUE TITLE
Cryptocat suspending operation pending software upgrade 2016/2/19

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1489]
Went to install Cryptocat on a laptop and went to its site, crypto.cat, which displays this message.

Dear Cryptocat users,

Since February 2015, I've been spending almost all of time working on my graduate studies. During this time, I have been unable to maintain Cryptocat and the project has gone without any software update for 19 months. The iPhone version has been completely non-functional for four months. Since it is the most correct way to proceed, I am temporarily suspending the Cryptocat service until the complete software rewrite that I'm working on is released. I promise you that this suspension is strictly temporary.

This complete Cryptocat rewrite benefits from a more mature understanding of secure messaging, incorporates more modern engineering, and will simply be good software. There is a design decisions that is not open for negotiation: it will be desktop-only. This due to the my belief that the mobile space has been elegantly solved by other well-written open source software, while the desktop/laptop space could still use an alternative for usable, fun and secure messaging software, developed in the vein of general purpose computing. Due to a personal conviction, the re-released Cryptocat will also not accept any donations or take in any sort of grant funding. All other decisions are open for discussion, and, as always, I will entertain random input to an almost unreasonable degree.

This decision may feel sudden but isn't. As it stands, the Cryptocat software is ageing and unmaintained. If one is to aim to provide secure messaging, it can't be without reasonable quality assurance and guarantees based on a modern engineering foundation. A piece of software that was written in 2012 and that has been unmaintained since 19 months ago is not a responsible way to provide secure messaging guarantees, even if there isn't anything particularly wrong with the software itself. It's a question of addressing the notion of responsibility with a counterweight of a baseline of quality standards. The new Cryptocat rewrite will meet this baseline, and I'm very excited to see it released.

The new Cryptocat rewrite will incorporate many interesting technologies that I've been working on at INRIA's PROSECCO lab. I have the highest of hopes for it and aim for it to satisfy your desktop secure messaging needs in the same way that Cryptocat has in the past. I am hoping to release the first version this year.

Thank you for your continued interest in what I believe has been one of the most pertinent software projects in modern secure messaging, and software that I will always enjoy writing. Most of all, thank you for using and supporting Cryptocat. A pure vision of democratized, pleasant secure messaging is something the world needs.

Nadim Kobeissi
February 19th, 2016

**Comment by jcluster** [comment]
CryptoCat is up and running again with a totally new client, which is currently in beta stage (available for Windows, Linux and Mac, 04/17/16).

**Comment by merlinnusr** [comment]
YES .

**Comment by mimi89999** [comment]
@nylira I think that this issue can be closed now.
