### ISSUE TITLE
add VIPole

### ISSUE THREAD

**Issue by AlexKirk** [nylira/prism-break#1490]
VIPole messenger strongly encrypts instant text messages, group chats, voice calls, video calls and files so that no third-party (even we as service provider) is able to listen to conversations or tap into a message or file. VIPole is a secure messaging app powered by strong encryption technologies that perfectly guard your privacy, sensitive private communications and files from prying eyes and surveillance efforts.

**Comment by hasufell** [comment]
This looks like proprietary software. At least, I couldn't find the source code. Where is it? And what's its license?

**Comment by yegortimoshenko** [comment]
https://www.vipole.com/en/

Proprietary software. Safe to close.

**Comment by alerque** [comment]
Ya, nope.
