### ISSUE TITLE
2 open source client-side encryped webmail services

### ISSUE THREAD

**Issue by bdimych** [nylira/prism-break#1498]
tutanota.com
protonmail.com

**Comment by alerque** [comment]
First of all, one issue per application please. That way each can be discussed on its own merits and the discussion of one won't side track the other.

Secondly, both of these applications have been discussed before. Please search the issue list ([tutanota](https://github.com/nylira/prism-break/search?q=tutanota&type=Issues&utf8=%E2%9C%93), [protonmail](https://github.com/nylira/prism-break/search?q=protonmail&type=Issues&utf8=%E2%9C%93)) and add anything useful to  the corresponding issues.

This issue should be close in favor of the existing discussions.

**Comment by Zegnat** [comment]
Closing this for all the reasons @alerque put down.
