### ISSUE TITLE
microG project as alternative to Google Play Services

### ISSUE THREAD

**Issue by hansWURSCHT10000** [nylira/prism-break#1503]
What about adding the micoG project to prism-break?

MicroG tries to replace the proprietary Google Play Services with a FLOSS (Free/Libre Open Source Software) alternative.
This is the main part of the project:
https://github.com/microg/android_packages_apps_GmsCore
But there are also many other parts:
https://github.com/microg

I use microG since 5 months and I'm very happy with it.

**Comment by anthologist** [comment]
I quote from their wiki https://github.com/microg/android_packages_apps_GmsCore/wiki
"This is currently alpha-grade Software. Don't use it if you're not aware of possible consequences. Possible consequences include that your very private data leaks to Fort Meade."
So maybe it's too early to include it, interesting project though.

**Comment by hansWURSCHT10000** [comment]
I think in stability it's not alpha software only the installation is a bit complicated. 
It's much better than using a ROM with Google Play Sevices in terms of privacy (and also battery life).
And it's also far better than using a ROM without the Google Services because many apps will crash or they don't even install if there are no Google Sevices available. Sometimes there are alternative apps which don't rely on Google Services but often there aren't any equal alternatives.

**Comment by strugee** [comment]
@hansWURSCHT10000 as @anthologist said, it's an interesting project. But in general when maintainers say that their software is alpha, PRISM Break takes that seriously.

I suppose we could add it with the "experimental" flag, but personally I'd be uncomfortable recommending an alpha-quality system component (as opposed to "just" an app).

**Comment by hansWURSCHT10000** [comment]
@strugee I think the experimental flag is a good compromise. So the people know of the existence of the microg project.
