### ISSUE TITLE
MEGA is now Open Source

### ISSUE THREAD

**Issue by blade1989** [nylira/prism-break#1506]
MEGA up until now, was not supported because they were not Open Source, we'll they are now, see there GitHub page:

https://github.com/meganz/

Mega Sync Client webclient and extensions are there!

**Comment by hasufell** [comment]
All I see are clients and a Mega SDK (which is not AGPL). I don't see the software that is run on the MEGA cloud or am I missing something?

**Comment by blade1989** [comment]
@hasufell Mega is nothing more than web-clients and Sync Clients. Or am I Missing something. I assumed the mega synced to a server, which is the webclient? 

See: https://mega.nz/#sourcecode

**Comment by hasufell** [comment]
https://github.com/meganz/webclient/blob/master/LICENCE.md

The license is very questionable. It's definitely not "free" in terms of the FSF. But it's even debatable if this qualifies as open source wrt the OSI.

E.g.
```
We may suspend, terminate or vary the terms of this licence and any access to the code at any time, without notice, for any reason or no reason, in respect of any licensee, group of licensees or all licensees.
```

and
```
 you are not entitled to use or do anything with the code for any commercial or other purpose, other than review and commentary on it
```

are very clear that this is not a project you can just fork, work on and deploy.

**Comment by blade1989** [comment]
... Should have research this better... My bad

**Comment by Zegnat** [comment]
It is basically stated in the very first line of the [LICENCE](https://github.com/meganz/webclient/blob/master/LICENCE.md) file:

> This licence grants you the rights, and only the rights, set out below, **to access and review** Mega's code.

This is called [source-available](https://en.wikipedia.org/wiki/Open-source_software#Open-source_vs._source-available) rather than open source. We have had projects with such licences before, and they are not free enough for PRISM Break.

Closing.

**Comment by merlinnusr** [comment]
I dont understand mega people ,why use a own license.

**Comment by hasufell** [comment]
> I dont understand mega people ,why use a own license.

A lot of companies, even these days, don't understand the concepts of opensource or free software. With it sometimes goes the wrong assumption that you cannot make money with those.
