### ISSUE TITLE
Add lantern and Firetweet

### ISSUE THREAD

**Issue by merlinnusr** [nylira/prism-break#1507]
[lantern](https://github.com/getlantern/lantern)

It's opensource :dancer:  :100:
And https://firetweet.io/

**Comment by strugee** [comment]
PRISM Break is not about censorship circumvention, it's about privacy and mass surveillance. Lantern has no useful privacy properties in the context of PRISM Break, and FireTweet promotes Twitter, which we specifically recommend against.

See also #319

**Comment by Zegnat** [comment]
@strugee is right. Lantern itself still [recommends Tor](https://github.com/getlantern/lantern/wiki/Questions-and-Answers) in their FAQ:

> **Lantern is not an anonymity tool.** If you require that the sites you visit do not learn your IP address or physical location (they normally can, which may come as a surprise), or you cannot risk network monitors being able to determine what sites you visit, we recommend you use Tor. 

(Emphasis theirs!)
