### ISSUE TITLE
How about adding Rumble?

### ISSUE THREAD

**Issue by bcu8heq2** [nylira/prism-break#1508]
I discovered Rumble (http://disruptedsystems.org) recently and find it quite promising for building mobile mesh networks. How do you feel about adding it to the PRISM BREAK collection?

**Comment by hasufell** [comment]
[licence](https://github.com/Marlinski/Rumble/blob/master/LICENSE.txt) looks ok, but it seems to have the [Antifeature Tracking](https://f-droid.org/wiki/page/Antifeature:Tracking) [according to fdroid](https://f-droid.org/repository/browse/?fdid=org.disrupted.rumble)

**Comment by bcu8heq2** [comment]
I think in this case the definition of this anti-feature made by F-Droid falsly covers the intended feature of Rumble and is nothing to worry about. This app of course monitors bluetooth and wifi for other Rumble users and then exchanges info automatically. Otherwise it would be useless.

Am 28. März 2016 18:31:24 MESZ, schrieb Julian Ospald <notifications@github.com>:

**Comment by merlinnusr** [comment]
Sounds nice .

**Comment by yegortimoshenko** [comment]
Still might be useful, but not updated since April 2017: https://github.com/Marlinski/Rumble

**Comment by yegortimoshenko** [comment]
We list many other mesh networking options, so doesn't seem warranted to list abandonware.
