### ISSUE TITLE
security issues on https://prism-break.org need improvement

### ISSUE THREAD

**Issue by wmra** [nylira/prism-break#1512]
please check configuration:

https://www.ssllabs.com/ssltest/analyze.html?d=prism-break.org

**Comment by strugee** [comment]
@wmra can you please change the title of this issue to something more descriptive, e.g. "TLS configuration on https://prism-break.org needs improvement"?

/cc @nylira since we need you to do this server-side

**Comment by merlinnusr** [comment]
www.linuxjournal.com/content/cipher-security-how-harden-tls-and-ssh

**Comment by wmra** [comment]
@strugee hope this title is more descriptive. TLS configuration is not the topic, but key exchange, Forward Secrecy.

**Comment by strugee** [comment]
@wmra yes, that's much better.

(That being said: TLS configuration _is_ the topic. Forward secrecy and key exchange are both parts of TLS. For example, @nylira needs to adjust the preferred TLS cipher suites in order to improve forward secrecy.)

**Comment by wmra** [comment]
@strugee you are right, of course. TLS is not only the protocol.

**Comment by nylira** [comment]
Thanks for bringing this to my attention, @wmra. It's been fixed.

https://www.ssllabs.com/ssltest/analyze.html?d=prism-break.org

**Comment by wmra** [comment]
well done - Triple A
