### ISSUE TITLE
ungoogled-chromium

### ISSUE THREAD

**Issue by tristan-k** [nylira/prism-break#1516]
# [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium)

**Patches for Google Chromium to remove integration with Google services and add additional features**
### Features

In addition to features provided by [Iridium Browser](https://iridiumbrowser.de/) and [Inox patchset](https://github.com/gcarq/inox-patchset), the following is also included:
- Remove additional detection of Google hosts
- Disabled searching in Omnibox
- Disabled automatic formatting of URL in Omnibox
- Disabled JavaScript dialog boxes from showing when a page closes (onbeforeunload dialog boxes)
- Added menu item under "More tools" to clear the HTTP authentication cache on-demand
- Disabled persistent per-site settings in Preferences file
- Make all popups go to tabs
- Replaced many domains in the source code with non-existant alternatives (see `domain_patcher.sh`)
- Stripped binaries from the source code (see `source_cleaner.sh`)
- Debian build scripts
  - (Debian build scripts change) Move the chrome-sandbox into a separate package
- (Iridium Browser feature change) Prevent URLs with the `trk:` scheme from connecting to the Internet
- (Iridium and Inox feature change) Prevent pinging of IPv6 address when detecting the availability of IPv6
## Patches

All features come in the form of patches. Patches are stored in the `patches` directory, with the exception of platform-specific patches (which are in the `build_templates` directory).

The latest set of patches are available on [the tags page](https://github.com/Eloston/ungoogled-chromium/tags). See the Building section below for information on using these patches.

Here's an overview of the files in the `patches` directory:
- `ungoogled-chromium/`
  - This directory contains new patches for ungoogled-chromium. They implement the features described above.
- `iridium-browser`
  - This directory contains patches derived from Iridium Browser.
  - Patches are from the `patchview` branch of its Git repository. [Web view of the patchview branch](https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/?h=patchview)
- `inox-patchset/`
  - This directory contains patches derived from Inox patchset.
  - Patches are from [inox-patchset's GitHub](https://github.com/gcarq/inox-patchset)
  - [Inox patchset's license](https://github.com/gcarq/inox-patchset/blob/master/LICENSE)
- `debian/`
  - This directory contains patches from Debian's Chromium.
  - These patches are not Debian-specific. For those, see the `build-templates/debian/` directory
- `patch_order`
  - Determines which patches are used and what order they should be applied
## Releases

Builds with these patches are available on [the releases page](https://github.com/Eloston/ungoogled-chromium/releases).

**Comment by merlinnusr** [comment]
Sounds good  . 
But chromium can be hardened like firefoxx 
in  ungoogled-chromium can disable webrtc ?

**Comment by strugee** [comment]
I'm a little uncomfortable that there's no way to verify download signatures.

**Comment by hasufell** [comment]
The build process is a mess and doesn't work properly unless you are on debian/ubuntu.

**Comment by Eloston** [comment]
Hi, I'm the developer of ungoogled-chromium.

Quite a bit has changed since this issue was posted. I'll start out by addressing the concerns:

> in ungoogled-chromium can disable webrtc ?

Yes. WebRTC is disabled through a build configuration flag, among other features. The patches make up for what the flags can't do.

> I'm a little uncomfortable that there's no way to verify download signatures.

I haven't gotten around to this yet. It should be fine for now as long as GitHub or my account isn't compromised.

> The build process is a mess and doesn't work properly unless you are on debian/ubuntu.

ungoogled-chromium now also supports Windows and Mac OS. There's a new build system in place that works across these platforms. I'm not sure what you consider a mess, but it's definitely better than before.
