### ISSUE TITLE
VoIP is not a Protocol

### ISSUE THREAD

**Issue by daniel-lucio** [nylira/prism-break#1522]
https://github.com/nylira/prism-break/blob/master/source/db/protocols/ca-protocols.json

VoIP means Voice over IP, it is a service. You can use many different protocols to get VoIP working, SIP is only the signaling part which it is optional now. Other protocols used to get VoIP working are RTP, AIX, WebRTC (which I am not really sure it is a protocol) and Verto. There are proprietaries as well such as the skinny or the closed one such as skype.

So, this is a fundamental concept error.

**Comment by Atavic** [comment]
Neither VoIP nor WebRTC are Protocols. Both are implementations over the Internet Protocol.
WebRTC 1.0: Real-time Communication Between Browsers
