### ISSUE TITLE
Include Scryptmail as an email provider in Prism Break

### ISSUE THREAD

**Issue by Roxenv** [nylira/prism-break#1530]
Scryptmail seems promising, judging by their feature set, privacy policy and terms of service.Here are the links:
https://scryptmail.com/

https://scryptmail.com/#TermsAndConditions

https://scryptmail.com/#PrivacyPolicy

For comparison with other email providers here is a link:

http://www.emailquestions.com/encrypted-email-service-providers/

Even though their servers are in usa, but they claim to be completely opensource and have their own reasons for keeping their servers in us only.Here is the link for their arguments regarding server locations:

https://blog.scryptmail.com/q-a/

Please review them and give your insights.Thanks

**Comment by mimi89999** [comment]
I don't think it is as good as they say it is.

I think that it is the best to use an email client with PGP/GPG for e2e and IMAPS/SMTPS to communicate with the mail server.

**Comment by Sephula909** [comment]
Depends on what you're trying to protect against. If you're trying to avoid PRISM, like this network would seem to imply, you need a solution with which to distance your real identity from association with the account, and any metadata. Protecting the email's content is beyond this scope, but equally important.

**Comment by Sephula909** [comment]
It might also be convenient to see a solution which prevents the email's origin or metadata from being associated with the account, but I don't think email is designed that way.
