### ISSUE TITLE
Add Wire (skype alternative)

### ISSUE THREAD

**Issue by Lymdun** [nylira/prism-break#1533]
Open source crypted (end-to-end) alternative to skype. (Pc, android and ios)

**Comment by mastercoms** [comment]
https://github.com/nylira/prism-break/issues/1514

**Comment by Lymdun** [comment]
https://github.com/wireapp
What is missing ?

**Comment by Lymdun** [comment]
https://github.com/wireapp
What is missing ?

**Comment by mastercoms** [comment]
Only components of encryption and data is open source. Everything else is closed source, including the actual client. Everything is mentioned in the issue mentioner above. This is a duplicate issue.
