### ISSUE TITLE
Include cockli email hosting as email and XMPP host

### ISSUE THREAD

**Issue by zaphodbblrox** [nylira/prism-break#1536]
cock.li is a "super serious" email host run by some guy in Romania. The server that it is run on has full-disk encryption, and the host strongly suggests everyone use PGP and XMPP. The website itself is also open source (here: https://gitgud.io/vc/cock.li).
Cock.li is my email host and the email host of most of my privacy-conscious friends.

**Comment by Zegnat** [comment]
PRISM Break will not be adding any more email providers, as the list is endless, so you might want to get it included on the [Privacy-Conscious Email Services](http://prxbx.com/email/) list instead.

**Comment by Hillside502** [comment]
Infantile homophobic "Contributing" section on:-

Vincent Canfield / cock.li · GitLab
https://gitgud.io/vc/cock.li

**Comment by vcanfield** [comment]
wtf is homophobic about traps?

**Comment by aybaebae** [comment]
As a gay black trap I've experienced no prejudice or hate at all during my lengthy experiences on the aaathats3as public mumble server. I find it hard to believe that someone like Vincent """""""""""""""""""""Gex""""""""""""""""""" Canfield would write "Infantile homophobic" slander in a portion of his website. All I see is harmless, pre-millennial banter. If it triggers you to see such harmless words on a website, maybe you are the problem?

**Comment by Hillside502** [comment]
@vcanfield @aybaebae 
"trap" is part of Vincent's "License" section --- not his "Contributing" section, as I said.

I quote from the latter --- "This shit is pretty fucking gay so make sure you say "no homo" before diving in."

Not so much "pre-millennial banter", more likely Neanderthal.

**Comment by Zegnat** [comment]
If you have a problem with what @vcanfield, please take that up with him directly instead of on the PRISM Break issue list. Locking this conversation for now, as I do not think our stance on email will change any time soon.
