### ISSUE TITLE
Mailfence, a potential email provider to be included in prism break

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1538]
An email provider by the name of mailfence has been becoming popular over the last several months.They are belgium based and are strictly against NSA. A few details about them can be found here:

https://mailfence.com/

It would be great to see them in the list of privacy conscious email providers.

**Comment by Atavic** [comment]
Interesting... this service is backing both Electronic Frontier Foundation and European Digital Rights Foundation.

**Comment by Mattel88** [comment]
Not a good idea I've learned because of Metadata, right?

**Comment by hasufell** [comment]
> Not a good idea I've learned because of Metadata, right?

Well, it doesn't do much against mass surveillance, but it's better than using google as an email service provider.

**Comment by Hillside502** [comment]
> Well, it doesn't do much against mass surveillance, but it's better than using google as an email service provider.

"Well", if ever there was a sweeping, unreferenced statement!

Try:-
Mailfence has a strong and understandable Privacy Policy
https://mailfence.com/c/mailfence/more/privacy.jsp

**Comment by hasufell** [comment]
> "Well", if ever there was a sweeping, unreferenced statement!

I've written a thesis is about anonymity in E-Mail system. There is none. That's a fact. Read the SMTP protocol.

**Comment by Hillside502** [comment]
A link to your thesis?

**Comment by hasufell** [comment]
> A link to your thesis?

[Here](https://github.com/hasufell/bachelor-thesis), it's in german though, but I can translate the relevant parts for you: SMTP relies on knowledge about source and destination (see the [RFC](https://tools.ietf.org/html/rfc5321)) and the only way to anonymize it would be via SMTP extensions (as is proposed in the thesis with a very naive reference implementation) or simply an alternative protocol like [Dark Mail Transfer Protocol](https://darkmail.info/downloads/dark-internet-mail-environment-march-2015.pdf).

**Comment by Hillside502** [comment]
Dark Mail Alliance - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/Dark_Mail_Alliance

Dark Mail Technical Alliance
https://darkmail.info/

DIME, Formerly DarkMail, Promises Secure Email
http://www.tomsguide.com/us/dime-secure-email-defcon,news-19296.html

**Comment by Hillside502** [comment]
"We’ve seen various cases of highly-audited and technically sound mechanisms of secrecy that still leak information (i.e., meta-data: to, from, time, message count, account creation time, …).

This kind of information can be anonymized to a certain extent either by hiding it, replacing it or even encrypting it. Unfortunately we haven’t seen a mechanism yet that allows for complete protection against this kind of information leakage though, some interesting research projects do exists: DIME, LEAP, …."

Secure email: Why end-to-end encryption is at the heart of it - Mailfence - Secure and Private email
https://blog.mailfence.com/secure-email-and-end-to-end-encryption/

**Comment by hasufell** [comment]
They also still leak metadata and have no control over what happens with an email once it's on another mail server. Even if they use S/MIME, which is rather pointless.

**Comment by yegortimoshenko** [comment]
Relevant: #1383
