### ISSUE TITLE
Cryptocat plugin is no longer available.

### ISSUE THREAD

**Issue by azat11** [nylira/prism-break#1543]
But it's still presented on the site as a plugin, when in fact it already evolved into a standalone messenger.

Am I missing sth?

**Comment by Zegnat** [comment]
Where is Cryptocat presented as a plugin? If I look at [its project page](https://prism-break.org/en/projects/cryptocat/) it shows it is put in "Instant Messaging" for several platforms and never as "Web Browser Addons".

**Comment by azat11** [comment]
You have a point. But it seems that exactly the same page in russian still says "Encrypted instant messaging in browser".
I guess that's what I noticed.

**Comment by Zegnat** [comment]
Oh, that could be, all non-English versions of the site are by random contributors and can lag behind compared to the canonical English version. If you have the time we would appreciate a proper translation from you.

**Comment by yegortimoshenko** [comment]
Thanks for the report!
