### ISSUE TITLE
Tox VS Ring

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1545]
https://ring.cx/
https://play.google.com/store/apps/details?id=cx.ring
"Ring featured on the Free Software Foundation website" - 2016

What do you think?

**Comment by Hillside502** [comment]
Ring have made a total pig's ear of their website security.

Ring | Ring gives you a full control over your communications and an unmatched level of privacy.
https://ring.cx/

Their Qualys rating is the worst of all worlds --- F for fail

SSL Server Test: ring.cx (Powered by Qualys SSL Labs)
https://www.ssllabs.com/ssltest/analyze.html?d=ring.cx

Bodes very badly for the security of the Ring software itself!

**Comment by vyp** [comment]
@proxifier But what is the purpose of opening this issue?

**Comment by vyp** [comment]
Closing because purpose is unclear. FWIW, if anyone is interested, the same issue was opened at https://github.com/tux3/qTox/issues/3435 where the topic saw some more discussion.
