### ISSUE TITLE
Keepass2Android

### ISSUE THREAD

**Issue by temporarium** [nylira/prism-break#1548]
Looks like an improved version of KeePass for Android...

https://keepass2android.codeplex.com
https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet

**Comment by Maxqia** [comment]
Seems like the regular version is here : https://play.google.com/store/apps/details?id=keepass2android.keepass2android

**Comment by fastcopy** [comment]
There's already Keepass for Android on "F-Droid". search it.

**Comment by temporarium** [comment]
It's not about it being on F-Droid. It's about being listed on the Prism-Break page.

**Comment by alerque** [comment]
I would agree Keepass2Android is a good candidate for listing. The source is available, but sadly I don't see a build on F-Droid yet (@fastcopy the listing you see for KeePassDroid is a different project and one I would be less inclined to recommend). Perhaps after an F-Droid build is available...
