### ISSUE TITLE
is Cryptpad welcome?

### ISSUE THREAD

**Issue by ansuz** [nylira/prism-break#1553]
Hi,

I work on a project called [Cryptpad](https://beta.cryptpad.fr/), the source for which is available [here on github](https://github.com/xwiki-labs/cryptpad).

tl;dr Cryptpad is like a zero-knowledge etherpad.

I'm happy to contribute a PR to add a listing for it, but I just wanted to confirm that it would be welcome, as I'm not sure of the policy regarding people using this site to advertise their own projects.

In any case, thanks for hosting such a wonderful resource!

**Comment by elimisteve** [comment]
+1 I'd like to see Cryptpad added, too

**Comment by nylira** [comment]
Hi Ansuz, your project looks interesting and a pull request is welcome.

Thanks!

**Comment by simonasd** [comment]
> The certificate for this site expires in 2016, and the certificate chain contains a certificate signed using SHA-1.

@ansuz  Could you fix this? Like your project :+1:

**Comment by ansuz** [comment]
@simonasd I'll see what I can do :smile:

**Comment by ansuz** [comment]
[PR sent](https://github.com/nylira/prism-break/pull/1564/)

**Comment by ansuz** [comment]
@simonasd I looked into the status of the certificate, and we're planning to move to letsEncrypt some time before the current certificate expires in November.

**Comment by vyp** [comment]
Thank you! :)

**Comment by ansuz** [comment]
:smile:

**Comment by simonasd** [comment]
@ansuz GJ :+1:
