### ISSUE TITLE
Request to add Gridcoin to Finance section.

### ISSUE THREAD

**Issue by Peppernrino** [nylira/prism-break#1558]
Would anyone be for/against adding Gridcoin (GRC) to https://prism-break.org/en/all/#finance?

website: https://gridcoin.us/
source: https://github.com/gridcoin/Gridcoin-Research

> Gridcoin was the first block chain protocol that delivered a working algorithm that equally rewards and cryptographically proves solving BOINC (Berkeley Open Infrastructure for Network Computing) hosted work, which can be virtually any kind of distributed computing process (ASIC/GPU/CPU/Sensor/Etc).

**Comment by grctest** [comment]
Seconded. The cryptocurrency section really needs updated overal - there's more than just Bitcoin and Litecoin, especially for privacy concerned individuals.

**Comment by yegortimoshenko** [comment]
I don't think that we should add every altcoin to the site. This one is very specific (rewards contributing to BOINC computing grid used for medicinal research), so I don't think it belongs.

**Comment by yegortimoshenko** [comment]
Closing, because it's not a general purpose altcoin. Maybe we could add Zcash on the list?

**Comment by yegortimoshenko** [comment]
> i don't understand what you mean by "general purpose"...

Design of Gridcoin (PoW based on BOINC) makes it unlikely to be used as a general-purpose payment medium. This is just my opinion, but a more factual thing is that it seems there isn't anyone accepting Gridcoin directly, and there are no design benefits related to this list beyond what any other altcoin offers.

**Comment by Peppernrino** [comment]
it's not a proof-of-work coin. it's proof-of-research. coins are distributed at a set rate (50,000 per superblock?), and are rewarded according to how much BOINC work you have done vs other people on the same project. PoW indicates that the computations are to make more coins, like Bitcoin mining.

there are actually several stores accepting Gridcoin now, and you are able to donate to a few popular BOINC projects... the most notable of which, being SETI.
