### ISSUE TITLE
Consider removing mention of Iceweasel now

### ISSUE THREAD

**Issue by rmlrml** [nylira/prism-break#1559]
[Firefox resumes distribution in Debian](https://wiki.debian.org/Iceweasel#Firefox_resumes_distribution_in_Debian)

"Firefox is now in Debian again with the official name and branding...iceweasel is a transitional package which installs the firefox-esr package"

**Comment by haary** [comment]
Iceweasel is still alive as a package in Parabola GNU/Linux-libre, see [https://www.parabola.nu/packages/libre/i686/iceweasel/](https://www.parabola.nu/packages/libre/i686/iceweasel/). Parabola GNU/Linux-libre is a libr version of Arch Linux and listed at prism-break.

**Comment by amarildojr** [comment]
I use Parabola's Iceweasel on Arch ;)

You can compile Iceweasel for any distro.

**Comment by Atavic** [comment]
Iceweasel runs on Windows, too.

**Comment by amarildojr** [comment]
>Iceweasel runs on Windows, too.

IIRC, that's bundled with spyware.

**Comment by Atavic** [comment]
This one is clean: [Icecat](http://savannah.gnu.org/projects/gnuzilla/)

**Comment by amarildojr** [comment]
Yes, Icecat is clean. It's slow as hell, but it's clean :P

**Comment by Atavic** [comment]
Ha! The startup............

**Comment by yegortimoshenko** [comment]
I'm against removing the notice entirely because it's present on some FSF distros like Parabola, and Firefox's trademark policy is still problematic. I think it would suffice to just remove the notice that Iceweasel is for Debian-based distributions.
