### ISSUE TITLE
Actor messenger

### ISSUE THREAD

**Issue by juanda-097** [nylira/prism-break#1562]
app android: https://github.com/actorapp/actor-android-open
server: https://github.com/actorapp/actor-platform/tree/server/v1.0.153
web site: https://actor.im/

**Comment by alerque** [comment]
I'm a bit skeptical of this one. Having both client and server components being open is a good place to start, but I don't see much evidence of the encryption being up to snuff. According to [the developer docs](https://developer.actor.im/docs/protocol) only the most recent revision 3 of the over the wire protocol een started to support encrypton! Given the complexities and pitfalls involved I would like so see a security audit of some kind or at least series review by encryption folks before I recomended this for PRISM-Break.

Do you know of such reviews?

**Comment by Zegnat** [comment]
It seems to use Telegram's MTProto. But as PRISM Break doesn't recommend Telegram, I have never looked at it.

**Comment by Atavic** [comment]
MTProto v2: https://developer.actor.im/

**Comment by juanda-097** [comment]
Actor is dead
