### ISSUE TITLE
Remove CloudNS from DNS section (dead)

### ISSUE THREAD

**Issue by theltalpha** [nylira/prism-break#1563]
The TLS certificate of https://cloudns.com.au/ has expired on June 3rd, 2016, so the site and the service is not reachable any more. An e-mail sent to the administrator of the site (retrieved through the Internet Wayback Machine) hasn't brought a reply in more than two weeks. I think it is safe to consider this DNS service dead.

**Comment by vyp** [comment]
I agree. Thank you very much for notifying and attempting to get to the bottom of it!

**Comment by berrythesoftwarecodeprogrammar** [comment]
That's odd. I'm still using the service as it's been my main resolver for a while now. Didn't notice any problems. Hopefully they are just busy and will fix the site soon.

**Comment by theltalpha** [comment]
Hallo! Are you sure you are using the service? I also thought I would use the service well beyond June 3rd, but when doing the DNS spoofability test some weeks ago at https://www.grc.com/dns/dns.htm I realised I was using a backup DNS server defined in my router.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yep still works
![grc_dns_nameserver_spoofability_test_-_2016-08-20_16 52 30](https://cloud.githubusercontent.com/assets/6548571/17829582/889d35aa-66f6-11e6-9762-7234fe1fd707.png)

**Comment by theltalpha** [comment]
How can this be? The TLS certificate expired and it stopped working for me. In any case, since the website is not accessible any more, new users won't be able to use this service due to lack of information. And a service which doesn't care for its TLS certificate may not be too trustable.

**Comment by JeremyRand** [comment]
Any service that can't be bothered to update its TLS cert should be
assumed to no longer be installing security updates on the rest of its
infrastructure, unless proven otherwise.  So even if the DNS service
looks like it works, it's probably still not safe to use.

**Comment by berrythesoftwarecodeprogrammar** [comment]
true

**Comment by Atavic** [comment]
> Welcome to CloudNS!

CloudNS is an australian based security focused DNS provider.

Currently our DNS hosting and Email infrustructure is under
construction, however our public DNS resolver is now online!
