### ISSUE TITLE
Add Riot (old name was Vector)

### ISSUE THREAD

**Issue by jinformatique** [nylira/prism-break#1567]
Could someone look into Vector, it's kind of a slack alternative that support end-to-end encryption, audio and video chat in the browser. There are also android and iOS apps.
It's based on Matrix an open standard for decentralised persistent communication.
You can host the server part yourself or use the matrix one.

Maybe could be added later in the section: Instant Messaging.
It could be featured as a Telegram alternative.

Everything you need to know is described on the home page:
https://vector.im/

**Comment by Atavic** [comment]
Android version uses Google Cloud Messaging.

vector.im.alpha  has a UUID in line 10 here:
`https://github.com/vector-im/vector-android/blob/master/google-services.json`

That's Zero Privacy.

**Comment by jinformatique** [comment]
Sure then. So maybe you could report it to the team. Using cyanogenmod without gapps, I'm not affected by google cloud messaging.

**Comment by jinformatique** [comment]
That's currently the state of e2e encryption in Riot.

> End-to-end encryption is in beta and may not be reliable.
> 
> You should not yet trust it to secure data. File transfers and calls are not yet encrypted.
> Devices will not yet be able to decrypt history from before they joined the room.
> Once encryption is enabled for a room it cannot be turned off again (for now).
> Encrypted messages will not be visible on clients that do not yet implement encryption
> (e.g. Riot/iOS and Riot/Android).

**Comment by DsOIL** [comment]
@Atavic  the Fdroid version doesnt have GCM
https://f-droid.org/repository/browse/?fdfilter=riot&fdid=im.vector.alpha

**Comment by strugee** [comment]
Riot is on the site now - this issue should probably be closed
