### ISSUE TITLE
Is http://stop-prism.org linked to this project ?

### ISSUE THREAD

**Issue by Sigmun** [nylira/prism-break#1568]
I wonder if http://stop-prism.org is linked to this project ? If not, can anybody tells us if it is also trustable or if it is a fake, or worse, a pishing site ?

**Comment by vyp** [comment]
No, from <http://stop-prism.org/privacy.html>:

> This site is copied from the original Prism-break.org because the original author refused to update section of the website to include other free and secure projects

Even if the intentions are sincere, a quick look over the site seems to show it being a copy of a very old version of the site, so it should not be used/trusted anyway. Thanks for asking! :)
