### ISSUE TITLE
Google Authentictor is open source, so why listed as Proprietary? 

### ISSUE THREAD

**Issue by alexjj** [nylira/prism-break#1569]
Isn't this the source code for the [App](https://github.com/google/google-authenticator)? (and [Android](https://github.com/google/google-authenticator-android) one)?

I'm all for FreeOTP but the google one is okay?

**Comment by vyp** [comment]
It was actually because that repository says it has diverged from the play store version, so I went with the safe route of placing it under proprietary. Do you know if I'm wrong? (Not being rude, I may have actually made a mistake! :flushed:)

It was from https://github.com/nylira/prism-break/issues/1479, which suggested that authenticator could do with an alternative.
cc @quicklyandremember @1029chris who may know more.

**Comment by alexjj** [comment]
I don't know for certain. It just surprised me when I saw that as I remember looking it up when I installed Google Authenticator (although that was several years ago now).

**Comment by strugee** [comment]
The note in the README was added September 1st, 2015. I dunno how much time went by between the divergence and that note being added, but it seems pretty recent.

**Comment by vyp** [comment]
@strugee FreeOTP and Authenticator were only added to prism break in June though.

**Comment by Atavic** [comment]
DISCLAIMER: This open source project allows you to download the code that powered version 2.21 of the application. Subsequent versions contain Google-specific workflows that are not part of the project. 
See: [Google Authenticator for Android](https://github.com/google/google-authenticator/wiki)

**Comment by alerque** [comment]
As @Atavic noted while there is an old version of the code available now the Google Authenticator as you'd download it from the Play Store is a much different version these days with proprietary code. As such it is correctly listed on PRISM-Break in the proprietary section with suggested alternatives.

Thanks for raising this, but I believe this issue can be closed.

**Comment by alexjj** [comment]
Thanks everyone for helping to clarify this issue. 

I now need to look into transferring all my 2FAs!
