### ISSUE TITLE
ChatSecure is no longer being developed

### ISSUE THREAD

**Issue by RoseTheFlower** [nylira/prism-break#1572]
In the latest version of the app you get a notification right after startup that says

> **An Import Message** [sic]
> 
> Thanks for being a part of the ChatSecure Android community.
> 
> As we are no longer actively developing this app, we want to share with you other great options for secure messaging.

If you press OK, it suggests you download [Zom](https://zom.im) or buy Conversations, which is already listed here, although it's quite confusing that it's under Free Recommendations.

**Comment by JeremyRand** [comment]
This seems to be confirmed by
https://twitter.com/ChatSecure/status/780848326002429953 .

Also note The Guardian Project's reply to
https://twitter.com/5uarf/status/781173822254882816 .

> although it's quite confusing that it's under Free Recommendations.

At least some version of Conversations appears to be GPLv3:

https://github.com/siacs/Conversations/blob/master/LICENSE

It's unclear to me whether the non-gratis version in the Google Play
Store is built from that source code.

**Comment by RoseTheFlower** [comment]
I just meant that it wasn't free as in "free of charge", which is probably how most users would interpret that adjective. I know the same goes for some other things recommended here, so the issue applies to those as well.

**Comment by Dostoi** [comment]
Conversation is free of charge if you download it from f-droid

**Comment by hasufell** [comment]
> I just meant that it isn't free as in "free of charge", which is probably how most users would interpret that adjective.

No, definitely not. "free software" is _totally_ unrelated to "free of charge". The GPL text even states it [explicitly](http://www.gnu.de/documents/gpl.en.html):

> Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish) ...

Other free software licenses just don't mention that aspect, because copyright-wise the granting of rights to modify, share and redistribute is completely unrelated to the way you distribute your software.

**Comment by RoseTheFlower** [comment]
Only PRISM BREAK doesn't call it free software. It's just under "Free Recommendations", so I believe most regular users would interpret the adjective free as "free of charge".

**Comment by hasufell** [comment]
> so I believe most regular users would interpret the adjective free as "free of charge".

I guess that needs to be fixed + a note in the README added that this site is not about "gratis" software.

**Comment by PrivacyDefender** [comment]
ChatSecure only stopped developing their Android fork, however they already announced to continue their iOS fork and bringing OMEMO to iOS. http://chatsecure.org/blog/chatsecure-v323-xmpp-push/

**Comment by RoseTheFlower** [comment]
Prism Break is reasonably against the proprietary iOS.

**Comment by vyp** [comment]
By the way, re: "Free Recommendations", #809. I've always thought "free recommendations" sounded alright but now I recognise that I am probably very biased. I remember prism break used to have clarification text in the footer referring to the free as in freedom definition. If not anything else, perhaps that could be brought back at least.

(Sorry for the OT.)
