### ISSUE TITLE
Up1 Official Website link points to "Server Down" Error 521

### ISSUE THREAD

**Issue by ccastigl** [nylira/prism-break#1575]
As of the writing of this message, I was trying to check out Up1 as an app for my device for encrypted image sharing. The "Official Website" link appears to be broken. I don't know how long their host has been down.

I am aware it's not really prism-break's job to make sure other website hosts are up, as it is their responsibility. I thought though, that I would make you aware of this. I would also perhaps make a suggestion of maybe having a script that on page load, it checks the links to ensure all are live, and if site is down, maybe display a notice saying "Temporarily unavailable".

The reason I suggest this is because I believe Prism-break provides an essential service in this day and age companies like Google and such who truly couldn't care less about user privacy, and if there are broken links, it may give the appearance of Prism "not keeping up to date", or perhaps "slacking" or even used as arguments by Google-ites to put down privacy concerns. I want to clarify, I do NOT believe any of that. I'm a web dev myself and I know sometimes things go down. It's just something I wanted to make you aware of.

Thanks for your time (and patience through my diatribe!).

C

![20161002-09 58est-screenshoterror521](https://cloud.githubusercontent.com/assets/17422762/19039967/fe33e194-894f-11e6-9bb0-5fb467be1ddd.PNG)

**Comment by mastercoms** [comment]
https://github.com/Upload/Up1/issues/62

**Comment by alerque** [comment]
Auto-testing for temporarily down sites is not as good an idea as it sounds. It's fraught with potential problems including but not limited to race conditions where the site comes up but t he message stays in place, caching issues, the need for the site to run active code rather than being 100% passive, regional outages being reported as if they were global, etc. Human intervention is really required to review whether a "down" site needs to be removed, has just moved, etc. Trying to report this automatically will only create more problems than it solves.

**Comment by vyp** [comment]
I agree with @alerque on auto-testing site availability. Looks like the site has been down for a while, but because it is server software that you can host, instead of removing Up1 as a suggestion just now, I would point the website link to the github page. Website being down for now doesn't necessarily mean the software cannot still be used.

**Comment by ccastigl** [comment]
I understand the challenges involved in checking, but a client side script to merely check if the link is live doesn't seem to me to be so harrowing, but I digress. That's true what vyp says, but you know, if the site's been own for a while, I have no reason to believe that software will have a long life and I would rather move on to somthing with life in it, that is actively maintained (app and site). On the Prism-Break side, it can create an air of "non due diligence". It sends a message that link an apps aren't truly vetted and or cared to check up on to see if they continuously follow the Prism-Break standard to be a "recommended" app or not. I am not saying due diligence isn't done, it's just an appearance of such is possible. I have been disappointed in the past where multiple sites were down and I admit asking myself "aren't these checked?" 

So that's just my two cents. I do truly appreciate Prism-Break. I appreciate your contribution to user privacy and I would love to see you guys only get stronger, bigger and make a larger impact.

**Comment by JeremyRand** [comment]
Perhaps I'm misreading, but are you suggesting making visitors to the
site generate a bunch of external requests to all the sites linked to?
That sounds *really* bad for privacy.

**Comment by ccastigl** [comment]
I'm not sure that is what I am suggesting... I was just floating the idea around of some automated or semi automated way to check whether the link is down. Also, I am unsure why that would be such a terrible privacy issue... the Official Website links are generally just one link, on one page, ergo only 1 request per user would occur if the user chooses to look into a specific application. On top of that, the link is there, accessible, public and the user is already connected to the page through their IP (burden of private anonymous browsing at that point would be on the user...they would need to use a Tor browser or something).

The burden of checking could be even placed on the user directly with a reporting button or something to notify Prism-Break admins if a link is broken with some anti spamming/robot function in there to prevent abuse.

Just a few thoughts. If admins feel this topic should be closed, I have no objections :)

**Comment by JeremyRand** [comment]
Generating external requests to other hosts will reveal to a Tor exit
relay which page on Prism-Break is being looked at, because Tor Browser
performs stream isolation by URL-bar host.  If the same user views
multiple pages on Prism-Break, then that adds to the correlation that
can be done.

Obviously it's even worse if not using Tor.

Technically HTTPS fingerprinting may be able to do this anyway, but
that's a lot more expensive for an attacker.

**Comment by ccastigl** [comment]
I wasn't aware of that. That is very interesting to know. Wouldn't a Tor exit relay be able to do that anyways though if a user opens the official sites of multiple apps on multiple tabs from the app pages? (say to save on time and keep browsing prism-break and then go to each tab afterwards instead of jumping back and forth.

I see what you mean though. I guess even innocuous opening of tabs could make a user more easily identifiable even if they are trying to be more anonymous.

**Comment by JeremyRand** [comment]
If the user opens the official site for an app (whether in a new tab or
just clicking a link on Prism-Break to open the site in the same tab),
then that site's requests will be stream-isolated based on the URL bar
host for that app's site.  Meaning that each official site will get its
own Tor exit.  That would not be the case if the Prism-Break site
generates requests to those hosts.

**Comment by alerque** [comment]
> [...] but a client side script to merely check if the link is live doesn't seem to me to be so harrowing [...]

Actually that's more harrowing than what I assumed you were asking about: a periodic server side check that updates a static flag on the site.

What you're suggesting would —by necessity— leak meta data like crazy. Letting a whole bunch of sites you haven't visited yet know that you're looking at a page that links to them is just not a good idea. Furthermore there is no magic way to "secure" this kind of activity. This is how privacy compromises happen. People want convenience features and in many cases these features are very difficult or impossible to implement without compromising the user's privacy: so they get the feature in exchange for their privacy.

PRISM-Break in particular shouldn't be in the business of compromising user privacy in exchange for convenience features. Until somebody develops some public distributed system for tracking site availability that we trust not to leak user data this is simply outside the scope of consideration.

**Comment by ccastigl** [comment]
I suppose so. I'm not so sure it's as harrowing as you suggest and that meta data would be leaking like crazy, but I agree, there are concerns with any implementation of an automated way of checking if a link is working (server side or client side). There's no magic unicorn way to make it 100% locked down if automation is involved. I agree with you there.

Like I said, I was looking at it from a user's perspective of going to Prism-Break to be a go to source that appears professional and high grade, where apps are checked for how they handle user privacy and educate people about privacy. For the most part Prism-Break succeeds in doing so (which is why I love checking it regularly and suggest to everyone I know to check it out). However, if the links go to dead apps, or broken sites, that reflects poorly on Prism-Break really more than anything else. Generally speaking, broken links, poor content curation and sparse updates translates for the user into "amateur", "not-legit" and/or "not reliable" source.

I understand Prism-break isn't in the business of compromising privacy for features, and I am not saying it should. I honestly don't have a master solution to this problem. I came into this with just some brainstorming as merely a starting point to resolve a problem. I appreciate the feedback as it is enlightening. 

We are kind of just going back and forth at this point though. I appreciate the conversation though. As I said, very enlightening.
