### ISSUE TITLE
I don't recommend Riseup, here's why.

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1576]
Last month Riseup send an email to their users, yelling they can't pay next month server fee
and urge their users to pay money to continue the service. Now, almost one month passed
and I can still use it's email service, hoping they cut the service without any notice. Some user
may become fear because of this.

Take a look at their support tickets, now.
Many people writing about "I can't log in" "Account deleted" "FBI got death threat from Riseup", etc.
And admins NEVER, EVER replied to these issues.

Also, the Riseup VPN is borken for several months. I already reported it but the admin
said I am the problem, and show me the wrong sample code. (disclaimer: I'm the network engineer)

I think Riseup is FUBARed.

**Comment by jinformatique** [comment]
What do you recommend then?

**Comment by GitHubHatesTor** [comment]
There are many other options like Riseup provides, for free and no logging.
Search them YOURSELF.

---
Crisis averted!
----------------------------------------------------------

Thanks again to all the people who contributed in September in response to our urgent appeal. Your generous response was overwhelming and inspiring.

Many people grew alarmed after reading our last newsletter, and wrote us to ask how serious our situation actually is. Yes, our financial situation has been dire. It is also true that Riseup has weathered lightning strikes, melting computers, internal conflict, illness, national borders, and a car crash. We cannot confirm the alien abduction. Riseup is a quixotic project: the thing we do is persevere, against all reason.

Somehow it works, but this is not a sustainable way to operate. What would it look like if Riseup was run properly? Help tickets would be answered in a timely manner, our services would be more reliable and more secure, and you would not need a different account for each different service. Most importantly, Riseup would be more accountable and more responsive to the needs of the communities we seek to serve. Although your generous support has averted our current crisis, Riseup does not yet generate the donations or the volunteer labor needed for Riseup to thrive.

This means we are going to keep asking for your support! If you missed out, it is never too late to donate. Please visit https://riseup.net/en/donate

**Comment by GitHubHatesTor** [comment]
And I can't even unsubscribe riseup's stupid newsletter ( newsletter@lists.riseup.net ).

**Comment by rafaelrpinto** [comment]
> There are many other options like Riseup provides, for free and no logging.
Search them YOURSELF.`

@GitHubHatesTor 

You open an issue to complain about one of Prism Break's recommendations, but upon the first comment you refuse (with capital letters) to answer a very pertinent question which the answer you allegedly know. 

What exactly are you trying to accomplish here? Find buddies to hate RiseUp or actually propose a better alternative?

**Comment by yegortimoshenko** [comment]
Not actionable.
