### ISSUE TITLE
Add a list of hacklabs/hackerspaces where you can get help

### ISSUE THREAD

**Issue by fauno** [nylira/prism-break#158]
That's it.  I'm from a [hacklab on Buenos Aires](http://hackcoop.com.ar) and we're happy to help people use the software recommended on prism-break.  I'm guessing other hacklabs too, it would be good to have a section linking to them :)

**Comment by yegortimoshenko** [comment]
I don't think that would work with PRISM Break in its current form very well: it doesn't fit the "proprietary/free" paradigm, and also it seems to be off-topic.

**Comment by alerque** [comment]
I agree, this doesn't sound like a good fit for our site. There are downsides to becoming the kitchen sink.

**Comment by strugee** [comment]
Agreed. If someone disagrees speak up and I'll reopen.
