### ISSUE TITLE
Maybe add Wire?

### ISSUE THREAD

**Issue by jinformatique** [nylira/prism-break#1582]
Could **Wire** be somewhere on the list?
It's much better than Telegram because everything is end-to-end encrypted whereas with Telegram, it's only secret chat. Have a look at the comparison table on this page:
https://wire.com/privacy/

Therefore much of the code is on github, but I don't know about the server part. The registration goes through there server and there is no federation.
I hope it's still a good way to avoid mass surveillance.

**Comment by Atavic** [comment]
Seems a fine project, have you tried it yet?

**Comment by jinformatique** [comment]
Of course I have, voice quality is very clear, video is working fine. App is not crashing. I'm in the process to switch all my friends and family to it. It's been since 2012 I was waiting for a good software like this that has end-to-end encryption activated by default!

**Comment by strixaluco** [comment]
Taking into account that Wire developers don't plan¹ to publish code of the server "at a later date", I doubt this project should be listed on Prism-Break. And that's the same issue for Telegram.

¹ - https://medium.com/@teller/currently-server-is-not-open-source-a4af44ab411f#.pc3z0frzh

**Comment by strixaluco** [comment]
@jinformatique btw, have you searched the issues before opening the thread? #1533 + #1514

**Comment by jinformatique** [comment]
@strixaluco I'm sorry I did not have the reflex to search for it.

**Comment by jinformatique** [comment]
_“So, in March we launched end-to-end encryption and open source apps and crypto protocol. In 2017, our servers will be open source too, so we are fully open source and our goal is to keep meta data for maximum 72 hours.”_ said Siim Teller Head of Marketing at Wire.
[Source](http://dataethics.eu/en/view-from-wire-a-privacy-tech-start-up/)

Will see in March then if we can add Wire to the list, if it's fully open source.

**Comment by strixaluco** [comment]
Interestingly enough, there is one more mention¹ of intentions to eventually release code of the server part:

> I like so much about Wire, but the lack of full source code to the server is a pretty big potential problem.
> 
> So, I sent a message to the CTO of Wire, Alan Duric, asking why the server was closed. He immediately got back to me to let me know that releasing the source code for the server was underway. When I pushed for specifics, I got the following response:
> 
> “License will be the same GPLv3 and timeline is next year.”

¹ — http://www.networkworld.com/article/3140014/open-source-tools/down-the-rabbit-hole-part-5-secure-and-private-instant-messaging.html

**Comment by strugee** [comment]
So this was just mentioned in #1672.

Wire still isn't going to make it into the list because, at least AFAICT, the server still isn't open source. Also it's not on F-Droid (wireapp/wire-android#233) and it seems its end to end encryption experience is really bad: https://medium.com/@pepelephew/a-look-at-how-private-messengers-handle-key-changes-5fd4334b809a

It's possible it's gotten better since that article was written, but it wasn't that long ago so I doubt it.

**Comment by jinformatique** [comment]
@strugee Thanks to you I discovered Tina Membe posts and I'm shocked about what I read on Wire encryption. But let's wait some months and see if the server source code will be released during 2017.

**Comment by strugee** [comment]
Sure, if a project improves we'll always reconsider them for PRISM Break. But I doubt Wire will improve significantly enough to make it onto the site.

**Comment by teller** [comment]
Hi, Wire server will be open soured by end of Q1 this year.

Independent security review was published earlier this week: https://medium.com/wire-news/wires-independent-security-review-61f37a1762a8#.q1jyk5pbl

As to Tina Membe (@strugee @jinformatique ) - anonymous troll who's identity is unknown and who's sole online purpose seems to be to attack Wire and spread alternative facts. We published a response to that article here: https://medium.com/wire-news/making-your-conversations-secure-dab207ab77fd#.39jgy6noq

**Comment by strixaluco** [comment]
Okay, so now the process of opening the sources of server part has started indeed¹:

> Open sourcing the server code has been a great exercise and a challenge to clean up the code and remove some legacy components from pre-March 2016 when we launched end-to-end encryption. We are ready to release the first backend components and will release all server code parts over the coming months as we finish the cleanup and documentation.
> 
> Wire server code: https://github.com/wireapp/wire-server
> 
> The source code of the server components is licensed under AGPL and can be used according to those terms unless otherwise specified for third-party components.

And the plan is to enable federation as well:

> In the longer term future there will be a self-hosted version of Wire that optionally federates with the main Wire cloud.

¹ — https://medium.com/@wireapp/open-sourcing-wire-server-code-ef7866a731d5

**Comment by jomahoney** [comment]
Their open-sourcing of the server code has revealed some worrying features. Most [notably](https://motherboard.vice.com/en_us/article/gvzw5x/secure-messaging-app-wire-stores-everyone-youve-ever-contacted-in-plain-text) there's the plain text sharing of every contact made as can be seen in this [file](https://github.com/wireapp/wire-server/blob/develop/services/galley/schema/src/V20.hs) which is still to be updated. 

I'd move that Wire not be considered until there's changes. Also worrying is that the [independent audit](https://www.x41-dsec.de/reports/Kudelski-X41-Wire-Report-phase1-20170208.pdf) did not flag this.

**Comment by strixaluco** [comment]
This contacts plain-text sharing is pretty creepy. But to be perfectly precise, independent audit¹ inspected only e2e encryption protocol implementation:
> This security assessment focused on Wire’s core cryptographic components: the Proteus
> protocol, and the Cryptobox API built over Proteus.

So Kudelski security and X41 are not to be blamed for this particular case, I assume.

¹ — https://www.x41-dsec.de/reports/Kudelski-X41-Wire-Report-phase1-20170208.pdf

**Comment by DestinFaroda** [comment]
Looks like Wire is now 100% Open Source:
https://medium.com/@wireapp/wire-server-code-now-100-open-source-the-journey-continues-88e24164309c
Next step: self-hostable server

**Comment by Sigmun** [comment]
Is there anything new on this ? I have to find a good candidate for texting between iOS and Android phones in my family. I usually go with Signal but this one seem better WRT prism-break recommendations.

**Comment by teller** [comment]
@Sigmun What update are you looking for? All code is now 100% open source in case you missed that.

There's another security audit coming up that focused on the application level for iOS, Android, webapp. Hopefully gets published next week already.

**Comment by Sigmun** [comment]
@teller In fact, I read this opening source of the server code. But it's still not approved here. So I was wondering if there is any chance to see its status changed on prism-break.org

**Comment by Hillside502** [comment]
Any thoughts @hasufell now that Wire is consolidated here?

**Comment by DestinFaroda** [comment]
Results of the second audit:
https://medium.com/@wireapp/wire-application-level-security-audits-98324d1f211b?source=user_profile---------1----------------

By the way, Wire made first place on https://secured.fyi/communication.html

**Comment by Hillside502** [comment]
Secure Messaging App Wire Stores Everyone You've Ever Contacted in Plain Text - Motherboard
https://motherboard.vice.com/en_us/article/gvzw5x/secure-messaging-app-wire-stores-everyone-youve-ever-contacted-in-plain-text

**Comment by teller** [comment]
@Hillside502 And a response to that story with background on how every messenger needs to find a balance on the security - privacy - UX triangle: https://medium.com/@wireapp/product-design-decisions-for-secure-messengers-e8a5e7d1a373

**Comment by Sigmun** [comment]
So what is the position of prism-break on this app ? I prefer their user interface more than Riot, but I am not sure I can encouraged my family/friend using it.

**Comment by yegortimoshenko** [comment]
Requires proprietary infrastructure to host, similar to https://github.com/nylira/prism-break/issues/1571.

See https://github.com/wireapp/wire-server#how-to-run-wire-server:

> As a brief overview, it requires setting up
>
>* database clusters (cassandra, redis, elasticsearch)
>* external dependencies
>    * Amazon account with access to
>      * SES
>      * SQS
>      * SNS
>      * S3
>      * Cloudfront
>      * DynamoDB
>    * Nexmo/Twilio accounts (if you want to send out SMSes)
>    * Giphy/Google/Spotify/Soundcloud API keys (if you want to support previews by proxying these services)
>    * TURN servers (if you want to support Voice/Video calls)
>* production-ready configuration for all services
>* additional infrastructure configuration (DNS, SSL certificates, metrics, logging, etc)

**Comment by Hillside502** [comment]
I thought this issue was about whether to recommend the Wire-hosted service.

Do the requirements for self-hosting indicate that parts of Wire hosted are still a black box?

**Comment by Atavic** [comment]
Setting up a Wire host requires something like an Amazon account: in late 2010 Amazon pulled the plug on hosting the WikiLeaks website in reaction to heavy political pressure. The signs of an Amazon/NSA partnerships are many, like earlier this year, when Amazon acquired Sqrrl, a security start-up with NSA roots.

**Comment by Hillside502** [comment]
Sqrrl - Wikipedia
https://en.wikipedia.org/wiki/Sqrrl

Sqrrl
https://sqrrl.com/

**Comment by DestinFaroda** [comment]
That lost of proprietary crap looks horrible. However, I remember they stated that they want to get rid of dependencies as much as possible. Well, let's see.
There's also the issue that only business users get all the standard features while people not paying have to live without online status, basic group administration, invitation of non-users etc.
Maybe Tox or Ring will become better.
