### ISSUE TITLE
GNU IceCat & K-Meleon Web Browsers?

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1583]
Web Browsers - Free Recommendations:

[GNUzilla and IceCat](https://www.gnu.org/software/gnuzilla/)
While Firefox from the Mozilla project recommends non-free software as plug-ins and addons, GNU Icecat is entirely free software with privacy protection features, as:
    _LibreJS
    Https-Everywhere
    SpyBlock
    AboutIceCat
    Fingerprinting countermeasures_

[K-Meleon - The Browser You Control](http://kmeleonbrowser.org/)
K-Meleon is a web browser based on the Gecko layout engine.
Free, Open Source software released under the GNU General Public License and is designed specifically for Microsoft Windows (Win32) operating systems.

**Comment by theltalpha** [comment]
Unfortunately, IceCat is effectively dead.

**Comment by vyp** [comment]
I am still using IceCat actually but I think for prism break it just does not see enough activity to even consider it. For example http://lists.gnu.org/archive/html/bug-gnuzilla/2016-08/msg00000.html. Also see #1310 for more about IceCat.

**Comment by hasufell** [comment]
> K-Meleon - The Browser You Control

I've used that one something like 10 years ago, but I don't see how it improves your _privacy_. Prism-break is not a list of just free software.

Also, the last release was a year ago, which is pretty bad for a browser, because the attack surface is huge.

**Comment by alerque** [comment]
I agree with the comments so far. The browsers @Atavic suggested are free and open source and people with special requirements are welcome to check them out, but neither of them is under active enough development to be a safe secure choice and the the latter in particular doesn't really do anything special for privacy. Neither are things PRISM-Break should be suggesting for general consumption or as a way to stay out of mass surveillance dragnets. This issue should be closed until there is some change in the status of the projects.

**Comment by vyp** [comment]
Closing due to previous comments.
