### ISSUE TITLE
İ need two riseup invite codes.

### ISSUE THREAD

**Issue by hknhpcn** [nylira/prism-break#1595]
İ am from Turkey. İ see prism break platform. And i need a vpn(safe) program because the internet most of the time are banned here. (communication sites and news sites etc.) News about events, so we couldn't get.  But i don't have riseup intive codes.  Can you help me? I don't know what to do about it. I wrote it here. Sorry I don't know too much English.

**Comment by nylira** [comment]
Hi, this is not the place to ask for riseup invites. This is only for issues with the PRISM Break site. Try looking at privacy discussion boards on sites like Reddit.

**Comment by GitHubHatesTor** [comment]
@hknhpcn

Go here: https://user.riseup.net/
Make a "help ticket", and write "I need an invitation code because I want to use(write your messages!!)".

Then, someone will assist you.
I recently got an account because of him. Try it and pray to the god.
