### ISSUE TITLE
Adguard? (ad plugin)

### ISSUE THREAD

**Issue by kekelemek** [nylira/prism-break#1596]

**Comment by alerque** [comment]
What would be the advantage over *uBlock Origin* or *Adblock Edge* which we already recommend? Remember we're not trying to be a directory of all available software here, we're trying to pick the best couple of alternatives in some categories from a privacy/security point of view. What does *Adguard* bring to the table that is an improvement  over our current suggestions?

**Comment by Zegnat** [comment]
I am not really seeing anything to set the [Adguard browser extension](https://adguard.com/en/adguard-adblock-browser-extension/overview.html) apart from other adblockers either. They claim it "uses half as much memory as other popular solutions: Adblock, Adblock Plus", but the extensions currently recommended by PRISM Break already have smaller memory footprints.

If you are talking about the desktop network filtering software they produce, it is specifically not open-source. Neither is the Android application.

**Comment by Atavic** [comment]
> it uses half as much memory as other popular solutions

This [test](https://www.raymond.cc/blog/10-ad-blocking-extensions-tested-for-best-performance/3/) proves it is false. Also, it's a "_Freemium_" addon.

**Comment by strugee** [comment]
I still don't see any compelling reason to list Adguard. Objections to closing?
