### ISSUE TITLE
Replace "free software" with "freedom-respecting software"

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1601]
Inspired by https://github.com/nylira/prism-break/issues/1572#issuecomment-259381219.

I could write a whole long issue description explaining why I think this is a good idea, or you could just to read [the blog post][1] I wrote on the very same thing.

 [1]: https://strugee.net/blog/2016/11/free-software-phrasing-considered-harmful

**Comment by hasufell** [comment]
:-1: 

`freedom-respecting software` is not an established term and may or may not yield the same search results as `free software`, depending on your search engine. Instead of rephrasing well-established terms, we should instead educate people about it.

And: this isn't a decision that should be discussed at prism-break, but at FSF etc. Otherwise WE are just increasing confusion.

**Comment by alerque** [comment]
I agree with @hasufell here; @strugee your proposal actually sounds like a good one to me but there is a train to divert upstream before considering changing the usage here. I'd be all for PRISM-Break being an early adopter if there was any noise at FSF about this being an endorsed alternative, but I don't think we should be pilot project for something with no traction at all behind it yet.

**Comment by strugee** [comment]
@hasufell did you read my blog post? Re: search results, "free software" is not a sufficiently unique term to actually yield really great search results in the first place, although I admit that I did just search "free software" on DDG, Google, Yahoo! and Bing and was _very_ surprised at the results, which were pretty good for us. And I'd seriously question our ability to educate people about such an ambiguous term. (I'd also point out that one could make the argument that the movement belongs to the people, not the FSF, and therefore any change in nomenclature will happen regardless of whether they approve, just like language evolves without the approval of governments, dictionaries or any other authority.)

That all being said, you both have an excellent point that it's smart to talk to the FSF first. So I'm fine with closing and punting this to them :P

Thanks for the feedback.
