### ISSUE TITLE
Turtl: A secure, encrypted Evernote alternative

### ISSUE THREAD

**Issue by core01** [nylira/prism-break#1602]
Turtl lets you take notes, bookmark websites, and store documents for sensitive projects. From sharing passwords with your coworkers to tracking research on an article you're writing, Turtl keeps it all safe from everyone but you and those you share with. 

Source code: [github](https://github.com/turtl)
Website: [turtlapp](https://turtlapp.com/)

Do you know about this app?

**Comment by alerque** [comment]
No, I've never heard of it until now. As long as we're looking into Evernote alternatives, I just heard of [paperwork](http://paperwork.rocks/) yesterday that seems to fill a similar gap. See #1603 for discussion on that.

**Comment by laprasx** [comment]
I just tried the Turtl application. I liked it. I hope this is a safe application.

**Comment by laprasx** [comment]
Privacytools.io suggested the Turtl app.

**Comment by hasufell** [comment]
> Source code: github

This is the relevant part, the server: https://github.com/turtl/api

**Comment by yasyasya** [comment]
Any progress? Would you recommend this app?
