### ISSUE TITLE
Kali linux to live os?

### ISSUE THREAD

**Issue by szymon1051** [nylira/prism-break#1607]
Kali linux to live os?
https://www.kali.org/

**Comment by strugee** [comment]
Kali is focused on penetration testing, not privacy. I don't see how this would be a useful inclusion.

**Comment by fedor1113** [comment]
What is important to note (as well) is that it is certainly not for inexperienced users (e.g. the default user is root, which is not good if you are not a security professional). So its usage is dangerous without understanding of what you are doing. It is not intended for an average user in any way. Also don't see how it can be included at all - it might be good for penetration testing, but that is not the point here.

**Comment by hasufell** [comment]
> Kali is focused on penetration testing, not privacy.

You can't be serious. Those things are very closely related. Privacy is a subset of security and depends on overall security.

**Comment by hasufell** [comment]
> Kali is focused on penetration testing, not privacy. I don't see how this would be a useful inclusion.

I first misread this, so let's make this clear: it's a distro providing tools for penetration testing, not doing penetration tests on their own distro (which would be extremely useful), afaiu.

**Comment by vyp** [comment]
Agreed with the above comments. Closing due to lack of response but feel free to still comment here if you still think Kali should be listed!

**Comment by strugee** [comment]
@hasufell yes, that's what I meant. Thanks for clarifying and sorry for the ambiguous language :)
