### ISSUE TITLE
I need Riseup invitation code! - The Answer

### ISSUE THREAD

**Issue by GitHubHatesTor** [nylira/prism-break#1615]
If you need Riseup.net invitation code, and you don't have ANY friends who use Riseup nearby,
I suggest you follow this steps(because it works!);

1. Go here: https://user.riseup.net/
2. Make a "help ticket", and write "I need an invitation code because I want to use(write your messages!!)".
^ Don't copy & paste my sentence! Use your words!

3. Then, someone(Riseup user) will assist you.
I recently got an account because of him.

Try it and pray to the god.

**Comment by GitHubHatesTor** [comment]
@nylira This is not a lie. I created my account using the code he given me a long time ago.
You could add a link to prism-break.org, Riseup section.

**Comment by GitHubHatesTor** [comment]
Hint(from the conversation with him):
He will not help you if you:
1. can't answer to his question correctly(basic English skill required)
2. already have or had a riseup account
3. are using fake, temporary or verification-free email(which spammers always use)
4. are not a polite person.

**Comment by alerque** [comment]
As was noted on #1595, this issue tracker is not the place to deal with user support issues for specific products. We don't tell people much about _how_ to use sites. At this point it's looking more and more likely we're going to stop even recommending Riseup. Even if we continue to list it, dealing with invite codes is outside the scope of PRISM-Break. Please stop spamming this issue tracker with things about this topic.

**Comment by GitHubHatesTor** [comment]
> At this point it's looking more and more likely we're going to stop even recommending Riseup
Which issue number is talking about this? I'm interested.

**Comment by vyp** [comment]
@GitHubHatesTor #1613

**Comment by kt000** [comment]
hi

**Comment by kt000** [comment]
hi

**Comment by strugee** [comment]
@kt000 hi and welcome to PRISM Break! We'd love to have you contribute but when you comment irrelevant things like "hi" it generates a lot of email for a lot of people. If you could refrain from doing that in the future, that'd be great :)

**Comment by kt000** [comment]
i need it i want you to generates and send the Riseup invitation code

 


Dr Keith Harper


Sent: Saturday, September 09, 2017 at 12:14 AM

**Comment by rahoolnikam** [comment]
Can anyone helpme with a riseup.net invitation? Desperately required.
Unable to find a friend with a rise up account. Please help.
I can share any information if, someone requires it.

**Comment by alerque** [comment]
@rahoolnikam Try searching Twitter. This issue tracker is not the place for this kind of request.

Can I suggest somebody with Collaborator permissions lock this issue? It seems it keeps coming up and people can't be bothered to read what's been said already or respect the nature of the venue.
