### ISSUE TITLE
privacy badger, disconnect and or tracker block adds about

### ISSUE THREAD

**Issue by laprasx** [nylira/prism-break#1618]
Which provides stronger privacy? Which do you recommend to me? Please do not disrupt the site structure.
 I use privacy badger. But I think ublock overlaps with origin

**Comment by laprasx** [comment]
But I think ublock origin overlaps with pd *

**Comment by alerque** [comment]
@laprasx Please just use the edit button at the top right of your post to fix your question. I can barely make out what you are asking.

Also this is a not a user support forum. It is an issue tracker where we discuss what to list on the site. The things currently listed on PRISM-Break are the products we recommend you consider user. Each section also has a comments section with some of our observations about what products are better for what purposes.

Obviously there is overlap between some of these, but they also have different purposes. The ad-blockers are just for ads, privacy badger covers more categories but is also more lenient, etc. You should review their respective sites and what they do and decide which most aligns with what you are trying to accomplish.

**Comment by vyp** [comment]
As @alerque pointed out by linking to the Privacy Badger FAQ, you can use both if you'd like.
