### ISSUE TITLE
Improve Qubes description

### ISSUE THREAD

**Issue by ShalokShalom** [nylira/prism-break#1620]
https://www.qubes-os.org/doc/templates/

Add this to the description of Qubes - maybe including the hint of the community maintained Templates?

**Comment by strugee** [comment]
I'm assuming the benefit here is using Debian tools with Qubes?

I get the idea but generally I'm a little skeptical... we can't go adding links to every project's documentation. And the OS section notes is crowded enough as it is.

**Comment by ShalokShalom** [comment]
? You write on the Qubes page of prism-break, that Fedora is the only one Distribution to use it.

**Comment by hasufell** [comment]
I think the `Fedora` part should just be removed instead of adding more.

**Comment by strugee** [comment]
I'm with @hasufell. That way we keep the OS section small(er).

**Comment by alerque** [comment]
Also agreed, what the default template is is not important to the listing at all. The description should be re-written to sidestep this issue and perhaps be slightly more useful in the process. For example we could clarify to readers not already versed in layers of virtual computing whether Qubes is something they would load on bare metal or itself something than runs inside another host (even the upstream projects documentation isn't nearly clear enough on this point).

**Comment by ShalokShalom** [comment]
It might be senseful to point out, that Qubes is something for advanced users and use more resources as other alternatives?

**Comment by strugee** [comment]
Seems like we've come to a consensus that the best course of action is to rewrite the Qubes description and not specifically mention Debian/Fedora. Changed the title and marking as accepting PRs to reflect that.

**Comment by strugee** [comment]
@ShalokShalom is there a reason you closed this issue?

**Comment by ShalokShalom** [comment]
Because your statement seems to mean, that this is solved?

**Comment by alerque** [comment]
@ShalokShalom That's not how I read it. We seem to have settled on what the course of action _should be_ but nobody has actually done it yet, so until a PR is submitted and accepted this issue should remain open to track the fact that there is an open item that needs addressing. It doesn't need more discussion but it does still need doing.
