### ISSUE TITLE
LessPass better than encrypted vault when you can choose your password

### ISSUE THREAD

**Issue by GammaNu** [nylira/prism-break#1623]
https://prism-break.org/fr/all/#password-managers

https://lesspass.com/
https://github.com/lesspass/lesspass/

**Comment by alerque** [comment]
Nope. Sorry, but deterministic password managers have several major drawbacks that actually open you up to more security issues than a traditional vault system. For a recent run down of the major drawbacks see Tony Archieri's writeup [4 Fatal Flaws in Deterministic Password Manages](https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers).

Arguably such systems are better that not having a scheme at all and forcing users to memorize all passwords and thus likely use less secure ones. However encrypted vault systems offer more in the long run that we should probably encourage over the initial convenience of not having to sync. I don't think we should be recommending any deterministic password managers.

**Comment by yegortimoshenko** [comment]
Closing based on consesus (@alerque, @strugee, me).
