### ISSUE TITLE
opennic dns about

### ISSUE THREAD

**Issue by laprasx** [nylira/prism-break#1630]
Do you recommend Opennic Dns? Android Dns category includes Opennic Dns. But not in the whole Dns category

**Comment by Atavic** [comment]
Just try! It's far more honest than _Opendns_ which is owned by Cisco, but due to extreme advertising is still trusted. I miss the service from _Chaos Computer Club_ and here suggest even _Yandex_ as DNS provider.

**Comment by strugee** [comment]
@Atavic "just try" is not a particularly good way to advocate for something to be included in PRISM Break.

As for the other things, if you have concerns unrelated to OpenNIC, please open separate issues.

I also don't see the original issue. See https://prism-break.org/en/subcategories/gnu-linux-dns/ - can we close?

**Comment by Atavic** [comment]
Well, opennic is an open project and did really work good when I used it. It even includes its own TLD option. For a complete opinion, I must say that some countries aren't covered as good as Germany. So, satisfaction differs from where someone is located.

**Comment by Hillside502** [comment]
@Atavic 
OpenNIC appears under all platforms except Servers

Servers - Platforms - PRISM Break
https://prism-break.org/en/categories/servers/#dns

DNS - All Projects - PRISM Break
https://prism-break.org/en/all/#dns

**Comment by vyp** [comment]
I'm not sure, can OpenNIC be used in a server? What about https://wiki.opennic.org/opennic:srvzone?

**Comment by Atavic** [comment]
Users of OpenNIC DNS servers can resolve host names in the OpenNIC operated namespaces. OpenNIC own TLDs are .geek, .free, .bbs, .parody, .oss, .indy, .fur, .ing, .micro, .dyn and .gopher

**Comment by vyp** [comment]
@Atavic I see. But should OpenNIC be added to Servers platform?

**Comment by JonahAragon** [comment]
[Anybody can run an OpenNIC server](https://wiki.opennic.org/opennic/tier2setup), and you can certainly use OpenNIC servers in your `resolv.conf` configuration on a server. I don't see why it isn't or wouldn't be added to the Servers platform.

**Comment by yegortimoshenko** [comment]
OpenNIC is currently listed.
