### ISSUE TITLE
Amaza,vlc apps about

### ISSUE THREAD

**Issue by laprasx** [nylira/prism-break#1631]
Amaze (Manage local files) - https://f-droid.org/app/com.amaze.filemanager
VLC (Media player) - https://f-droid.org/app/org.videolan.vlc

What do you think about these applications? Are they safe?

**Comment by hasufell** [comment]
I don't particularly see how these apps are relevant for prism-break.

**Comment by strugee** [comment]
Agreed. As long as they're from F-Droid, I don't particularly see a reason to look closely at these. Browsing your local filesystem really has nothing to do with the kind of mass surveillance PRISM Break aims to change... they're completely orthogonal.

**Comment by hasufell** [comment]
> they're completely orthogonal

Unless the file-manager allows ftp/webdav/... connections as well (my desktop filemanager does). But it's arguable whether that justifies its own section. Also, the proposed filemanager seems to focus on _local_ files anyway.

**Comment by strugee** [comment]
Good point, though I don't see a reason to keep this open further. Any objections to closing?
