### ISSUE TITLE
Travis CI builds aren't running

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1637]
There's a `.travis.yml` file in the repo, but Travis doesn't seem to be set up to test incoming PRs.

**Comment by alerque** [comment]
If my `Makefile` makeover is accepted (#1639) I will have a look at the Travis config and make sure it's doing something useful. Additionally it would be relatively simple to set it up to actually _deploy_ the rebuilt static site to the right repo on success if that's something we'd be interested in. That should shorten the lag quite a bit between contributions and published site (as well as making slipups such as seen in #1638 much less likely).

**Comment by strugee** [comment]
@alerque to clarify, Travis right now runs `make test`. The real problem is that AFAICT it's not set up to integrate with this repository, so it's not run when people e.g. send pull requests.

I think @vyp can fix this, but it might be that @nylira needs to.

**Comment by alerque** [comment]
@strugee I get the picture. I've been in the trenches with Travis before.

Yes we'll need one of the repository owners to turn on the lights, but I can run it on my own fork first to work out the kinks. Running `make test` in the state is it is right now is a first step, but doesn't go far enough to be really useful. At this point that target tests the tooling more than it does the data and most PR's here are data updates. That's not a real CI run. I have some ideas but am going to wait on my current Makefile PR to go through first.

**Comment by vyp** [comment]
@strugee Sorry no I cannot.

**Comment by strugee** [comment]
@alerque ah, OK. I thought you might have interpreted the title as "`.Travis.yml` is borked"

@vyp np. I'm unsurprised. @nylira?

**Comment by strugee** [comment]
Just emailed @nylira about this :)

**Comment by strugee** [comment]
Fixed :tada:
