### ISSUE TITLE
Confidant Mail

### ISSUE THREAD

**Issue by Hxs2fJKjYZ** [nylira/prism-break#1642]
A possible inclusion of Confidant Mail on prism-break.
https://www.confidantmail.org/

Server and client packages available.

Description:
Confidant Mail is an open-source non-SMTP cryptographic email system optimized for large file attachments. It is a secure and spam-resistant alternative to regular email and online file drop services. It uses GNU Privacy Guard (GPG) for content encryption and authentication, and TLS 1.2 with ephemeral keys for transport encryption.

Confidant Mail is the easiest way to use PGP encryption. You can download and install the software and start using it in a few minutes. The only information you have to know and type in is your name, email address, and a password. No complex setup is required. Your public key will be created automatically.

**Comment by hasufell** [comment]
This appears to be a custom protocol https://www.confidantmail.org/download/spec.pdf

Without further investigation, I'd take this very cautiously.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I realize that there are other email alternatives recommended by
PRISM-Break that are no better on this point (e.g. Bitmessage), but I
would be very cautious about recommending anything that uses PGP, due
to the lack of forward secrecy and deniability.

(Queue the irony due to this message being PGP-signed.)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYWUK+AAoJELPy0WV4bWVwYsMQANfhqhSxVgCBgq7XfX0Hk/M4
W4kw6ZSD9LB6XBBJgep6Wvi5ZUeg1P9lf/nI7AV+3fKtp0YOWduQmLLQMge6szbR
QS7FMrFUfaWHiUiTMky+5z2/dBwVv4gzAKNFvVXJLZke7oI0Zq5ixGUKKVdAEuX8
EpjKonJ1bR4YPg9y93n2Upqa/0XmjH6+dXfGWzGJW92KPVuMNBT0axkf9AbW6KcL
nYoTY6DaA41Bt1YNp6MdgxmHvqEcY9FH6PhGfH6HvR1qIvzYnrnarT9eXFnQNbc5
WeepDMd+RqBGvhgXM9uBDsc+C7AUjMUdOZBRcBz7UJ3+J2JTOiJKC9CF673twR5y
n8IEL1ieBinzbcA4JUGLH2+YDgSCQhVK6me/JyfpgMsuPX1vUAOkS2tlwOKhK0nD
FCAw7DCjp7m9amC3qzn22C5pU/Qvb6J9f6EPB+y+i4+sMvNGGYmdXqoAp/Cx8m5j
fFUWw1Ez+WQ35i+nOgXpcQWL61CjaSr2lCFaIPTibDq66T+9oO2paH7nKiJSrw0t
Gp7rp0PBl5V7bEa0CpWFt9l+jCjRUhjylpLFqzKZIrMkr3+f6syoRiYGsVQgS/ER
aOPhG6LA5h4is2DCyAm7sF2/HG8KCN1xXMeLkPwS9ydRB4hftkDfUpgTrCLOaKdI
7wWRkhzUTUI1/eu8Zn1S
=VxYQ
-----END PGP SIGNATURE-----

**Comment by Hxs2fJKjYZ** [comment]
As per description above: "and TLS 1.2 with ephemeral keys for transport encryption"

And documentation as follows: https://www.confidantmail.org/docs/forward_secrecy.html
"You can change your encryption subkey once a week, with little risk of receiving mail you cannot decrypt. Your conversation partners will automatically refetch your key. It requires two key changes to permanently destroy an old key; the first one revokes the key, and the second deletes it. This means the minimum exposure is roughly the last two weeks - much better than "forever" if you don't rotate your key."

I believe this is more than what Kontalk offers for example: https://prism-break.org/en/projects/kontalk/
which is also based on openGPG and has no way to rotate the keys, and is tied to your phone number.

Maybe a little time to read through the documentation is needed?
I hope it can be further investigated before it is dismissed :-)

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hxs2fJKjYZ:
> As per description above: "and TLS 1.2 with ephemeral keys for
> transport encryption"

TLS is a transport security protocol; it accomplishes nothing
whatsoever in mitigating the undeniability of PGP.  TLS is probably
helpful for forward secrecy, but standard SMTP-based email supports
TLS anyway.  Unless they're doing something very different with TLS
than SMTP uses it for, I don't see how this is an improvement.

> And documentation as follows:
> https://www.confidantmail.org/docs/forward_secrecy.html "You can
> change your encryption subkey once a week, with little risk of
> receiving mail you cannot decrypt. Your conversation partners will
> automatically refetch your key. It requires two key changes to
> permanently destroy an old key; the first one revokes the key, and
> the second deletes it. This means the minimum exposure is roughly
> the last two weeks - much better than "forever" if you don't rotate
> your key."

If it handles key rotation automatically, then that is a significant
improvement over standard email implementations of PGP.  However, I
suspect that Axolotl-based systems (of which the best-known is Signal)
are much better in this aspect.  Granted, I'm not an expert on Axolotl.

Signal does have its own problems, e.g. a dependency on Google Play
Services, but there are other systems based on Axolotl that don't have
this issue.  For example, the OMEMO-based XMPP systems.

> I believe this is more than what Kontalk offers for example:
> https://prism-break.org/en/projects/kontalk/ which is also based on
> openGPG and has no way to rotate the keys, and is tied to your
> phone number.
> 
> Maybe a little time to read through the documentation is needed? I
> hope it can be further investigated before it is dismissed :-)

I don't think anyone here dismissed it; we simply expressed a desire
to be very cautious.  :)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYWdF+AAoJELPy0WV4bWVwFa8QAMFbC2JJAjyRpHqCO0b5caJe
mncQCFfsBKqv20QNZl2HHdm0bJBOYra+lH47IjzAcUOQxv4LOoHHtV5gZv/miyZS
zsPoqosm7rFXe/KT30oT1+EXjr35vnRFxL8t2nEldtgyfgRg66TQAjkNw89gHiH6
xk0pI6tMKYHXYJXDP2gllpn0CZdENzPhyDnacwx3dbVsS0ZrQZWxrndxIn2it01J
ZqWnr94itlQdXteV/PRR1pfLLM4CnlalohYTfFcOBMwx+77ci8dB/TUodXqwVR1w
YRUQlBRPJNoJTdFMwiO1dCAlRVDPa3kaE/PjFiJUuwA1i/4WkVnvAe0jufnZztcL
lqv1MbYU8WAsbpeXBacAXfkir5NqJw93Ry5AidEJj3t8/XZBtI4yCBYuVXJVvOUL
6afZk1jgG44+NykpRd92qC8/MP3tRq8f8CGWkcN8yAMsUHgU/AsCusRYJ9ZcCXV6
t9TGmV7I03RMZr0bdIWdwfUCfUKU+L1PmJ4ArBKxhy6MsFOp4Aro0n4h0KVIATv8
P6oZts8HCuPoxqycVviTse7hFQpFUP16xOtwZfT+VzFSoiqwcYdcKTh+BCaapYKc
3wudscWH3DiZ/nqfDZ9edqJmD5DsHPVqxTKwYqnK7kzdqOsWFHLd8xvoRd+pGMna
0unG1sQ6oknNycAXeYVd
=dCS2
-----END PGP SIGNATURE-----

**Comment by Hxs2fJKjYZ** [comment]
Of course, I totally understand your points above, but what is the threat model that Prism-break is aiming at, is it the ultra paranoid, or people wanting to avoid passive surveillance?

"I don't think anyone here dismissed it"
I'm happy to hear that, all I ask is for it to be be investigated further and considered as a viable alternative ;-)

I appreciate your feedback.

On another note, I noticed that Gajim now has an OMEMO (Axolotl) plugin making it compatible with conversations mobile chat app.

**Comment by hasufell** [comment]
> but standard SMTP-based email supports
> TLS anyway

Not consistently across MTAs. An MTA may choose to relay any mail unencrypted and an MTA may freely decide how to proceed in case of a TLS handshake failure (as in: just proceed unencrypted) ...and this perfectly in line with the SMTP specification.

I currently don't have the time to look at the (badly formatted) spec in-depth. Probably next year.

**Comment by mike805** [comment]
I am the author of Confidant Mail. CM handles forward secrecy better than other asynchronous protocols like regular email. With a synchronous (both key holders online at once) protocol, you can of course re-key after every exchange. CM does not make that assumption. You can rotate your key every couple of weeks, other users automatically re-fetch your key, and the client removes the "tail" of expired encryption subkeys so the key block does not grow forever.

Unlike regular email, the from/to/subject is all inside the envelope. As admin I don't know who is talking with whom. You can run your own servers or use mine.

CM lets you email someone a file larger than 4GB with no special effort, and resumes a partial transfer automatically.

The protocol is pretty simple: headers, message, and attachments go in a zip file, zip is signed and encrypted,  broken into 8MB blocks and uploaded. Keys are looked up by the key id or hashed email address in a DHT. Clients post their own keys and refetch others' keys at regular intervals. There are two servers in a cluster to prevent downtime.

The user interface looks a bit like Mozilla Thunderbird. There is detailed documentation and a screen shot walkthrough on the website.

https://www.confidantmail.org
