### ISSUE TITLE
SEDutil for disk encrytpion

### ISSUE THREAD

**Issue by ZJaume** [nylira/prism-break#1645]
Software to manage self-encrypting drives, it is under GPLv3. I think it is very useful for those people who have SSDs that support TCG OPAL.
https://github.com/Drive-Trust-Alliance/sedutil

**Comment by strugee** [comment]
AFAICT this essentially just "activates" encryption already in the drive. In that case I'd feel uncomfortable recommending this since most (all?) disk encryption firmware is proprietary and almost certainly hasn't had its cryptography audited or even studied in any way.

**Comment by Atavic** [comment]
Bright Plaza and the [Drive Trust Alliance](https://github.com/Drive-Trust-Alliance) joined the _Trusted Computing Group_ as Contributors.

_Trusted Computing Group_ explained:
[Trusted Computing Platform Alliance: The Motherboard of all Big Brothers](
https://github.com/CHEF-KOCH/NSABlocklist/issues/5)

**Comment by strugee** [comment]
Closing given the above comment. PRISM Break isn't going to recommend software that just "turns on" unknown, not publicly-audited cryptography.
