### ISSUE TITLE
web Search: peekier.com

### ISSUE THREAD

**Issue by vdo** [nylira/prism-break#1646]
Some days ago I found this web search engine:
https://peekier.com

They also have a good [privacy policy](https://peekier.com/privacy), but they are not very transparent about what search engine they use as a backend, where are they located and so on.

Some information anyone?

**Comment by Hillside502** [comment]
Show HN: Peekier – A new way to search the web
https://news.ycombinator.com/item?id=13166461

**Comment by strugee** [comment]
Nice, but I don't think this should be on the site since it requires JS (which DuckDuckGo doesn't). Also, they're on Cloudflare, which means Tor users may have trouble accessing it. That being said I didn't hit a CAPTCHA when I loaded it in Orfox, so I dunno if it's a real problem.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
> they're on Cloudflare

No thank you.

**Comment by strugee** [comment]
Closing as this doesn't seem to be going anywhere.
