### ISSUE TITLE
Please recommend Privacy Badger for Firefox on Android

### ISSUE THREAD

**Issue by jony0008** [nylira/prism-break#1648]

**Comment by alerque** [comment]
Please search the issue repository when posting. See #1609 and #1606 for discussion on why this was removed. If you have something to add to that discussion that should change the outcome please _explain_ what that is.

**Comment by strugee** [comment]
Privacy Badger still isn't supported on Android: https://www.eff.org/privacybadger#faq-Will-you-be-supporting-any-other-browsers-besides-Chrome-/-Firefox?

Closing based on @alerque's comment. If there's anything we've missed, comment and I'll reopen.

**Comment by jony0008** [comment]
https://addons.mozilla.org/en-US/android/addon/privacy-badger17/

Works with Firefox for Android 48.0 - *

**Comment by strugee** [comment]
Looks like this will be working in the near future but needs some time to bake: EFForg/privacybadger#1084

**Comment by strugee** [comment]
Closing to keep our issue tracker clean, given https://github.com/EFForg/privacybadger/pull/1516#issuecomment-323632263 and the fact that this has lingered on for many months now

**Comment by ghostwords** [comment]
The `addons.mozilla.org` website incorrectly claims all WebExtensions addons support Firefox for Android. This is a known issue: https://github.com/mozilla/addons/issues/348.

**Comment by strugee** [comment]
Reopening: https://github.com/EFForg/privacybadger/issues/1084#issuecomment-355060963
