### ISSUE TITLE
Ensichat

### ISSUE THREAD

**Issue by contrapunctus-1** [nylira/prism-break#1649]
I did not see this mentioned anywhere in the issues or the code, so figured I'd mention it here. I cannot speak as to the maturity and security of this project, but hopefully more knowledgeable people will weigh in. It is present in the F-Droid main repos.

https://github.com/Nutomic/ensichat/

PS thank you all so much for prism-break!

**Comment by strugee** [comment]
Oh yeah, I saw this in F-Droid recently.

Their crypto is pretty rudimentary, so I don't see this getting added anytime soon. See Nutomic/ensichat#57.

**Comment by strugee** [comment]
Any objections to closing this? The crypto isn't really up to snuff and also my (admittedly cursory) look at the GitHub repo makes it seem like this project isn't maintained very consistently. Also, the routing is _kinda_ neat, but I'm not sure it's compelling enough to add to the existing list.

**Comment by alerque** [comment]
I looked at the code too and agree there is nothing there that merits inclusion over and above existing options.

**Comment by strugee** [comment]
Closing due to the crypto problems, plus the fact that it's unmaintained: https://github.com/Nutomic/ensichat/issues/57#issuecomment-270278466
