### ISSUE TITLE
Zom Instant Messenger

### ISSUE THREAD

**Issue by Tdoor** [nylira/prism-break#1651]
From their github - "Zom for Android (previously known as ChatSecure and Gibberbot) is a secure messaging app built on open standards like XMPP/Jabber and OTR encryption."

Now that ChatSecure is no longer developed, should we consider adding Zom as one of our recommended free software apps?

**Comment by strugee** [comment]
More info on the difference between Zom and Conversations: https://chatsecure.org/blog/chatsecure-conversations-zom/

@Tdoor can you provide a link for the quote you mentioned?

**Comment by vyp** [comment]
@strugee https://github.com/zom/Zom-Android/blob/dfd17b681fe66da83f5103d9bb88f60644c32dfc/README.md

Additionally this blog post has some more information: https://chatsecure.org/blog/chatsecure-conversations-zom/.

**Comment by yegortimoshenko** [comment]
I would be against it, because we already list Conversations which is nearly perfect, with very low battery consumption, which also spearheads new XMPP XEPs. We strive for quality over quantity, and it's really hard to beat Conversations.

**Comment by yegortimoshenko** [comment]
Our IM section is already way too large, so would like to close unless there are compelling advantages over Conversations (which is the flagship XMPP client).
