### ISSUE TITLE
Remove Riseup from the list already

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1654]
https://user.riseup.net/ticket/111777

Opening this up because this is not email related but Canary related

**Comment by alerque** [comment]
Dude we just went through this with #1652. There are _two_  running discussions on this, one to do with stability, password reset issues, and other email problems (#1554), the other to do with the canary situation (#1613). This is a duplicate. Please stop opening new issues without searching for existing discussions first. Also this link has exactly the same problem we described before, it is not reachable for most people without logging in leaving nothing to actually discuss. If you comment on the existing issues be sure to include something we can actually work with.

**Comment by strugee** [comment]
Not only that but I have a hard time believing that this is about something different given that the link is the _exact same_.

**Comment by alerque** [comment]
Thanks @strugee. At this point this guy is basically spamming us. I don't know whether he keeps deleting and re-creating his account of if Github is booting him off for spamming. If you can I would suggest deleting the last three comments to the --54 issue that have third party PII in them. I don't think we need that in our issue tracked.

@githubhatestor If you are listening, please stop this. We get it, Riseup should probably be removed from our recommendations. We're working on it and there is ongoing discussion. In the mean time whatever your personal grievances are, spamming our issue tracker like this doesn't help to speed this up. Stop using it yourself if you are dissatisfied, but don't make a mess of things here.
