### ISSUE TITLE
Open Code of Conduct is dead

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1657]
Our Code of Conduct isn't being worked on anymore: http://todogroup.org/blog/followup-open-code-of-conduct/

In particular, http://todogroup.org/opencodeofconduct/#PRISM-Break/abuse@prism-break.org no longer shows our project name and abuse contact for me, though it could just be a browser misconfiguration on my end.

Not sure if we want to do anything about this, but I thought I'd bring it up for discussion anyway.

**Comment by vyp** [comment]
> In particular, http://todogroup.org/opencodeofconduct/#PRISM-Break/abuse@prism-break.org no longer shows our project name and abuse contact for me, though it could just be a browser misconfiguration on my end.

Doesn't show for me neither. :/

We could adopt the [Contributor Covenant](http://contributor-covenant.org/), WDYT? It's pretty popular and it's also one of the default templates on GitHub now.

**Comment by strugee** [comment]
@vyp sounds good to me; I use Contributor Covenant on all my other projects too. AFAICT it's sort of the standard.

**Comment by vyp** [comment]
If we do go ahead with the contributor covenant, do you think we should have a copy of it in the repository, or just link to it like we do now with the open code of conduct?

**Comment by strugee** [comment]
> do you think we should have a copy of it in the repository

I think most projects check it into Git in `CODE_OF_CONDUCT.md` or somesuch. They also don't have a webpage that will fill in the contact info and project name like our old one had, so we would _have_ to keep a copy to provide that info (at least inline).

**Comment by vyp** [comment]
Sorry I think I just forgot to reply, but that sounds good to me. I think this project definitely needs to fix this in some way asap though so I'll be making a PR to add the contributor covenant when I get some time (if no one else does). That would also give people another chance to speak up if there's any objections to this.
