### ISSUE TITLE
CSipSimple seems dead

### ISSUE THREAD

**Issue by contrapunctus-1** [nylira/prism-break#1661]
The page linked on prism-break 404s - https://code.google.com/archive/p/csipsimple/
Even at https://github.com/r3gis3r/CSipSimple the last commit was on 20th March 2015.

**Comment by hasufell** [comment]
It seems development is still active http://nightlies.csipsimple.com/trunk/?C=M;O=D except no one knows where the repo is located (development doesn't seem to happen on the github repo, probably because the original googlecode repo was subversion).

**Comment by strugee** [comment]
Does someone want to contact the maintainers? A couple emails are listed on the homepage. It'd be nice to keep CSipSimple, but if source has disappeared we should remove them ASAP.

**Comment by hasufell** [comment]
> It seems development is still active

correction. It seems they get automatically built from the abandoned repo. I just compared md5sum from `CSipSimple-latest-trunk.apk` (2017-01-17) and it matches the md5 from the file `CSipSimple-r2470-trunk.apk.md5sum` (2015-03-21).

**Comment by alerque** [comment]
Ouch. Talk about a waste of CPU cycles!

**Comment by strugee** [comment]
Nice catch, @hasufell. Truthfully I thought of that myself and then said, "nah, there's no way they're doing that." :/

Any objections to removing?

**Comment by alerque** [comment]
I think it needs the ax (from both PRISM-Break and my Android devices).

**Comment by mimi89999** [comment]
I looks quite abandoned.

Also,
>Wiretapping End-To-End Encrypted VoIP Calls: Real-World Attacks on ZRTP - https://www.sufficientlysecure.org/2017/03/15/zrtp.html

I guess it should be removed from prism-break. Of you add the accepting PR label, I will PR to remove it.

**Comment by mimi89999** [comment]
Will there be `Status: Accepting PRs` on this one?
