### ISSUE TITLE
HSTS preloading

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1664]
It'd be nice if PRISM Break was on the HSTS preload list. https://hstspreload.org/

/cc @nylira

**Comment by strugee** [comment]
@nylira ping - I'd really really like to see this happen. The issue right now is that `www.prism-break.org` doesn't have a valid cert, which is disqualifying us from the preload list.

**Comment by contrapunctus-1** [comment]
I am unable to open prism-break.org on Firefox v52.4.0, Debian Stretch. Is it related to this?

**Comment by vyp** [comment]
I can't access https://prism-break.org either at the moment since the security certificate expired. Pinging @nylira.

**Comment by Hillside502** [comment]
Expired Sun, 08 Oct 2017 06:39:00 UTC
