### ISSUE TITLE
Please Add Signal 

### ISSUE THREAD

**Issue by username4leaver** [nylira/prism-break#1667]
Signal is an encrypted instant messaging and voice calling application for Android and iOS.
https://en.wikipedia.org/wiki/Signal_(software)

Cheers!

**Comment by jinformatique** [comment]
Please make a search before posting about Signal. It has been discussed since 3 yo. Have a look at those issues. Thanks

#552 
#896
#1314

**Comment by strugee** [comment]
Closing as a duplicate. Please search next time - but thanks for contributing to PRISM Break!
