### ISSUE TITLE
Ricochet's logo is vertically squished

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1668]
https://prism-break.org/en/projects/ricochet/

**Comment by mimi89999** [comment]
@strugee I am ready with a commit for this.

**Comment by strugee** [comment]
@mimi89999 awesome! Can you send a PR?

**Comment by mimi89999** [comment]
@strugee Waiting for the other PR to be merged.

**Comment by strugee** [comment]
@mimi89999 PR from a different branch.
