### ISSUE TITLE
Add Discord to the list of proprietary software

### ISSUE THREAD

**Issue by RoseTheFlower** [nylira/prism-break#1670]
It could be added to the Instant Messaging and Video & Voice categories. Millions of people use it these days, but it's [not open source](https://www.reddit.com/r/discordapp/comments/43z4yh/open_source_protocol_encryption_privacy/cznvmxl/).
Moreover, the [Privacy Policy](https://discordapp.com/privacy) states: "Information we collect may include but not be limited to username, email address, and **any messages, images or other content you send via the chat feature**."

**Comment by griffindoors** [comment]
instead

https://meet.jit.si

**Comment by DestinFaroda** [comment]
All you need to know about Discord:
https://r4p3.net/threads/what-is-discord.861/

People and investors will never learn, so Jason Citron robs them again.

**Comment by strugee** [comment]
This is clearly proprietary and I don't see any reason not to add this. Marking as accepting PRs.
