### ISSUE TITLE
What about Kontalk?

### ISSUE THREAD

**Issue by Mattel88** [nylira/prism-break#1671]
http://kontalk.org

It is open source. I did not find any thread here so I guess it could be a way of adding more privacy?

**Comment by alerque** [comment]
Kontalk is already [listed on PRISM-Break](https://prism-break.org/en/projects/kontalk/). It was added in #1482. The logo was updated in #1660. There are also [other issues](https://github.com/nylira/prism-break/search?q=Kontalk&type=Issues&utf8=%E2%9C%93) mentioning this including translations to some languages. Please search the issue tracker before posting, and maybe make a note to use your browser's find in page from the [all projects page](https://prism-break.org/en/all/) too.
