### ISSUE TITLE
Inox patchset for Chromium

### ISSUE THREAD

**Issue by nyancat18** [nylira/prism-break#1673]
Inox patchset:

http://data.gpo.zugaina.org/frabjous/www-client/inox/

https://github.com/gcarq/inox-patchset/releases

Readme: https://github.com/gcarq/inox-patchset/blob/master/README.md

chromium has good security features, and inox removes all google crap 

https://www.menlosecurity.com/hubfs/pdfs/Menlo%20State%20of%20the%20Web%202016%20Dec12.pdf?t=1481642038948

**Comment by strugee** [comment]
Leaving open (for now) since the Inox patchset hasn't been suggested on its own before, but see for example #1516 for a similar suggestion.

**Comment by triceratops1** [comment]
@strugee   its Inox...sorry for the correct

**Comment by strugee** [comment]
@triceratops1 no problem - nice catch. My phone's autocorrect messed it up :)

**Comment by Zegnat** [comment]
I have been trying out the [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium) build for a bit, which incorporates the Inox patchset. So far it has been doing what I expected it to do: not call home.

**Comment by hasufell** [comment]
I too use the inox patchset (not ungoogled chromium though, the builds are messy, patches don't apply cleanly etc) for quite some time now.

**Comment by griffindoors** [comment]
@strugee 

samsung autoINcorrect?

**Comment by griffindoors** [comment]
#LessGoogleIsMoreBetter

How does a non programmy person use this?  Maybe wait for F-droid builds?

**Comment by triceratops1** [comment]
@griffindoors 

there are two packages at aur.

inox  (you only run yaourt -S inox  and wait to compile)

inox-bin, just run and enjoy
