### ISSUE TITLE
Open hardware PC?

### ISSUE THREAD

**Issue by kompowiec** [nylira/prism-break#1679]
Hi, i interested some open hardware + open source PC projects. I find actually two projects:
Pursim https://puri.sm/products/
Elbrus 401 PC
however i have doubts about these projects:
Pursim use intel processors
Elbrus looks promising

of couse does exist still thinkpad but latest models are created before 2005
Post your types.

**Comment by hasufell** [comment]
https://github.com/nylira/prism-break/issues/611
https://github.com/nylira/prism-break/issues/788
https://github.com/nylira/prism-break/issues/1616#issuecomment-264105662

**Comment by kompowiec** [comment]
Och, it was, sorry - can closed.

**Comment by strugee** [comment]
Closing as out of scope for PRISM Break.
