### ISSUE TITLE
Diskcryptor encryption system is discontinued.

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1684]
Disk Encryption system _Diskcryptor_ has been discontinued: last update was 09.07.2014
Also, diskcryptor.net site is unmantained.
https://github.com/nylira/prism-break/issues/1042
https://github.com/nylira/prism-break/issues/995

**Comment by strugee** [comment]
Are we sure it's not just that there wasn't a compelling reason to put out a new release? diskcryptor.net seems fine to me...

Also, I'm not clear on why you're linking to those other issues. Can you elaborate?

**Comment by Atavic** [comment]
There was an error on my side:
https://diskcryptor.net/wiki/Main_Page didn't work when I posted this issue.

Veracrypt and Gostcrypt are reliable options, too.
