### ISSUE TITLE
Improvements for XMPP server recommendations

### ISSUE THREAD

**Issue by contrapunctus-1** [nylira/prism-break#1688]
As someone trying out XMPP (via Conversations) for the first time after seeing Prism Break's recommendations, I was under the mistaken impression that all XMPP services are created equal. dukgo.com, as I found out the hard way, is among the worst in terms of feature support. This either causes users to write off XMPP (or, in case of tech-illiterate users - such as the friends and family members I invited to use it - the client application itself) as crap, or causes them as well as their contacts to suffer inconvenience as they migrate to new servers.

I suggest that we remove the dukgo.com recommendation, suggest a few top recommendations from this link, as well as provide this link itself -
https://gultsch.de/compliance_ranked.html

**Comment by strugee** [comment]
👍 for removing dukgo.com. I think this probably would be best in the IM notes section? Though that's a bit overloaded already...

**Comment by strixaluco** [comment]
I'm definitely pro removing dukgo.com. The recommendation is pretty misleading given the fact that the server is poor in features.

**Comment by contrapunctus-1** [comment]
@strugee - as far as de-overloading the IM section goes -
- I believe the OTR description could be safely removed (notwithstanding the next point)
- AFAICT OTR is a legacy protocol, and any recommendations based on it should be removed
- Xabber seems set to go - #1659 
- ChatSecure should be removed from the Android section, as it's iOS-only now, as should the corresponding notes (the guide link could perhaps be replaced with https://medium.com/@mathiasrenner/setup-whatsapp-like-chat-messaging-with-open-source-software-complete-guide-ec7adc0d3519#.7vde30gal instead?)
- I'm not sure why notes on Pidgin exist in the Android IM section, as it is neither available for Android nor recommended in the Android section
- SMS applications (Silence) should be given a separate section, as they are not (AFAIU) used in the same way as IM applications

(along with explaining that Conversations is an XMPP client and requires an account with an XMPP server, it may help to mention that "you can also use your XMPP account to chat using desktop XMPP clients, e.g. Gajim")

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

contrapunctus-1:
> - SMS applications (Silence) should be given a separate section, as
> they are not (AFAIU) used in the same way as IM applications

FWIW I use XMPP as an SMS substitute.  Not certain how common this is,
but I think it's probably a good security practice regardless of
commonness.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzg9+AAoJELPy0WV4bWVwEAoQALKNz6sWcaQYygehB10rwTs2
kOzF8Z1bM3CLXB6zU3pY0QWWwruCD4gKH/BWRljqnOUUQZHxwTWegcSpJOmeeeaT
LW8OQyCmjHJGWtnAUHPLJhRf76pQpA6pl7SeOFIf3BPTBTAGbKgHRZRkQ1k1AlJS
n27evWtNC4qPuSjw4+uVJid6oL0rRWCRk/bYvjLrRyxb277L+H3FOc0GvD2jKwRD
TpCMcMaOX3zhyNZsT0qG40+0x93PIKZ4obM736ZhokzGwwrGTiCilj+2Aq6IDADB
PMCKDSzJGRc1AtJpJ5y++bhbYNKf4CPgUTKKL+M8Xbra19RUwbdf+Gg5DEwyUKAd
mEcyNZDzTaXUrQxeuf0M/D072snrMc76rpe4vX2I0K67vmQ2bqMqDmd+ajVuAoAP
ys2DvC1R1EyKsOqMPpikH6ZRvc/NGfsMRyiBGnJKS1pA0q2v6tPbtqjlKaqEaZXo
ZY9duguQgcYxPRLNmXiTvpHhi5/UhkeIuWxoFEq/0cTz93Iu+MWx6h9DNXoBK4PY
JLBngiSU23mbvcMHpSIanwYMUnTV1BuhbP7qBC+heNnDsItLzRKksTPpPpAXiD29
SGfRMcTI3K8q2nfyusXXq/+hRNOOORzun4nenywS/KEaIiECvyyZQWgAgyEHjziD
r6/sT9NYSBlqymbHdi7+
=82Qa
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
Marking as accepting PRs. I'd love to get PRs that remove dukgo.com or implement suggestions in https://github.com/nylira/prism-break/issues/1688#issuecomment-280147743, with the exception of the remark about "SMS applications":

> SMS applications (Silence) should be given a separate section, as they are not (AFAIU) used in the same way as IM applications

I've said this before and I'll say it again: SMS is mostly the same as IM. They're basically the same _medium_ - see https://github.com/nylira/prism-break/issues/1267#issuecomment-111041198 for an explanation of what I mean by this. They're mostly used in the same way as far as I've seen. I don't see a reason for these to have a separate section, but if you feel strongly about it, please open up a separate issue.

**Comment by mimi89999** [comment]
@strugee I will make a PR removing dukgo.com.

As for recommending servers, we need to check privacy policies.

**Comment by Atavic** [comment]
Most of them have no privacy policies. Also, some may raise some doubts:

_conversations.im_ has a trial XMPP account for 6 months only. 
_jabber.rwth-aachen.de_ it's a german university hosted service.
_mail.de_ is a commercial project.
_high-way.me_ is a forum with some commercial offers.

**Comment by hasufell** [comment]
> jabber.rwth-aachen.de is a german university hosted service.

curious why you consider that a problem

**Comment by Atavic** [comment]
I see the name of the university, not any mantainer. Maybe @mathiasertl knows more?

**Comment by mathiasertl** [comment]
jabber.rwth-aachen.de is maintained by @debalance, who is also the maintainer of the mainline Debian package for ejabberd.

I should note that jabber.at also runs at a university, if that is a problem for you (for whatever reason). The University is however just the provider, it's run by the students union (of which I'm a member).

**Comment by mathiasertl** [comment]
After looking at https://prism-break.org/en/protocols/xmpp/, let me add, content wise:

* We have a list of clients [here](https://jabber.at/p/clients/).
* I recommend removing Thunderbird. It doesn't support SRV records, causing problems for many larger servers.

**Comment by debalance** [comment]
Please note that while jabber.rwth-aachen.de is (currently) fully compliant, only people with a working e-mail address from one of the universities in Aachen are eligilbe for an account.

**Comment by Atavic** [comment]
@mathiasertl No problems for me, only lack of info that you kindly provided.

**Comment by Atavic** [comment]
chinwag.im	--- ChinWag is Australian-hosted and pitched primarily as a provider of services primarily to Australians: https://chinwag.im/2015/10/08/chinwag-privacy-and-metadata/
chatme.im --- hosted in Italy.
hot-chilli.net --- hosted in Germany: https://www.hot-chilli.net/impressum/
neko.im --- hosted in Holland. Privacy: No more information is collected and stored than what is absolutely necessary. Rosters, vcards, offline messages, and so forth.

**Comment by Atavic** [comment]
[How to Make Thunderbird Chat Work with Most XMPP/Jabber Accounts](http://rmore.net/2012/09/07/how-to-make-thunderbird-chat-work-with-most-xmppjabber-accounts/) and
[Check DNS SRV records for XMPP](https://kingant.net/check_xmpp_dns/) give a working solution.

**Comment by yegortimoshenko** [comment]
All changes asked in https://github.com/nylira/prism-break/issues/1688#issuecomment-287598774 are implemented at this point, except OTR deprecation for which there is a more recent issue (https://github.com/nylira/prism-break/issues/1927). Closing this ticket, if someone wants to propose adding some XMPP server to the list, it would be easier to process if every XMPP server had its own ticket.
