### ISSUE TITLE
www.prism-break.org HTTPS certificate error

### ISSUE THREAD

**Issue by realulli** [nylira/prism-break#1689]
Hi,

at the moment, going to https://www.prism-break.org/ is giving a certificate error.

(trying to insert a screenshot here but failing to upload a .png...)

prism-break.org (without the www.) works fine. I guess there is a slight server misconfiguration somewhere... 

Cheers, Ulli

**Comment by realulli** [comment]
![Uploading prism-break.org_insecure.png…]()

**Comment by Hillside502** [comment]
@nylira 
There is indeed an error in the certificate chain --- Firefox (correctly) flags it.

Please visit:-
SSL Server Test: prism-break.org (Powered by Qualys SSL Labs)
https://www.ssllabs.com/ssltest/analyze.html?d=prism-break.org

expanding the section:-
Certificate 2: RSA 2048 bits (SHA256withRSA) No SNI
reveals the error:-

```
Common names 	cosmos.nylira.com   MISMATCH
Trusted 	No   NOT TRUSTED
```

**Comment by strugee** [comment]
Yep. Fixing this and #1664 would be nice @nylira

**Comment by paperbag** [comment]
![cert](https://cloud.githubusercontent.com/assets/19257585/23127513/4c2a364e-f7b6-11e6-93ac-d95dac5c9bad.png)

**Comment by nylira** [comment]
Solved!

**Comment by Hillside502** [comment]
@nylira 
It ain't fixed --- look again at my comment above for the **exact** details --- just because it's A+, doesn't mean the error has gone away!

**Comment by strugee** [comment]
@Hillside502 no need to lecture @nylira. That being said I can also still reproduce the problem here

**Comment by Hillside502** [comment]
@strugee 
Lecture?
Touchy, Touchy!

**Comment by strugee** [comment]
@Hillside502 heh, I was just about to edit my comment so it sounded less touchy :P

You beat me to it.

**Comment by Atavic** [comment]
Still a problemo yet.

**Comment by Hillside502** [comment]
@nylira @strugee 
Just to through a bit more light on this problem.

When running the Qualys test for --- prism-break.org --- the result gives A+ but expanding the detail shows the trust error detailed **above**.

Running the test for www.prism-break.org --- shows _Certificate name mismatch_ followed by the text:-

Try these other domain names (extracted from the certificates):

    cosmos.nylira.com

What does this mean?

We were able to retrieve a certificate for this site, but the domain names listed in it do not match the domain name you requested us to inspect. It's possible that:

    The web site does not use SSL, but shares an IP address with some other site that does.
    The web site no longer exists, yet the domain name still points to the old IP address, where some other site is now hosted.
    The web site uses a content delivery network (CDN) that does not support SSL.

My money is on:-
`The domain name is an alias for a web site whose main name is different, but the alias was not included in the certificate by mistake.`

(www.)prism-break.org and cosmos.nylira.com share the same IP address --- 139.59.225.79

Hope this helps!

@nylira 
cosmos.nylira.com is using Google Analytics --- how about Piwik --- naughty, naughty --- smack bottom :-)

**Comment by mimi89999** [comment]
@nylira Could you have a look at this?
