### ISSUE TITLE
Why is VeraCrypt not listed under disk encryption?

### ISSUE THREAD

**Issue by Ezra566** [nylira/prism-break#1693]
I apologise if this isn't the right place to post this question.

**Comment by alerque** [comment]
This might be the right place to ask the question but if you'd [searched](https://github.com/nylira/prism-break/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20VeraCrypt%20) you'd have found it's been asked a dozen times before. Still active issues  related to  this are: #995 #1273 #1612.
