### ISSUE TITLE
Is simplenote a safe alternative to evernote?

### ISSUE THREAD

**Issue by yasyasya** [nylira/prism-break#1696]
https://simplenote.com/

**Comment by Atavic** [comment]
Have you tried it?

**Comment by yasyasya** [comment]
Yes. "Simple" application like name. Not as advanced as Evernote. But if it is safe, this is enough for me.

**Comment by Atavic** [comment]
I read the policy, that's on Automattic site (bottom left), are there Ads in Simplenote?

**Comment by yasyasya** [comment]
No. I have seen a new application. The application of Turtl seems to be more useful. It also aims to be a safe alternative to evernote. It is developing further. Do you have any idea about this practice? 
https://turtlapp.com/

**Comment by Atavic** [comment]
No idea, the Code' s [here](https://github.com/turtl).

**Comment by vyp** [comment]
I don't think so because it looks like simplenote is proprietary. There's #1602 for turtl.
