### ISSUE TITLE
Add a File Sharing section

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1697]
Proposed Recommendations:

* [OnionShare](https://onionshare.org): sets up a temporary onion service to share any file of any size (it has reached stable v.1 now, and it also now supports stealth onion services).

* Torrenting with i2p.

**Comment by Atavic** [comment]
Some torrent clients can and will break user's privacy: one of them is surely _utorrent_.

**Comment by strugee** [comment]
Torrnting will probably never be private because _by design_ the protocol includes/broadcasts things like IP addresses. So I'm pretty sure _all_ torrent clients will break privacy in terms of PRISM Break's threat model.

**Comment by tailslover** [comment]
send.firefox.com

**Comment by strugee** [comment]
If we wanted to add this section, I could also see things like Nextcloud going in there. I think I'm +1 on this - it's not like we're trying to keep the list as a whole short.

**Comment by hasufell** [comment]
We already list one filesharing alternative: RetroShare
