### ISSUE TITLE
About my z5 compact phone

### ISSUE THREAD

**Issue by yasyasya** [nylira/prism-break#1698]
I have a Sony z5 Compact phone. But Replicant does not support my phone. What should I do? (I do not know much about such issues) Note: I can not get a new phone right now.

**Comment by strugee** [comment]
Unfortunately there isn't a whole lot that you _can_ do. I'd install LineageOS or OmniROM. However I want to be clear that while these are better than nothing, they don't provide a solution that can be considered "secure" by PRISM Break's standards.

Closing as there are no action items here.
