### ISSUE TITLE
Poor score when tested with securityheaders.io

### ISSUE THREAD

**Issue by problenatic** [nylira/prism-break#1699]
https://securityheaders.io/?q=prism-break.org&followRedirects=on

It misses a lot of security headers including: [Content-Security-Policy](https://scotthelme.co.uk/content-security-policy-an-introduction/), [Public-Key-Pins](https://scotthelme.co.uk/hpkp-http-public-key-pinning/), [X-Frame-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options), [X-XSS-Protection](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection), [X-Content-Type-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options), and [Referrer-Policy](https://scotthelme.co.uk/a-new-security-header-referrer-policy/).

**Comment by strugee** [comment]
X-XSS-Protection, X-Content-Type-Options and X-Frame-Options don't matter. The rest we should probably do.

/cc @nylira

**Comment by strugee** [comment]
Thinking about this more I also don't particularly see a reason to do Content Security Policy. The only directive that might be useful is the one that disallows all Mixed Content, and I think that's still just a draft.

**Comment by hasufell** [comment]
Duplicate of #1570
