### ISSUE TITLE
Add turtl

### ISSUE THREAD

**Issue by gygygh** [nylira/prism-break#1701]
https://turtlapp.com/

**Comment by Hillside502** [comment]
@gygygh 
Hmm --- looks like another processed pork account created 8 minutes ago

**Comment by gygygh** [comment]
Yes, because I opened it to ask questions. I want to know if Turtl is safe. I said "Add" because it seemed safe to me. If not, I will learn. There has not been a conclusion about this application before. I'm following the Prism-break platform and I'm asking questions. That's why I opened my account. How is that strange?

**Comment by strugee** [comment]
Duplicate of #1602
