### ISSUE TITLE
Prism-BREAK live site not removing deleted files

### ISSUE THREAD

**Issue by alerque** [nylira/prism-break#1707]
As spotted in conjunction with #1171, the process of deploying the live Prism-BREAK site is broken. Files that _change_ get updated and overwritten, but files that get removed from the source entirely do not get removed from the site. The file ends up being an unlinked orphan, but it is still discoverable through search engines that have previously indexed the site and makes it look like we're listing things we're not.

For example the main site is showing a build date of 2017-03-13 right now, but [the deleted APG page](https://prism-break.org/en/projects/apg/) artifact is still showing up with a build date of 2016-12-13.

This needs fixing so the site deploy mechanism places a fully clean set of files on each update.

**Comment by Hillside502** [comment]
Also, every page --- including the main site --- showed a build date of 2016-12-13, until just a few days ago.

Between that date and the present, several site updates must have been made --- but the build date didn't change.

So, there appears to be a problem with dates remaining static.

**Comment by strugee** [comment]
@alerque do you know if this is something we need to fix in the Makefile, or does @nylira need to fix his cronjob?

@Hillside502 can you file a separate issue for that?

**Comment by alerque** [comment]
@strugee I had a quick look at the Makefile before I submitted this issue with an eye to contributing a quick PR instead of an issue, but it looked like all was in order there.  It looks to me like @nylira would have had to run a build without starting with `make clean` and/or use custom commands to copy to the static site rather than the rsync that's in the Makefile. 

If that turns out not to be the case and there is some subtle bug in the Makefile I'd be  happy to do a more careful review.

**Comment by alerque** [comment]
@strugee I'm not convinced @Hillside502's issue is  different either. The date thing is likely just  an artifact of not doing a clean build when releasing. The build system only builds things that changed, so some pages / languages might not get new dates when doing a build unless it was specifically a clean build.

Long story short we could probably make `reset` a prerequisite to the `sync` target, but that would possibly impinge on how @nylira wants to step through the process.
