### ISSUE TITLE
about f-droid apps

### ISSUE THREAD

**Issue by gygygh** [nylira/prism-break#1708]
There's something I'm curious about. Can I count on the applications on the F-droid? You do not suggest the telegram, but there's an F-droid.I do not know anything about the code. I'm an ordinary user.

**Comment by strugee** [comment]
Being on F-Droid is a precursor to good security. But it's not sufficient. Search around this issue tracker and you'll find discussions on what's wrong with Telegram, for example.

**Comment by hasufell** [comment]
No, you can't count on f-droid. A lot of apps are outdated, which is pretty bad for security. F-droids focus is more on the open source part.

**Comment by strugee** [comment]
Exactly. Closing since there are no action items here.
