### ISSUE TITLE
FreeOTP Authenticator Webpage moved.

### ISSUE THREAD

**Issue by screamerbeetle** [nylira/prism-break#1721]
It looks like the FreeOTP webhost service ( https://fedorahosted.org/freeotp/ ) has shut down (redirects to https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement).  Wikipedia points to  https://freeotp.github.io/ and there's a link to download for Android and iOS there.

**Comment by Atavic** [comment]
F-Droid links to github, too.
https://f-droid.org/repository/browse/?fdid=org.fedorahosted.freeotp
