### ISSUE TITLE
Replicant drivers for CopperHeadOS?

### ISSUE THREAD

**Issue by 09f2486744e3844349af** [nylira/prism-break#1722]
Would it not be possible to get a Replicant supported phone install CopperHeadOS on it but install drivers from Replicant and delete non-free drivers from CopperHeadOS? So you get the security of CopperHeadOS and free drivers of Replicant.

**Comment by alerque** [comment]
This issue tracker is not the place for this question. This is either about rolling a custom ROM for yourself or starting a new one based on remixing parts of existing ones. Either way _developing_ new software is out of scope for this issue tracker which deals with whether existing projects should be listed.

Come up with something cool like what you describe, get the project some traction and scrutiny from the security world, then we'll consider listing it!

**Comment by 09f2486744e3844349af** [comment]
Okey so i don't know a lot about android but i might look into it. I tought that we could mention a note or something like that but i think you are right so should this be closed or not? 
Thank you for the reply.

**Comment by strugee** [comment]
Closing as there isn't much for us to do here.
