### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by hamoid** [nylira/prism-break#1723]
Hi, any thoughts on https://mastodon.social/about ? I just heard about it. Cheers!

**Comment by Atavic** [comment]
:+1: for the source on GH.
:-1: for the Terms (everytime, terms provided are about the webpage and forum, not the service)

Unless I didn't spot them, I couldn't find the User _Terms for the service_ itself.

**Comment by strugee** [comment]
Terms of Service are mostly irrelevant because we'd be recommending the software, not the primary hosted instance.

**Comment by Hillside502** [comment]
Open Source Mastodon Alternatives - AlternativeTo.net
https://alternativeto.net/software/mastodon/?license=opensource

**Comment by strugee** [comment]
Mastodon ~= GNU Social, which is already listed. The main questions here are Mastodon's licensing (though I can't imagine it's problematic) and development community which has an impact on how security will be treated.

**Comment by Gargron** [comment]
Mastodon is AGPLv3 licensed

- https://github.com/tootsuite/mastodon
- https://joinmastodon.org

>Mastodon ~= GNU Social, which is already listed

This is not quite true. Even though they share the same network, it's wildly different software with different design and features. Now it's also primarily ActivityPub-based, which is a new federation protocol.

**Comment by strugee** [comment]
> This is not quite true. Even though they share the same network, it's wildly different software with different design and features. Now it's also primarily ActivityPub-based, which is a new federation protocol.

Lol, I'm aware - I'm `ajordan` on W3C IRC :P

FWIW when I wrote that comment, it was much more accurate.

Thanks for the ping. Since the Social Networking section is kinda overloaded, I vote for replacing GNU Social with Mastodon. AFAIK Mastodon is easier to set up and ActivityPub is a W3C standard that lots of these projects are converging on, so Mastodon will interoperate with more stuff. Plus it supports things like PMs that GNU Social does not and development seems more active as well. @Gargron does it still federate with GNU Social instances or did y'all drop that already? That would be another compelling point in favor of Mastodon.

**Comment by deutrino** [comment]
It still federates with ostatus-capable nodes, including gnusocial.

**Comment by strugee** [comment]
Nice. I don't see any reason to prefer GNU Social over Mastodon then, and I see compelling reasons to prefer Mastodon. Marking as accepting PRs.

**Comment by alerque** [comment]
I'm ... not too sure about this on. Don't get me wrong I love Mastodon, I have accounts on several hosts, run my own node, package the software for some distros, etc. I like Mastodon and I like getting away from proprietary services and walled gardens. It's a great bit of open source work.

But this is PRISM-Break we're talking about here, and I'm not sure recommending even a great open ecosystem is in line with what we are trying to promote. My observation is that if you wanted to run a closed network of your own it might be possible to have a "privacy" factor, but if you federate with anything at all –and let's face it here federation is the point of Mastodon/GNU-Social both– then you leave yourself wide open to surveillance. Raking in content and meta data from vast swaths of the network would be trivially easy for a nation-state attacker and this really isn't even part of the "threat model" the architecture is designed around.

Why are we recommending it here exactly?

**Comment by deutrino** [comment]
Those same objections are true of Diaspora, Friendica, Hubzilla, pump.io, and essentially anything that is both federated and without end-to-end encryption, yes? The point raised seems broader than the scope of this particular issue. If the others are recommended, it seems logical to me to recommend Mastodon, while potentially discussing the issue of recommending such platforms at all in a separate issue.

**Comment by Gargron** [comment]
Those same objections are true of Twitter, Facebook, G+, etc. The prism-*break* here is the break out from deliberate *surveillance capitalism*.

**Comment by alerque** [comment]
@strugee I agree on that last point, so I guess go for merge. Maybe we do need a general conversation about classifying threats and which of our recommendations address which threat models.

**Comment by yegortimoshenko** [comment]
Live!
