### ISSUE TITLE
zero-knowledge file sync ? (SpiderOak)

### ISSUE THREAD

**Issue by pmilosev** [nylira/prism-break#1724]
Hi 

I've been doing some research lately and I can't compile any solution, which would offer end-to-end / zero-knowledge cloud sync, based on the software proposed by prism-break.

SpiderOak seems to offer it, but I saw several issues where it was rejected.
Now, I can use it regardless of wether it is listed on prism-break or not, but I would like your opinion on why do you consider it unsafe ?

- The backend is AGPL licensed.
   https://github.com/SpiderOak/nimbus.io
- Mobile app is Apache 2.0 licensed.
   https://github.com/SpiderOak/SpiderOakMobileClient
- OS X / Windows / GNU Linux file watchers (not exactly sure if this is the complete client) are GPL v3.0 licensed.

I didn't go trough all the repos, but it looks like their entire software (or at least the essential one: server and clients) are free software.

Perhaps they were closed source before and decided to switch to free-software later ?

Thanks

**Comment by Atavic** [comment]
Some parts are open source, not the whole tools: https://github.com/nylira/prism-break/issues/1049#issuecomment-48045942
https://spideroak.com/faq/why-isnt-spideroakone-open-source-yet-when-will-it-be

**Comment by hasufell** [comment]
> The SpiderOak desktop backup client is the product of years of a typical startup scramble, and the codebase itself is tightly interwoven with a lot of other moving parts and sensitive information that we cannot release. We would like to correct this as much as anyone else, however the cost of doing so would stall our limited engineering resources enough that it would threaten our ability to continue providing world-class privacy preserving products.

Lol, sounds like they violated a bunch of licenses xD

**Comment by Atavic** [comment]
Anything _Cloud_-related smells like a scam to me, on topic: consider running your own server.

**Comment by Hillside502** [comment]
Open Source Self-Hosted SpiderOak Alternatives - AlternativeTo.net
https://alternativeto.net/software/spideroak/?license=opensource&platform=self-hosted

**Comment by pmilosev** [comment]
OK, now I see that SpiderOak's desktop client is not free software, and they actually claim zero-knowledge only when using the desktop client, not the mobile ones - so not really a solution ATM.

Regarding self-hosting, I hope you guys realise that this is not a plausible option for big majority of world's population. As you can not expect everyone to be able to maintain one's car on his own, you should also not expect that everyone can maintain one's own various servers. So if the goal of prism-break is to assist everyone, not just technical persons with a lots of free time, to break free, we should really try to provide reasonable, as convenient as possible, options.

Currently I'm a heavy Gapps user (I'm not sure how I got so sucked in by Google, but anyway) who tries to completely replace Google with privacy-respecting alternatives. Once I'm done I plan to document the whole process. 

What do you think of including a section in prism-break where others can contribute such guides / stories ? I believe this will ease the transition for non-tech people, who either lack knowledge or time to do research themselves.
There we can address the issues that are still left open (e.g. zero-knowledge cloud photo gallery) and comment / suggest / add to each other research.
