### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by hrsyvg** [nylira/prism-break#1725]
I suggest adding more categories. Antivirus programs, applications for various purposes

**Comment by Atavic** [comment]
Similar issue had this answer: https://github.com/nylira/prism-break/issues/1715#issuecomment-289714060

**Comment by strugee** [comment]
If you have specific categories you'd like to see on PRISM Break besides antivirus, please list them. Otherwise this is a wontfix.

**Comment by strugee** [comment]
Thanks for contributing to PRISM Break!
