### ISSUE TITLE
Gajim leaks DNS outside of proxy, devs don't seem to care

### ISSUE THREAD

**Issue by JeremyRand** [nylira/prism-break#1727]
[A bug report about Gajim leaking its DNS requests outside the configured proxy has been open for over 2 months.](https://dev.gajim.org/gajim/gajim/issues/8538)

The only developer who replied is declining to fix it, and suggests that a transparent proxy should be used to prevent these leaks.  This suggestion is not sufficient, because any Gajim DNS requests that are caught by a transparent proxy will go over the same Tor circuit as everything else that's using the transparent proxy, making it trivially easy to link the user's various activities together.

In my opinion, this raises questions about Gajim's suitability to be recommended on PRISM Break.

**Comment by hasufell** [comment]
You're misrepresenting the opinion of the developer, he clearly said

> if you want to work on that in gajim you are welcome to supply patches.

Also, I don't see how Tor-compatibility is a must-have feature. Where did we define that criteria?

**Comment by JeremyRand** [comment]
Julian Ospald:
> You're misrepresenting the opinion of the developer, he clearly said
> 
>> if you want to work on that in gajim you are welcome to supply patches.

Saying he would merge a patch suggests that he doesn't plan to work on
it, and also suggests that privacy is not a high priority for the Gajim
developers.

> Also, I don't see how Tor-compatibility is a must-have feature. Where did we define that criteria?

I can't think of any reason why Tor compatibility wouldn't be an
expectation for a privacy-friendly XMPP client.  Pidgin and
Conversations (both on PRISM-Break) support Tor, and Tor Messenger and
CoyIM do as well (both proposed for PRISM-Break).  Does a project like
Gajim that doesn't seem to be focused on privacy and doesn't support Tor
safely have any clear advantages over projects like Tor Messenger or
CoyIM?  (I grant that it does clearly have advantages over Pidgin,
namely better memory safety.)

My impression is that usually, PRISM-Break only recommends software that
can't work with an anonymizing network in cases where no alternatives
exist for the given use case.  In the category of desktop XMPP clients,
this doesn't appear to be the case.

**Comment by mimi89999** [comment]
@JeremyRand Gajim does care about privacy. It was the first client after Conversations to have full OMEMO support. As for the leaked queries, you should think about your threat model. Even if you won't leak them in Gajm, you might in other apps. If this is important, you should use an isolated system passing everything through TOR.


I think that issue can be closed.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Michel Le Bihan:
> @JeremyRand Gajim does care about privacy. It was the first client
> after Conversations to have full OMEMO support.

That's great to know.  Their response to this issue did not make it
clear that privacy is a priority.

> As for the leaked queries, you should think about your threat
> model. Even if you won't leak them in Gajm, you might in other
> apps. If this is important, you should use an isolated system
> passing everything through TOR.

That's not how DNS leaks work.  Yes, it's trivially easy to redirect
outgoing DNS traffic to Tor's DNS port via iptables (Whonix does
this), but any such DNS traffic will bypass stream isolation, which
will lead to identities unexpectedly being linkable.  I suppose you
could run every identity in a separate VM to prevent stream isolation
from being broken (this is technically doable in Qubes), but you'll
quickly run out of RAM if you attempt this with a lot of applications.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZmiJ2AAoJELPy0WV4bWVwzzIQAKijF84xVCCnO/3P+rjM8BmT
HXI/0nympdDdnTxltO5q76WAzRdCha4t5yIQ7oqKuC+ZiWHTPFjH02aeGMeXvdWc
e4btWK6fH3Ef8BxcD4mp1T//40HZF33lqherfIMhXOXyRe82P5uvtJiH0oIjR8tk
mzYO0SNs77da4fSHbkm2yYlpNjD6pk7WwrSV6xHbqJEmAdhYqmY+gKwNhXIp9Asm
HgcYo7G4/Xzwgig/bVrf0bHhZvG6Nax9yVixV2ZtosoMmZJRGqh9MUgehmPse3MH
MPDn7u6htPABlpHwUdFVZ4TOfTCjf3nykMAszBxIxbTMoNVPDcAbT55W+eDKT9Jz
ONM+cQGH2i1n/9mTENb3UpSpRL1NsnqEZIH142XF3GG2jo/ZGcF8Px15MgfIGUUo
opBA26Bntk5VjRUOXA8MHZQhvrpDtB72/xC1VmNtP1RSlI8pDajifgz+6L9JRPm2
5XyyI/hK9G9Odg4vxVKiHGRRim8crpQs20t2FsKVY6g09CDqnh4Ha9jmmUlF1v0K
Uez579Tf5LrEBmU4//shJtPJPctuHbuS5TN4wUxLldEiS3cPK7AflYlKWd8NUC9c
LXEk3AZAMdOL3G1rpKTwT+iSoZAy5+e1lnjN1uAolmjYt+lAZ9OJSeuiKbu6cpWP
3is0CqQ7fl8y4GH86MSA
=/70a
-----END PGP SIGNATURE-----
