### ISSUE TITLE
adding apps & devices to your website?

### ISSUE THREAD

**Issue by briannyeko** [nylira/prism-break#1728]
When will you add safe hosting websites(for domains etc..) and safe financial apps & devices(trezor,digitalbitbox,ledger,keepkey)(not cryptos like Bitcoin,Litecoin,Monero,Dash,Ethereum,Ethereum Classic).

**Comment by Hillside502** [comment]
The apps you mention above are nowhere to be seen on AlternativeTo or Wikipedia --- with the possible exception of:-
Open Source Ledger Alternatives - AlternativeTo.net
https://alternativeto.net/software/ledger/?license=opensource

Please flesh out some details as a basis for discussion.

https://alternativeto.net/
https://en.wikipedia.org/wiki/Main_Page

**Comment by Atavic** [comment]
[Trezor](https://trezor.io/), a Bitcoin wallet device has a GH Page: https://github.com/trezor

For webhosting, a safe way is host your own site by yourself: https://github.com/Kickball/awesome-selfhosted#web-servers
