### ISSUE TITLE
Investigate pfSense

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1732]
Someone I'm at a conference with says that pfSense runs PHP as root. We should investigate.

**Comment by Hillside502** [comment]
Why does everything run as root?
https://forum.pfsense.org/index.php?topic=117178.0

**Comment by Atavic** [comment]
It's the WebConfigurator (PHP GUI), you can change default address:port.

**Comment by strugee** [comment]
@Hillside502 so that forum thread confirms that things run as root.

In general that doesn't sit well with me. Unless there are objections I think we should just remove this project. We aren't helping anyone by recommending a solution that's "easy" but insecure.

**Comment by Hillside502** [comment]
+1 for OPNsense

**Comment by Atavic** [comment]
opnsense is a fork of pfsense and uses PHP for configuration. So, the security problems aren't very different IMHO

**Comment by strugee** [comment]
Given that there haven't been any objections to removing pfSense in 6 months, marking as accepting PRs.
