### ISSUE TITLE
Add OPNsense

### ISSUE THREAD

**Issue by ignitedPotato** [nylira/prism-break#1733]
More libre alternative to pfSense: https://opnsense.org/

**Comment by strugee** [comment]
This project seems kinda sketchy to me - they advertise that the firewall can "issue Let's Encrypt certificates" and "backup to Google Drive", both of which don't really make a lot of sense.

**Comment by strugee** [comment]
Also, how is it "more libre"?

**Comment by ignitedPotato** [comment]
Sorry, it seems like pfSense changed their license since I switched to OPNsense, so strike "more libre".
But also have a look at https://docs.opnsense.org/fork/thefork.html#so-why-did-we-fork

**Comment by fraenki** [comment]
> they advertise that the firewall can "issue Let's Encrypt certificates"

OPNsense provides a nice [plugin system](https://docs.opnsense.org/development/examples/helloworld.html). I've contributed the Let's Encrypt plugin; it's just one of those purely optional plugins. None of these plugins is automatically installed. It's up to the user/administrator to decide wether this functionality makes sense or not on a firewall/router.

**Comment by sachaz** [comment]
OPNSense is a real rock solid prism resistant firewall:

- opensourced, package of FreeBSD: https://github.com/opnsense
- HardenedBSD security contributions: https://hardenedbsd.org/article/shawn-webb/2015-05-08/hardenedbsd-teams-opnsense

**Comment by yegortimoshenko** [comment]
pfSense has been recently removed. Also, this is unlikely to be better in security/privacy or popularity aspect than currently proposed router distributions (Openwrt, OpenBSD, LibreCMC).

**Comment by sachaz** [comment]
I really like OPNSense and use it daily.
The main issue with OPNSense to be in the Prism Break list is that most processes are running with root rights.
```
root@cerbere11:~ # ps aux | cut -d' ' -f1 | sort | uniq -c |sort
   1 USER
   1 _flowd
   1 dhcpd
   1 nobody
   1 unbound
  80 root
```
Help is welcome to work on it ;)

**Comment by yegortimoshenko** [comment]
This was the reason why pfSense was removed.
