### ISSUE TITLE
Add CanvasBlocker

### ISSUE THREAD

**Issue by tunguyen6** [nylira/prism-break#1736]
A Firefox Plugin to block the <canvas>-API
https://github.com/kkapsner/CanvasBlocker/
https://addons.mozilla.org/firefox/addon/canvasblocker/

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Tu Nguyen:
> A Firefox Plugin to block the <canvas>-API 
> https://github.com/kkapsner/CanvasBlocker/ 
> https://addons.mozilla.org/firefox/addon/canvasblocker/

Noteworthy that Tor Browser already has a subset of this functionality
(Tor Browser prompts users whether to allow websites to readout Canvas
data).


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZNRQMAAoJELPy0WV4bWVwchQP/jquj8z+UXnlO7gUBeawXrbl
vToT0MV6hnuR0BYPWAcLEWdEZYEZ8h2S7Vv2RaJTi02ygOLPq+8T+ZfcqGkfHEIl
cYEasA/XvFOWYbJpnlIr6CqEO/8kR0ZCyexaDcrAbPgRQGL5+dEtZVyAwFifLGTJ
fJ8QD56I1aNya9k7zg6AgNs71ryw10zWaP3WeNLbpxmlWvcEC69eBrmYBusPmMx5
W/Msr2Fn/QgtGrxd7sz8cmnUBcOK91ZyRWdNXIVb9+Q5EWMnYNeN40DnT5yaJfiR
+qLUm/jNHllnj7LSStOirApNVDEm33FSZqhmnQPVFfH3ZE4LcixvQCysiG6Ncl3c
TzXIJFMJ8Gx0pUGnJQOdQ5L33PGTN0A5tKZD/sCS/A2+d7rkcQCwvZ45l2H4LSAF
nFUtYFNU3tZPeV5x2ehsixJdFUWY62BuaE8lWnDaRLEIECf2I32s2VOVJdIle8A5
U+MfVCIB4ZEo8oT3ltJ/ySMgddihDpNuzFZLTWBS7rw3ezu5JOjvOs8+6e6VnNZ+
R1W1NHsZGfiFV1ynwpdjB26MnBTyu3wTe9DmaLbrNLQflTdy312K8k1/bAnQA3bU
cQp9pvu0rO4+Yh0H+R990ZSo5RN9UKtj4XyFiUC5sOxXNgRj2mKsN5sgV+nH6qhn
lxB9BW8F8Xs+2CpEuKbo
=CUj+
-----END PGP SIGNATURE-----

**Comment by yegortimoshenko** [comment]
Firefox now asks if user wants to give access to canvas API or not, so this doesn't seem to have much use anymore.

**Comment by strugee** [comment]
It does? I've never seen any such prompts. Is that only with fingerprinting resistance enabled?

**Comment by yegortimoshenko** [comment]
Apparently you're right, prompts only appear if `privacy.resistFingerprinting` is `true`:

![canvas](https://user-images.githubusercontent.com/1643293/37554417-041e7cb4-29d0-11e8-852b-0eedb559b0a4.png)

That said, I thought it's on by default because they did consider setting it on by default in Firefox 58: https://thehackernews.com/2017/10/canvas-browser-fingerprint-blocker.html

**Comment by yegortimoshenko** [comment]
Superseded by https://github.com/nylira/prism-break/issues/1957, because this functionality is present in Firefox itself, we just need to tell people how to enable it.
