### ISSUE TITLE
Standard Notes

### ISSUE THREAD

**Issue by mobitar** [nylira/prism-break#1740]
Simple and private encrypted notes app. Makes a good encrypted Evernote alternative. 

[Open-source](https://github.com/standardnotes) (GPLv3)
[Android APK](https://github.com/standardnotes/android/releases).

Strict privacy policy: https://standardnotes.org/privacy

Website: https://standardnotes.org/

Would be happy to submit a pull request for this. Thoughts?

**Comment by Atavic** [comment]
They use Piwik for analitics.

**Comment by hrsyvg** [comment]
Analytical service is preferred. It can be turned off from the settings. So I know that. That's what the privacy policy says. I received a random account and I see that it can be disabled from the settings.

**Comment by Atavic** [comment]
It should go into: Productivity > Free Recommendations

**Comment by Zegnat** [comment]
I like the idea of Standard Notes, and I have been looking for cross-platform synchronising note taking. Definitely going to give this a shot when I have some more time.

That said, I have some minor concerns about [the security audit](https://standardnotes.org/blog/7/announcing-our-2017-security-audit-results) as it seems to have audited [an incomplete synchronisation specification](https://standardfile.org/) only. The encryption seems solid and have made it past their scrutiny, but I will always be biased against incomplete standards (cf. standardfile/standardfile.github.io#12).

**Comment by mobitar** [comment]
Thanks for taking a look. I posted some follow-up comments on your thread: https://github.com/standardfile/standardfile.github.io/issues/12#issuecomment-352266619

I wouldn't call SF incomplete, but mostly currently largely suited for convenient use with Standard Notes. But, this is something I'm actively working to change, and currently allocating a large amount of time to improving the documentation for the entire Standard Notes ecosystem. I've been spending so much time building and developing, that I've mostly forewent thorough documentation. But I'm doing work now to get everything caught up.

**Comment by yegortimoshenko** [comment]
I don't mind incomplete specs insofar clients are free software, which they are. I think Standard Notes is an amazing note-taking app, usability- and privacy-wise, and worthy of listing.

**Comment by Zegnat** [comment]
Note that currently the default web and desktop Standard Notes clients are no longer Free Software – such as currently [required for inclusion](https://github.com/nylira/prism-break/blob/94f6c3eb7d2ef7be3b6d782c6ba9840cc5452e28/README.md#project-inclusion-guidelines) on PRISM Break. Apart from having its source available it has gone completely proprietary on [2018-02-23 (commit `76b37d7`)](https://github.com/standardnotes/web/commit/76b37d7d53fc160dfb452f499f9feb32ed45bf10).

Discussion about this licence change is going on in standardnotes/web#189.

**Comment by yegortimoshenko** [comment]
I've evaluated Standard Notes just before the license change, in late February, and I haven't expected this to change. Sorry to hear that.

**Comment by Hillside502** [comment]
Summarizing the license bummer, only the (current) mobile apps and "collab-editor" are now open-source.
https://github.com/standardnotes

In addition, I always had my doubts about where users' data is stored.
https://iplookup.flagfox.net/?ip=34.228.118.242&host=standardnotes.org

A good app consigned to the dustbin of closed-source history!

**Comment by yegortimoshenko** [comment]
@mobitar: Licensing has been shifting around, would like to know what the current status is and if you are committed to keeping client- and server-side code under a free software license.

**Comment by Hillside502** [comment]
> read-only license

equals:-
https://en.wikipedia.org/wiki/Permission_culture

So, the extensions would be closed-source?

**Comment by mobitar** [comment]
Yes, extensions would be closed source. Read [this thread](https://github.com/standardnotes/web/issues/189) for context.
