### ISSUE TITLE
About Qwant and Brave Browser 

### ISSUE THREAD

**Issue by hrsyvg** [nylira/prism-break#1741]
Qwant search engine and Brave browser can be a safe alternative?

**Comment by Zegnat** [comment]
Qwant is mostly Bing search through a French company. I am not fully up-to-date one French privacy law, but it mostly sounds like yet-another-european-search-engine. By my reading of [their privacy policy](https://about.qwant.com/legal/privacy/) they do not store your search queries, but will store your IP address for 6 months.

Brave is discussed in #1566, if you have any new arguments for its inclusion you can take it up there.

**Comment by strugee** [comment]
@Zegnat sounds like there isn't anything really compelling about Qwant? Can we close this issue then?

**Comment by Zegnat** [comment]
@strugee, imho this can simply be closed. Didn’t want the liberty as I haven’t been able to be very active here.
