### ISSUE TITLE
keepassxc - Cross-platform KeepassX fork

### ISSUE THREAD

**Issue by rafaelrpinto** [nylira/prism-break#1744]
https://github.com/keepassxreboot/keepassxc
https://keepassxc.org/

Today my keepass2 + keefox combo stopped working again because of new versions mismatch. Looking around for an alternative I found keepassxc. 

Might be worth mentioning on the linux page instead of keepassx that requires all that mono stuff to work with browser plugins. 

Related reading: https://www.reddit.com/r/privacytoolsIO/comments/6c63i4/keepassxc_can_we_trust_it/

Cheers,

**Comment by HexwellC** [comment]
That's a great piece of software, I've been using it for a while and it's both the most secure and the most comfortable password manager out there.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Looks like the last commit to KeePassX was 8 months ago, which doesn't
bode well.  https://github.com/keepassx/keepassx/branches

Things about KeePassXC that seem worthy of further investigation
before recommending it:

> Password strength meter

Historically, these meters tend to greatly overestimate the entropy of
passwords, which can cause users to do stupid things if the UX isn't
carefully done.

> YubiKey HMAC-SHA1 authentication for unlocking databases

Admittedly I'm not familiar with the YubiKey ecosystem, but anything
that uses SHA1 is kind of suspect these days.

> KeePassHTTP is not a highly secure protocol and has certain flaw 
> which allow an attacker to decrypt your passwords when they manage 
> to intercept communication between a KeePassHTTP server and 
> PassIFox/chromeIPass over a network connection (see here and here).
> KeePassXC therefore strictly limits communication between itself
> and the browser plugin to your local computer. As long as your
> computer is not compromised, your passwords are fairly safe that
> way, but use it at your own risk!

So why is this protocol implemented?

> Add feature to download favicons and use them as entry icons

Does this feature cause a proxy leak?

Also, I notice that KeePassXC developers aren't OpenPGP-signing their
Git commits.  This isn't a regression compared to KeePassX, so it's
not really an issue in terms of replacing KeePassX with KeePassXC on
PRISM-Break.  The release tags of both KeePassX and KeePassXC are
OpenPGP-signed.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZSH6BAAoJELPy0WV4bWVw6O4QAIzY/vxDiVvYci5GG2U7aDE4
xhlAcZIT+44GZLIth+dC6fYq0GsYMtZr2r9M1x5tPZmW7b6+j6MPXdslqJ7BYUOH
ziDKJ1unqH4W9tDZPLCvAM7pDFp4fKHo3weV8Y7bUITc7nnlSSq3DO+8RFw+wr2O
LW/V+Ki8oudgZgWY6zwziNrij3Ydm8NteRRtqhUM2XODkpvwOHMbb4aDt5brJLQt
GFAJ2PkKTwp1PTlIumlL563oFVJKMypU8ZPVy3wH7cv0hZcBB9UtbrpB7BvXqVck
espM37jBw/laI7F55PHZ1q3Hn9SFd3xhMMX3OJApi0zMwLddJ1hC6YVBsPMfrKbg
IaENi5Nfa+5tNJacFteK9efwAnJG/ciOwijP6qz6ofC9VhbizNJA7es4zDZAnL70
rXGKOPWV+rprPPJfV7GwiR6SYIeTC1KCPUxHdin5J35DUNFeN73UyTe2vnAM1DS6
tdvjJL04uHMawN7v/h2+IdUKgbCb7+4oK0E/vJOdei1oBRzAi6D0P/ZlTc9CBoUh
BZXD2eDN7mV3i89++zvaqzFsGbBl+XVIwEfDozXSStXzjVUs2RtOuV3I1TJGai1x
ywUIfqOufUkK35hDR3UUpsqnzpwla6RQID3RMN/fFuTzEcOqbK8XaOyfwgRZFkfE
qkRLXP/4EFx0pLS2eg8s
=BE2Y
-----END PGP SIGNATURE-----

**Comment by Zegnat** [comment]
I have very little to say about KeePassXC, but I want to address @JeremyRand:

> > YubiKey HMAC-SHA1 authentication for unlocking databases
> 
> Admittedly I'm not familiar with the YubiKey ecosystem, but anything that uses SHA1 is kind of suspect these days.

This should not make you feel suspect, though it is easy to understand why you feel that way and you are not the first. The trick: HMAC-SHA1 is **not** SHA1.

SHA1 has (theoretical) collision attacks against it, and should be upgraded to SHA2. But HMAC-SHA1 is a message authentication algorithm using a signing key and does not suffer from known collision attacks against SHA1.

Just making sure we aren’t throwing oil on the FUD fire.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Martijn van der Ven:
> I have very little to say about KeePassXC, but I want to address
> @JeremyRand:
> 
>>> YubiKey HMAC-SHA1 authentication for unlocking databases
>> 
>> Admittedly I'm not familiar with the YubiKey ecosystem, but
>> anything that uses SHA1 is kind of suspect these days.
> 
> This should not make you feel suspect, though it is easy to
> understand why you feel that way and you are not the first. The
> trick: HMAC-SHA1 is **not** SHA1.
> 
> SHA1 has (theoretical) collision attacks against it, and should be
> upgraded to SHA2. But HMAC-SHA1 is a message authentication
> algorithm using a signing key and does not suffer from known
> collision attacks against SHA1.
> 
> Just making sure we aren’t throwing oil on the FUD fire.

Thanks for the correction, I was unaware that HMAC was unaffected by
the collision issues.  Learn something new every day....


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZSNG5AAoJELPy0WV4bWVwNg4P/3yaGaTmlesJ8eZf1dzF6249
Cq7GfF57lOP+dyEshMPD8XdEczuRNJznqpah8S10HOAeOx7n1zP2qJVZGFoYsn8y
yxC37Winayxim3fbzU3Sw/x9GucdbMhVR+oTWmOjXUSB8TDGFV3AW6VGVkFqsSEs
9mPyV6UOdczBWSn2OBekmVxmvHd+YIznKbvG7GupTMmMGh4skeegTxwlgWELUNf+
I/x3Beg8Tqsj44hJdvMFO1HRhekliRmkNzPQqidBOkGKGBlfc9l2lp+D14MSP76V
KwpiLLsU3Y8JxJdCf3QSK8julPucn5rnkbAqMKwbefzk9qFAe2527rOULceAaKqy
8dE9N2cH9HmtWgCdCoNHa4ZYs/lgMzRIDvizFbjVtQ9Oe1UqeUfsF4vM0qiZwzPq
0f/Rhhw0xt4L7jyRuiqzI73zAsNhhz0RKC5GFIX0qGK38cSiFQR/MpbZWDEDF9Q3
u22Hgcfx6uMhUhAYAdvBy1XUv88Y38aKvMWgrLeJcGQdrZNiTop4DkODhwjl90RB
SlaAY6S7CWvPpyIXqH0k5DE9b9MNaerQRFPczWwkFba9nDJpsn/uW4oqNv7uRCE9
OFDCWItrbUH2/+5p2k4D1az9KHhEam91rDFTMM59u9NsvaGue3471honxh3FIkkD
50YvgHVapSitw6+INyLO
=ygkL
-----END PGP SIGNATURE-----

**Comment by rafaelrpinto** [comment]
About KeePassHTTP:

You are only vulnerable if you run Keepassxc on a remote server an use this protocol for the communication between it and your browser, which are not encrypted. If you use chrome you will have to use the same protocol for keepassx too.

The way they prevent this problem is to restrict keepassxc to communicate only locally, which I believe is more than keepassx does.

Also consider that you need to use mono on linux to run keepassx, which I believe can expose mono related vulnerabilities. With keepassxc you dont need mono.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Rafael Pinto:
> About KeePassHTTP:
> 
> You are only vulnerable if you run Keepassxc on a remote server an
> use this protocol for the communication between it and your
> browser, which are not encrypted. If you use chrome you will have
> to use the same protocol for keepassx too.
> 
> The way they prevent this problem is to restrict keepassxc to
> communicate only locally, which I believe is more than keepassx
> does.
> 
> Also consider that you need to use mono on linux to run keepassx,
> which I believe can expose mono related vulnerabilities. With
> keepassxc you dont need mono.

I think you're confused between KeePass and KeePassX.  Everything you
said above applies to KeePass, not KeePassX.  KeePassX doesn't use
Mono, nor does it implement the KeePassHTTP protocol.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZUElFAAoJELPy0WV4bWVwO6sP/A9t6YvK5q17/eeGxiIMTvOA
XZ56YzgPHIABggclS9LtYdHGwpF6hQe6jiIxfSZhRm9Khk0fcPrplq7uo8BRymZE
lKdMexER8rbWjgticbAs4aZ1DFE7BK2EzcXEUC0EplOvEIuoblEk2StqL261oqaB
D0/xdLp1myJ2UC15R3VoJe3u2FoLP1bPSXeWp8C/KTiwka44OAbCkgcQl8m5ed1g
/4pd2X4PZnMEd21EgYT2N+rK7LOIZndb53hwRtpO3BHNqyCxPaLt1GB0ltFsCBwT
L82Sc5vpFnQB+tRBGLgrcHDlOwA30zJ2vpYJUsLR1xTIkslIBWPX6wIbQi1NKj6y
3L+on27dbhYD3weWkLFeZPFanMgeBmQXMkHiMjIyQGz1DKp8QpIAtnZpk5DSgNCP
KgK6n/zRztagXwnO+kn1YdBls6cPIDSBl2s+GmIGuZCM4MUAluRvG3ZCB0ek4l+z
4ydF1ExaU6guDyvqm/U9u8wvJQPjZVBPtQFQH+5hxgHaUKUsq84C1tG/uDsV2Y2X
J5Z0OxYEZ79ksNt4w3JcWP4JsLEuxlFB/FOPh9EBy2NLY0i8jeiQVyaeIx7ZeRx8
3slI+K2/6LTKmYeXlgCUPEbDzmBkqt6rnsgIdw+vZNgFTDFhuyt0lAtjbDaRT09Y
CqjZbhEXcAwzwX3ATtWH
=ezxA
-----END PGP SIGNATURE-----

**Comment by rafaelrpinto** [comment]
You are right :)
I thought keepassx was the same as keepass1/2.

**Comment by hasufell** [comment]
> Also consider that you need to use mono on linux to run keepassx, which I believe can expose mono related vulnerabilities.

Which ones?

**Comment by rafaelrpinto** [comment]
> Which ones?

Depends on mono's version. Here are some known vulnerabilities from previous versions: http://www.mono-project.com/docs/about-mono/vulnerabilities/

As @JeremyRand pointed out, this issue was opened mainly because I confused keepassx with keepass1/2. So I will close it to avoid polluting the issues list. If anyone believes there is more to the subject feel free to reopen it.

**Comment by hasufell** [comment]
> Depends on mono's version. Here are some known vulnerabilities from previous versions: http://www.mono-project.com/docs/about-mono/vulnerabilities/

I cannot really follow how you came to the conclusion mono is a problem. Any runtime has potential bugs, including libc, JVMs, .... Any reason we should be particularly suspicious of mono? The only runtime I know with unfixed and publicly known vulnerabilities is the Oracle java VM.

**Comment by p2635** [comment]
I was reading through this thread but have no idea why it was closed. 

Is keepasscx not recommended?

**Comment by noorbertt** [comment]
Is keepasscx not recommended?
Up

**Comment by noorbertt** [comment]
https://github.com/keepassx/keepassx/pull/204

**Comment by alerque** [comment]
I think this issue could probably be re-opened — just not for the reasons initially stated. The initial post includes several red herrings and conflates two different projects. But replacing KeepassX with KeepassXC is something we should look into. Personally I've already switched.

There are some security benefits to switching (using hardware keys in the unlock process being the major one) and there is a LOT more developer momentum and review happening on the new project. On the flip side there have been some compromises made in implementing features that if used improperly could compromise the overall security (http api, external http calls, etc.).

Neither project is in a known broken or dangerous state right now and it isn't a clear cut thing which is more secure at the moment, but with development stagnating on the original and being quite active on the community project it's only a matter of time before the only practical thing we can do is recommend the active project. The question is have there been any changes that make it unsuitable for PRISM-Break?

**Comment by hasufell** [comment]
> But replacing KeepassX with KeepassXC is something we should look into. Personally I've already switched.

My distro has even dropped KeepassX completely in favor of KeepassXC. The former also looks "sorta" unmaintained https://github.com/keepassx/keepassx/releases

**Comment by alerque** [comment]
> My distro has even dropped KeepassX completely in favor of KeepassXC. The former also looks "sorta" unmaintained https://github.com/keepassx/keepassx/releases

The developer of KeepassX has a _long_ history of not cutting releases. Even after years of development there were 3 years of alphas and 2 years of betas while we waited between 0.4 and 2.0. There was a slow trickle of devel activity he just took forever to actually release. The same was true between alphas and now between point releases. Basically if you want to run KeepassX you'd be almost crazy _not_ to build from HEAD. Which is one reason _not_ to recommend it to anybody. Half the distros that have X around are still on 0.4, another chunk are packaging XC anyway.

The status quo with a trickle of development work (ignoring community contributions and issues) is still going on, but given all the _other_ developer eyeballs abandoning it in droves and following the fork I'd say if we recommend it at all it should be KeepassXC that we recommend.

And I don't see any show stoppers for including it in PRISM-Break.

**Comment by Zegnat** [comment]
If this is being discussed in honest again, lets at least reopen this issue. As you might know, I am always a fan of replacing listings on PRISM-Break rather than adding new project <i>ad infinitum</i>. Leaving it up to the people who are more in the know about password managers to mark this as accepting PRs.

**Comment by yegortimoshenko** [comment]
I agree, we should list KeepassXC instead.
