### ISSUE TITLE
Compiler/VM/etc. recommendations

### ISSUE THREAD

**Issue by HexwellC** [nylira/prism-break#1745]
Hello,
I think prism-break project should also contain some general recommendations on languages, compilers and hardware for programmers and IT specialists.
So Microsoft is going wild. They are [including telemetry on language level](https://github.com/dotnet/cli/issues/3093) and [injecting things into bytecode](https://i.imgur.com/TiVrXyf.png) (MSVC 2015). Just think about it: we cannot be sure that dotnet binaries have no injected code. *Open-source will never guarantee you transparency *fully**.
I think there should be a page that compares compilers/VMs (There is no evidences that Oracle VM has no backdoors, but there is OpenJDK), hardware/software solutions (like RDRAND, which can contain transistor-level backdoors, should use /dev/urandom instead, see [here](http://lxr.linux.no/#linux/drivers/char/random.c#L1587)) and even mention architectural backdoors (Intel Management Engine is an explicit backdoor)

**Comment by strugee** [comment]
Anything having to do with hardware is out of scope for PRISM Break. Search the issue tracker; this has been discussed several times.

I'm not sure what you mean by this:

> we cannot be sure that dotnet binaries have no injected code.

This seems to me more like a problem with where you're getting your binaries... presumably if you get your binaries from a distribution, they'd patch the compiler to not enable this antifeature. I honestly don't know, though. This is uncharted territory, AFAIK.

Related to that I'm not really sure what you mean by this:

> Open-source will never guarantee you transparency fully.

Is there a concrete action that we can take here?

**Comment by hasufell** [comment]
At least compilers and VMs are not hardware, but the topics brought up here sound like you want to do academic security assessment of those... and I don't think we have the capacity for that. Do you?

**Comment by strugee** [comment]
@hasufell agreed that compilers generally aren't oriented towards users, and that seems antithetical to our stated goals as a project. However, we _do_ have things listed that aren't packaged in Linux distributions, and the user is expected to build them from source. That's the main reason I'm not just dismissing this as out of scope (though I could still see that argument).

**Comment by hasufell** [comment]
Well, we could list all those nice opensource tools like gcc, clang, OpenJDK. But how useful is that really? What he is suggesting is a more technical assessment:

> I think there should be a page that __compares__ compilers/VMs

I don't think that's our job.

**Comment by strugee** [comment]
@hasufell we already have comparisons. That's what the proprietary/free columns are for. I was imagining that we'd just add a new category into the existing design. Although .NET Core isn't proprietary... I guess it falls under an Ubuntu-style "not proprietary but problematic for other reasons" category

See also #1686

**Comment by strugee** [comment]
Now that I think about it though this seems like something we'd just judge projects for... i.e. if it was written with .NET we'd add a note or something. So I'm leaning towards closing this.

**Comment by hasufell** [comment]
> we already have comparisons. That's what the proprietary/free columns are for.

That's not what the TS had in mind afaiu. Proprietary vs free is a very easy distinction.

**Comment by Zegnat** [comment]
If we were to make recommendations aimed at “programmers and IT specialists” (although I don’t think PRISM Break is the place) it could make sense to give a proprietary vs free view for compilers. So people can choose a recommended compiler when they compile any of the programs listed. But really, people who choose to not download binaries and compile all their software from source are probably in a place where they can already search for compilers elsewhere.

Anything else – I would say – is clearly out of scope for PRISM Break.

**Comment by strugee** [comment]
Yeah. Closing as out of scope. Thanks for contributing to PRISM Break, @HexwellC!

**Comment by HexwellC** [comment]
Still, I think making some more notes on tool used for building programs would be a good idea. But I can agree that PRISM Break isn't aimed at "programmers and IT specialists", so yeah, out of scope.

**Comment by strugee** [comment]
@HexwellC lol, thanks. Forgot to actually hit the close button :P

**Comment by hasufell** [comment]
> Still, I think making some more notes on tool used for building programs would be a good idea.

There is a plethora of privacy oriented stuff wrt development/industry, e.g. http://pripareproject.eu/
Also search for "privacy by design".
