### ISSUE TITLE
Still confused about Protonmail

### ISSUE THREAD

**Issue by siennk** [nylira/prism-break#1747]
So, I have been looking into Protonmail, and I am just plain confused.

There have been many postings regarding issues with Protonmail, but they seem to be from two years ago. So I am not sure if the issues stated in the past have been fixed. 

And it is listed on http://prxbx.com/email/. 

So I'm just getting some mixed messages when it comes to Protonmail. 

**Is Protonmail safe or unsafe to use?**

Also, unrelated to Protonmail, http://prxbx.com/email/ states that Tutanota is unsafe to use, and it was one I was looking into. I don't see how it's unsafe though, can someone explain it to me please.

**Comment by bezcitu** [comment]
The reasons are still the same: 
**ProtonMail is a "walled garden".** Both sender and receiver have to use ProtonMail accounts to use their OpenPGP implementation (there is one exception: ProtonMail users can receive PGP-inline e-mails). This implementation is the second reason against ProtonMail: The whole **cryptography is browser-based** (which is considered insecure) and **your private key is stored on their servers**.

They provide a way to communicate with non-ProtonMail users (using symmetric encryption), however you have to share your secret key off-band via a secure channel which is quite difficult and you can only respond five times and then you need a ProtonMail account, too.

There are many other reasons against ProtonMail and they mostly remain valid (even after two years). (The same is true for Tutanota, for the sake of completeness.)

**Comment by Hillside502** [comment]
Please note the HTTPS:-
https://prxbx.com/email/

**Comment by strugee** [comment]
@bezcitu is correct.

I'm closing this issue to keep our issue tracker clean, but feel free to keep discussing.
