### ISSUE TITLE
VyprVPN

### ISSUE THREAD

**Issue by DestinFaroda** [nylira/prism-break#1751]
I've stumbled upon this VPN provider and it sounds quite convincing:
https://www.goldenfrog.com/vyprvpn
Is it recommendable and truly safe? They're sitting in Switzerland and claim to own 100% of the hardware used for VPN.

**Comment by Atavic** [comment]
Best option is to use your own private VPN.

**Comment by jimenezrick** [comment]
Yeah, it's simply one of the multiple commercial VPN offerings.

**Comment by yegortimoshenko** [comment]
VyprVPN offers a proprietary protocol (Chameleon) and promotes use of their proprietary clients.
