### ISSUE TITLE
Consider Fossdroid as possible substitute for F-Droid.

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1754]
[Fossdroid](https://fossdroid.com/) is a web frontend of F-Droid: an alternative software repository comprising only free, open source software for Android.

**Comment by hasufell** [comment]
This is not an alternative to F-Droid afaiu
https://fossdroid.com/blog/about

> Fossdroid takes its data from F-Droid and organizes the apps in an attractive Google Play-like arrangement, with the ability to view apps by what’s new / trending / most popular.

Can you point me to the resource that says it uses a different repository? Or is the title just misleading?

Also: [License is MIT](https://github.com/SnaKKo/Fossdroid-Core#license), so we don't know what runs on the servers. It even says [it's not all of the code](https://github.com/SnaKKo/Fossdroid-Core#why-core).

**Comment by Atavic** [comment]
Should the title be changed?

**Comment by hasufell** [comment]
Note that we are currently also discussing the removal of F-Droid: https://github.com/nylira/prism-break/issues/1748

**Comment by strugee** [comment]
I don't really see a compelling advantage to this, besides the fact that it's somewhat prettier (note too that F-Droid recently improved their design significantly). F-Droid may have its problems but at least there's some semblance of trust... this is just downloading binaries from a web page with no upgrade path and no meaningful signature checking. Plus, the fact that some of the backend is closed is potentially problematic.

Unless anyone disagrees with this assessment, I'd like to close this issue.
