### ISSUE TITLE
Remove Thunderbird from XMPP?

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1755]
From https://github.com/nylira/prism-break/issues/1688#issuecomment-308356717:

> I recommend removing Thunderbird. It doesn't support SRV records, causing problems for many larger servers.

If this is true we should probably remove Thunderbird from the XMPP category.

**Comment by Atavic** [comment]
[How to Make Thunderbird Chat Work with Most XMPP/Jabber Accounts](http://rmore.net/2012/09/07/how-to-make-thunderbird-chat-work-with-most-xmppjabber-accounts/) and
[Check DNS SRV records for XMPP](https://kingant.net/check_xmpp_dns/) give a working solution.

**Comment by strugee** [comment]
Those are hacks to compensate for a bad client. I don't see why we should list a bad client, even if there are workarounds.

**Comment by tailslover** [comment]
Try "Tor Messenger". It looks like Thunderbird - mail + XMPP protection.

**Comment by strugee** [comment]
Marking as accepting PRs since the links that @Atavic provided seem to indicate that the problem described in OP is indeed an issue.

@tailslover there is already an issue open about Tor Messenger; please don't pollute this issue tracker with unrelated comments :)

**Comment by mimi89999** [comment]
On top of that AFAIK it doesn't support any E2E encryption. I will submit a PR.
