### ISSUE TITLE
Include Onion Services links for projects 

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [nylira/prism-break#1757]
Inspired by another issue on a related project: https://github.com/privacytoolsIO/privacytools.io/issues/190

--------------

It would be great if we could add links to onion services for all the projects that are mentioned. I'm sure that many of you already know about what onion services are and what their privacy and security features are. 

Here's a non-exhaustive list for mentioned projects on prism-break.org:

- [ ] Tor Browser : http://expyuzz4wqqyqhjn.onion/

- [ ] searx.me : http://ulrn6sryqaifefld.onion/

- [ ] OnionShare : http://elx57ue5uyfplgva.onion/

- [ ] Qubes OS : http://qubesos4rrrrz6n4.onion/

- [ ] Debian : http://sejnfjrq6szgca7v.onion/

- [ ] Whonix : http://kkkkkkkkkk63ava6.onion 

- [ ] DuckDuckGo : https://3g2upl4pq6kufc4m.onion/

- [ ] Facebook : https://facebookcorewwwi.onion

- [ ] Riseup : http://nzh3fv6jc6jskki3.onion/

From the UX side I imagine that we could have something like this,

`---------------------------------------`                
`| ???? Whonix --------------------|` :link: `|`             
`| ???? ---------------------------|-----|`                
`| ???? VM-friendly OS... --------      |` ![](https://icons.duckduckgo.com/ip2/www.torproject.org.ico) `|`         
`---------------------------------------`               

Ok, not the best ASCI art out there but you get the idea.

**Comment by tailslover** [comment]
related: https://trac.torproject.org/projects/tor/wiki/org/projects/WeSupportTor

**Comment by strugee** [comment]
Marking as accepting PRs to do one or both of:

1. Update the data to add `onion_url` keys for these services or something
2. Update the website code to consume `onion_url` keys
