### ISSUE TITLE
Make a section on how modern hardware (Intel post 2006 and AMD post 2012) should be avoided?

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [nylira/prism-break#1758]
Before anyone points that prism-break is only about tools, let me respectfully affirm that all these tools are only effective as long as the underlying hardware is not compromised. 

This issue has not received the coverage that it needs, and I think we should at least mention it.

https://libreboot.org/faq.html#intel
https://libreboot.org/faq.html#amd

Edit: Just to be precise, it doesn't have to be an obligation "don't buy intel post /amd post... since X", we could just shed some light on this issue.

**Comment by hasufell** [comment]
> Before anyone points that prism-break is only about tools, let me respectfully affirm that all these tools are only effective as long as the underlying hardware is not compromised.

Yes, but the scope you are pulling in when you open the can "hardware" is huge, and prism-break tries to be not of anecdotal nature, but give relatively firm and transparent recommendations. Also, no one appears to eager to do all that work to create a __proper__ hardware section.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@hasufell  

> Yes, but the scope you are pulling in when you open the can "hardware" is huge, and prism-break tries to be not of anecdotal nature, but give relatively firm and transparent recommendations. Also, no one appears to eager to do all that work to create a proper hardware section.

I'm not saying that a hardware section is required, only something that sheds some light on this issue. This could be for example in the form of a warning, "All these tools are only effective as long as the underlying hardware is not compromised. However, post-2006/post-2013 Intel/AMD CPUs ....blahblah"

**Comment by hasufell** [comment]
So you want to dump all the literature on the user?

**Comment by strugee** [comment]
PRISM Break does not exist to "shed light" on issues, it exists to give actionable recommendations.

Hardware has been brought up many times before - please search the issue tracker if you want to find all the discussions we've had on this before.

> Before anyone points that prism-break is only about tools, let me respectfully affirm that all these tools are only effective as long as the underlying hardware is not compromised.

There's a fallacy here, although I'm not sure what kind. The problem is that, while you are _absolutely_ correct, PRISM Break is still *just* about tools.

We just don't have the capacity to tackle hardware. It's too difficult. Given what I've written above, I'd like to close this.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
Fair enough :)
