### ISSUE TITLE
Expand the list of tweaks to Firefox?

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [nylira/prism-break#1759]
Currently, the only tweak that is suggested is to change the default browser search engine,

> Firefox notes: This browser uses Google search by default: replace it with a more private alternative. Another debranded alternative to Firefox is Iceweasel, a browser for Debian-based distributions.

However there are **many** other tweaks that can benefit one's privacy, for example allowing `privacy.resistFingerprinting` and `privacy.firstparty.isolate` will enable some of the Tor Browser patches that have been incorporated into mainline Firefox for better fingerprinting defenses and first party isolation.

Edit: Another alternative here is to recommend using the Tor Browser for clearnet. Whonix has some nice documentation in their wiki on how to do so. 

What's the right course here?

**Comment by hasufell** [comment]
Prism-break is currently not a compendium of privacy __techniques__, but __privacy-aware free software alternatives__. Configuration etc. is generally out of scope, with a few exception we add to the Notes.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@hasufell 
If some FOSS requires some configuration changes to unlock its potential, why shouldn't it be mentioned?

In any case, the only alternative I see here is to recommend using the Tor Browser for clearnet. Whonix wiki has some nice documentation on that.

**Comment by hasufell** [comment]
> If some FOSS requires some configuration changes to unlock its potential, why shouldn't it be mentioned?

Because that usually requires its own blog post per topic.

**Comment by strugee** [comment]
Closing as this is out of scope for PRISM Break.
