### ISSUE TITLE
Add WireGuard (open-source VPN software)

### ISSUE THREAD

**Issue by jimenezrick** [nylira/prism-break#1766]
(I'm using it on my servers and it works great)

From https://www.wireguard.com/:

WireGuard is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN.

**Comment by tailslover** [comment]
> considerably more performant than OpenVPN.

Report?

**Comment by jimenezrick** [comment]
https://www.wireguard.com/performance/

4x faster than OpenVPN on throughput and even faster than IPsec on that benchmark.

**Comment by yegortimoshenko** [comment]
I think this is a good idea, to anyone in doubt, see: https://www.youtube.com/watch?v=eYztYCbV_8U

**Comment by Zegnat** [comment]
:+1:

Local-to-me VPN provider Mullvad has labelled it as [the future](https://mullvad.net/en/blog/2017/9/27/wireguard-future/) and I was very happy to see they [funded development time](https://mullvad.net/en/blog/2017/7/13/mullvad-donates-wireguard/).

**Comment by yegortimoshenko** [comment]
Mullvad itself might be worthy of listing, they are one of a very few reputable VPN providers (in my opinion, the only other one is IPredator, also local to @Zegnat :-)

**Comment by Hillside502** [comment]
Alpha Android app:-
https://play.google.com/store/apps/details?id=com.wireguard.android

**Comment by Hillside502** [comment]
@yegortimoshenko 
According to:-
https://thatoneprivacysite.net/vpn-comparison-chart/

IPredator logs timestamps, bandwidth and IP addresses.

**Comment by strugee** [comment]
https://www.wireguard.com/ says it's not ready for production use, and in pretty strong terms to boot. I'd lean towards rejecting it on those grounds but I could also see an argument for labeling it "experimental".

**Comment by Hillside502** [comment]
https://www.wireguard.com/#work-in-progress

**Comment by yegortimoshenko** [comment]
@strugee While I support labeling Wireguard as experimental, I am very skeptical about such claims. Almost always, those disclaimers mean that the author has very high standards of what should be considered to be production-ready.

Similar story with security considerations: usually, when service doesn't have any sort of description of what cryptography they use, it usually means that they don't care deeply about the subject, and we are likely to find issues there, while services that list a lot of considerations and descriptions on that subject are usually indeed secure.

Treating those claims seriously results in software developed by people with much looser standards getting preference over technically superior, and de facto, even more production-ready software.

**Comment by yegortimoshenko** [comment]
Regarding VPN specifically: alternatives to Wireguard have at least 50x times larger codebase. Unlike other VPN implementations, Wireguard is specifically designed to be easily auditable, and is under 4 KLOC: https://youtu.be/eYztYCbV_8U?t=4m41s

There are multiple Wireguard implementations: in kernel-space (C), in Go, in Rust, at least at some point there was one in Haskell, and a [Tamarin proof](https://tamarin-prover.github.io/) of the protocol:

https://git.zx2c4.com/wireguard-go
https://git.zx2c4.com/wireguard-rs
https://git.zx2c4.com/wireguard-hs
https://git.zx2c4.com/wireguard-tamarin/

I'm quite sure both OpenVPN and IPsec are so complex that writing a proof is just not feasible. Given the background of the Wireguard author (kernel security researcher), and the state of the art other than Wireguard, it does seem to me that he just has extremely high standards.

IPsec in particular is so complex that there are legitimate concerns about the spec having backdoors.
