### ISSUE TITLE
Add andOTP 2FA for android

### ISSUE THREAD

**Issue by chikenchik** [nylira/prism-break#1771]
This is a fork of the great OTP Authenticator app. It's open sourced, encryption (openkeychain) and lock screen supported awesome app.
https://github.com/flocke/andOTP

**Comment by jumpwe-movim-eu** [comment]
➕💡

**Comment by 2SI3NX** [comment]
I agree, why isnt this listed yet? 
BTW the official link is redirected to: https://github.com/andOTP/andOTP

**Comment by Zegnat** [comment]
I have also been looking at moving from FreeOTP to andOTP. Not in the least because the latter allows me to pull a back-up in case I am moving phone. Not there yet, so I cannot speak of experience, but I have been hearing good things.

**Comment by Primokorn** [comment]
I use andOTP for several weeks now (+OpenPGP).
We can lock to the app through a PIN code, password or fingerprint.
Custom logos for well-known services
Backups can be signed
Backup/Restore tested several times and it works very well.

**Comment by 2SI3NX** [comment]
Nice..seems like the way to go and should definitely be listed!

**Comment by yegortimoshenko** [comment]
andOTP is significantly better than FreeOTP, I'd suggest replacing the current recommendation.

**Comment by Zegnat** [comment]
I too have switched fully from FreeOTP to andOTP, no complaints so far. (For what it is worth.)
