### ISSUE TITLE
Home Surveillance Recommendations

### ISSUE THREAD

**Issue by p2635** [nylira/prism-break#1773]
Sorry if this is the wrong place to post.

Does anyone have any recommendations for home surveillance systems?

Specifically I'm based in the UK.

**Comment by Atavic** [comment]
[ZoneMinder](https://github.com/ZoneMinder/ZoneMinder/) (Linux)

**Comment by Hillside502** [comment]
Open Source ZoneMinder Alternatives - AlternativeTo.net
https://alternativeto.net/software/zoneminder/?license=opensource

openHAB
http://www.openhab.org/
