### ISSUE TITLE
Add Open Root Server Network (ORSN) -> DNS

### ISSUE THREAD

**Issue by disklamer** [nylira/prism-break#1777]
Open Root Server Network (ORSN) is a network of Domain Name System root nameservers for the Internet. ORSN root zone information is normally kept in synchronization with the "official" root nameservers coordinated by ICANN. ORSN Public DNS Servers are operated by the community of ORSN, providing Domain Name System access freely for everyone, without any limitation. ORSN public DNS servers respect privacy and do not log usage.

**Comment by Zegnat** [comment]
This is pretty interesting. Could you provide some links for your claims so we do not have to go and search for logging policies etc?

**Comment by Hillside502** [comment]
"Are DNS queries saved on the ORSN servers?

No. All ORSN root servers are running without  query logs. The public nameserver, that are offered to the ORSN project,  should be configured equally. But the ORSN cannot influence this part  of configuration."

ORSN | Open Root Server Network - FAQ
http://www.orsn.org/en/faq/

Open Root Server Network - Wikipedia
https://en.wikipedia.org/wiki/Open_Root_Server_Network

Alternative DNS root - Wikipedia
https://en.wikipedia.org/wiki/Alternative_DNS_root

ORSN | Open Root Server Network - Technical Information
http://www.orsn.org/en/tech/

ORSN | Open Root Server Network - General Information about this Project
http://www.orsn.org/en/

**Comment by disklamer** [comment]
I discovered ORSN some time ago when i was looking for a safer way to browse the net. I quickly became a sponsor and started dedicating my own colocated servers and resources to the network. I can honestly say privacy is at the forefront of the project since that's the main reason why it was created. It also explicitly mentions PRISM and other government surveillance. My goal is to increase the global presence of ORSN which includes a footprint in the USA.

_After the revelations of Edward Snowden and reports in the media about the extent of total surveillance by intelligence agencies in the United States (NSA with Prism) and the Britsh EU partner (GCHQ with Tempora) now we only learn about the degree of observation and control by this government run agencies._

_ORSN will have no technical possibility to disable surveillance or fight against them. But we as Internet users (community) can distance us from this system (which record our daily communications and processes) and build or own private DNS-server network which will be controlled by the community in Europe and other parts of the world._

[http://www.orsn.org/en/](url)
