### ISSUE TITLE
Steem (Social Network? Reddit-like)

### ISSUE THREAD

**Issue by fervi** [nylira/prism-break#1778]
Steem is blockchain network (like bitcoin)

In Steem works steemit (something like reddit), busy.org (also), chainbb (forum-like interface). I create my own bash.org site (www.steemdash.tk). There is also instagram (I don't know address :/) or (very beta) Youtube-like software

**Comment by Zegnat** [comment]
I am not sure how this is more free than e.g. Reddit itself..?

**Comment by fervi** [comment]
Aw, reddit is also open source :P 
But Steem is decentralized, anti-censorship etc.

**Comment by FexelFox** [comment]
@fervi Reddit is subject to FISA requests, and so is locked under the PRISM umbrella.

**Comment by FexelFox** [comment]
@fervi plus, Steemit has the issue of it taking longer and longer to actually have an account generated, so it limits the intake of how many people can actually join at any given time. https://steemit.com/steemit/@retailtrader/account-creation-delays-on-steemit

**Comment by strugee** [comment]
At this point I don't remember when or why RetroShare was included in PRISM Break but according to us it's peer-to-peer. So I don't see how this has an advantage over RetroShare, especially since they have an issue with account signups - and if we add any more social networks I worry that section will start to get bloated like the OS section used to be.

**Comment by FexelFox** [comment]
@strugee not to mention that Mastodon is far more decentralized than steemit.

**Comment by FexelFox** [comment]
Also Steemit inc. is based in the USA, so they would have to comply with information requests unless they moved to another country.

**Comment by strugee** [comment]
Closing given the reasons I mentioned and the legal concerns @FenelFox mentioned.

**Comment by vyp** [comment]
[psa reddit is now proprietary](https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/)

**Comment by FexelFox** [comment]
@vyp Reddit has always been under the watch of the 14 eyes.

**Comment by vyp** [comment]
True

**Comment by hasufell** [comment]
![stallmanwasright](https://shop.spreadshirt.com/image-server/v1/designs/12460201,width=178,height=178/rms-was-right.png)

**Comment by fervi** [comment]
@FexelFox Steemit is only client, you can use other - busy.org for example. Of course the problem is with law, but you can't remove posts from database (blockchain), so everybody can create own steemit (or other) website on localhost
