### ISSUE TITLE
Review openmailbox.org

### ISSUE THREAD

**Issue by MiCoArcher** [nylira/prism-break#1782]
I am not certain of the current standing of openmailbox.org with prism-break.
All I have is this: https://github.com/nylira/prism-break/issues/294

About 12 hrs ago, if not less, the service became mostly pay-to-use.
Changes impacted:
- Use of external mail clients(no longer available in the free version of the mail)
- Use of aliases(no longer available in the free version), thus effectively rendering most current mailbox addresses unavailable, which in turn prevented their former owners from receiving mail and being able to reply to letters that were already received

The changes came with solid three days of 0 uptime and without any prior warning.

**Comment by vyp** [comment]
There's also #461, #852 and #854. #294 also mentions #157. Additionally, it's not listed on the site, so by default it should be assumed to not be recommended. So what are you suggesting?

**Comment by MiCoArcher** [comment]
Aha, I see.
I was not certain of whether it was listed on the site or not.
Now I am content.
The issue is closed.
