### ISSUE TITLE
Add Bitwarden

### ISSUE THREAD

**Issue by juanda-097** [nylira/prism-break#1785]
Code: https://github.com/bitwarden
License: AGPLv3
Web site: https://bitwarden.com/
Alternative to last pass

_Enviado desde mi Motorola XT1650 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Hillside502** [comment]
@juanda-097 
Thumbs up on your own post???

**Comment by Hillside502** [comment]
bitwarden - Free Password Manager Reviews - AlternativeTo.net
https://alternativeto.net/software/bitwarden--free-password-manager/reviews/

**Comment by Zegnat** [comment]
I wouldn’t use what they are offering on their website.

1. It looks like it **requires** storing your vault with them in the cloud.
2. This seems to depend on encryption within the browser:
   * You can use their browser extension, but you would need to be sure there are no more compartmentalise bugs like #1743 with Mailvelope or you risk leaking your entire vault’s content to every other extension.
   * You can also get access to your vault through their website, though that means you have to trust them not to read your password when you are entering it **on their site**.
      
     Fun fact: their online portal (`https://vault.bitwarden.com/`) loads external JavaScript from `ajax.googleapis.com`, `maxcdn.bootstrapcdn.com`, `js.braintreegateway.com`, and `js.stripe.com` for me. Meaning I need to trust that none of those hosts will try to access my vault? (Maybe they load a different set of resources when logged in, but this doesn’t bode well.)

The only way I would recommend this is if you could somehow get it to run locally. Which probably requires a new fork of the project, and you going through it to make sure it doesn’t use any external JavaScript libraries.

**Comment by Hillside502** [comment]
@Zegnat 
Also google-analytics.com

**Comment by Zegnat** [comment]
> Also google-analytics.com

That’s probably loaded through JS then. I block JavaScript on unknown websites and it does not show in my request log. Which would be why I missed it. Not that it matters, with `ajax.googleapis.com` already on the list.

**Comment by kspearrin** [comment]
Hey guys,
I am the lead developer on bitwarden. I was pointed here by one of our users.

> It looks like it requires storing your vault with them in the cloud.

> The only way I would recommend this is if you could somehow get it to run locally. Which probably requires a new fork of the project, and you going through it to make sure it doesn’t use any external JavaScript libraries.

This is true today, however, in the current release we are working on at the moment we are packaging everything up so that users can easily host this themselves on Windows and Linux distributions via Docker containers.

**Comment by FexelFox** [comment]
Honestly better off using Keepass. @Zegnat mentioned that it requires the passwords be stored on the cloud, so that means you don't have executive control over how they are stored and you must trust a third party to store them (rather unsafe like Lastpass). If you could get it to run locally, that would be great. In the meantime, using Keepass in conjunction with either Syncthing or a self-hosted Nextcloud server would be better in terms of having control over your own data. (personally prefer the nextcloud method, not hard to set up in a VM on a workstation at home.)

**Comment by kspearrin** [comment]
@FexelFox @Zegnat It is now possible to easily deploy and host the entire bitwarden backend yourself using Docker. No more cloud dependencies. See https://help.bitwarden.com/article/install-on-premise/

3 minute demo: https://www.youtube.com/watch?v=MmfL4zL-xtM

**Comment by FexelFox** [comment]
Cool, but does it require internet access at all times? @kspearrin

**Comment by kspearrin** [comment]
@FexelFox The answer is that it depends on what you're trying to do:

- Use the web vault? of course, yes you need internet to use a website.
- Use the browser extension or mobile apps? No, you only need internet access if you are trying to sync new data. You can remain offline indefinitely and still use the applications in read-only mode.

And yes, as mentioned in that help article, self-hosting is currently in beta and it is advised not to store real data in them yet until everything becomes stable. But shortly this will be a first-class feature of the product.

**Comment by yegortimoshenko** [comment]
Requires proprietary dependencies (at least SQL Server 2017, I'm not sure about status of .NET Core 2.x SDK). Would like to close this similar to #1571.
