### ISSUE TITLE
Hardware Section (Phones/Tablets/Laptops/Desktops)

### ISSUE THREAD

**Issue by Kaboosh** [nylira/prism-break#1787]
The best software is all for nought, after all, if your hardware chips are bugged (such as with Intel AMT/ME).

I've been doing research into this for a while and the best I've found are Coreboot (open source BIOS/firmware) and a company called Purism (http://puri.sm who break the AMT/ME on laptops as part of their build process).

Anyone have any other ideas or research they can share in this area?

**Comment by strugee** [comment]
Hardware recommendations have been discussed several times now on this issue tracker and are out of scope for PRISM Break. I'd encourage you to search for these old issues and read the discussions there.

Thanks for contributing to PRISM Break :)

**Comment by hasufell** [comment]
I think this warrants a section in the readme that explains the __scope__ of prism-break explicitly. Maybe issues as these will pop up less then.

**Comment by strugee** [comment]
@hasufell #1685 maybe?

**Comment by strugee** [comment]
Regardless feel free to open a new issue, there's definitely room for improvement here

**Comment by vyp** [comment]
Although I mean it could be argued that coreboot at least is software in some part, so I wouldn't be opposed to mentioning it somehow.. any opinions on that?

**Comment by Kaboosh** [comment]
That's a shame.  In today's environment I think software solutions alone may be insufficient to avoid unwarranted spying and privacy violations.  If Coreboot qualifies then please consider the ME_CLEANER python script as well (https://github.com/corna/me_cleaner).

**Comment by strugee** [comment]
> That's a shame. In today's environment I think software solutions alone may be insufficient to avoid unwarranted spying and privacy violations.

I think most of us agree. But that doesn't change the fact that PRISM Break doesn't have the bandwidth for it, unfortunately.

I also would support a "boot software" section or something, with Coreboot/Libreboot et. al. Since that seems to have a sufficiently small scope.

**Comment by strugee** [comment]
Looks like that's been raised before: #842

**Comment by Kaboosh** [comment]
It mentions Coreboot.  What about ME_CLEANER (link in my post above)?  Do you think that might have a place in PRISM-break as well?

**Comment by strugee** [comment]
@Kaboosh can you file a new issue?

**Comment by strugee** [comment]
But search for duplicates first
