### ISSUE TITLE
Add date to audit tags

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1792]
Audits happen at a specific point in time, on a specific state of a project. We should put that into perspective.

**Comment by yegortimoshenko** [comment]
We collect this as metadata: https://github.com/nylira/prism-break/blob/03f120628608716c60a87db52a63500f6f508cab/source/db/de-projects.json#L1180

It is rendered in audit notes: https://github.com/nylira/prism-break/blob/c8402ba51ce5833edddaa23b025ae6884f808b2e/source/views/projects/mixins.jade#L108

This seems to resolve the issue. If not, please tell.
