### ISSUE TITLE
Remove or replace Self-Destructing Cookies, is no longer maintained

### ISSUE THREAD

**Issue by MER-C** [nylira/prism-break#1796]
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

"This add-on is no longer maintained. It is incompatible with Firefox 55+ and this will never change. Also, it will not be rewritten as a WebExtension." Firefox 55 is the current version.

The closest replacement I could find is [Cookie Auto-Delete](https://addons.mozilla.org/en-us/android/addon/cookie-autodelete/), but this cannot flush LocalStorage yet due to a limitation in the WebExtension API.

**Comment by vyp** [comment]
@MER-C Thank you for reporting this!

I'm personally satisfied enough with cookie autodelete to add the accepting PRs label to replace self destructing cookies with cookie autodelete. If anyone else finds any concerns with cookie autodelete, of course please comment about it. 🙂

> but this cannot flush LocalStorage yet due to a limitation in the WebExtension API

They have an issue open about this, https://github.com/mrdokenny/Cookie-AutoDelete/issues/44, which has a firefox (webextensions) blocker: https://bugzilla.mozilla.org/show_bug.cgi?id=1388428. It seems like it might be resolved sooner or later. 🎉

**Comment by JustOff** [comment]
JFYI: [Cookies Exterminator](https://github.com/JustOff/cookies-exterminator) still works with FF55 (including LocalStorage), but I have no plans to rewrite it usings WebExtensions API.

**Comment by Hillside502** [comment]
Open Source Self-Destructing Cookies Alternatives - AlternativeTo.net
https://alternativeto.net/software/self-destructing-cookies/?license=opensource

**Comment by juanda-097** [comment]
### Cookie-AutoDelete
Source code: [MIT](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete)
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

**Comment by Hillside502** [comment]
The correct spelling is "Cookie AutoDelete"

Cookie AutoDelete :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/
https://addons.mozilla.org/en-us/android/addon/cookie-autodelete/

**Comment by hasufell** [comment]
except cookie autodelete does not work

**Comment by Hillside502** [comment]
@hasufell 
Self Destroying Cookies is Custom License --- **closed source**
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/versions/

**Comment by hasufell** [comment]
@Hillside502 I mailed the developers about it

wrt cookie autodelete, there are tons of users reporting it not working:
* https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/75
* https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/157
* https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/188
* https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/281
* https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/289

**Comment by kehugter** [comment]
@hasufell 

From v0.1041's code and some data I could gather:

- there's no real information about the devs in `dirtylittlehelpers.com` whois
- the hardcoded subdomain `https://addon.dirtylittlehelpers.com` has an invalid cert issued to `addons.synatix-gmbh.de`
- `synatix-gmbh.de` works on ads and big data: https://www.synatix.com/
- there's a hardcoded url that 404s: `df-srv.de`
- contact information in whois for `df-srv.de` has an `abilicom.de` email address
- `abilicom.de` redirects to www.contactimpact.de. Contact Impact sells aggregated tracking data
- the extension likes to call home. I see no reason for this kind of extension to do so
- the extension, ironically, sets a cookie for itself
- `synatix.com`, `df-srv.de` and `contactimpact.de` are all registered on the same physical German address (and the extension has lots of comments in German)

The extension doesn't look evil now, but I wouldn't let it auto-update and I certainly won't install it.

**Comment by hasufell** [comment]
Interesting dig @kehugter 

Since I work for an advertisement company myself, I would be rather confused why someone would engage in that kind of deceptive play in order to potentially get cookies from privacy-aware users. The user base is so small that we don't really care. And it would possibly even be against european law.
