### ISSUE TITLE
Mozilla ponders making telemetry opt-out, 'cos hardly anyone opted in

### ISSUE THREAD

**Issue by rafaelrpinto** [nylira/prism-break#1801]
[Mozilla ponders making telemetry opt-out, 'cos hardly anyone opted in](https://www.theregister.co.uk/2017/08/24/mozilla_considers_move_to_opt_out_telemetry_for_firefox/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BcUrXIGICSsaNd4T8n2HRwQ%3D%3D)

> Most controversial is the idea that the data collection let Mozilla compile a browser-side “top 100” of sites users visit. As developer David Teller explains, there is a “considerable bias” between users who okay telemetry collection and those who don't, which makes it hard for developers to optimise the browser for “websites that matter to our users”.

Since Firefox it's one of the few browsers prism break recommends, we should keep a an eye on how this develops.

For anyone else that wants to express discontent, here is the official thread: https://groups.google.com/forum/#!topic/mozilla.governance/81gMQeMEL0w

**Comment by Atavic** [comment]
Related: https://github.com/ghacksuserjs/ghacks-user.js/issues/219

**Comment by 2SI3NX** [comment]
Im starting to lose trust in firefox as well. This issue is similar: https://github.com/nylira/prism-break/issues/1789

What is a better privacy focused browser besides Waterfox?  Is Waterfox the only and best alternative?

**Comment by hasufell** [comment]
> What is a better privacy focused browser besides Waterfox?

https://github.com/nylira/prism-break/issues/1311 https://github.com/nylira/prism-break/issues/1516 https://github.com/nylira/prism-break/issues/1673

How does inox check whether it doesn't phone home: https://github.com/gcarq/inox-patchset/issues/64#issuecomment-287914076

**Comment by Atavic** [comment]
Palemoon is close to old Firefox and focused on privacy:
https://github.com/MoonchildProductions/Pale-Moon

**Comment by DestinFaroda** [comment]
SeaMonkey?
It consists of a Mozilla browser and Thunderbird which is very comfortable. Besides, it's much more stable than Crashfox/Freezefox and has a classical GUI you can work with.

**Comment by hasufell** [comment]
> SeaMonkey?

https://www.seamonkey-project.org/releases/seamonkey2.48/

> SeaMonkey 2.48 uses the same backend as Firefox and contains the listed Firefox 51.0.3 security fixes".

:>

**Comment by strugee** [comment]
@hasufell but presumably that's just Gecko, not any of the telemetry stuff? Dunno though.

**Comment by 2SI3NX** [comment]
The thing about SeaMonkey that im a bit weary about, is it integrates both emails and browser so if (lets say hypothetically) the browser part gets infected somehow, wont that affect your emails too?

**Comment by Atavic** [comment]
It's like having both browser and mail client always opened. BTW a hack that cares to go from gecko (browser engine) to mail accounts covers a very little population. As an hacker, once I got into the browser, I wouldn't mind looking at mails. Do you fear your mails are under peril? Look at phishing mails and social engineering scams in incoming mail.

**Comment by yegortimoshenko** [comment]
> Palemoon is close to old Firefox and focused on privacy: https://github.com/MoonchildProductions/Pale-Moon

They have Google ads on their site. You can't even reliably download the browser without being tracked.

**Comment by strugee** [comment]
According to https://wiki.mozilla.org/Telemetry/FAQ this is still opt-in on the release channel. Kinda thinking we should close?

**Comment by alerque** [comment]
Changes is Firefox are definitely something we should keep an eye on, but I don't think we need this issue to do it. If something actually changes then lets re-convene. In the mean time I think we have agreed on no-change from our side unless something actually changes on their side. Less open issues would be better if we've agreed they are not needing either more discussion or action.

**Comment by Hillside502** [comment]
> They have Google ads on their site. (Palemoon)

Even worse, "We use responsible ad services to keep your visit to our websites a safe and uninterrupted one."

`googlesyndication.com` "responsible"  LOL

**Comment by yegortimoshenko** [comment]
This has not been implemented so closing.
