### ISSUE TITLE
What about disroot.org?

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1803]
Disroot.org is based on Nextcloud. They offer free space (4GB) and a lot of services. All server are encrypted. One place for multiple solutions. I don't know nothing similar. I like it.
In my opinion is a good prism-break tool(s), but I'm not an expert.

**Comment by Hillside502** [comment]
https://disroot.org/

https://github.com/privacytoolsIO/privacytools.io/issues/312

**Comment by baimafeima** [comment]
Would make sense to have them listed under `Cloud Service Provider` as well.

**Comment by 1fallmanager** [comment]
the disroot.org backend is opensource (nextcloud with many usefull addons), also the communication inside the disroot.org team is public. the disroot.org services with mail, cloud, cal+card-dav, newsreader, projectmanagement and some more is a very good solution when you want to leave google service! You need only register mail+pass (no phonenumber) and there a no problems to connect with tor-ip.

One of few services i spend some monero because i use the services with a good feeling!

**Comment by XIncognito10** [comment]
Any update on adding this?

**Comment by cyanotex** [comment]
I personally would like to see this website added.

**Comment by yegortimoshenko** [comment]
They host Riot for chat, which is a quite bad decision (see #1936). I think activist platforms should strive to only ever store encrypted data. They also use Lufi for encrypted file sharing, which is by the same author as Lutim, which had major cryptography weaknesses: https://github.com/nylira/prism-break/issues/875#issuecomment-369903704 Perhaps I'm biased, I might check Lufi.

This somewhat comes off as Disroot not deeply understanding software that they host.

I think this is what Riseup is very good at, even email is encrypted with the account password, most non-essential headers are stripped, their XMPP pretty aggressively enforces E2E. They use Up1 for encrypted file sharing which we also recommend. Micah (one of Riseup birds) is also the author of OnionShare and Bitmask, and Riseup generally seems very knowledgeable in privacy/security aspects of software that they host.

**Comment by XIncognito10** [comment]
I used to use riseup, but my main issue is that theyre hosted in the US

**Comment by yegortimoshenko** [comment]
I don't really understand being over-focused on that :-) Most of the other places in the world have surveillance states too. US is definitely not the worst in that respect: freedom of speech is decent, and there are no key disclosure laws. The same things cannot be said about most places in Europe.

**Comment by Hillside502** [comment]
Key disclosure law
https://www.privacytools.io/#kdl

Key disclosure law - Wikipedia
https://en.wikipedia.org/wiki/Key_disclosure_law

Global Mass Surveillance - The Fourteen Eyes
https://www.privacytools.io/#ukusa

Internet censorship and surveillance by country - Wikipedia
https://en.wikipedia.org/wiki/Internet_censorship_and_surveillance_by_country

**Comment by hieu-van** [comment]
Found 2 problems with Disroot:
* No account activity log.
* No 2FA.

Still, adding it needs much consideration.
