### ISSUE TITLE
Add Delta Chat

### ISSUE THREAD

**Issue by respel** [nylira/prism-break#1804]
From the project website - 
> Delta Chat is a project that aims to create a messaging app that is completely compatible to the existing decentral email-infrastructure.

Website  - https://delta.chat

**Comment by Hillside502** [comment]
Please change this issue title to "Delta Chat"

**Comment by Hillside502** [comment]
The messenger - Delta Chat
https://delta.chat/en/

Why Delta Chat? Your Advantages. - Delta Chat
https://delta.chat/en/features

Standards used in Delta Chat - Delta Chat
https://delta.chat/en/standards

deltachat/deltachat-android: Email-based instant messaging for Android.
https://github.com/deltachat/deltachat-android

Introducing Autocrypt: Encrypted E-Mail for Humans — Autocrypt 0.9.0dev1 documentation
https://autocrypt.org/en/latest/

**Comment by jumpwe-movim-eu** [comment]
Delta chat falls back to not-encrypted.  How is this a good idea?

**Comment by yegortimoshenko** [comment]
I think Delta Chat should be included.

**Comment by Hillside502** [comment]
Excellent rapid/frequent development cycle!
https://delta.chat/en/changelog

**Comment by alerque** [comment]
I'm not convinced here. I don't see how this helps against PRISM-like surveillance issues that much. Email as a protocol leaks information like a sieve. While _Delta Chat_ may not be seeing or collecting meta data, that doesn't mean that nobody is or can. In this case everybody can and is.

Meta data leaks aside, end-to-end encryption seems to be an optional addon that requires extra setup.

**Comment by yegortimoshenko** [comment]
@alerque Delta Chat specifically leaks about as much as Signal does.

**Comment by alerque** [comment]
@yegortimoshenko Can you confirm my understanding that E2E requires extra setup over the default installation?

**Comment by yegortimoshenko** [comment]
if you're chatting with an Autocrypt-capable client (Mailpile, Thunderbird + Enigmail, or another DeltaChat) there's no setup involved. See: https://delta.chat/en/help#what-do-i-have-to-do-to-activate-the-end-to-end-encryption
