### ISSUE TITLE
Namecoin metadata is outdated

### ISSUE THREAD

**Issue by JeremyRand** [nylira/prism-break#1809]
As was alluded to in https://github.com/nylira/prism-break/issues/200#issuecomment-42620823 , Namecoin's official website is now https://www.namecoin.org/ .  The website listed by PRISM-Break redirects to that URL.

The logo listed by PRISM-Break is also outdated; the current logo is at https://github.com/namecoin/namecoin-graphics/blob/master/svg/namecoin-coin.svg (`.png` versions are available in that repo if you prefer).

The source code link and license link listed by PRISM-Break are outdated; they point to the old Namecoin 0.3.80 repo (based on Bitcoin 0.3.x), which is EOL.  Probably it makes more sense to simply link to https://github.com/namecoin/ for the source code, since there are multiple repos under that organization (in particular, namecoin-core and ncdns are both highly relevant repos).  I'm not sure how you'd prefer to list the license, since different repos are under different licenses (Namecoin Core is MIT, ncdns is GPLv3+).

Cheers!

-Jeremy Rand (Lead Application Engineer at Namecoin)

**Comment by vyp** [comment]
Probably just link to the core license. Thanks for opening this issue. 🙂
