### ISSUE TITLE
LEDE firmware

### ISSUE THREAD

**Issue by 2SI3NX** [nylira/prism-break#1813]
Should this be part of Routers firmware?

**Comment by quantumpacket** [comment]
As far as I am aware LEDE and OpenWRT are merging and the process has already begun. So it would be pointless to add LEDE when OpenWRT is already on there.

https://www.theregister.co.uk/2017/05/10/openwrt_and_lede_peace_plan/

**Comment by yegortimoshenko** [comment]
LEDE has been merged into OpenWrt: https://www.lede-project.org
