### ISSUE TITLE
Get rid of extensions that won't support Firefox 57+

### ISSUE THREAD

**Issue by RoseTheFlower** [nylira/prism-break#1815]
Self-Destructing Cookies is already mentioned [here](https://github.com/nylira/prism-break/issues/1796).

RAS is also [no longer maintained](https://github.com/dillbyrne/random-agent-spoofer#readme) and will not work under Firefox 57 that will come out on November 14.

And while we're at it, the Disconnect extension is also no longer relevant because their malware and spyware filters are included in Firefox and uBlock Origin (under the 3rd party filters).

**Comment by mimi89999** [comment]
What should be done exactly? I already removed `Self-Destructing Cookies`.

**Comment by Hillside502** [comment]
@mimi89999 
The remaining non-57 compatible add-ons to remove are:-
```
Mailvelope
Random Agent Spoofer
Request Policy
```
(Disconnect **is** compatible --- relevance debatable)

**Comment by alerque** [comment]
* Random Agent Spoofer is officially discontinued. I'm submitting a PR to remove it.
* Mailvelope [is supported](https://www.mailvelope.com/en/blog/mailvelope-2.0-web-extension) and was even before FF 57 came out.
* Disconnect is also comparable. I tend to agree it's usefulness is limited given the overlap with other addons but that should probably be discussed in a separate issue as it's categorically a different kind of thing that removing an unsupported addon.

**Comment by 2SI3NX** [comment]
@alerque yes RAS needs to be removed. But any idea what there is to replace it?
How about https://github.com/tarampampam/random-user-agent ?
