### ISSUE TITLE
Add PrivateBin (pastebin alternative)

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1816]
https://github.com/PrivateBin/PrivateBin

Related to old https://github.com/nylira/prism-break/issues/217 but the remarks there don't make a lot of sense afais. This is self-hostable, encrypted, zero-knowledge for the hoster and allows a password to protect the paste.

**Comment by Hillside502** [comment]
PrivateBin
https://privatebin.info/

PrivateBin/PrivateBin: A minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted in the browser using 256 bits AES.
https://github.com/PrivateBin/PrivateBin

Open Source Self-Hosted PrivateBin Alternatives - AlternativeTo.net
https://alternativeto.net/software/privatebin/?license=opensource&platform=self-hosted

**Comment by yegortimoshenko** [comment]
I've reopened all 8 issues you've just closed because all still seem valid. If you don't want to receive updates anymore, could you unsubscribe instead?
