### ISSUE TITLE
Add Uruk GNU/Linux

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1817]
Uruk GNU/Linux

https://urukproject.org/dist/en.html

I think it can be added, bacause, as reported in the homepage:
- Is a libre distro (it "follows the Free System Distribution Guidelines", "is currently based on the Trisquel GNU/Linux core")
- is simple for the final user, it has a simple interface and "the most common software for popular computing tasks" and "the Update Manager assures similar ease-of-use for software updates. "
- you cau install .deb as well as RPM packages
- it has an easy command for intall programs from sources
- you "can simulate popular package managers' commands" , so you can use command from most popular package managers of the most popular distros

**Comment by Hillside502** [comment]
Uruk is derived from Trisquel which, in turn, is derived from Ubuntu.

Ubuntu has previously been rejected:-
https://github.com/nylira/prism-break/search?q=ubuntu&type=Issues&utf8=%E2%9C%93

**Comment by strugee** [comment]
@geplus is there a compelling advantage to Uruk in terms of privacy/security? We just recently cleaned up the OS section and I don't want it to get cluttered again. Given that and the fact that this is based on Ubuntu, as @Hillside502 mentioned, I'm inclined to close this.

**Comment by geplus** [comment]
1) The fact that the distro derived from Ubuntu means nothing: open-source means you can modify and redistribute the software, turning the code into something else.
Ubuntu derived from Debian Testing, but Ubuntu is not Debian, they are not the same thing (Debian is approved by Prism-Break's team).
Trisquel and also Uruk are 100% libre, they don't have any of the "bad" Ubuntu code, and can be considered different from Ubuntu.

2) Advantage of Uruk:
- 100% libre code, this mean zero proprietary code, that can hypothetically spy or infect your PC, and the users can't accidentally install proprietary code, because it's not included in the repos.
It's more secure than Fedora, that have "certain kinds of nonfree firmware" in its kernel ( see https://www.gnu.org/distros/common-distros.html )
- Easy to install/update/manage for the newbies
- .deb and .rpm  packages compatible, this means lots of software
- " with Uruk GNU/Linux building software from source is very easy. Just type in the terminal:
u-src followed by the file you want to build. For example: u-src src.tar.gz " . Compiling opereations are very easy for newbies
- "Uruk GNU/Linux comes with Package Managers Simulator. This program can simulate popular package managers' commands. This means that you can install, uninstall, update, and remove packages with any package manager you wish." Again is very easy using Uruk if you are a newbie or even if you are coming from another distro.

**Comment by strugee** [comment]
> Trisquel and also Uruk are 100% libre, they don't have any of the "bad" Ubuntu code, and can be considered different from Ubuntu.

In the past we have rejected Trisquel because they don't actually rebuild packages from source and in fact pull lots of `.deb`s from Ubuntu infrastructure, which makes us uncomfortable. If that's changed I'd love to reevaluate though - I'd encourage you to search the issue tracker so you understand the issues at play better :)

> It's more secure than Fedora, that have "certain kinds of nonfree firmware"

Anyone who _really_ wants to avoid all proprietary firmware can install Debian. You're right thought that this isn't mentioned on the website - filed #1818 to track that.

I still don't see any compelling advantages in terms of privacy or freedom. Mainstream distros will have more support and come with graphical tools for managing packages, making package management on the CLI irrelevant.

**Comment by hasufell** [comment]
> 100% libre code, this mean zero proprietary code

Same true for debian, not a unique feature

> Easy to install/update/manage for the newbies

True for any mainstream distro

> .deb and .rpm packages compatible, this means lots of software

You can do that pretty much on any distro as well, if you know how. I also suspect this might not be a very clean feature, but that's just a guess from 5 years of packaging experience.

> with Uruk GNU/Linux building software from source is very easy

That's also true for Fedora (and partly debian).

> Uruk GNU/Linux comes with Package Managers Simulator

Not an interesting feature for privacy.

**Comment by strugee** [comment]
Closing as I haven't seen a compelling reason to add this distro and as noted above, there are several disadvantages.
