### ISSUE TITLE
Note that Fedora ships proprietary firmware

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1818]
As noted in https://github.com/nylira/prism-break/issues/1817#issuecomment-333405956, Fedora ships proprietary firmware in their repositories. We should maybe add a real short sentence/half-sentence about this in the Notes section.

**Comment by hasufell** [comment]
https://fedoraproject.org/wiki/Firmware#Packaging_guidelines

**Comment by yegortimoshenko** [comment]
Perhaps we shouldn't support misconception that operating systems with blobs are less free: https://github.com/nylira/prism-break/issues/1663#issuecomment-369924182.

**Comment by yegortimoshenko** [comment]
I'd like to remove "help wanted" label until we decide that this is the way to go (this hasn't been established yet in a discussion, I think).
