### ISSUE TITLE
Reconsider A/I inclusion?

### ISSUE THREAD

**Issue by RoseTheFlower** [nylira/prism-break#1821]
I've been using the A/I email service for a while, and I believe the guys stand for good things but the recent events remind us how terrible they are at keeping the servers secure. 

Back in 2004 the servers were compromised, and it [took the admins a year](https://www.autistici.org/ai/crackdown/) to realize that every message passed through them may have been read.

More recently, a similar thing happened. [This September the A/I team said](https://cavallette.noblogs.org/2017/09/9123#breach17-eng) that another breach had allowed the attackers to fully access an admin's account. The post asked every user to change their passwords, recovery questions and reset 2FA.
Yesterday, a new blog post [said](https://cavallette.noblogs.org/2017/10/9194): "If you logged into autistici.org to read your mail via web in the last two months, you should consider your passwords virtually compromised", to add to the issue above, and the admins asked that the users change their passwords again.

They also continue suggesting to not keep anything on the servers and use GPG, but whoever uses encryption for every message might as well use gmail or any other popular email service, benefit from higher uptimes and unlimited space.

**Comment by anthologist** [comment]
All services would be a mess when attacked, if they're living a bad moment it doesn't mean they will not be reliable anymore. Nobody could be listed or suggested.
"They also continue suggesting to not keep anything on the servers and use GPG" this is suggested by everybody, if seriously concerned about privacy.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
A/I leaked their data 3 times. It's a red flag and user should evacuate immediately.

**Comment by anthologist** [comment]
Riseup has been compromised too, plus it's USA-based. So we should remove both and keep only Kolab?
How do you know if others are currently compromised and they just don't know it?
This is a complex topic.

**Comment by Atavic** [comment]
A/I has been around for a long time (15 years) and recently got some problems (maybe due to higher usage and the same support as when it started). They were early providers of services that respect their users’ privacy and the origins of the project is Italy.

**Comment by yegortimoshenko** [comment]
More than a year ago A/I appeared to use a 64-bit key for their VPN service (#1599):

> "WARNING: this ciphers block size is less than 128 bit (64 bit) Consider using a -cipher with a larger block size." open vpn for android app alert.
