### ISSUE TITLE
Add Peerio (dupe)

### ISSUE THREAD

**Issue by timatron** [nylira/prism-break#1827]
https://github.com/nylira/prism-break/issues/1243

Issue 1243 should be reopened, it seems reasonable to add Peerio now.

**Comment by Atavic** [comment]
https://github.com/PeerioTechnologies/

**Comment by Piktori** [comment]
Why it should be after this ?

![capture-decran-2016-01-17-06 24 53](https://user-images.githubusercontent.com/33253097/32224080-461b5584-be40-11e7-8a96-8355a52e5139.png)

**Comment by Hillside502** [comment]
Why the image and no link(s)?

**Comment by Piktori** [comment]
I'm just asking and the source is in french so I was thinking it was useless to post the link.
Personally when  I read this kind of stuff. I have some difficulties to trust corporation and think like "Ok let's go it looks cool even if there's some backdoors in" w
I was wondering "How they can set backdoor in an open-source software ?" I think somebody's gonna audit the code and reveal the trap. So it will be over for them.

Source :https://korben.info/le-mauvais-etat-desprit-de-peerio.html

**Comment by yegortimoshenko** [comment]
Issues described in #1243 still apply, we don't recommend Chromium browsers and Peerio is only available as an Electron application on the desktop.
