### ISSUE TITLE
[URGENT] Parabola and Trisquel GNU systems still MISSING!

### ISSUE THREAD

**Issue by hd-scania** [nylira/prism-break#1828]
Why is our free OS list still missing for our notable GNU systems, Parabola and Trisquel, even their kernels are free, but under your list, Debian (no contrib or nonfree), Fedora (no nonfree repo), FreeBSD, they are still tolerant to nonfree kernels, which is still led to PRISM watching thru the nonfree drivers and firmware. Unlikely, GNU systems like Parabola and Trisquel notably, you are EVEN NEVER possible under any watching, due to the free kernels disabling EVERY nonfree backdoors.

**Comment by Hillside502** [comment]
urgent?  our?

**Comment by hd-scania** [comment]
@Hillside502, do you remember what RMS has warned us what are problematic and how much from nonfree software?

**Comment by Hillside502** [comment]
Richard Stallman - Wikipedia
https://en.wikipedia.org/wiki/Richard_Stallman

**Comment by hd-scania** [comment]
In fact he has endorsed the GNU systems thru GNU and FSF I told us, namely Parabola and Trisquel.

**Comment by strugee** [comment]
Parabola was removed because it's based on Arch which is a pretty niche distro and didn't really have compelling advantages in terms of privacy or usability over the other options in the list. Trisquel was removed because they reuse binaries from Ubuntu.

Remember that PRISM Break is about quality, not quantity.

**Comment by hasufell** [comment]
> they are still tolerant to nonfree kernels, which is still led to PRISM watching thru the nonfree drivers and firmware

Kernel deblobbing can be done on any distro and pretty much any kernel: https://linux-libre.fsfla.org/pub/linux-libre/releases/

It's simply a script you run. I agree it's a bit awkward that the distros we recommend don't really have an option during installation or so to enable a deblobbed kernel. Recommending forks of debian/arch is, however, also awkward. And in the end, this is just a usability issue, not an actual technical one.

**Comment by strugee** [comment]
I thought Debian separated the blobs into nonfree years ago? Such that if you didn't enable nonfree during installation you'd get a deblobbed kernel?
