### ISSUE TITLE
Offer a Tor Onion Service

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1831]
We should serve PRISM Break over a Tor Onion Service in addition to the clearnet https://prism-break.org.

If @nylira wants to spend some CPU cycles generating a vanity onion URL, I'd suggest going for the prefix `prism`.

**Comment by JoaoPortugal** [comment]
Or just go crazy and make the new onion address ( https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions ) that will look like: ​http://vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion that should provide superior security for the next years. Not easy to record, I fully agree, but people won't memorize it, they will just cut/ paste it somewhere, and will provide all the security improvements from right now for the future to come.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
Add your onion to this tpo wiki when done :)
https://trac.torproject.org/projects/tor/wiki/org/projects/WeSupportTor
