### ISSUE TITLE
Syncthing's discovery server is USA-located!

### ISSUE THREAD

**Issue by Hillside502** [nylira/prism-break#1834]
How's this for an entry in my firewall logs?

Hostname | discovery-v4-2.syncthing.net |   | ISP | Digital Ocean, Inc. (AS14061)
-- | -- | -- | -- | --
Continent | North America |   | Flag |  
Country | United States |   | Country Code | US (USA)
Region | NJ |   | Local time | 18 Nov 2017 16:50 EST
Metropolis* | New York |   | Postal Code | 07014
City | Clifton |   | Latitude | 40.833
IP Address | 45.55.230.38 |   | Longitude | -74.131

https://iplookup.flagfox.net/

Hypothesis:-
Syncthing is untrustworthy because it uses USA-located services --- wide open to US government surveillance.

**Comment by strugee** [comment]
Syncthing is peer-to-peer. If this server really is just for discovery, I don't really see a big problem. It's unideal but I certainly don't think it's worth taking it off the list for.

**Comment by Hillside502** [comment]
If it's just for discovery, it still soaks up IP info and whatever else like a sponge --- it's a war out there!

**Comment by Zegnat** [comment]
Syncthing runs certain infrastructure to enable the peer to peer network by default. All documented on [their infrastructure page](https://docs.syncthing.net/dev/infrastructure.html). This includes the default relay pool server `relays.syncthing.net` (see documentation on [relaying](https://docs.syncthing.net/users/relaying.html) and [the `relayServer` option](https://docs.syncthing.net/users/config.html#options-element)) as well as a number of discovery servers (`discovery-v[46]-[123].syncthing.net`).

For the discovery servers, I think you have to set `globalAnnounceEnabled` to `false` if you do not want to make your device known. Or you can use `globalAnnounceServer` to set up your own server. (Again, see [the configuration documentation](https://docs.syncthing.net/users/config.html#options-element).) People want to be able to easily find their servers so it makes sense to have included this. Compare it to the announce a BitTorrent client makes to a tracker, necessary to make first contact with other nodes.

Could they have defaulted to false on these things? Yes. Would that have made people complain more about setting up Syncthing? Probably also yes.

If you have multiple devices and want them to easily be able to announce their presence in the network, but do not want to rely on Syncthing’s discovery servers, it is actually really easy to [run your own](https://docs.syncthing.net/users/stdiscosrv.html).

**Comment by alerque** [comment]
It's been a while I used Syncthing last (and honestly I miss it) it allowed you to use your own discovery server or make manual connections without one. Assuming this is still the case at most I would include a warning about this aspect of the setup, but a US based discovery server with no other role in the function of the product is hardly one of the more major problems in our listings.

**Comment by strugee** [comment]
Marking as accepting PRs since it seems like we'd be fine resolving this with a small note about running your own discovery server
