### ISSUE TITLE
prism-break.org's server is apparently Ubuntu

### ISSUE THREAD

**Issue by palaboy** [nylira/prism-break#1835]
According to ssl server test you are using ubuntu server
https://www.ssllabs.com/ssltest/analyze.html?d=prism-break.org

![prism-break org-ubuntussl-11 20 2017](https://user-images.githubusercontent.com/2505495/32994039-aa66c8c8-cd9c-11e7-82be-8bc6ac4d7c6f.png)

**Comment by strugee** [comment]
Ubuntu has been discussed extensively before - search closed issues in this issue tracker.

Not sure if we really _need_ to do anything about the website hosting, though it's definitely unfortunate. Leaving open to track that issue.

**Comment by Hillside502** [comment]
https://prism-break.org is running on a DigitalOcean droplet in Singapore.

Distros other than Ubuntu were/are available from the inception of PRISM Break!
https://www.digitalocean.com/products/compute/

Using Ubuntu is a major piece of "do as I say, not as I do".

I rest my case.

**Comment by Atavic** [comment]
Related to https://github.com/nylira/prism-break/issues/1471

**Comment by alerque** [comment]
Is this site the only thing hosted on that droplet?

**Comment by Atavic** [comment]
Do you mean Digitalocean? That IP address is hosting two domains.

**Comment by Atavic** [comment]
Do you mean Digitalocean? That specific IP address is hosting two domains.

**Comment by Hillside502** [comment]
https://reverseip.domaintools.com/search/?q=prism-break.org
