### ISSUE TITLE
Firefox starts adding ads within the browser

### ISSUE THREAD

**Issue by cristianarbe** [nylira/prism-break#1842]
So apparently Mozilla has decided to include in its code content from a TV show/game called Mr. Robot mostly in the Nightly build but some users have also detected it in the normal release:

https://www.reddit.com/r/firefox/comments/7jh9rv/what_is_looking_glass/
https://wiki.mozilla.org/Firefox/Shield/Shield_Studies/Queue
https://ubuntuforums.org/showthread.php?t=2380114

The ad is opt-out instead of opt-in and does not inform the user about what is it doing, only a "cute" explanation without really saying what does it do.

Also more ads hidden in the browser:

https://gfycat.com/DishonestDiscreteAfricanfisheagle

**Comment by beerisgood** [comment]
Shame on mozilla to include more and more crap like this

**Comment by Sa-Ja-Di** [comment]
Considering Mozilla's recent development in the last few years to kill all what was unique and special and replace it with generic Google Chrome similar - from removing UI customization towards adding Chrome extension technology... - this is just another step of "advancing" seen from their point of view.

Mozilla believed once in "your browser - your way" - now it is "our browser - our way".

The days where Mozilla loved user integrity are long gone.

**Comment by Hillside502** [comment]
Open Source Mozilla Firefox Alternatives - AlternativeTo.net
https://alternativeto.net/software/firefox/?license=opensource

**Comment by Atavic** [comment]
Not new, it appeared and automagically uninstalled itself in the past, see:
https://github.com/pyllyukko/user.js/issues/319

As @Hillside502 says, find an alternative.

**Comment by cristianarbe** [comment]
Maybe [Icecat](https://www.gnu.org/software/gnuzilla/)?

**Comment by beerisgood** [comment]
@cristianarbe: Looks like no Windows support.
I recommend Pale Moon

**Comment by LigH-de** [comment]
Or [Pale Moon](http://www.palemoon.org/), maybe even [Basilisk](http://www.basilisk-browser.org/).

**Comment by cristianarbe** [comment]
> @cristianarbe: Looks like no Windows support.

You might be kidding me.

**Comment by RoseTheFlower** [comment]
Based on what I've read on this, there's no difference between the issue and the reason Ubuntu and its derivatives are not included on PRISM BREAK, as the argument for excluding Ubuntu has always been the lack of trust.

**Comment by Zegnat** [comment]
I have been hearing the weirdest things being brought up about telemetry and SHIELD after this, so it definitely warrants looking into what is *actually* happening.

1. I have heard that anyone who has installed Firefox as supplied by Debian Unstable has been unaffected completely, as “Data reporting is disabled for this build configuration”. If you are using an operating system recommended on Prism Break, chances are you are not even affected by any of this.
2. I have also been shown that the telemetry configuration option (in `about:config`) is locked to being enabled on the beta and nightly channels of Firefox. In this case it means that no matter if you uncheck things in `about:preferences#privacy` the browser is still going to participate in telemetry things. This feels extremely bad.

Also note that Mozilla has always documented [the SHIELD program](https://wiki.mozilla.org/Firefox/Shield) to include both opt-in and opt-out (web extension based) studies. They have just always handled it much better than this week. Hopefully they will be changing their policies internally, as I have seen several Mozilla contributors talk about on Twitter.

Regarding replacing Firefox with one of the many forks out there: this comes up every once in a while.

The main issue with the forked Firefox browsers has always been whether they can keep up with security patches. If anyone wants to look into how quickly Firefox updates have historically been imported to those different forks and start a thread to get one included in Prism Break that would be neat.

If you personally want to use a fork because you are in love with XUL and do not like how its use has been minimised in newer releases. Or because you dislike the “Chrome extension technology” (which, BTW, isn’t Google technology. [The specification](https://browserext.github.io/browserext/) is developed by [a W3C Community Group](https://www.w3.org/community/browserext/) and edited by a Microsoft employee). Those are all valid reasons, but can not be the main reason for Prism Break in my opinion.

**Comment by cristianarbe** [comment]
I still find kind of odd the continuous bashing to Ubuntu because the lack of trust in a couple of incidents to now defend Mozilla who's actually been messing with their users for a few months. Saying that on the release you recommend it hasn't been implemented so you're secure is definitely not an argument following past conversations here, as we're talking about trust in the developers of the software, not about the release that you're currently using.

Personally, I now expect anything from Mozilla. Yesterday was Google, today is Mr. Robot. Who assures you that the next week they won't be supporting [insert a mainstream company here].

In any case, if you have a reason as to why this was the last incident and sh*t like this won't happen again (and it won't happen in the stable release) I will be glad to hear it.

**Comment by Atavic** [comment]
@christianarbe https://github.com/privacytoolsIO/privacytools.io/issues/375

**Comment by cristianarbe** [comment]
Glad to know privacytools has also taken it into consideration.

I've been having a look at the Firefox alternatives today. Watefox seems to be the one with the largest user based and from their site:

> -     Disabled Encrypted Media Extensions (EME)
> -     Disabled Web Runtime (deprecated as of 2015)
> -     Removed Pocket
> -     Removed Telemetry
> -     Removed data collection
> -     Removed startup profiling
> -     Removal of Sponsored Tiles on New Tab Page
> -     Locale selector in about:preferences > General

Looks like it's Firefox with the stuff that we wouldn't like. Been browsing with it today and seems to work fine. I can't say about how fast they pull the security fixes compared to the other alternatives, maybe someone else can provide some insight on this.

On the other side, as I mentioned previously there is IceCat, but the user base may be alarmingly small plus, you know, it's FSF, so that means it will break every site that is not completely free.

**Comment by Atavic** [comment]
Mozilla had an EME-Free version of firefox, up to version 52.0.1:
http://ftp.mozilla.org/pub/firefox/releases/

Last Icecat for windows seems version 38.8.0:
https://ftp.gnu.org/gnu/gnuzilla/

Waterfox seems a little CPU hungry (problem reported only by users with many tabs opened).

I'm an happy user of both Palemoon and K-meleon. Pale-moon is like old firefox and security aware. With tools like PM Commander and it's own adapted addons (for those that doesn't work from AMO) you can still have the previous usability of Firefox.

:+1: K-meleon is the lightest one. 

You can find other options on Sourceforge, as one called Light.

**Comment by cristianarbe** [comment]
> Last Icecat for windows seems version 38.8.0:
> https://ftp.gnu.org/gnu/gnuzilla/

If you're going to browse on an OS with continuous non-opt-out telemetry why would you even use free software?

> 👍 K-meleon is the lightest one.
As far as I know K-meleon is only for Windows.

**Comment by hasufell** [comment]
> As far as I know K-meleon is only for Windows.

And the last release from 2015, seriously?

**Comment by 253OCt6A9IAt1UkH** [comment]
[Midori](http://midori-browser.org/) might also be another non-firefox based alternative. Privacy-wise:

> As of Midori 0.4.4 you can add a hidden option to ~/.config/midori/config like so:
> 
> site-data-rules=-google.com,-facebook.com,!bugzilla.gnome.org,+bugs.launchpad.net
> 
>     Values prefixed with “-” are always blocked
>     Values prefixed with “+” are always accepted
>     Values prefixed with “!” are not cleared in Clear Private Data
>     No wildcards.
>     LSO, local storage and application caches ignore all policies.
> 
> The feature is currently experimental and will change in future versions.
> 
> The Advertisement Blocker can be activated under Extensions. It uses the same lists as Adblock Plus. URLs are blocked completely and never loaded. Lists can be added through the option button on the right side in the extension list.

From what I know, the elementary os team is under the browser so there are security patches being released. Small user base though.

**Comment by hasufell** [comment]
Midori is unstable crap, search for "crash" and "segfault" on the bug tracker. I used it for 1-2 years sporadically, it never worked reliably, broke my config and kept crashing.

**Comment by beerisgood** [comment]
As @Atavic wrote, see https://github.com/privacytoolsIO/privacytools.io/issues/375

**Comment by 253OCt6A9IAt1UkH** [comment]
> Midori is unstable crap, search for "crash" and "segfault" on the bug tracker. I used it for 1-2 years sporadically, it never worked reliably, broke my config and kept crashing.

Agreed, I just don't really know any other "decent" non-firefox.

Honestly, I'd go for some Firefox compiled without telemetry/fishy studies/ads, whichever is the most popular.

**Comment by Atavic** [comment]
Correction to my previous [post](https://github.com/nylira/prism-break/issues/1842#issuecomment-352262216): Firefox 56.0.2 has an EME-Free version, too.

@hasufell K-Meleon 76 RC2 is one year old. I contain/lock it. On windows you can use old versions and spoof them as the latest, greatest firefox with Fiddler web proxy by Telerik.

@cristianarbe Gnuzilla is a fine project, sadly left behind, with some good addons.

**Comment by cristianarbe** [comment]
Appart from a trust issue is also a security issue, from: https://www.reddit.com/r/firefox/comments/7kjn4y/security_is_a_real_issue_of_the_looking_glass/

> Shield Studies must be approved by
> 
>     a Firefox Product Manager
>     Data Steward
>     Legal
>     QA
>     Release Management
>     AMO review
>     a member of the core Shield Team.
> 
> So either none of those people though it's a stupid idea or the process for the deployment was not followed.
> 
> Now onto the malice case: Someone deployed this extension without following the procedures. What does that mean?
> 
> It means a rogue employee or a hacker can deploy an extension to a whole Firefox user base at any moment. Without any safe checks, without peer review, without signoff.

**Comment by anthologist** [comment]
@Atavic the latest version is EME-free too, they're keeping it up to date. ;)
https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.2/

**Comment by Atavic** [comment]
:+1: Plus for it. But minus because isn't very easy to find it (could be my fault).

**Comment by beerisgood** [comment]
@anthologist but is this Version without remote addon install or without telemetry?

**Comment by anthologist** [comment]
@beerisgood no, that one is just EME-free. You can remove/edit any firefox setting (including telemetry and remote install) in the internal config. There are already some privacy-oriented user.js file around github.

**Comment by DestinFaroda** [comment]
Several months ago, I switched to the WebKit-based Brave browser.
https://brave.com/
It blocks ads, trackers, phishing and fingerprinting by default. The CEO is Brendan Eich, the developer of JavaScript and one of the Mozilla founders.

**Comment by Hillside502** [comment]
@DestinFaroda 
Brave browser · Issue #1566 · nylira/prism-break
