### ISSUE TITLE
Scuttlebutt

### ISSUE THREAD

**Issue by orenwf** [nylira/prism-break#1844]
Beakerbrowser & Dat - beakerbrowser.com/docs/inside-beaker/
Scuttlebut - https://www.scuttlebutt.nz/

**Comment by strugee** [comment]
Split Beakerbrowser off into a separate issue.

**Comment by yegortimoshenko** [comment]
Scuttlebutt supports Tor: https://www.scuttlebutt.nz/faq/misc/tor.html
