### ISSUE TITLE
Beakerbrowser

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1845]
Ref #1844, cc @orenwf

https://beakerbrowser.com/docs/inside-beaker/

**Comment by yegortimoshenko** [comment]
Any peer-to-peer technology in this space at current moment is unlikely to be privacy-respecting: IPFS, even when used over Tor, leaks all sorts of metadata, including local network topology, and I think external IP address as well. Beaker seems to not support anonymization at all. See: https://groups.google.com/forum/#!topic/beaker-browser/qVojGU2d4rw

This seems to be outside of scope (similar to torrent clients). Additionally, I don't think this is mature enough to recommend, at least not yet.
