### ISSUE TITLE
Enhancement: Add a news or changelog section to the website

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1846]
I often browse the PRISM break catalog to find new recommended projects, but wouldn't it be cool if the site offered a section where recent changes (new recommendations and revoked recommendations) are listed, ideally together with a short description of their reason for being included/excluded?

I'm sure I'm not the first person to come up with that idea, but I didn't find any previous posts about it.

**Comment by Atavic** [comment]
A simple *changelog.md* may fit well.

**Comment by strugee** [comment]
Yeah, that could work. Idk if it would add too much overhead. I guess not if we just keep it to adds/removals and other major changes?

**Comment by Atavic** [comment]
Seems the best option to me, as seen in other repos.

**Comment by yegortimoshenko** [comment]
I do not see advantages of `changelog.md` over running `git log`.

**Comment by Zegnat** [comment]
> I do not see advantages of `changelog.md` over running `git log`.

You don’t have to do a checkout to read a change log :wink:

**Comment by hasufell** [comment]
check out https://github.com/skywinder/github-changelog-generator

**Comment by yegortimoshenko** [comment]
If you don't want to checkout, you can use web interface: https://github.com/nylira/prism-break/commits/master

**Comment by strugee** [comment]
http://keepachangelog.com/en/1.0.0/ see "can change logs be bad?"

**Comment by Hillside502** [comment]
> Who needs a changelog?

People do. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how.

**Comment by yegortimoshenko** [comment]
I think we should strive for better commit logs in that case, although I think it's quite good as it is: https://github.com/nylira/prism-break/commits/master

I don't think it's realistic to request more than that. I just don't see anything more we can do here: even if we were to have a changelog file, it would have pretty much the same stuff in it.

**Comment by yegortimoshenko** [comment]
If someone believes that changelog file is important, or better than git log, I propose them to make a changelog file that encompasses all changes in 2018 (there are only a few) and compare the result with [GitHub log](https://github.com/nylira/prism-break/commits/master).

Even if it will be marginally better (and I don't think so, at least because git log includes hyperlinked issue numbers) it will be a lot of duplicated work for maintainers (additionally to maintaining multiple locales) and likely not every significant change will get into changelog file anyway. Git is good in that it forces every change to be properly logged.

**Comment by strugee** [comment]
@yegortimoshenko I don't think anyone was proposing _all_ changes. Just project inclusion and removal.

**Comment by yegortimoshenko** [comment]
Oh, that changes everything. Then I'm all for it :-)

One way to implement this log is to add new keys to JSON object (say, `removed_at`, `removed_reason`, `added_at`). Then we could generate the log page.

**Comment by strugee** [comment]
Meh. Seems like a lot of code complexity when a Markdown file (which GitHub has good rendering for) would suffice. Plus people know to look for stuff in CHANGELOG.md files.

**Comment by yegortimoshenko** [comment]
Approach that I've proposed would allow translating changelog to each locale without much effort, and people who don't know or care enough to visit GitHub would be able to see what's new and what has been removed more easily, with icons, descriptions and stuff.
