### ISSUE TITLE
Rotonde

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1848]
Ref. https://github.com/nylira/prism-break/issues/1845 https://github.com/Rotonde

While beaker deals with sites, rotonde deals with feeds, see: https://louis.center/p2p-social-networking/

**Comment by Hillside502** [comment]
Beaker is deprecated
https://github.com/Rotonde/beaker

For the general concept:-
Webring - Wikipedia
https://en.wikipedia.org/wiki/Webring
