### ISSUE TITLE
Certificate expiration

### ISSUE THREAD

**Issue by varenspukis** [nylira/prism-break#1849]
Certificate expired today the 27th december 2017, at 07:56

**Comment by Hillside502** [comment]
What is it with the management of PRISM Break?

History does --- indeed --- repeat itself!

**Comment by nylira** [comment]
Sorry, it should be resolved.

**Comment by Hillside502** [comment]
Surely, it's closed **when** it's fixed.

**Comment by strugee** [comment]
@Hillside502 this IS fixed. Please remember this is a volunteer project. Complaining does nothing but add negative energy.

**Comment by Hillside502** [comment]
If you keeping repeating the same mistakes, don't expect anything else.

**Comment by Hillside502** [comment]
https://www.brainyquote.com/quotes/harry_s_truman_153785
