### ISSUE TITLE
Open Source Hardware U2F Devices

### ISSUE THREAD

**Issue by 0verk1ll** [nylira/prism-break#1860]
For extra security on user accounts, U2F hardware tokens are potentially easier to use than an app like FreeOTP.
I don't know if you plan on mentioning hardware devices or not. [U2F Zero](https://www.u2fzero.com/) and [Nitrokey](https://www.nitrokey.com/) are open source hardware/software tokens that are worth looking into.

**Comment by Hillside502** [comment]
USB Dongle Auth List
http://www.dongleauth.info/

**Comment by strugee** [comment]
> I don't know if you plan on mentioning hardware devices or not. U2F Zero and Nitrokey are open source hardware/software tokens that are worth looking into.

We're not, sorry. Hardware is out of scope for PRISM Break.
