### ISSUE TITLE
Add PureOS to Suggested Operating Systems

### ISSUE THREAD

**Issue by 0verk1ll** [nylira/prism-break#1861]
[PureOS](https://www.pureos.net/) is a 100% FLOSS OS that is designed to protect users freedom. It has a beautiful GNOME 3 interface and is very easy to use. It is [recommended by the Free Software Foundation](https://www.gnu.org/distros/free-distros.html).

**Comment by hasufell** [comment]
Seems it's just a derivate of debian with different pre-installed packages. Any real reason to use it over debian?

**Comment by strugee** [comment]
Well, Purism is supposed to be security-focused. They recently turned on [AppArmor](https://puri.sm/posts/pureos-apparmor-activated-by-default/), for example. Plus it's apparently a [rolling release distribution](https://forums.puri.sm/t/apparmor-in-pureos/2125/2).

That being said this is still kinda niche and I don't really see the point of adding it. It has _some_ advantages, but not really compelling ones. I'd say just go with Subgraph if you really want to have that kind of maximum protection.

**Comment by hieu-van** [comment]
Honestly I don't see many differences between PureOS and Debian.
> Plus it's apparently a rolling release distribution.

Debian Unstable is a rolling release distribution too

**Comment by hasufell** [comment]
> Debian Unstable is a rolling release distribution too

Not fully. It's used for testing purposes, which also means they may freeze versions for that reason.

**Comment by yegortimoshenko** [comment]
I don't think PRISM Break should promote vendor-specific reskins of larger distributions. System76 also did that with [Pop!_OS](https://system76.com/pop). This practice further fragments Linux community and packaging effort, which is already in a bad state, and adds a lot of short-lived names which makes it harder for users to identify systems that they are working with.

**Comment by hasufell** [comment]
> This practice further fragments Linux community

What? We don't want to be windows, thanks.

**Comment by yegortimoshenko** [comment]
Recommending lesser forks is a security issue, that applies to, say, Firefox forks as much as distribution forks. There is an inherent cost in doing that.

The problem with Windows is that it's proprietary. I'm not sure what do you mean by saying that.

**Comment by strugee** [comment]
PureOS, AFAICT, is more than just a reskin. But I still think we shouldn't recommend it. Unless anyone can come up with a compelling advantage PureOS has, I'm going to close this issue.

**Comment by strugee** [comment]
Actually this has been sitting for a month already so I'm just gonna close now. If anyone has objections holler and I'll reopen.

**Comment by hasufell** [comment]
> Recommending lesser forks is a security issue, that applies to, say, Firefox forks as much as distribution forks. There is an inherent cost in doing that.

Correct. But that is orthogonal to your initial comment about "linux community fragmentation".

**Comment by yegortimoshenko** [comment]
@strugee I think I came up with an objection that might warrant reconsidering this issue: PureOS will be featured as default operating system on Librem 5 phones shipping next year. Given that we only list Replicant in mobile OS list, which is unfortunately semi-abandoned, this would seem to be a valuable addition.

**Comment by strugee** [comment]
Is the proposal here to include it in the mobile OS section? If so that seems at least somewhat sensible. But I would be strongly against cluttering up the desktop OS section again.

**Comment by yegortimoshenko** [comment]
Sure, I only propose PureOS for the mobile phone section. I am against clutter and would prefer PRISM Break to present only a few best options instead of becoming a free software directory.

This is blocked until Librem phone release, we could evaluate when that happens.
