### ISSUE TITLE
Is PasswdSafe vulnerable?

### ISSUE THREAD

**Issue by deniss-s** [nylira/prism-break#1865]
Today after reflashing my phone and installing all apps from scratch noticed that F-Droid warns about some issues with PasswdSafe.
> We found a vulnerability with PasswdSafe. We recommend uninstalling this app imediately.

In ANTI-FEATURE section following a listed:
 * The upstream source code is not entirely free
 * KnownVuln
 * DisabledAlgorithm

Didn't find anything on F-Droid forum. Does anyone know something about vulnerability?

**Comment by Zegnat** [comment]
Hmm, it seems surprisingly hard to confirm where the `KnownVuln` tag is coming from. The tag is probably automatically assigned by the F-Droid repository, as it isn’t explicitly declared in [the PasswdSafe metadata file](https://gitlab.com/fdroid/fdroiddata/blob/f2a2940a9714afbc44a2abe050b151466df89e13/metadata/com.jefftharris.passwdsafe.txt).

The only [two (documented) scans](https://f-droid.org/wiki/page/AntiFeature:KnownVuln) are:

* “current APK has a weak MD5 signature aka [AntiFeature:DisabledAlgorithm](https://f-droid.org/wiki/page/AntiFeature:DisabledAlgorithm)”
* “uses a version of OpenSSL that has known vulnerabilities”

Take your pick, I guess? 🤔

This also doesn’t tell us if the OpenSSL feature(s) used by PasswdSafe are affected by the known vulnerabilities at all. Overall I find it a very weird tag by F-Droid. See also, [their discussion on the matter](https://gitlab.com/fdroid/fdroidclient/issues/1070).

**Comment by Hillside502** [comment]
Keepass2Android Password Safe
https://github.com/PhilippC/keepass2android

bypasses the clipboard, but seems to be available only from Google Play:-
https://play.google.com/store/apps/developer?id=Philipp+Crocoll+(Croco+Apps)

**Comment by alerque** [comment]
@Hillside502 Please keep issues on topic. You posted this blurb on several issues (#1695), If you're proposing including it, it should be in an issue by itself. I don't see how the information is forwards the discussion of the other issues. Thanks.

**Comment by Hillside502** [comment]
blurb?

Sarcasm is the lowest form of wit!
