### ISSUE TITLE
Drop blank and otherwise untranslated strings from localizations

### ISSUE THREAD

**Issue by alerque** [nylira/prism-break#1868]
Per [this comment](https://github.com/nylira/prism-break/pull/1854#issuecomment-358544725) I was going to drop all empty keys in translation files (since they inherit from English better if not present than if blank).

Additionally and probably in the same PR I'll try to drop "translated" strings that are actually just copies of the English without being properly translated.

Perhaps also both these could generate a warning in the lint step so that they don't get so out of whack again.

**Comment by Zegnat** [comment]
> Can you even assign issues to non-collaborators?

Yes :wink: But I think only if they have commented within the issue.
