### ISSUE TITLE
Add XprivacyLua

### ISSUE THREAD

**Issue by jj-pietro** [nylira/prism-break#1872]
This is an Android app which can avoid any application from reading your personal data by feeding fake/empty values.
From their github:

> Really simple to use privacy manager for Android 6.0 Marshmallow and later (successor of XPrivacy).
> Revoking Android permissions from apps often let apps crash or malfunction. XPrivacyLua solves this by feeding apps fake data instead of real data.

Github link: https://github.com/M66B/XPrivacyLua
License: GPLv3
Website: https://lua.xprivacy.eu
Support: https://forum.xda-developers.com/xposed/modules/xprivacylua6-0-android-privacy-manager-t3730663

**Comment by Atavic** [comment]
Rooted phone + Xposed framework is needed for it.

**Comment by alerque** [comment]
I don't think this is a good idea. I mean the concept has it's uses — somebody with a very specific threat model or, for example, a security researcher trying to evaluate other software in a sandbox environment might find this very valuable. But as a general purpose recommendation for broad public  adoption I think it's a bad idea. Needing root would be one, the fact that the result will be brittle and difficult to tell when it stops working is another, and that it encourages running apps that have other privacy issues at all is another. Better just not to run apps that crash if they can't drag net your private data in the first place.

**Comment by Primokorn** [comment]
@Atavic root is *not* required.
What is required:

* Unlocked bootloader
* Custom recovery (TWRP)
* Xposed framework + installer

I use this app (I also used XPrivacy) and it's likely the best privacy app on Android.
Very good recommendation for people who know how to manipulate a device. Don't give this advice to your grandma for example :)

**Comment by Hillside502** [comment]
@Primokorn 
Looking at the dev's apps on Google Play:-
https://play.google.com/store/apps/developer?id=Marcel+Bokhorst
I don't see an executable (excluding license keys) that **doesn't** need Root.

**Comment by Primokorn** [comment]
@Hillside502 Many Xposed modules don't require root since they use Xposed framework capacities.
https://forum.xda-developers.com/showpost.php?p=75096801&postcount=31

FYI I have Magisk Manager to manage root permissions and none of my Xposed modules are listed in the 'su' logs.

**Comment by Atavic** [comment]
@Primokorn is technically right. My point is that all these requirements for the new xPrivacy are very demanding for a project like prism-break. I use xPrivacy myself and agree it's a good tool.

Problem here is to explain on-the-site how to unlock bootloader, load TWRP on device etc.

**Comment by hasufell** [comment]
We recommend Replicant, is that less intrusive/complicated? err.

**Comment by pietropacchio** [comment]
I don't think replicant can feed fake data to apps without using anything else and anyway it supports very few devices

**Comment by hasufell** [comment]
> I don't think replicant can feed fake data to apps

That was not what I was saying. I was responding to the concerns that this is "too complicated".

**Comment by pietropacchio** [comment]
Oh ok, sorry. I misunderstood

**Comment by Atavic** [comment]
@hasufell Replicant [how-to](https://redmine.replicant.us/projects/replicant/wiki) lists ADB (CLI commands) while Xposed usually is loaded with TeamWin's Recovery Project (TWRP) that has a GUI.

TWRP includes ADB commands, but for this issue they do the same thing. If one gets Replicant OS, then he can even load xPrivacy.

XprivacyLua is the new version for Android 6.0

**Comment by yegortimoshenko** [comment]
Xposed is very intrusive, and requiring root is a security hole.

**Comment by Primokorn** [comment]
Xposed *modules* can be intrusive. Not more than Google and [3rd party apps](https://www.xda-developers.com/android-apps-tracking-mic-always-listening/).
XprivacyLua does offer a better privacy. It can even restrict Android itself.
Again, Xposed/XPrivacyLua does NOT require root.
