### ISSUE TITLE
Adding ox.io and Open-Xchange

### ISSUE THREAD

**Issue by Sigmun** [nylira/prism-break#1874]
I have tried [ox.io](http://ox.io) and it seems to be a good candidate for plenty of services. Their goal is to provide a full alternative to Google services:
- Email Account
- Enterprise Suite
- File Storage & Sync
- Productivity

Here are their [policy](https://freemail.ox.io/data-protection/)

Their server are based on the open source [Open-Xchange](https://www.open-xchange.com/) which also might be considered here for 
- Mail Servers
- Productivity

**Comment by alerque** [comment]
What exactly in Open-Xchange is open source and relevant to PRISM-Break? I'm aware of Dovecot (which wasn't their project until a merger happened and they took an open source project and developed a paid pro version), but I don't see source code for their app suite or anything else relevant here. If I'm missing something editing in some links and a better explanation of the scope of what you are proposing and how it's relevant to our expectations would be useful.

**Comment by Hillside502** [comment]
https://www.open-xchange.com/ carries the **proprietary** tracker piwikpro.com

**Comment by Sigmun** [comment]
@alerque 
You can get the source-code here http://oxpedia.org/wiki/index.php?title=SourceCodeAccess.

For the scope, I think this is a very realistic alternative to the google suite, with an easy access (no invitation nor motivation filter like riseup). This can help many people to get out of google. 

@Hillside502 
It seems to be use on there site but I'm not sure it is embedded in the open-xchange product itself. Furthermore, I am proposing here two different solutions: the open-xchange product to be compiled and installed and the webservice ox.io.
