### ISSUE TITLE
Consider removing YaCy

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1888]
See https://github.com/nylira/prism-break/pull/1877#issuecomment-369790653; YaCy's quality is extremely low. Admittedly I last tried it several years ago but I remember it being clunky, Java-based and not terribly useful overall. I really feel like we're scraping the bottom of the barrel with this one and I'd rather just remove it.

**Comment by yegortimoshenko** [comment]
I agree. I've just tried it today, and previously I've tried it a few years ago, and search quality hasn't improved enough to be of much use.

**Comment by alerque** [comment]
I'd be good with this. As much as I'd _like_ this space to heat up, I don't think we are doing anybody any favors promoting projects which just don't cut the mustard yet.

**Comment by strugee** [comment]
Making as accepting PRs, if anyone still disagrees speak up and we'll talk.

**Comment by yegortimoshenko** [comment]
I should state that #1890 includes this change.
