### ISSUE TITLE
Propose adding Mycroft voice assistant

### ISSUE THREAD

**Issue by alerque** [nylira/prism-break#1889]
There are a number of open source voice assistants available now, and given the popularity of the commercial ones and how intrusive they are privacy wise, I think it might be time to add this as a category and list at least one or two. Issue #898 has been outstanding for a while now, but I'd like to see it take it's original form of noting the proprietary things to be avoided (Google Now / Google Assistant, Apple Siri, Amazon Echo / Alexa, Microsoft Cortana, Samsung Bixby).

By reputation I know the most about [Mycroft](https://mycroft.ai/), and this issue is to propose adding it. There are others to look into ([Lucida](http://lucida.ai/), [Hey Athena](https://github.com/rcbyron/hey-athena-client), [Blather](http://www.jezra.net/projects/blather), [Dragonfire](https://github.com/DragonComputer/Dragonfire), [Kalliope](https://kalliope-project.github.io/)) but I would suggest if anybody wants to see them added that each should be proposed in a separate issue one per project for review.

Mycroft can be run on dedicated hardware, on a Linux desktop, an a Raspberry Pi, on Android, or baked into something else. All the sources for various platforms are on the [organization's Github](https://github.com/MycroftAI). The core is written in Python and Apache licensed. Some of the front end clients are GPL, libraries to access it are LGPL, etc. Basically everything seems to be available to be able to run assistants that don't call out to the web or turn a microphone over to some corporate overlord.

**Comment by strugee** [comment]
Definitely agree with all these points. I too know Mycroft the best by reputation, but I wonder if anyone has looked closely at how it works. E.g. if it answers questions by calling out to Google's Knowledge Graph, that's a no-go. Unless it's not tied to a user identifier, possibly. I'm not sure if that would be okay or not. (It _seems_ like it would? But it also seems risky to assume so.)

**Comment by yegortimoshenko** [comment]
Can I merge this with #898? Seems to be a single issue, i.e. a new category, with proprietary rejected software and free recommended software.

**Comment by alerque** [comment]
No. Adding the category in general is not the same as a specific discussion of Mycroft as a suggestion.
