### ISSUE TITLE
Automate image resource generation

### ISSUE THREAD

**Issue by alerque** [nylira/prism-break#1898]
Right now a bunch of manual work is involved in adding project logos at several sizes. We keep ending up with mistakes like bogus aspect ratios (e.g. #1894) and inconsistent compression etc.

I  started on some code for the build system the other day so we can just keep one higher resolution resource around for each project (much easier to find from upstream projects) and automatically generate al the sizes and scales we need for the site. This should take both the errors and trouble involved in manual image generation out of the process.

(Somebody can assign this to me, the issue is just a reminder that I'm working on it.)

**Comment by yegortimoshenko** [comment]
Good idea!

Just for reference, for `medium@2x`:

* from SVG: `inkscape -z -e shaarli.png -w 120 -h 120 ../original/shaarli.svg`
* from PNG: `convert shaarli.png -resize 120x120 ../original/shaarli.png`

Lossless optimization: `zopflipng -m shaarli.png shaarli.zopfli.png`, `mv shaarli.zopfli.png shaarli.png`

**Comment by alerque** [comment]
Thanks for the tips, but I do have a [little bit of](https://github.com/alerque/casile/blob/master/makefile#L782) ImageMagick & Inkscape build automation under my belt ;-)

**Comment by strugee** [comment]
Sounds awesome. Thanks for working on this.
