### ISSUE TITLE
Some logos are squashed

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1902]
See for example https://prism-break.org/en/all/#bookmark-sync. I think we can probably fix this with some CSS?

**Comment by yegortimoshenko** [comment]
This issue is fully fixed in #1893 + #1894.

**Comment by alerque** [comment]
...and will be fixed for future images via #1898.

**Comment by yegortimoshenko** [comment]
#1893 and #1894 are merged, so this is fixed now. #1898 is tracked separately, so closing.
