### ISSUE TITLE
Consider Habitica

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1910]
Extracted from #510. To-do manager with RPG elements, can be self-hosted.

https://habitica.com/
https://github.com/HabitRPG/habitica

**Comment by yegortimoshenko** [comment]
I am personally against it because in my experience it is addictive in a bad way and makes you less productive. The reasons behind that it devolves into playing a game first and doing things second, in retrospective it seems to be a bad idea to embed game, and social chat, into a todo application.

**Comment by alerque** [comment]
Although I agree that having gaming elements probably isn't the smartest move here, I don't see how our opinion should even count for or against including the project on PRISM-Break. It just doesn't seem like a relevant point. I don't think this is ready to tag as `waiting for objects` until there somebody actually makes a case one way or another based on reviewing our usual criteria.

**Comment by yegortimoshenko** [comment]
Good point.
