### ISSUE TITLE
Consider Systemli

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1912]
Extracted from #1472.

https://www.systemli.org/en/index.html

> systemli.org, Your friendly tech collective
> Non-commercial provider of privacy friendly communication. Without surveilliance.

Systemli provides their service for free, hosted in Germany. Email, Etherpad, XMPP. All services are available as Onion hidden services. Registration requires an invite: https://www.systemli.org/en/service/mail.html

**Comment by Hillside502** [comment]
Source
https://github.com/systemli/
