### ISSUE TITLE
[Announcement] I made #prism-break on Freenode

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1914]
I'm abusing the issue tracker to make this announcement since we don't really have a better way of communication. Just wanted to let people know I've registered `#prism-break` on Freenode and am idling there. Thought it might be useful for quick discussions and also just to get to know people better.

I would like to put this in the documentation, but am not sure where. Probably a link to Freenode web chat in `CONTRIBUTING.md`, at minimum?

**Comment by yegortimoshenko** [comment]
Great! I'm idling now too (on Riot). I think `README.md` would be the appropriate place because it's more visible and also encourages everyone who is interested to join, not just the people who contribute.

**Comment by yegortimoshenko** [comment]
I've sent a bridge request between Riot channel #prism-break:matrix.org and IRC, could you accept it?

**Comment by cyanotex** [comment]
Idling on it too.
