### ISSUE TITLE
README.md doesn't actually say what the project is

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1916]
https://github.com/nylira/prism-break/issues/1659#issuecomment-335206427

This is... regrettable.

**Comment by Atavic** [comment]
Repository description has a link to the site. Maybe adding the link into the readme may help?

**Comment by yegortimoshenko** [comment]
I don't think this is an actual problem, a) there is a link in the repo's description which is the canonical place for project homepages, b) any search engine will find that page if one searches for "prism break", "prism-break" or even "prism/break".
