### ISSUE TITLE
Consider FreeDNS

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1917]
IPv4 only and probably no DNSSEC. No logging. https://freedns.zone/en/why/

**Comment by Hillside502** [comment]
Firefox (correctly) gives a "Connection is not secure" warning for https://freedns.zone/en/why/
The offending code is `http://ogp.me/ns#`

Also, tracker payload:-
`google-analytics`
`snippypages`

**Comment by yegortimoshenko** [comment]
Thanks for the research. There are DNS services that don't have all these problems, so closing this issue.
