### ISSUE TITLE
Consider Yalp Store

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1924]
Supersedes #1433.

Yalp Store is an app that can be used to download apps from Google Play store without signing up / logging into Google account and without accepting any EULAs. It is based on a reverse-engineered implementation of Google Play protobuf protocol.

It also provides metadata on which apps require Google Play Services installed and which don't.

https://f-droid.org/en/packages/com.github.yeriomin.yalpstore/
https://github.com/yeriomin/YalpStore

**Comment by hasufell** [comment]
That makes zero sense. You recommend software to download proprietary software or software packaged by a totally untrustable source?

**Comment by Atavic** [comment]
Wait, as I buy an android phone I am stuck to the Google Play Store unless I use an alternative.
Providing a link and a short description to alternatives to the Play Store allows android users to bypass

> signing up and logging into Google account + metadata

as written above.

**Comment by yegortimoshenko** [comment]
@hasusfell: please be less presumptious. I'm not recommending Yalp Store, this ticket only supersedes #1433 (Raccoon). I can't unilaterally close issues based only on my opinion, which is why I sometimes extract proposals from older tickets.

Also see #1909, #1910, #1911, #1912, #1913, #1917, etc.

**Comment by strugee** [comment]
Can't see this making it into the main list, but I can see the use for a note. E.g. I've encountered some FOSS applications that were only distributed through the Play Store - OwnTracks and (until recently-ish) Onionoo come to mind.

**Comment by hasufell** [comment]
> please be less presumptious

You seem to be taking things overly personal, like with the Pale Moon discussion. I literally don't care **who** has proposed this. I am against it. Please keep this technical.

**Comment by yegortimoshenko** [comment]
Software distributed in Google Play is signed by developer, not Google, so it's tamper-proof in a way, if you trust developer's build process. That said, Google Play contains various applications that we don't recommend. I'm also not sure if we should mention it.

**Comment by Hillside502** [comment]
> some FOSS applications that were only distributed through the Play Store

Exactly!

**Comment by yegortimoshenko** [comment]
Another concern is that developer keys are not pinned and Google can mount a MITM attack.
