### ISSUE TITLE
Remove Profanity

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1926]
I think we should remove Profanity.

It's console-based so a bit intimidating for inexperienced users, especially when we also have GUI clients that can do the same. OMEMO requires a plugin setup too.

I don't see a reason to keep it, especially since the IM section is so long.

**Comment by yegortimoshenko** [comment]
We should really clean up Instant Messaging section. I support removing Profanity based on that it is a CLI client, also I would like to support XMPP clients that prioritize OMEMO over OTR.

**Comment by coreyreichle** [comment]
I do not believe removing something solely because it's a cli-based tool is really a good idea.  Other reasons?  Sure.  but cli-only is a bad idea.

Sometimes, you are restricted to just a text term (Remotely working, low resource machine, etc).

**Comment by Zegnat** [comment]
The removal is part of the fact that we are trying to minimise the amount of options shown in the IM category. And recommending people GUI tools will usually help them to change from proprietary software sooner.

The assumption often being that people who are working in terminals will be able to Google for a secure alternative outside of the PRISM Break list.

**Comment by coreyreichle** [comment]
Fair enough.  Especially since the IM list is already long.
