### ISSUE TITLE
Remove XMPP clients that do not support OMEMO

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1927]
See: https://omemo.top/, https://conversations.im/omemo/

OTR can't be used with multiple devices, has annoying concept of starting/ending conversation (which perhaps makes sense from forward secrecy perspective), doesn't handle file transfers in a standard way, messages can't be sent offline...

Gajim 1.0 [dropped OTR support](https://dev.gajim.org/gajim/gajim/blob/gajim_1.0/ChangeLog), and Conversations plans to drop OTR support this year, in 2.0.

XMPP clients that do not have short- to mid-term plans to support OMEMO:

* Bitlbee (https://bugs.bitlbee.org/ticket/1239)
* Jitsi (only from IM section, https://github.com/jitsi/jitsi/issues/199)
* Kontalk (https://github.com/kontalk/androidclient/issues/132)
* Mozilla Thunderbird (only from IM section, https://bugzilla.mozilla.org/show_bug.cgi?id=1237416)

**Comment by hasufell** [comment]
> OTR can't be used with multiple devices

It's debatable whether that is a problem or a feature.

> has annoying concept of starting/ending conversation (which perhaps makes sense from forward secrecy perspective) doesn't handle file transfers in a standard way, messages can't be sent offline...

usability issues, not fundamental

Please no hype-driven decisions. OTR is solid as a protocol, or is there proof that it is not?

**Comment by Atavic** [comment]
OTR does not suppport offline messages, that's it.

*Related:*
https://github.com/pfleidi/yaxim/issues/82
https://github.com/pfleidi/yaxim/issues/197

**Comment by Atavic** [comment]
[Are we OMEMO yet?](https://omemo.top/)

Related to: https://github.com/nylira/prism-break/issues/1926#issuecomment-373831138

**Comment by yegortimoshenko** [comment]
> usability issues, not fundamental

Usability issues are actually fundamental. It's not OK for a chat application to not support sending offline messages. This results in people using plaintext messages for when the person is offline. Similarly, not supporting multiple devices means people will prefer plain text to OTR.

We should push OMEMO because it's user-transparent and secure.

**Comment by hasufell** [comment]
> It's not OK for a chat application to not support sending offline messages.

That's just an arbitrary opinion.

> This results in people sending plain text messages when the person is offline.

No. That's an assumption.

> Similarly, not supporting multiple devices means people will prefer plain text to OTR for when they're on the phone.

First, some xmpp servers don't support multiple devices anyway. That's a usability issue and not a fundamental one.

Second, OMEMO requires additional xmpp extensions for that feature. While that is nice, it's in no way a reason to disregard messengers that focus on proper OTR support.

**Comment by yegortimoshenko** [comment]
>> This results in people sending plain text messages when the person is offline.
>
> No. That's an assumption.

I've used OTR, and that's what regularly happened when I was offline.

Usability issues are fundamental issues, because software is strictly about practicality. Software not doing its job properly doesn't have meaning or value. Why would we want to keep listing subpar software while there is something that is more approachable and harder to get wrong?

**Comment by yegortimoshenko** [comment]
Conversations has dropped OTR.

**Comment by rharvest** [comment]
Conversations ostensibly never correctly supported OTR to begin with:

**Comment by wiktor-k** [comment]
Gajim also [dropped supported for OTR in favor of OMEMO](https://dev.gajim.org/gajim/gajim/blob/bc24ab470d87896425684dbee543e9563564a177/ChangeLog#L80) since version 1.0.0.
