### ISSUE TITLE
[TAG] There are 200 opened issues, some tagging may help.

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1928]
For example a **browser** tag for:

https://github.com/nylira/prism-break/issues/1789
https://github.com/nylira/prism-break/issues/1516
https://github.com/nylira/prism-break/issues/1385
https://github.com/nylira/prism-break/issues/1418
https://github.com/nylira/prism-break/issues/1566
https://github.com/nylira/prism-break/issues/1559
https://github.com/nylira/prism-break/issues/1311
https://github.com/nylira/prism-break/issues/1116
https://github.com/nylira/prism-break/issues/1355
https://github.com/nylira/prism-break/issues/1117
https://github.com/nylira/prism-break/issues/1648
https://github.com/nylira/prism-break/issues/1736
https://github.com/nylira/prism-break/issues/1802

...may help solving the long list of issues.

Also, https://github.com/nylira/prism-break/issues/1380 and https://github.com/nylira/prism-break/issues/819 should both have the useful **ops** tag added.

**Comment by Atavic** [comment]
...a **dns** tag for:

https://github.com/nylira/prism-break/issues/1918
https://github.com/nylira/prism-break/issues/1917
https://github.com/nylira/prism-break/issues/1630
https://github.com/nylira/prism-break/issues/1777
https://github.com/nylira/prism-break/issues/1563
https://github.com/nylira/prism-break/issues/1481
https://github.com/nylira/prism-break/issues/1274
https://github.com/nylira/prism-break/issues/1150
https://github.com/nylira/prism-break/issues/1033
https://github.com/nylira/prism-break/issues/1245
https://github.com/nylira/prism-break/issues/1021
https://github.com/nylira/prism-break/issues/879
https://github.com/nylira/prism-break/issues/779
https://github.com/nylira/prism-break/issues/518
https://github.com/nylira/prism-break/issues/463
https://github.com/nylira/prism-break/issues/184
https://github.com/nylira/prism-break/issues/50

**Comment by Atavic** [comment]
and **XMPP** for:

https://github.com/nylira/prism-break/issues/1927
https://github.com/nylira/prism-break/issues/1912
https://github.com/nylira/prism-break/issues/1900
https://github.com/nylira/prism-break/issues/1727
https://github.com/nylira/prism-break/issues/1688
https://github.com/nylira/prism-break/issues/1672
https://github.com/nylira/prism-break/issues/1651

**Comment by Hillside502** [comment]
Sorry you've closed this.  Was that because of the lack of response?

**Comment by yegortimoshenko** [comment]
I've labeled issues that you've sent. I will do https://github.com/nylira/prism-break/issues/1958 in free time so that it would be easier to contribute for you in this manner. Thank you!
