### ISSUE TITLE
Consider DTube

### ISSUE THREAD

**Issue by AnarchoEcologistCatgirl** [nylira/prism-break#1932]
DTube is a decentralized, open-source video hosting platform, functioning as an alternative to YouTube. 
It's built on top of the STEEM blockchain and the IPFS Peer-to-Peer network

https://d.tube/
https://about.d.tube/
https://github.com/dtube

**Comment by yegortimoshenko** [comment]
I couldn't find the full node source code on their GitHub, only several small components.

**Comment by hasufell** [comment]
https://www.reddit.com/r/dtube/comments/6z7ukb/so_where_is_the_code_for_dtube_how_can_we/

**Comment by yegortimoshenko** [comment]
Closing because it's proprietary.
