### ISSUE TITLE
Add freelan

### ISSUE THREAD

**Issue by xfm00mm** [nylira/prism-break#1935]
https://www.freelan.org/
https://github.com/freelan-developers/freelan-all

**Comment by Hillside502** [comment]
Looking at https://github.com/freelan-developers gives the impression of being only **partially** open-source.

**Comment by alerque** [comment]
Can you explain why? What's the advantage of this VPN client over others we recommend? How does the project line up with PRISM-Break's expectations? What's the basic argument for inclusion here?
