### ISSUE TITLE
Consider adding PocketMaps (Word Maps) alternatives in Android

### ISSUE THREAD

**Issue by RiQuY** [nylira/prism-break#1937]
The only alternative to propietary software listed in Prism-Break to download on Android is OsmAnd.
But PocketMaps exists too, available in F-Droid and GooglePlay.
Dowload:
https://play.google.com/store/apps/details?id=com.starcom.pocketmaps
https://f-droid.org/packages/com.junjunguo.pocketmaps/
Source code:
https://github.com/junjunguo/PocketMaps

Comparing with OsmAnd, PocketMaps don't have non free addons, services or resources, PocketMaps project uses OSM data, Mapsforge and Graphhopper open source API. It is a little less powerfull without Internet connection, but it is still a valid option complete offline navigation is possible.

So I think, this app will be a nice addition to the (World Map) section on Android.

**Comment by Hillside502** [comment]
For "Word Maps" read "World Maps"
