### ISSUE TITLE
Add Mailpile

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1947]
Duplicate of #905, #1007. As of now, Mailpile is a stable, mature email client. We should add it. See: https://www.mailpile.is/ (https://github.com/nylira/prism-break/pull/905/commits/a58d3872e83f0adef8243fb8c2c49bd84e30ac60 looks salvageable)

**Comment by Hillside502** [comment]
> We are currently working towards a 1.0 release candidate. Until it is ready, Mailpile is really only suitable for developers who can help us find and fix the last few bugs. 
https://github.com/mailpile/Mailpile

Very promising, excellent piece of software --- but looks like we should hold off recommending until 1.0 release.

**Comment by yegortimoshenko** [comment]
Perhaps. That said, software that we currently list, with exception of Thunderbird, is more buggy in my experience. For example, PRISM Break currently lists Sylpheed; I've [worked on its fork](https://github.com/lukav/lukav-legacy), and there are major issues with memory handling, incomplete/biased format and protocol implementations, major locking issues, even metadata leaks against SMTP spec: Sylpheed might leak local hostname to SMTP server, i.e. computer name (by RFC, it should use public IP address; practically, it can use any IP address, e.g. 127.0.0.1).

 Mailpile's developers have very high standards,

**Comment by Hillside502** [comment]
> Can Mailpile synchronize contact information with an external contact manager...?
Not yet.
https://www.mailpile.is/faq/#fea-2

So, I'm not sure that Mailpile can currently beat Thunderbird with Enigmail, [CardBook](https://addons.mozilla.org/en-US/thunderbird/addon/cardbook/) and 
[EteSync](https://github.com/nylira/prism-break/pull/1720)

**Comment by Hillside502** [comment]
> I never use address book in email clients

Do you copy/paste addresses from another app? if so, which one?

**Comment by yegortimoshenko** [comment]
I currently store my contacts in [BBDB](http://bbdb.sourceforge.net/bbdb.html), but I plan to switch to EteSync any time now.
