### ISSUE TITLE
Rename Protocols to Standards

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1959]
Standard is a more general word for more or less the same idea, only without any implications of being network-related. Currently, GPG "Protocol" is out of place, and we could, say, also add Git standard/protocol to git-annex, pass and Sparkleshare to show that they are interoperable to some extent.

**Comment by alerque** [comment]
This sounds good, that's always bothered be too but I never stopped to think of an appropriate replacement.
