### ISSUE TITLE
AOL Instant Messenger (AIM) is discontinued

### ISSUE THREAD

**Issue by davidhedlund** [nylira/prism-break#1960]
Oath Inc. discontinued AIM as a service on December 15, 2017.

https://www.aim.com/ is down.

Can you please remove "AOL Instant Messenger" from https://prism-break.org/

**Comment by yegortimoshenko** [comment]
Thanks for noticing!

**Comment by davidhedlund** [comment]
@yegortimoshenko Thanks.
