### ISSUE TITLE
PRISM Break is blocked in Russia

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1962]
I can't access prism-break.org directly anymore. This is likely collateral to recently blocked Telegram. It'd be nice to do something about this if not resolved soon.

**Comment by Hillside502** [comment]
The following indicates that AWS is blocked:-
https://www.reddit.com/r/Eve/comments/8d2yqy/psa_due_to_the_russian_government_blocking_all/

So, as PRISM Break is hosted on a DigitalOcean droplet in Singapore, maybe other/all similar hosting providers are blocked.
https://iplookup.flagfox.net/?ip=139.59.225.79&host=prism-break.org
https://www.shodan.io/host/139.59.225.79

Of course, the censors could be specifically targetting freedom/privacy sites.

How about hosting via a rapidly changing dynamic address --- or via a static VPN address?

I run a Cloudron server from my Living Room in the UK --- appearing to the world as a Swedish static!

**Comment by yegortimoshenko** [comment]
Issue seems to be unrelated to Telegram. I've found PRISM Break's IP address (139.59.225.79) in Russian blocklist registry (http://blocklist.rkn.gov.ru/):

![abc](https://user-images.githubusercontent.com/1643293/39098028-269c5e5a-466d-11e8-86a8-3c3827aa1ad3.png)

**Comment by yegortimoshenko** [comment]
Domain is not blocked, but IP address is. I wonder if they didn't like some other site that @nylira hosts on the same IP.

**Comment by Hillside502** [comment]
https://reverseip.domaintools.com/search/?q=prism-break.org
gives:-
http://laura-guerra.net/
https://nylira.com/
https://prism-break.org/

**Comment by Hillside502** [comment]
Internet censorship and surveillance by country - Wikipedia
https://en.wikipedia.org/wiki/Internet_censorship_and_surveillance_by_country

Internet censorship in Russia - Wikipedia
https://en.wikipedia.org/wiki/Internet_censorship_in_Russia

Mass surveillance in Russia - Wikipedia
https://en.wikipedia.org/wiki/Mass_surveillance_in_Russia

**Comment by yegortimoshenko** [comment]
Resolved.
