### ISSUE TITLE
Track Riot E2E status

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1963]
Riot currently doesn't use E2E by default (although it's available), but it is planned to enable it by default in the near future: https://github.com/nylira/prism-break/pull/1953#issuecomment-384660933 This issue is for tracking progress on this.

**Comment by strypey** [comment]
The Riot team is tracking the work that needs to be done to turn on E2EE by default in this meta-issue:
https://github.com/vector-im/riot-web/issues/6779

**Comment by alerque** [comment]
Please use the [current issue tracker on Gitlab](http://gitlab.com/prism-break/prism-break/issues/).
