### ISSUE TITLE
Use Base64-encoded file names for logo assets in order to circumvent Fanboy's Annoyance block list

### ISSUE THREAD

**Issue by cyanotex** [nylira/prism-break#1965]
![chrome_2018-05-14_12-41-59](https://user-images.githubusercontent.com/36788381/39995480-3a663a42-5774-11e8-9241-10733d0c3f1c.png)

That's weird that we don't have a logo for Discord but we have one for Snapchat.

Discord provides resources for their logo which can be found here:
https://discordapp.com/branding

I personally believe either the black or colored logo would fit with the white theme PRISM Break has.

**Comment by Zegnat** [comment]
We definitely have the icon: https://github.com/nylira/prism-break/blob/master/source/assets/images/logos-rejected/small/discord.png

It also seems to show up for me on the site. Is it being blocked by some adblocker on your end?

**Comment by yegortimoshenko** [comment]
Fanboy’s Annoyance List blocks that for you. Nevertheless, we could just change the file name so it isn't blocked anymore.

**Comment by yegortimoshenko** [comment]
So it's more than just Discord, then. I wonder if we could add some prefix to all of those to circumvent blocking.

**Comment by Zegnat** [comment]
> I wonder if we could add some prefix to all of those to circumvent blocking.

Looking at @cyanotex’ screenshot of the rules, not really. As they all match `*` before the file name.

Giving the images cryptic names in the repository is less than ideal. Maybe on deployment rename all image files to a base64 encoded hash, or something? Though honestly people should be able to run their preferred block lists even against PRISM Break.

Maybe we should consider some graceful styling for when the image doesn’t load. Load a “broken image” graphic in the background, in case a logo is being blocked? At the least make sure all the text names still line up?

**Comment by yegortimoshenko** [comment]
I like Base64 idea.

**Comment by alerque** [comment]
Crosslink #1898 where this could be implemented while working on the same code.
