### ISSUE TITLE
Consider me_cleaner

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1968]
Intel ME removal tool. Extracted from https://github.com/nylira/prism-break/issues/1787#issuecomment-323820679.

**Comment by yegortimoshenko** [comment]
Homepage: https://github.com/corna/me_cleaner

**Comment by strugee** [comment]
So, in general I think we can all agree this is overall a net win. That being said I don't really know where we would put this tool on the site. I also wonder if we're straying close to our "hardware is out of scope" rule though instinctively I think the answer is no in this case.

**Comment by Zegnat** [comment]
Not sure if it gets close to the hardware rule, but it is surely a little hard to fit into PRISM Break.

PRISM Break hasn’t really given a lot of general advice outside a couple of notes below some categories, instead focussing on offering more private/secure/open alternatives to software that may be leaking your personal data. There isn’t really any “software” in that sense that is being replaced with this tool.

**Comment by yegortimoshenko** [comment]
I just would like to communicate to people somehow that Intel ME is dangerous and should be stripped if/when possible, maybe in a note. that said, it would probably belong to a currently missing Boot Software section.

**Comment by strugee** [comment]
> There isn’t really any “software” in that sense that is being replaced with this tool.

There does seem to be _some_ precedent for this? We accepted Android IMSI-Catcher Detector.

**Comment by Zegnat** [comment]
> There does seem to be some precedent for this? We accepted Android IMSI-Catcher Detector.

You are right! I always forget about the mobile section of the list. Just like that one has the overly-broad category of “cellular”, maybe a very broad category could be thought of for me_cleaner too? So a catch-all is created for future projects like this that could be worth listing.

**Comment by Atavic** [comment]
Related issues: https://github.com/nylira/prism-break/issues/1663#issuecomment-369924182, https://github.com/nylira/prism-break/issues/1787

**Comment by strugee** [comment]
I wonder, if we make a Boot Software section, if we should then put Libreboot in it too. I guess we should have a separate discussion but that seems like it would work.
