### ISSUE TITLE
Consider removing Replicant

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1969]
Extracted from #1600. Unfortunately, Replicant doesn't keep up with CVEs, or with Android updates and bug fixes. There is no hardware graphics acceleration, which makes it really sluggish (although that's understandable because most phones don't have a usable GPU that doesn't require blobs), everything is really, really buggy, non-vulnerable browser can't be installed because of renderer that's being used, ...

**Comment by cyanotex** [comment]
I agree with this issue.

**Comment by p2635** [comment]
So we're left with no recommendations? What shall I do?

**Comment by cyanotex** [comment]
Re: Librem 5 @yegortimoshenko 

How will we know if they deliver all of their promises? And if they host their code here, should we go through it and see if we can recommend it?

**Comment by yegortimoshenko** [comment]
> How will we know if they deliver all of their promises?

It'd be better to research that yourself and decide whether you trust them enough or not, rather than basing that off my opinion :-) There is no warranty, as with any crowdfunding campaign.

> And if they host their code here, should we go through it and see if we can recommend it?

See https://code.puri.sm/Librem5, also some source is linked to in https://puri.sm/news/.

**Comment by yegortimoshenko** [comment]
Also, https://gitlab.gnome.org/Community/Purism. But this is off-topic :-)

**Comment by yegortimoshenko** [comment]
I've joined Replicant IRC channel and I should've done that earlier. There's a lot of work in progress, including porting Replicant to a newer Android release, and porting Samsung S3 to a mainline kernel (!): https://blog.forkwhiletrue.me/pages/midas-mainline/

**Comment by NoseyNick** [comment]
Still listed at the top of https://prism-break.org/en/categories/android/

**Comment by strugee** [comment]
#2011 (but the GitLab project isn't super active either, heads up)
