### ISSUE TITLE
Switch to GitLab Pages

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1973]
We regularly have problems that affect PRISM Break's uptime: #1689, #1863, #1971, #1972.

If we were to use GitHub Pages alongside with Travis CI, we would also get continuous delivery (instead of current seemingly manual https://github.com/nylira/prism-break-static approach).

GitHub Pages now offers TLS:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by nylira** [comment]
Will investigate this.

**Comment by alerque** [comment]
I might be able to help with this. I've done quite a bit of work with Gitlab's CI system.

BTW what was the motivation for the Github → Gitlab switch in this issue? I am aware of the recent acquisition, but unless we also plan on migrating this repository I'm not sure it's wise to split across two ecosystems.

**Comment by yegortimoshenko** [comment]
@alerque We do plan complete migration: see #2011.
