### ISSUE TITLE
OTR encryption cracked

### ISSUE THREAD

**Issue by ohmynameisrico** [nylira/prism-break#1976]
See bitmessage's general chan

**Comment by yegortimoshenko** [comment]
Could you link me to it?

**Comment by ohmynameisrico** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/477

**Comment by Zegnat** [comment]
I think Beamstat has pretty up-to-date mirrors of Bitmessage – but correct me if I am wrong – so [this is the discussion](https://beamstat.com/chan/privacy/550ac4c97ab7e69bccde4d308af8829828d869ad5d44e934240e30838cda61f1) you are talking about? I am not seeing anything of note in there, and really nothing actionable.

Could of course be there is another thread. I do not actually use Bitmessage myself.

**Comment by yegortimoshenko** [comment]
No one has broken OTR, and it's very unlikely that would ever happen (messages are just AES-CTR encrypted with session-specific symmetric key, maybe there could be a flaw in key negotiation but no one has pointed out one in this thread.
