### ISSUE TITLE
Switch to SVG

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1980]
This is an alternative to #1898.

We could just either convert or find all currently listed logos in SVG and switch to that instead of making build pipeline more complex.

https://caniuse.com/#feat=svg

**Comment by alerque** [comment]
Not all projects have SVG available, and re-creating logos is not a good plan.

My idea (which my marriage this last month has blocked my sitting down to implement) was to keep just one best-available-quality resource in the repo. If that is SVG then great, we can use it across the site. In the event that it's not, we can auto-convert to other sizes and formats as needed.

**Comment by yegortimoshenko** [comment]
From 130 logos that we have, there are SVGs for 98 and 32 still only have PNG. I estimate that out of 32, I will be able to get SVG source for at least a half, so 16.

Additionally, some projects that only have PNGs (Dudle, Orweb) are pending removal.

See: https://github.com/nylira/prism-break/tree/svg/source/assets/logos

The small number of PNGs that will be left can be used verbatim in high resolution, I think, because SVG savings will compensate for using oversized PNGs here and there.

**Comment by yegortimoshenko** [comment]
Just driven PNG count down to 29, which will go further down to 23 when some of the pull requests and triaged issues (labeled "help wanted") will be committed. From those 23 that are left, there are only 4 projects currently for which we surely can say that there is no SVG source (Exim, Tinc, Tor Browser, Weechat). I've sent email/forum inquiries to the rest (Kolab, Kolab Now, Metager, Unbubble, Subgraph OS, StartPage, Weechat, Tigase, NoScript, ejabberd, Cookie AutoDelete, GPGTools, FreeSWITCH, iRedMail, Open Web Analytics).
