### ISSUE TITLE
Consider Gitea

### ISSUE THREAD

**Issue by JeremyRand** [nylira/prism-break#2012]
[Gitea](https://gitea.io/en-us/) is a fork of Gogs.  A quick glance at things that look relevant to PRISM-Break:

* Gitea [supports](https://docs.gitea.io/en-us/comparison/) GPG signed commits; Gogs [doesn't](https://github.com/gogs/gogs/issues/2981).
* Gitea [supports](https://docs.gitea.io/en-us/comparison/) FIDO U2F for authentication; Gogs [doesn't](https://github.com/gogs/gogs/issues/4384).

Might be worth considering replacing Gogs with Gitea on PRISM-Break.

**Comment by yegortimoshenko** [comment]
I support replacing Gogs with Gitea. Gogs is undermanned and fully curated by a single person, while Gitea is a community project.
