### ISSUE TITLE
Consider DNSSEC-Trigger

### ISSUE THREAD

**Issue by JeremyRand** [nylira/prism-break#2014]
[DNSSEC-Trigger](https://www.nlnetlabs.nl/projects/dnssec-trigger/about/) is a wrapper around Unbound that makes it use DHCP-provided upstream DNS if that DNS supports DNSSEC, and otherwise use authoritative nameservers.  It's maintained by NLnet Labs (same org who maintains Unbound).  Might be worth considering listing it instead of Unbound, since it's generally easier to set up for novices than plain Unbound is, and doesn't seem to have any downsides.  Fedora [recommends](https://fedoraproject.org/wiki/Networking/NameResolution/DNSSEC#Installation) installing DNSSEC-Trigger rather than plain Unbound as a method of enabling DNSSEC validation.

**Comment by strugee** [comment]
The documentation says it's experimental. Someone should look into just how experimental. Is it really immature?

**Comment by JeremyRand** [comment]
> The documentation says it's experimental. Someone should look into just how experimental. Is it really immature?

The code has been around [since 2011](https://www.nlnetlabs.nl/svn/dnssec-trigger/tags/dnssec-trigger-0.15/Changelog).  I haven't explicitly asked NLnet Labs why they call it experimental, but my guess is that they mean that the general design/approach is experimental rather than the codebase; i.e. they reserve the right to decide to replace the codebase with something entirely new if they decide that there's a better way to do it.  (This makes sense, since the concept of client-side DNSSEC validation is arguably inherently experimental, since traditionally DNSSEC validation was done by ISP's.  I don't think client-side DNSSEC validation is a problem from PRISM-Break's perspective, though.)
