### ISSUE TITLE
Consider Loomio

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#2018]
https://www.loomio.org/
https://github.com/loomio/loomio

Decision making/polling service under AGPLv3. Here's an example of a poll: https://www.loomio.org/p/vTstcW6q/poll

Would be nice to replace Dudle with that.

**Comment by Hillside502** [comment]
Loomio - Wikipedia
https://en.wikipedia.org/wiki/Loomio

Open Source Loomio Alternatives - AlternativeTo.net
https://alternativeto.net/software/loomio/?license=opensource
