### ISSUE TITLE
Replace Android IMSI-Catcher Detector with instructions on how to disable 2G

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#2019]
IMSI-catchers work by downgrading connection to 2G and intercepting IMSI/IMEI of the device. 3G and newer standards, on the other hand, are encrypted in transit and include mutual authentication, which makes classic MITM impossible.

AIMSICD is no use, because once it tells you that there is an IMSI-catcher in range, data has already been harvested. It would be nice to just tell how to disable 2G.

**Comment by strugee** [comment]
I guess this would resolve #1974

**Comment by yegortimoshenko** [comment]
I think so, yes.
