### ISSUE TITLE
Add Kodachi 

### ISSUE THREAD

**Issue by ZarusMods** [nylira/prism-break#2024]
Here is the website https://www.digi77.com/linux-kodachi/
And also code https://github.com/WMAL/kodachi/
And page on sourceforge https://sourceforge.net/projects/linuxkodachi/

**Comment by yegortimoshenko** [comment]
Sorry, but this has been abandoned. It's dangerous to use distributions that haven't been patched for a year.

**Comment by ZarusMods** [comment]
Ok, i understand you

**Comment by WMAL** [comment]
"haven't been patched for a year" That is not correct check the website please
https://www.digi77.com/linux-kodachi/
