### ISSUE TITLE
Ixquick doesn't exist anymore

### ISSUE THREAD

**Issue by Undigon** [nylira/prism-break#2025]
Ixquick gets redirected to startpage. This was announced some months ago. I found this article to give some reference. I didn't store it or found any reference on startpage's blog, sorry about that.
[https://www.ghacks.net/2018/04/02/search-engine-ixquick-eu-redirects-to-startpage-com/](url)

I found it
[https://www.startpage.com/blog/coming-soon-ixquick-eu-will-forwarded-startpage-com/](url)
_terrific new privacy features_

**Comment by yegortimoshenko** [comment]
Sure, see: d2d7e58829d74ffb435fcef8874b1f88f07fed4d
