### ISSUE TITLE
Whatsapp?!

### ISSUE THREAD

**Issue by eloydegen** [nylira/prism-break#221]
I think I’ve missed something, but what happened with Whatsapp?!

**Comment by Sigmun** [comment]
Does the recent use of Open Whiper Systems for encryption in it has changed anything on that app?

**Comment by strugee** [comment]
No. It makes it marginally better, but far from enough for PRISM Break to reconsider listing it.

Specifically the fact that it's still not freedom-respecting software means that we have to take their word for it that their encryption is strong and backdoor-free.

**Comment by merlinnusr** [comment]
NO, It's closed source.
