### ISSUE TITLE
Trustable SSL providers

### ISSUE THREAD

**Issue by oli-ver** [nylira/prism-break#233]
What SSL providers can we trust? I think very important would be to analyse free services like StartSSL for Server-Certificates and E-Mail-Certificates (S/MIME).

Are there others? Should payed services be analysed, too?

Edit (thank you finn and Zegnat):
There are providers that offer the possibility to let them generate your private key, like StartSSL. This should never be done from perspectives of security.

As we cannot validate the providers itself, we could inform about what is a good approach when securing a self hosted service.

**Comment by yegortimoshenko** [comment]
We now have one, kinda, as much as you can trust someone in the broken authority-based system.  It is Let's Encrypt.
