### ISSUE TITLE
Psi Plus (Psi+)

### ISSUE THREAD

**Issue by ozhank** [nylira/prism-break#253]
Could Psi+ be added as secure IM, as it uses gpg as default, and can use otr as well.

**Comment by sedrubal** [comment]
I tried psi+ and pidgin and I like psi+ much more... I think, it isn't much more complicating than pidgin. If prism-break recommends one of them, it has also to recommend the other if there are no reasons against.

**Comment by nylira** [comment]
Psi+ is on the site. https://prism-break.org/en/projects/psi/

**Comment by sedrubal** [comment]
Thx

Somehow I didn't find it yesterday...
