### ISSUE TITLE
Add Kontalk as alternative to WhatsApp

### ISSUE THREAD

**Issue by elaratain** [nylira/prism-break#276]
http://kontalk.org/
based on XMPP, supports own servers, encryption and is open source

**Comment by daniele-athome** [comment]
Hello, just a comment to say that we entered the beta stage using XMPP with a slightly customized (but %100 standards compliant) Tigase server.

**Comment by pravi** [comment]
XMPP rc version is now available via fdroid. I think we can include it now.

**Comment by Zegnat** [comment]
Thanks for the update there @pravi. I’ll reopen this for discussion, though I think we should wait for the actual stable release before inclusion on PRISM Break. I hope some people will be able to comment on Kontalk already.

**Comment by daniele-athome** [comment]
Hi! Just wanted to inform that Kontalk 3.0 has been released today! I hope we can have a place in your list! For any information you may contact our organization e-mail .

**Comment by TheLastProject** [comment]
Kontalk is my go-to WhatsApp replacement and I have had nothing but very good experiences with it. Seeing how it does not depend on Google Play Services and thus works perfectly on devices without Google Play (like mine) and is available on F-Droid as well as Google Play, it would be great if Kontalk could be included.

Small note: Kontalk does still lack group chats, making it not a complete replacement of WhatsApp, but except from that it is the most solid WhatsApp replacement I could find and I use it daily with great experience. The progress on group chats can be tracked on kontalk/androidclient#179.

**Comment by josephholsten** [comment]
@daniele-athome perhaps you'd like to draft a pull request to add info about Kontalk?

**Comment by daniele-athome** [comment]
Yes @josephholsten I probably should :-) I will take note of it and do it ASAP.

**Comment by daniele-athome** [comment]
See #1482.
