### ISSUE TITLE
Jitsi leaks information from secure chats by default

### ISSUE THREAD

**Issue by Olathe** [nylira/prism-break#291]
Jitsi is set up to, by default, leak information about some links that are pasted over secure chats.

0. Open an encrypted chat with someone.
0. Wait for them to paste a YouTube link.
0. Watch as it loads a preview image, meaning that it asked YouTube for it, letting eavesdroppers know that a YouTube link was just sent via secure chat (because it makes the request immediately after receiving a secure message and because it only asks for a preview image rather than an entire page). I haven't checked, but it probably lets eavesdroppers know exactly what link was pasted, since it probably doesn't use HTTPS (not that that would stop the NSA from requesting Google's logs).

I think either Jitsi should be removed or instructions for setting it up properly should be added.

**Comment by josephholsten** [comment]
@nylira sounds like this is safe to close?
