### ISSUE TITLE
Ubuntu derivatives ({L,X,K}ubuntu) are OK, while Ubuntu itself is not

### ISSUE THREAD

**Issue by sgtpep** [nylira/prism-break#334]
Suggest to add them to the list. They are pretty vanilla LXDE, Xfce, KDE based distros. They don't have Unity Dash and don't send any data to Canonical or third parties (except for submitting of crash report, which is optional).

**Comment by dolohow** [comment]
Now the Ubuntu 16.04 ships with Amazon spyware turned off by default.

**Comment by alerque** [comment]
Please consider locking this issue for [the reasons I cited above](https://github.com/nylira/prism-break/issues/334#issuecomment-59557871). It was closed [three years ago](https://github.com/nylira/prism-break/issues/334#event-57936171), almost everything has been repeated several times, and if anything productive or actionable comes up on the topic that's actually new it needs to be dealt with in an issue specific to whatever is being brought up. Meanwhile people can't seem to let this thread alone.

**Comment by Zegnat** [comment]
This issue is now locked. Please open separate issues for separate operating systems. Do note that we will probably stay sceptical about Canonical's Ubuntu for a while longer.
