### ISSUE TITLE
MAPS: NASA World Wind?

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#387]
"NASA World Wind" is opensource, but has it's own license (NASA OPEN SOURCE AGREEMENT VERSION 1.3). I do not know much about that project and that would probably need some investigation.

homepage: http://worldwind.arc.nasa.gov/java/

also see #386

**Comment by josephholsten** [comment]
@hasufell: is there any action to be taken for this? seems like we're okay with it.
