### ISSUE TITLE
New positions to add

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#430]
There will be need to translate Polish version from scratch, but now... I don't have free time yet.
But some ideas what to add:

OPERATING SYSTEM:
- Write Ubuntu in proprietary column. Really, people always telling "too long, didn't read". They will not read "Notes" column. There is not time to joking. Write under Ubuntu that is using Unity, Amazon and 3rd party apps.
- Add ReactOS to replacements. I think that is rather open source, because it is written from scratch, and doesn't include AdvApi.dll with NSA keys included, and similar spy drivers.

ANDROID:
- Superuser by ChainsDD, SuperSU are proprietary. I think that is the biggest fail of Unix world - why basic Unix/Linux function (su) is controled by closed source software?! Sorry, not software - in free version of SuperSU there are always ads like "Granted permissions for XXXXXXX. Consider buying Pro version"!!! Use Superuser by Clockworkmod (Koushik Dutta) only. Only open source manager for open source command!!!
- Google Play Music -> Music, Vanilla Music. Do not keep music online. Use open source players. "Music" is stock player from Android (AOSP) 1.6-4.3. Vanilla Music is more stable, more functional app, based on "Music". Both apps there are in FDroid.
- Stock Browser, Chrome, Opera Mini, Opera, UC Browser -> Tint Browser. Stock browser contains only proprietary search engines. Chrome is by Google. Opera and UC Browser are using own servers to compress sent/received data. Tint is great enhancement of stock browser, with Adblock addon and full choise of search engines (I have tried only DuckDuckGo yet).
- Write that using Google Apps (gapps) is FORBIDDEN TO KEEP PRIVACY!
- And if anyone can't install CyanogenMod/others, it is good choice to root device and try to remove gapps (look at gapps package content, and remove files from /system, /data/app partition. Privacy is more important than manufacturer's warranty.

WINDOWS PHONE:
- There is NO replacement.

DESKTOP BROWSER:
- Add Chromium and Opera as not recommended. Opera because using own servers to compress websites (Opera Turbo), Chromium because contains proprietary parts.

MAPS:
- I don't know if it is good choice to add Nokia HERE Maps as restricted.

CLOUD STORAGE:
- I don't know if it is good choice to add Box.com as restricted.

MEDIA PUBLISHING:
- I don't know if it is good choice to add Vimeo and Dailymotion as restricted.

FEATUREPHONES BROWSERS:
- Add Nokia Xpress Browser and Opera Mini as proprietary. Opera compresses and customises pages to look good on small screens and be small. The same in Xpress Browser, I don't know if there is any open source browser for featurephones. If not, better not use internet in phone.

TEXT TRANSLATING SERVICES:
- Google Translate, Microsoft Translator. I don't know if there are any good replacements.

MEDIA PUBLISHING:
- Add Joomla, DokuWiki, and few similar. DokuWiki have even repository with open source addons and themes.

OTHERS:
- Generally, we can move services/apps not recommended by PRISM Break to "proprietary" column, to keep better visibility.
- Do not use Flash Player. Use Gnash instead of. Works with YouTube, if install Gnash, and then in Iceweasel click "Install missing plugins...".

**Comment by lukateras** [comment]
Everything mentioned by the OP has already been fixed, is non-actionable, or is mentioned in other open tickets (#514, #1018). Safe to close.
