### ISSUE TITLE
Trustedbird?

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#485]
> Trustedbird - is a set of security and feature patches for Thunderbird, to bring more security in email management.

Did any1 have a look at that project or even the code?

HP: http://adullact.net/plugins/mediawiki/wiki/milimail/index.php/Trustedbird_Project
repo: http://adullact.net/scm/browser.php?group_id=569

Some features are:
Deletion receipts - Message Delivery Notification (MDN);
Delivery receipts - Delivery Status Notification (DSN);
Encryption/Signing with triple wrapping;
RFC 2634 Security Labels and Signed Receipts;
Address autocompletion with several LDAP directories;
CRL download from LDAP directories;
Manage Out of Office settings on a Sieve server;

**Comment by yegortimoshenko** [comment]
Patches have not been updated since 2015. Will not apply on top of current Thunderbird version. Safe to close.
