### ISSUE TITLE
Groupware and organization services?

### ISSUE THREAD

**Issue by bugsle** [nylira/prism-break#510]
Wouldnt be good to add solutions which help people to get organized in not-tiny/not-big groups? Social networks are fine, but I think there is space for more specific services like Crabgrass, which help groups get organized and actionable.

CrabGrass (last updated 2011)
https://we.riseup.net/crabgrass
crewmate (fork of teambox, not-so-alive)
https://github.com/crewmate/crewmate

**Comment by yegortimoshenko** [comment]
Crewmate is dead, Crabgrass is not really groupware (it's similar to Redmine). We now list Kolab and Nextcloud. This seems to be safe to close.

**Comment by yegortimoshenko** [comment]
Closing in favor of #1909 and #1910. All the other projects mentioned in this thread do not seem to be active anymore.
