### ISSUE TITLE
Translation service section?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [nylira/prism-break#514]
Hi, I have a suggestion on adding the translation service alternatives. So I'm thinking about alternatives to Google Translate and Bing Translator, doesn't matter if it's a web service or a program. Most program alternatives are proprietary and not free and I don't trust Google and Microsoft so I'm stuck. I bet there are more people like me.

**Comment by nicolasrpmaia** [comment]
This thread has stalled, but it really shouldn't have. Right now the tools to substitute Google Translate and Bing Translate are not immediately obvious to most users. I suggest Apertium to be added to this new section.

**Comment by aleksandar-todorovic** [comment]
I forgot I even opened this issue.

I, personally, currently use Google Translate both as a dictionary and as a translator.

I've tried Tatoeba as suggested by @maccaches. 3/15 times the example sentences in my native language were completely useless (we never use them). So I tried to translate a couple of familiar English words (like social, develop, career, tattoo) and it translated none of them. Same thing happened with Apertium. Then I tried Linguee and it doesn't even support any of the three languages I speak natively: Bosnian, Croatian and Serbian (and in a case you wondered, they are practically the same, like British English, American English and Australian English).

What I learned in the meantime:

Google Translate is one of the most complicated Google services. They used texts (like articles or books) that are translated in two languages around the web and looked for patterns. For example, if there's a word called _vijesti_ 12 times in the Croatian version of the text and word _news_ 11 times in the English version of the same text, there is a high probability that the word _vijesti_ corresponds to the word _news_ (and yes it does, because I made up this example).

Considering the amount of computing power needed to complete such a translator service, I came to a conclusion that (unfortunately) there is no way for any free service to compete with proprietary services in this area.

Free software just can't offer anything that is even close to Google Translate.

**Comment by nicolasrpmaia** [comment]
@aleksandar-todorovic I see what you mean, and I think these observations should be in a Note section. I imagine Tatoeba and Apertium should work better on languages with more speakers like French or Spanish.

If a person/project *really* needs a FLOSS translation tool (or is very very concerned with ethics/security) these should be listed, with notes explaining that they still pale technically in comparison to proprietary alternatives.

**Comment by aleksandar-todorovic** [comment]
I just tried that with English to German (both very popular as you will probably agree). Tatoeba gives me some good results, while some of them are useless (it translated _search me_ to _ich weiß nicht_ which actually means _I don't know_).

Apertium still seems useless. It keeps detecting my words in Norwegian Bokmål for some reason, and there are no available translations for any of the words I've tried. Linguee works good, but it is also a proprietary service, so is practically useless.

Considering that GoldenDict + FreeDict seems a bit hard to set up for me (and I am tired currently), I think that Tatoeba is the best we got.

**Comment by aleksandar-todorovic** [comment]
I just found out that Google Translate uses mostly dictionaries posted under free licenses like CC-BY-SA and MIT ([source](http://translate.google.com/about/intl/en_ALL/license.html)). So it seems like only their algorithms and their implementations are proprietary?

**Comment by Dostoi** [comment]
You might be interested by this project (based on Apertium and other translation project) http://www.mitzuli.com/
Never really tried it but so I'm not sure about the real quality of the translation
