### ISSUE TITLE
Suggestion: privacy oriented Card / Cal Dav providers (for syncing contacts and calendar)

### ISSUE THREAD

**Issue by annonman** [nylira/prism-break#516]
I use Fruux, and they seem OK (based in Germany, good privacy laws...).

But, I would prefer a service that supports server-side encryption and an emphasis on privacy.

**Comment by yegortimoshenko** [comment]
We might not recommend Fruux, but we can recommend Baikal, their CalDAV/CardDAV backend: http://sabre.io/baikal/

I've used it a few years ago and it worked. Some people don't want the whole suite of services and want just contacts/calendars a la carte, so perhaps it would be a useful addition.
