### ISSUE TITLE
Add more SSL cipher suites

### ISSUE THREAD

**Issue by myano** [nylira/prism-break#532]
It appears that prism-break.org only supports SSL_RSA_WITH_RC4_128_SHA and nothing else. Can we get support for more SSL cipher suites? Maybe even TLS 1.1/1.2 support? (Forward Secrecy would be fantastic.)
1. https://www.ssllabs.com/ssltest/analyze.html?d=prism-break.org
2. https://sslanalyzer.comodoca.com/?url=https%3A%2F%2Fprism-break.org%2F

**Comment by strugee** [comment]
PRISM Break gets an A+ grade on SSL Labs these days.
