### ISSUE TITLE
Trashmail services 

### ISSUE THREAD

**Issue by alex-fischer-70** [nylira/prism-break#535]
The best anonymity is a changing identity. So we should recommend email-services for addresses which are only valid for a certain time. So the user can change it as oft as he wants. Services like MyKolab have the problem, that there you have an address as long as you pay.
The services should be able to send emails as well.

Alex

**Comment by yegortimoshenko** [comment]
Guerrilla Mail is free software and can be self-hosted:

https://www.guerrillamail.com/
https://github.com/flashmob/go-guerrilla

Self-hosting a semi-private instance can circumvent domain blacklists. It also supports address scrambling which makes it somewhat better for private communication.
