### ISSUE TITLE
cloud storage encryption (sshfs, encfs, truecrypt)

### ISSUE THREAD

**Issue by bocaj-brief** [nylira/prism-break#539]
When using cloud storage service files should be encrypted. What do you think is the best?

Probably to have ssh-access and mount the cloud storage drive using sshfs is the best way. But unless you host the cloud storage yourself you won't have ssh access. So what can be recommended?

Trucrypt? Not free software, and as it is using a container only one person or device can work on a container at the same time.

Encfs is running really smooth for me on lubuntu, but hasn't been updated for more than 2 and a half years, what makes me feel suspicious. (http://www.ict.griffith.edu.au/anthony/info/crypto/encfs.hints http://www.arg0.net/encfs)

Any other ideas? Reccomendations?

Thanks for the great work so far!

**Comment by lukateras** [comment]
This issue has been resolved: TrueCrypt is dead and we don't include any proprietary software, encfs is now listed. sshfs is just a FUSE filesystem to mount remote drive via ssh, so not storage encryption at all.

Safe to close.
