### ISSUE TITLE
add:  PDroid framework (android)

### ISSUE THREAD

**Issue by XMPP-is-texting** [nylira/prism-break#541]
PDroid framwork patch restores to the user CONTROL of not merely permissions but which data apps MAY NOT access

http://forum.xda-developers.com/showthread.php?t=1357056

Other forks of this project exist for android versions JellyBean and future

addressing some of the issues raised in
https://code.google.com/p/android/issues/detail?id=6266#c101 

XDA Developers Android and Mobile Development Forum
Remember Me? Forgot your password?

```
Swappa
```

Portal  Forum   Wiki    XDA TV  Quick Links         

Advanced Search

XDA Developers > Android Development and Hacking > Android Apps and Games > [APP] PDroid - The Better Privacy Protection [2012-03-18: Bugfixes in Patch 1.32]
PrintPrint  EmailEmail
Page 1 of 195       1   2   3   11  51  101     >   >>  
THREAD CLOSED
[APP] PDroid - The Better Privacy Protection [2012-03-18: Bugfixes in Patch 1.32]
    Tip us?

svyat   Old
21st November 2011, 09:02 PM
(Last edited by svyat; 27th March 2012 at 10:21 PM.)
#1

Senior Member - OP
Thanks Meter 553
Posts: 171
Join Date: May 2010
More Info >

DONATE TO ME  
Arrow [APP] PDroid - The Better Privacy Protection [2012-03-18: Bugfixes in Patch 1.32]

PDroid allows blocking access for any installed application to the following data separately:

```
Device ID (IMEI/MEID/ESN)
Subscriber ID (IMSI)
SIM serial (ICCID)
Phone and mailbox number
Incoming call number
Outgoing call number
GPS location
Network location
List of accounts (including your google e-mail address)
Account auth tokens
Contacts
Call logs
Calendar
SMS
MMS
Browser bookmarks and history
System logs
SIM info (operator, country)
Network info (operator, country)
```

For device ID, phone and mailbox number, SIM serial, subscriber ID and device location it also allows supplying custom or random values. 

[[I myself donated to the developer via paypal.]]

**Comment by lukateras** [comment]
This "software" is a ZIP archive with patches on top of Android (AOSP) 2.3 released in 2011 without any particular license (AOSP source is under Apache, which is not a copyleft license, so we can't assume that this code is free to modify, distribute etc. without a license).

Hasn't been updated for the last 5 years. Last comment from XDA thread:

>  I'm going to close this since it doesn't appear the OP is supporting this any longer. There is a PDroid2.0 here on XDA if anyone wants to search for that. OP if you come back just shoot me a PM if you are going to continue support.

Anyway, this software predates more granular permissions in more recent Android versions. 

Safe to close.
