### ISSUE TITLE
Add warnings for insecure (but open) Crypto-Software

### ISSUE THREAD

**Issue by allo-** [nylira/prism-break#548]
What about some section with a warning against new "cool" Cryptosoftware? And then recommend to use software, which already runs without (major) flaws for a long time?

Example what can happen: "Crypto.cat was a nice idea, but was broken at beginning"
Example of something which is long there and seems to be secure: "PGP seems to be uncracked for a long time, and the algorithms and libraries were studied by experts"

**Comment by yegortimoshenko** [comment]
Reclosing this bug because we already list security warnings where applicable (e.g. TrueCrypt) and there is nothing actionable in this bug. We care deeply about security of the listed software and regularly remove insecure software from the list (e.g. Pidgin).
