### ISSUE TITLE
TextSecure and RedPhone rely on proprietary services

### ISSUE THREAD

**Issue by exteroceptiveunfastening** [nylira/prism-break#552]
It's contradictory and unsafe to recommend TextSecure and RedPhone even though they are open source software because they rely on the existence of APIs provided by the Play Services Framework. These apps also have no distribution method other than the proprietary Google Play Store. 

This issue has been addressed by Moxie and he has no plans to change this as of 3 months ago. Link here:
https://github.com/WhisperSystems/RedPhone/issues/143

**Comment by Dyras** [comment]
WhisperSystems has now removed Signal's dependency on Play Store. Maybe it's time to reconsider adding it?

**Comment by strugee** [comment]
Yes, but I'd like to keep discussion in one place. Our discussions about Signal have gotten really scattered across different issues over the year. I'd like to see someone put together a canonical list of things that are good and bad about Signal that've been brought up in the past - I'll do this at some point when I have time but anyone's welcome to take this on in the meantime
