### ISSUE TITLE
Protection for enterprises

### ISSUE THREAD

**Issue by alex-fischer-70** [nylira/prism-break#554]
I think we should add a focus on protection for enterprises and companys. They are obviously the victims of industrial espionage but live cds are not really useable in enterprise environnements. So what could a company do to "break prism"? We should give them also some tips.

**Comment by Atavic** [comment]
Unified Threat Management (UTM) are tailored for enterprise use: Sophos UTM, Endian Firewall, Untangle NG, IPFire, pfSense.

**Comment by Hillside502** [comment]
Open Source Endian Firewall Community Alternatives - AlternativeTo.net
https://alternativeto.net/software/endian-firewall-community/?license=opensource

**Comment by yegortimoshenko** [comment]
We list a whole bunch of enterprise-friendly fully free (not open core) software with optional paid support from developers: Kolab, Nextcloud, Fedora, CentOS, OpenVPN. I don't see anything actionable in this issue perhaps other than adding "Support" link where available in fashion similar to #1906.

**Comment by Atavic** [comment]
Some software has telemetry, like Sophos UTM; while IPFire hasn't such "feature".
