### ISSUE TITLE
Truecrypt alternative- Scram Disk for Linux

### ISSUE THREAD

**Issue by mzs114** [nylira/prism-break#560]
Saw your encryption listing about truecrypt. 
SD4L looks like a viable alternative, at least on linux. 
## Scramdisk

http://sd4l.sourceforge.net/

Other methods of encryption include Encfs(Cryptkeeper or gnome encfs manager as the Gui), encfs is supported both on Linux and BSD.

And thanks for such informative website :)

Regards,
zfs

**Comment by lukateras** [comment]
The proposed software hasn't been updated since 2011 (!). Safe to close.
