### ISSUE TITLE
Add Seamonkey(Iceape).

### ISSUE THREAD

**Issue by mzs114** [nylira/prism-break#561]
Seamonkey(Iceape on Debian) is another alternative, though Mozilla is not developing it(like Thunderbird, just providing security support), however, it is actively developed by the seamonkey community. 

 It is an internet suite, which has, email client, browser, newsfeed reader, a html composer and has Enigmail support.

The codebase has not radically changed like when mozilla decided to go fastrack from version 3 to version 4. 
But they do backport the features, like private browsing,etc. 
This might appeal to users who prefer the "old firefox", but want features of new firefox.

Adding this will recognize and support the product. And will provide choices to the users in general. 

http://www.seamonkey-project.org/

https://launchpad.net/iceape

http://packages.debian.org/search?keywords=iceape

PS- If space is an issue, then include this in the "show all" option.

**Comment by yegortimoshenko** [comment]
I'm against adding Seamonkey. It's a browser + email based on Firefox ESR release and Thunderbird ESR release, so it shares all functionality with Firefox and Thunderbird.

But, it pretty much breathes its last. It's clearly legacy and also very undermanned, with Seamonkey Project Blog being controlled by a single developer with handle ewong, which I think  is the only person still maintaining Seamonkey: https://blog.seamonkey-project.org/

**Comment by strugee** [comment]
This seems pretty niche so I'm closing. If anyone has objections though I'd be happy to reopen.

**Comment by mzs114** [comment]
@yegortimoshenko and @strugee  many FLOSS project blogs are maintained by a single person.

Fyi, following page lists the developers managing, I could count like six developers.
https://www.seamonkey-project.org/dev/project-areas

If we go by the number of people managing any software project it is mostly 80:20, meaning approximately 20% of contributors actually managing/contributing major changes.

IMO, Seamonkey is far from dead, yeah it uses the code from ESR. However, it gives a stable old UI and all-in-one suite, not just browser + email client. The browser addons work fine, I use uBlock Origin, HTTPS Everywhere, and NoScript.

**Comment by mzs114** [comment]
Further to add, Seamonkey is included in FreeBSD ports:

https://www.freshports.org/www/seamonkey/

Debain and Ubuntu don't have it in stock repositories, but a separate community repo exists:
https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/#welcome-to-ubuntuzilla

People need to know that options exists over Firefox, which is removing many configurable options which now require user to open `about:config` page, for instance, removing history older than X days, this was something bugging me like couple of days back, Seamonkey still has this, again there are some more examples like this, but you get the idea.

If people are unaware of such options then such options don't get enough users, starting a cycle of down spiral. Well this is how when average people think of "Linux" they think Ubuntu, not Debian and certainly not other GNU endorsed distros, you get the idea. Whereas there exists arguably better options than Ubuntu and we need to make users aware of this.

Imo, prism-break needs play this role and leave it to the discretion of user. Maybe we might wanna add a tag/label like  'recommend', or, 'widely used' to Firefox and friends, but list Seamonkey as a viable alternative.

**Comment by alerque** [comment]
@mzs114 We actively recommend against Ubuntu, so that's a pretty poor choice for your argument.

We are not a directory and are not aspiring to list all available alternatives. Seamonkey isn't dead, but there simply isn't enough momentum or scrutiny behind it to even consider it viable. Of course some projects get by with less developers, but a browser + email suite is going to take more for us to consider. It might serve a niche need for some advanced or opinionated users, but  that isn't our target and it really isn't viable to make a recommendation on at this time.

**Comment by mzs114** [comment]
@alerque I don't know how you called it a poor choice as I did not keep this project(or people here) in the same bucket.
I took an example to elaborate how word of mouth recommendations work.

Why will it become a directory?

Afaik many categories have more than five listings, for instance IM category:

https://prism-break.org/en/subcategories/gnu-linux-instant-messaging/

Compare it with browser category which has just three!

https://prism-break.org/en/subcategories/gnu-linux-web-browsers/

Imo, by your statement we need to cut down the IM listings. So it does not make sense that adding one more browser breaks something.

**Comment by strugee** [comment]
We probably _do_ need to cut down the IM listings.

**Comment by mzs114** [comment]
@strugee So the point is what goes wrong by adding one browser listing?
Come to think of it, the list probably needs a mention of Chromium as alternative to Chrome, as the other two are used for TOR/JonDo network. I think the anonymous network browsers belong to a different category where something like Opera's VPN service belongs.

**Comment by strugee** [comment]
Chromium has been discussed before, please search the issue tracker.

The problem is that PRISM Break does not exist to list all software. This is what is meant by "PRISM Break is not a directory." By its very nature the project is opinionated, and anything that makes it onto the list has to have some sort of broad appeal. SeaMonkey is a bit too niche for that, and as @alerque mentioned there's also concerns around developer momentum.

**Comment by Hillside502** [comment]
18 in Instant Messaging --- quantity over quality?

**Comment by strugee** [comment]
@Hillside502 as I said in https://github.com/nylira/prism-break/issues/561#issuecomment-373068935, the IM section probably needs to be cut anyway. Please keep things on topic.

**Comment by Hillside502** [comment]
Alright, keep your hair on!
