### ISSUE TITLE
New browser addons

### ISSUE THREAD

**Issue by alex-fischer-70** [nylira/prism-break#577]
Hello together,
the browser addon section could get more content. In my opinion the following addons are practical:
CookieMonster: To block cookies.
RefControl: Block the HTTP referrer
Certificate Patrol: My favorite addon, it compares the SSL certificate with this one of your last visit

Especially Certificate Patrol seems to be a very nice tool to protect you against man-in-the-middle attacks. So I think this is an addon which must be really added.

**Comment by yegortimoshenko** [comment]
All addons suggested in this issue have not been updated to Firefox Quantum (57+). Safe to close
