### ISSUE TITLE
Some more MTAs (mail transfer agents)

### ISSUE THREAD

**Issue by neelchauhan** [nylira/prism-break#614]
Your prism-break.org website is good, but I think there are some things to add. In the mail transfer agents section, some alternatives to Postfix and Exim include Qmail, OpenSMTPD, and Sendmail, although my personal email server runs Postfix (I wanted to go with Postfix if you were wondering why). Qmail isn't maintained anymore, but the other two are.

**Comment by strugee** [comment]
Unless someone can demonstrate why Qmail, OpenSMTPD, or sendmail can offer privacy features Exim or Postfix can't, I'd be inclined to close this.

**Comment by alerque** [comment]
Nope. Those are pretty much your best bet at this point for running your own MTA — _caveat emptor_ email is unfixable.

**Comment by strugee** [comment]
Sounds good.

**Comment by hasufell** [comment]
I don't know about Exim, but if you compare the state of postfix source code vs sendmail, you'll see a huge difference in terms of documentation.
