### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by duub** [nylira/prism-break#63]
How can RSS appear to be promoted as a way to stay informed, seems that there are interest to make it disappear, in the benefit of the use of surveillance social networks

**Comment by jau88** [comment]
Can this be reopened please? Times have changed...

**Comment by strugee** [comment]
We already list several RSS projects on the site. https://prism-break.org/en/protocols/rss/

**Comment by beerisgood** [comment]
The list is more focused in Email clients.
Why not add stuff like TinyTinyRss?

**Comment by Hillside502** [comment]
Open Source Tiny Tiny RSS Alternatives - AlternativeTo.net
https://alternativeto.net/software/tiny-tiny-rss/?license=opensource

**Comment by strugee** [comment]
@beerisgood we don't generally create new categories without a compelling reason. Are there existing, popular hosted RSS solutions that are potentially part of dragnet surveillance programs? Or in other words, stuff we'd need to put in the Proprietary column?

**Comment by Hillside502** [comment]
> Are there existing, popular **hosted** RSS solutions that are potentially part of dragnet surveillance programs?

Feedly
https://en.wikipedia.org/wiki/Feedly

Inoreader
https://en.wikipedia.org/wiki/Inoreader

Flipboard
https://en.wikipedia.org/wiki/Flipboard

and many others

**Comment by Zegnat** [comment]
I don’t think @strugee was doubting the abundance of hosted solutions, only in how far these are affecting people’s privacy and are cooperating in surveillance. I personally do not remember reading about any such cases. As we’ve often said, PRISM Break’s goal isn’t to list self-hostable or open-source alternatives for all software.

**Comment by Hillside502** [comment]
It's pretty obvious that the likes of Feedly know what is subscribed to, what, when and where a post is read and "feeds" all this into the conglomerate data banquet that is:-

Surveillance capitalism - Wikipedia
https://en.wikipedia.org/wiki/Surveillance_capitalism
