### ISSUE TITLE
Newebe, cozy cloud et Open-UDC

### ISSUE THREAD

**Issue by Thatoo** [nylira/prism-break#661]
Bonjour,

Merci pour ce bon catalogue d'alternative éthique.
Je vous propose une modeste contribution.
Dans les alternatives de réseaux sociaux, vous pouvez ajouter newebe (http://newebe.org/).
Dans les alternatives pour le cloud, vous pouvez ajouter cozy cloud (http://cozycloud.cc/ )
Dans les alternatives pour les transactions en ligne, vous pouvez ajouter Open-UDC (http://www.openudc.org/)

Bien à vous,

Thatoo

**Comment by lukateras** [comment]
Newebe [has not been updated since Sep 2016](https://github.com/gelnior/newebe), http://www.openudc.org is defunct, and we already list [Cozy](https://prism-break.org/en/projects/cozy/). Safe to close.
