### ISSUE TITLE
I recommend "SoftEther VPN"

### ISSUE THREAD

**Issue by gitkitten** [nylira/prism-break#672]
1. Many method to connect
   OpenVPN supports only one method to connect - openvpn.
   Softether(I call it SE) can handle many type - see this:
   http://www.softether.org/4-docs/2-howto/7.Replacements_of_Legacy_VPNs/2.Replacements_of_OpenVPN
2. Setup is SUPER EASY than OpenVPN!
   I get a headache when trying to setup OpenVPN server. This is bulls**t.
   SE has "better performance and easy-configurable GUI-based management tools".
   Many security option, totally easy than OpenVPN.
   http://www.softether.org/1-features/3._Security_and_Reliability
3. Open source.

What do you think?
http://www.softether.org/

for more user-talk:
http://lowendtalk.com/discussion/8783/softether-very-powerful-easy-to-use-multi-protocol-vpn-software
# 

If you're paying for VPN company(such as VPNUK), re-think your privacy.
The VPN company you trust maybe betray you!
http://torrentfreak.com/proxy-sh-vpn-provider-monitored-traffic-to-catch-hacker-130930/

> Most of the traffic is logged as otherwise they would be in a deep shit when customers do something illegal.
> So if you trust their ‘no-logs’ policy, you are just a fool.
> Therefore, if you think using a “VPN provider” will keep you protected and anonymous, forget about it.

Build up your own VPN server.
1. Buy VPS(Virtual Private Server) or use your other computer as VPN server.
2. Install this super-easy-VPN
3. Connect it from your PC, smartphone from other network

**Comment by PacoBell** [comment]
Also, technically, SoftEther's VPN Gate public project logs everything for a couple weeks for censorship blocking reasons (and, apparently, because the Japanese gov't demands it). They have to know their enemy (i.e. GFW) if they hope to combat them. In that sense, they're using the logs like an IDS, much like Proxy.sh was using Wireshark (and even that was an atypical case). The standalone SoftEther server, however, is totally under your control to log or not.

**Comment by lukateras** [comment]
Development is very Windows-centric: for example, every node in aforementioned VPN Gate project is required to run a proprietary Windows-only program. Some other tools are also Windows-only, see: https://www.softether.org

Also, supporting multiple protocols is never a particularly good idea in a security context.
