### ISSUE TITLE
Incorrect statement "However, note that LMDE does not support full disk encryption."

### ISSUE THREAD

**Issue by xray-zebra** [nylira/prism-break#678]
Super work on the prism-break.org website. Really excellent project well done.

Small modification I would like to propose, currently there is the following statement on the website: "However, note that LMDE does not support full disk encryption." 

This is incorrect, the mint installer as of mint 15 does support FDE in the installer. 
References: http://forums.linuxmint.com/viewtopic.php?f=90&t=138423
http://www.linuxbsdos.com/2013/06/29/linux-mint-15-cinnamon-review/

Thoughts?

**Comment by strugee** [comment]
Closing as LMDE isn't even on the site anymore.
