### ISSUE TITLE
Add Addon: Secret Agent / RefControl

### ISSUE THREAD

**Issue by gitkitten** [nylira/prism-break#689]
https://www.dephormation.org.uk/?page=81 ... randomize UA and Headers
http://www.stardrifter.org/refcontrol/ ... Block or modify Referrer

Works great on FF24.
Scramble your queries :)

**Comment by lukateras** [comment]
RefControl has been proposed in #577. It is not supported by Firefox 57+ and has not been updated since 2011.

Secret Agent has last been updated in 2016 and is not supported by new Firefox versions.

Safe to close.
