### ISSUE TITLE
Add Ghost in media publishing category

### ISSUE THREAD

**Issue by prodigeni** [nylira/prism-break#691]
Ghost is a platform dedicated to one thing: Publishing. It's beautifully designed, completely customisable and completely Open Source. Ghost allows you to write and publish your own blog, giving you the tools to make it easy and even fun to do. It's simple, elegant, and designed so that you can spend less time messing with making your blog work - and more time blogging.

**Comment by strugee** [comment]
I'd like to close this. The Media Publishing category is pretty full and I don't think we need this. Any objections?

(Also as a _completely_ unrelated side note I got here while looking up my oldest comment in this repository, to determine when I started contributing - what a wild ride it's been. And what a pleasure and an honor to work with you all.)
