### ISSUE TITLE
Providing an picker

### ISSUE THREAD

**Issue by prodigeni** [nylira/prism-break#693]
It would be better if instead of providing a list, a picker was provided. It would suit better with the guided tour and an OS/distro picker would be good for the beginning.
examples are:
http://tuxradar.com/content/distro-picker-0
http://www.zegeniestudios.net/ldc/
http://distrogue.awardspace.com/

**Comment by lukateras** [comment]
Most links seem to be down. The general problem with this is that if we were to adopt this, we would lose control over what distributions we recommend. Also, that would support a misguided notion that a desktop environment or even the package update frequency is inherently coupled with specific distributions (it's not, say Debian can be used as a rolling release distribution).
