### ISSUE TITLE
Add InterTwinkles in Document collaboration category 

### ISSUE THREAD

**Issue by curiousjohn** [nylira/prism-break#695]
https://github.com/yourcelf/intertwinkles

**Comment by yegortimoshenko** [comment]
From https://intertwinkles.org/:

>  InterTwinkles has shut down.
>
> Thanks everyone for making it a fun experiment in online decision making! If you're looking for other friendly free tools for groups, I recommend: Loomio, Sandstorm

Has not been updated since 2014 (2016 update is a shutdown notice): https://github.com/yourcelf/intertwinkles/commits/master

Safe to close.
