### ISSUE TITLE
Add grml as live image and admin tool.

### ISSUE THREAD

**Issue by prodigeni** [nylira/prism-break#702]
It's pretty usefull and a life saver:
grml.org

**Comment by strugee** [comment]
Any objections to closing this? grml, AFAIK, doesn't add any privacy features and the OS section is crowded already.

**Comment by alerque** [comment]
Agreed. Just because it's a useful tool to have in a toolkit as an IT admin doesn't mean it fits on the site. In this case it doesn't really target any of the problems we're trying to solve.

**Comment by strugee** [comment]
If anyone objects comment and I'll reopen.
