### ISSUE TITLE
ADD WebRTC Copy

### ISSUE THREAD

**Issue by AlexandreHagen** [nylira/prism-break#708]
https://rtccopy.com is WebRTC based (http://www.webrtc.org)

**Comment by yegortimoshenko** [comment]
> rtccopy.com uses an invalid security certificate. The certificate expired on February 24, 2017, 6:40 PM. The current time is March 6, 2018, 12:03 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Safe to close.
