### ISSUE TITLE
add Pixi.me to Media publishing > Free alternatives

### ISSUE THREAD

**Issue by negimaki** [nylira/prism-break#711]
I would to request if https://pixi.me/ can be added under Media publishing > Free alternatives. We use FreeBSD, Gallery and Apache as our hosting platform on our own dedicated box. Please advise. thank you!

Best regards,

Steve

**Comment by yegortimoshenko** [comment]
http://pixi.me now redirects to Piximedia, which is a site in French that appears to advertise a proprietary iOS app.
