### ISSUE TITLE
Anti virus section

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#727]
Any thoughts about a anti virus section?

Most anti virus software are commercial. So some of them could deliver not only definition updates for anti virus, but also deliver backdoor "viruses" for NSA and co.

ClamAV (for an example) is a libre anti virus software.

**Comment by Atavic** [comment]
ClamAV runs on all major systems and has plugins for scanning emails attachements, too.

**Comment by Hillside502** [comment]
Also (Linux only):-

ClamTk
https://dave-theunsub.github.io/clamtk/
https://github.com/dave-theunsub/clamtk
