### ISSUE TITLE
Paranoid Andriod

### ISSUE THREAD

**Issue by truecrime** [nylira/prism-break#730]
Paranoid Android is an alternative to Cynogenmod and stock Android

**Comment by lukateras** [comment]
Paranoid Android comes with proprietary blobs that run on the main CPU. For example, here is a list of blobs in device tree for Nexus 5: https://github.com/AOSPA/android_device_lge_hammerhead/blob/nougat-mr2/proprietary-blobs.txt

That means it's no better than LineageOS (or its predecessor, CyanogenMod).

**Comment by alerque** [comment]
I don't see what the advantage would be in including this. If we were trying to be a directory of all projects then sure, but Lineage seems to have several advantages over Paranoid. First the device list is longer and the developer roster a lot bigger, so scrutiny on the code is a lot better. Second there are some privacy focused additions to Lineage that I do not see in Paranoid. Actually besides the name I don't see any documented privacy measures over and above AOSP. Until such a time as somebody comes up with an argument for _why_ this should be included and details what it offers in the privacy department that is better than our current suggestions I think this issue can be closed.

**Comment by strugee** [comment]
Agreed.

**Comment by yegortimoshenko** [comment]
Closing this because it's less active than LineageOS and has no significant advantages over it. That seems to be the consensus (@alerque, @strugee).
