### ISSUE TITLE
Archive/back-up service [feature request]

### ISSUE THREAD

**Issue by craibuc** [nylira/prism-break#742]
Secure alternatives to:
- backblaze.com
- carbonite.com
- crashplan.com
- livedrive.com
- mozy.com
- safesync.com

**Comment by lukateras** [comment]
All services proposed in the OP are proprietary,

I've extracted S4 to #1954, and also proposed borg in #1966. There is also Deja Dup that has great UI, but unfortunately uses duplicity as its backend (which is quite flawed), and there is duplicacy which is nonfree.
