### ISSUE TITLE
What are your rules for listing a product as an "alternative"? [question]

### ISSUE THREAD

**Issue by craibuc** [nylira/prism-break#743]
I didn't see a formal definition (here or at prism-break.org).  

I'm guessing that some or all of the following apply:
- encrypted data, when applicable; minimum bit-rate?  allowed/disallowed cyphers?
- encrypted transmission; what is the minimum standard?
- open-source software
- acceptable payment methods; what are they?
- server logs; why is this relevant?
- non-US based?  if the software is open source and the data is encrypted (during storage and transmission), doesn't this negate the location issue?
- service provider's email server is open source; what is acceptable?  do you have issues with other types of server software?  
- free software; i would be OK with paid software as long as it complies with the other rules

Perhaps one way to visualize this is to list the 'ideal' inclusion criterion for each section, then show a table of how each vendor's project matches the criterion; think feature-comparison matrix.

**Comment by yegortimoshenko** [comment]
Merged into #1967.
