### ISSUE TITLE
Add PeerBlock, Acrylic DNS Proxy

### ISSUE THREAD

**Issue by makaronye** [nylira/prism-break#757]
For windows users.

PeerBlock - to block bad IPs easily. Block Microsoft IPs, Facebook IPs, and Google IPs.
Acrylic DNS Proxy - to block/filter your DNS query. You can use this software like this.

127.0.0.1 (A)google(A) (A)microsoft(A)
127.0.0.1 (A).mscdn.net
127.0.0.1 (A)yahoo(A)

^ this sample prevent user from connecting to www.yahoo.com, etc.

// replace (A) to ASTERISK.

**Comment by Atavic** [comment]
PB is useful and can be applied on different scenarios, not only for a PC dedicated to torrenting.
Regarding the false sense of security, PB improves security but isn't 100% secure like almost everything. 
A project similar to [Acrylic DNS](https://sourceforge.net/projects/acrylic/) but cross-platform is [Unbound](http://unbound.net/) or [MaraDNS](http://maradns.samiam.org/index.html)/[Deadwood](https://github.com/samboy/MaraDNS/).
