### ISSUE TITLE
Add Lsyncd

### ISSUE THREAD

**Issue by sgtpep** [nylira/prism-break#780]
Sidenote: I tried to add it by myself, but the process became too complicated (you should keep on your head all site structure) and time-consuming (very long compilation times). I desided to post the request for adding Lsyncd as an issue.

Name: Lsyncd (Live Syncing Daemon)
URL: https://code.google.com/p/lsyncd/
Category: File Storage & Sync
OS: Linux / OS X
Description: Lsyncd watches a local directory trees event monitor interface, aggregates and combines events for a few seconds and then spawns one (or more) process(es) to synchronize the changes.

**Comment by yegortimoshenko** [comment]
New source code repository: https://github.com/axkibe/lsyncd

**Comment by lukateras** [comment]
I think the current recommendations are more approachable. Recommending lsyncd would be a lot like recommending rsync. Against inclusion on that basis.

**Comment by yegortimoshenko** [comment]
We've recently dropped Profanity based on CLI interface, so this would apply here as well: https://github.com/nylira/prism-break/issues/1926

**Comment by lukateras** [comment]
It seems to be relatively established that CLIs are less preferable. That said, I wouldn't mind a CLI tool that is significantly better than GUI tools (common among backup software).

For file sync, we already list Syncthing. We might want to list sync software that doesn't require trusting some of the peers with access to data (e.g. Gridsync for Tahoe-LAFS).
