### ISSUE TITLE
Information lost with new design

### ISSUE THREAD

**Issue by DavidCWGA** [nylira/prism-break#786]
With particular reference to the list of Linux distributions, the old design used to contain better descriptions of the difference between the choices, such as "Most cutting edge" or "Most stable".

The new design lacks this, containing only generic descriptions of the distributions that all say pretty much the same thing, as they seem to come from the distributions themselves.

Finally, I think there are too many options shown by default. The old design used to show only the "main" choices by default, with a "show all" checkbox to show the less common options. This has gone, but I think it should come back.

**Comment by yegortimoshenko** [comment]
This has been fixed in fda77425f32438c24832fda71ffbd8aed16e65f3.
