### ISSUE TITLE
Ring (formerly SFLphone)

### ISSUE THREAD

**Issue by xeverse** [nylira/prism-break#808]
ZRTP enabled softphone for GNU platform..

**Comment by mimi89999** [comment]
It's licensed under GPL v3 as stated here: https://ring.cx/en/documentation/about-ring

**Comment by mimi89999** [comment]
https://projects.savoirfairelinux.com/projects/ring/wiki/How_to_build In "How to build" you can find git repos for each part of the app.

**Comment by strixaluco** [comment]
By the way, Ring has recently [got beta status](https://blog.savoirfairelinux.com/en/2016/ring-beta/).

**Comment by juanito003** [comment]
@xeverse Ring does not use ZRTP anymore. It's SRTP with openDHT.

It would be great to add it to the list in Video & Voice.
