### ISSUE TITLE
coreboot instead of UEFI / BIOS

### ISSUE THREAD

**Issue by juergenhecht** [nylira/prism-break#842]
coreboot is a Free Software project aimed at replacing the proprietary firmware UEFI or BIOS found in most computers.
http://www.coreboot.org/Welcome_to_coreboot

coreboot currently supports over 230 different mainboards.
http://www.coreboot.org/Supported_Motherboards

100% Free Software (GPL), no royalties, no license fees!
Fast boot times (500 milliseconds to verified Linux kernel)
http://www.coreboot.org/Benefits

coreboot presentation at the 25th Chaos Communication Congress (25C3)
https://www.youtube.com/watch?v=e3mkOW3mTRU

coreboot - Interview - How coreboot could replace traditional BIOS
https://www.youtube.com/watch?v=HKdLhbmjrDI

**Comment by pkubaj** [comment]
You should also add Libreboot. It's a completely free derivative of Coreboot: http://libreboot.org/
