### ISSUE TITLE
Hospitality networks

### ISSUE THREAD

**Issue by Remigr** [nylira/prism-break#847]
I was thinking that it could be great to have a "hospitality networks" category.
Bewelcome.org is an open source alternative to Couchsurfing. Bewelcome is non-profit, couchsurfing is a company and not really cool with your data : https://en.wikipedia.org/wiki/Couchsurfing#Criticism
There is also Hackercouch github.com/jancborchardt/hackercouch
I don't think there are p2p alternative for hospitality network, but that's a start.
What do you think ?

**Comment by yegortimoshenko** [comment]
Hospitality networks are clearly out of scope.
