### ISSUE TITLE
privatesearch.net

### ISSUE THREAD

**Issue by weakish** [nylira/prism-break#851]
[privatesearch](http://privatesearch.net/) a google search proxy

> Privacy Policy
> 1. No logging. Access to our server is not logged
> 2. IP Addresses. No IP Addresses are recorded. Ever
> 3. No search keywords are recorded
> 4. No identifying cookies
> 5. Governmental requests. Will be answered but since we do not log, there is nothing we could provide
> 6. Highest privacy standards.
> 
> Owner and operator of privatesearch.net is Link64 GmbH, Karlsruhe.  
> (info@privatesearch.net)

**Comment by lukateras** [comment]
This does not work anymore. Probably due to some Google redesign.
