### ISSUE TITLE
GentleGPG

### ISSUE THREAD

**Issue by lasseter** [nylira/prism-break#863]
GentleGPG

A gpg text encryption program that uses drag and drop to easily encrypt test for email clients and text programs.

http://gentlegpg.sourceforge.net

**Comment by strugee** [comment]
Any objections to closing this? As @Zegnat says anyone using GPG probably should just use an integration for their email client

**Comment by alerque** [comment]
Yes, integrated clients are what we should be recommending in this case. Also this doesn't appear to be an active project any more.
