### ISSUE TITLE
Add Posteo.de - E-Mail provider

### ISSUE THREAD

**Issue by benskie** [nylira/prism-break#865]
Offers:

*anonymous accounts

*payment via Paypal, bank transfer, cash - Transactions aren't matched with accounts [You'll add a code (for example GhJK7) and they'll match it, after this is done the code will be destroyed]

*full site HTTPS, actually HSTS

*encrypted HDD's for their E-Mail storage

*encrypted calender/address book

*no logging of IP's; IP-Stripping

*2 free Alias adresses

*servers hosted in Germany, very decent privacy laws.

It's 1€/month ($1,36/month) and I think it's well worth it.

https://posteo.de

**Comment by feinstaub** [comment]
> The issue with Posteo was also that they develop proprietary software for their web interface, so there isn't much difference to GMail and others. MyKolab on the other hand as an explicit and exclusive "Free Software Only" policy and is developing the web interface that many companies, Posteo included, use.

I requested an update from posteo.de on the unfree software issue and got this response:

```
Unser Angebot setzt aus Sicherheitsgründen ausschließlich auf
Open-Source-Software und freie Protokolle. Auch verwenden wir
ausschließlich Javascript, dessen Code Open-Source ist und das den
Richtlinien der Free Software Foundation entspricht:
<https://www.fsf.org/blogs/community/fsf-javascript-guidelines-picked-up-by-posteo-webmail>

Wir unterstützen Ende-zu-Ende-Verschlüsselung vollwertig im Webmailer
mit dem Opensource-Addon Mailvelope:
<https://posteo.de/en/blog/new-posteo-webmail-interface-can-find-public-keys>

U.a. dazu entwickeln wir Opensource-Software, die wir unter freien
Lizenzen auf Github zur Verfügung stellen:
<https://github.com/posteo>

Posteo ermöglicht außerdem eine vollständig anonyme Anmeldung und
Bezahlung. Siehe u.a. hier:
<https://posteo.de/en/site/payment>
```

Most notable is the referenced FSF blog post https://www.fsf.org/blogs/community/fsf-javascript-guidelines-picked-up-by-posteo-webmail (2015-02), where the new achievements are praised: 

"They have also done everything possible to ensure that it is 100% compatible with the GNU LibreJS browser extension, which automatically blocks any potentially nonfree JavaScript, making it easy to browse the Web in freedom. This is an outstanding effort in defense of the freedom of Posteo's users, and the company deserves recognition for it. We hope others will follow their lead."
