### ISSUE TITLE
Add LUTIm ?

### ISSUE THREAD

**Issue by ldidry** [nylira/prism-break#875]
You could add [LUTIm](https://github.com/ldidry/lutim) in GNU Linux/ Media Publishing

It's a free (as in free speech) and anonymous image hosting system. You can see it at http://lut.im

**Comment by lukateras** [comment]
[Up1](https://github.com/Upload/Up1) seems to be a way better option, with client-side encryption (Lutim encrypts server-side, like AWS S3). Lutim can be trivially modified to retain a user's encryption key without them noticing, while with Up1 one would have to change the JS served to the user, which involves much more risk.

Besides that, Up1 can be used for all kinds of files, while Lutim only supports images.

And Up1 goes into detail what crypto they use and comes with a long list of useful caveats (some of which also apply to Lutim). I don't see any flaws with cryptography used by Up1. 

Lutim uses a fixed [IV](https://en.wikipedia.org/wiki/Initialization_vector) in CBC mode which makes encryption predictable: https://github.com/ldidry/lutim/blob/a69e0df68d920a733555979ec4dd4de3d7d0fbe3/lib/Lutim.pm#L239

Here is an explanation of why this should not be done: https://crypto.stackexchange.com/a/3885

Also, it uses an unauthenticated encryption mode (CBC), which allows to modify cypher text without knowing the corresponding plain text. GCM would have been a better pick. See: https://crypto.stackexchange.com/a/50622

Also, AES would be a more up-to-date pick than Blowfish.

I think this issue along with #1124 should be closed.

**Comment by ldidry** [comment]
Up1 and Lutim can't be compared, their purposes are not the same: one is for sharing files, the other is to host images (which can be used on a website, and that's why the encryption is done server-side, otherwise you couldn't use them as `img` source without adding javascript). I wrote another software, [Lufi](https://framagit.org/luc/lufi) (demo [here](https://demo.lufi.io/)) to share files with client-side encryption.

Thank you for the crypto advices, I'll change that.

**Comment by lukateras** [comment]
> Up1 and Lutim can't be compared, their purposes are not the same: one is for sharing files, the other is to host images [...]

I understand, but it appears that the value such encryption provides (over just encrypting the file system) is limited: if the server gets compromised, and a file is accessed once again afterwards, the attacker would be able to decrypt it. It's not possible to tell whether the server is compromised or not.
