### ISSUE TITLE
Add mailbox.org to Email Alternatives

### ISSUE THREAD

**Issue by VincentvdE** [nylira/prism-break#878]
https://mailbox.org/

**Comment by baimafeima** [comment]
@cr1pt0 Could you explain that a bit further? 

I think mailbox.org is an excellent choice both from a security and privacy perspective. 
- https://mailbox.org/en/guiding-principles/
- https://mailbox.org/en/security-privacy-at-mailbox-org/

From their website: 

> - Anonymous registration
> - No ads and no passing on of user data to third parties
> - Payment via bank transfer, PayPal, Bitcoin, cash by mail (EUR only, no cheques), direct payment on account
> - Transparent data retention and deletion deadlines for log files and connection data
> - Aliases and temporary e-mail addresses
> - Certified information security officer

**Comment by yegortimoshenko** [comment]
Proprietary groupware. We already list Kolab Now which is much better from privacy/security/freedom perspective.
