### ISSUE TITLE
Add Peersm (anonymous P2P inside browsers) in Anonymizing Networks

### ISSUE THREAD

**Issue by Ayms** [nylira/prism-break#883]
Peersm is a new P2P network inside browsers, no installation, anonymous and secure, please check out http://www.peersm.com, the project is live and can be used.

As a matter of fact, if you change the place of the 'r' in the name you get Prism, it's contrary.

Peersm is trying to mix the different concepts of Tor, I2P, Freenet and P2P projects, and latest web technologies so the application is inside your browser and data are distributed inside browsers (+ optional Peersm clients).

It is extending the Tor protocol to P2P and using the Tor and Peersm nodes, but it is not Tor.

The browsers are talking this protocol and connecting to the nodes using WebSockets.

The final goal is to build a complete serverless P2P where anonymizer nodes are inside the browsers too relaying the traffic, using WebRTC techno.

The code is here: https://github.com/Ayms/node-Tor/tree/master/min and https://github.com/Ayms/node-Tor/tree/master/install

But minified and not open source for now, after discussion with @nylira it appears it should be open source to be on prism-break

The counter argument would be that in our case the code is inside browsers, then completely transparent, it's not difficult for a js dev to deminify it and/or see what it is doing.

We find it even more transparent than some open source projects, does someone check that the code is the same when it gets packaged? No. Is it easier to read? Not really, I don't know if someone has ever looked at the Tor code for example...

We think people desserve to know it exists and we are asking if it can be added on prism-break.org

**Comment by lukateras** [comment]
Proprietary; also hasn't been updated in 4 years.
