### ISSUE TITLE
Add TextSecure to Secure Instant Messengers

### ISSUE THREAD

**Issue by SecUpwN** [nylira/prism-break#896]
First of all: The search function for Issues that have already been covered on GitHub is crappy as hell. That being said, let's continue with my suggestion to add the awesome [TextSecure](https://github.com/WhisperSystems/TextSecure/), licensed under GPL v3.

### Da fuq?
If you've been living under a rock until now: "TextSecure provides a robust encrypted instant messaging and text messaging solution on Android. It is intended to be used in place of the standard text messaging application. TextSecure users can exchange encrypted messages, media and attachments. TextSecure encrypts both the message database on the user's device and all messages that are sent to other TextSecure users." To be honest, I wonder why TextSecure has not been added to [Prism Break](https://prism-break.org) yet?

### Also interesting to know:
A secure text messaging application for Android (perfect replacement for WhatsApp):

TextSecure is a replacement for the standard text messaging application and WhatsApp, allowing you to send and receive text messages as normal. Additionally, TextSecure provides:

1. Local Encryption -- All text messages, regardless of destination, that are sent or received with TextSecure are stored in an encrypted database on your phone.

2. Wire Encryption -- When communicating with a recipient who is also using TextSecure, text messages are encrypted during transmission.

### Cool! Where to get the good stuff?
* [GooglePlay](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms)
* [Official TextSecure GitHub](https://github.com/WhisperSystems/TextSecure/)
* [Open WhisperSystems](https://whispersystems.org) (more fun stuff to check out)

**Comment by attackvector** [comment]
Great work @SecUpwN!

**Comment by Sigmun** [comment]
Up, I use it a lot and promote it also to my friends and family, am I doing well ?

**Comment by SecUpwN** [comment]
>Up, I use it a lot and promote it also to my friends and family, am I doing well ?

In fact, you're not up to date. `TextSecure` has been merged into [Signal](https://github.com/WhisperSystems/Signal-Android), which removes offline SMS encryption. The fork with continued offline SMS encryption is [SMSSecure](https://github.com/SMSSecure/SMSSecure). And if you'd like to stay with the main project, I recommend using the GCM-free version with websocket support [LibreSignal](http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging/). Cheers!

**Comment by Sigmun** [comment]
In fact, i am necessarily up to date because I am using an iPhone (so I have no choice but to use Signal). @SecUpwN What are your recommendations for that device ?

Also, WhatsApp adopts OpenWhisper right now. Does it mean it become trustable ?

**Comment by strugee** [comment]
@Sigmun WhatsApp adopting the Signal Protocol has nothing to do with this discussion. Neither Signal nor WhatsApp are now more trustable because of this. (WhatsApp is marginally more trustable, but not nearly enough for PRISM Break to change its stance.)
