### ISSUE TITLE
Add OpenKM

### ISSUE THREAD

**Issue by oLux** [nylira/prism-break#897]
Dear All,

Please consider OpenKM as a document management system. Compared to the other packages under "File Storage & Sync" it has the advantage of OCR full text extraction, indexing and search for a variety of document formats including office documents and pdf. Packages such as ownCloud only name that as a future feature while remaining limited to full text indexing and search for a limited set of document formats only, e. g., just plaintext and pdf documents. In my view, advanced search capabilities including both office documents and scanned documnts are an important prerequisite for effective document (rather than file) management. OpenKM can help to achieve this without using prorietary cloud services. Thus, it should be more suitable for the office, small and medium enterprise, knowledge worker and science communities than some of the other packages already listed. The project genesis as described in the wikipedia article also looks credible and adequate.

Regards

oLux

  {
    "description": "Document management system.",
    "license_url": "http://www.openkm.com/en/community.html",
    "logo": "openkm.png",
    "notes": "",
    "privacy_url": "",
    "source_url": "svn checkout svn://svn.code.sf.net/p/openkm/code/trunk openkm-code",
    "name": "OpenKM",
    "tos_url": "",
    "url": "http://openkm.com/",
    "wikipedia_url": "https://en.wikipedia.org/wiki/OpenKM",
    "protocols": [
      "SSL/TLS",
      "WebDAV"
    ],
    "categories": [
      {
        "name": "Servers",
        "subcategories": [
          "File Storage & Sync"
        ]
      }
    ],
    "slug": "openKM"
  },

![openkm](https://f.cloud.github.com/assets/6894461/2376197/b7d52aa6-a873-11e3-97fe-c9bbd17fba6d.png)

**Comment by yegortimoshenko** [comment]
Open core enterprise document management system, I don't think that is something that would make sense listing here (it doesn't fit "File Storage & Sync").

**Comment by yegortimoshenko** [comment]
Labeling as "waiting for objections" because it's open core enterprise software, not designed for personal use.
