### ISSUE TITLE
Add Google Now and Siri as proprietary intelligent assistants

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#898]
AFAICT, there are no FLOSS alternatives to these. This might also include whatever is shipped with Windows Phone, which IIRC has something to do with Bing.

**Comment by strugee** [comment]
Since there are actually alternatives that we're actively discussing right now (see #1889) if someone comes along and picks this up, we should probably just add a new category since https://github.com/nylira/prism-break/issues/898#issuecomment-40301460 doesn't really apply anymore.

**Comment by RoseTheFlower** [comment]
Shouldn't Cortana also be on the list?

**Comment by strugee** [comment]
👍

**Comment by cyanotex** [comment]
Don't forget Alexa too. AFAIK, Amazon isn't gonna let anyone peek into the code.

**Comment by Hillside502** [comment]
Alexa is partially open-source, but not enough to call it so:-
https://github.com/alexa/
