### ISSUE TITLE
Suggest OMNIrom instead of Cyanogenmod?

### ISSUE THREAD

**Issue by wolftune** [nylira/prism-break#903]
Apparently Cyanogenmod is going toward proprietary stuff and various people are suggesting OMNIrom as the next best option to Replicant.

**Comment by lukateras** [comment]
Not up-to-date (unlike LineageOS) and has as many blobs as LineageOS:

https://github.com/omnirom/android_device_samsung_i9300/blob/android-5.1/proprietary-files.txt
https://github.com/LineageOS/android_device_samsung_i9300/blob/cm-14.1/proprietary-files.txt

If we are going to tolerate blobs running on the main CPU, LineageOS would undoubtedly be a much better pick.

**Comment by strugee** [comment]
Yeah, this issue predates LineageOS by many years. I don't see the point in keeping it around now.
