### ISSUE TITLE
Suggestion: PryNotes.com

### ISSUE THREAD

**Issue by derek3x** [nylira/prism-break#929]
PryNotes.com as an alternative to EverNote.

Opensource: https://github.com/derek3x/PryNotes

(I am the author)

Pros:
-The website is opensource
-The notes are all encrypted (server side with rotating keys and padding)
-The user has an option to password encrypt their notes.  This will encrypt their notes and they will need to use the password to decrypt them.  The server does not store the password, so without the user we can not decrypt the note.  We then encrypt the password using the keys again.  
-SSL
-Server itself requires two phase rotating key authentication
-OpenID login (google, stackexchange, yahoo, launchpad, flickr)

Cons:
-Currently hosted in United States for speed reasons.  

I believe it would be a good fit for your site.  I honestly use prism break and have since near the inception.  I made prynotes.com as an alternative for myself so my data would not be sold out.  I have made it public for everyone now.

This site offers encryption, and allows users to organize and share notes.  You can download notes as pdfs, and offers a lot of other features that the other secure encrypted note websites do not.  Mainly the organizing of your notes and being able to switch freely between your notes.  There is currently an app on the firefox marketplace to use on firefox os and android if you have firefox installed.

**Comment by lukateras** [comment]
The site is dead, the certificate has expired two years ago: https://prynotes.com

Safe to close.

**Comment by strugee** [comment]
Plus the Productivity section already has a lot of solid options.

**Comment by Hillside502** [comment]
> Certificate:
Validity
            Not Before: Apr 16 23:29:19 2014 GMT
            Not After : Apr 16 23:29:19 2015 GMT

https://www.shodan.io/host/192.241.239.221
