### ISSUE TITLE
Pidgin actually support GPG through plugin

### ISSUE THREAD

**Issue by noway** [nylira/prism-break#933]
Here's plugin for that: https://github.com/segler-alex/Pidgin-GPG
It make available XEP-0027 support.
Not tested myself, but at least it compiling and loading via pidgin.

**Comment by yegortimoshenko** [comment]
This can be closed, as we don't list Pidgin anymore.

**Comment by noway** [comment]
why though

**Comment by strugee** [comment]
Why don't we list Pidgin anymore? See #1653, #1847
