### ISSUE TITLE
Ansible / sovereign open source cloud storage

### ISSUE THREAD

**Issue by annonman** [nylira/prism-break#934]
Has anyone ever heard of these? 

Looks really good.

http://www.ansible.com/home
-half the install offered via Yum
-free for 10 computers - open source

https://github.com/al3x/sovereign
-extends the above

"Sovereign is a set of Ansible playbooks that you can use to build and maintain your own personal cloud (I know I know). It’s based entirely on open source software, so you’re in control."

**Comment by lukateras** [comment]
Out of scope.
