### ISSUE TITLE
New open source alternative to BitTorrent Sync called Syncthing

### ISSUE THREAD

**Issue by CGBBlackburn** [nylira/prism-break#937]
http://syncthing.net/ website
https://github.com/calmh/syncthing Github

" Syncthing replaces Dropbox and BitTorrent Sync with something open, trustworthy and decentralized. Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet.

Using syncthing, that control is returned to you."

This is a full blown open source alternative to BitTorrent Sync

**Comment by juh2** [comment]
+1 for adding. In my private setup it is rock solid.

**Comment by ThomasWaldmann** [comment]
+1 for adding.
