### ISSUE TITLE
Software Development Section

### ISSUE THREAD

**Issue by x19161511** [nylira/prism-break#942]
Right now we have a good list of software that is already developed, but we don't have any place to develop new software options. Some of what we need is only partially developed and needs more work before it would be accepted on a large enough scale to "make mass surveillance of populations uneconomical." Not everything has an approved alternative yet. There will eventually be new threats that we do not have a way to fix yet.

I suggest adding links to organizations that help develop the kind of software we want. It might also be good for prism-break to become such a place, to expand its role from reporting on technologies to developing them.

**Comment by vyp** [comment]
I feel this issue can be closed now that we have an "experimental" label as @strugee says.
