### ISSUE TITLE
Openwatch.net

### ISSUE THREAD

**Issue by theGuruWithin** [nylira/prism-break#944]
Does anyone have any thoughts about this Community App that Surveilles the Surveillance State #Corruptocracy as they violate human, constitutional and universal rights?

https://openwatch.net/about/

IMHO this is what we need with more support to bring Truth2Power!

I hope i am posting this properly since i am new to this community.  Please instruct if I have committed a faux pas

ty prism-break - I love this community! Another world is possible but it is up to open source, community & love for each other Om Mani Padme Hum

In Gratitude
@theGuruWithin

**Comment by yegortimoshenko** [comment]
Link is defunct, seemingly domain has a new owner. Safe to close.
