### ISSUE TITLE
Suggestion: Seafile as file storage and sync tool

### ISSUE THREAD

**Issue by stenogriz** [nylira/prism-break#945]
Seafile (http://seafile.com/) can be suggested as an open source dropbox alternative in "File Storage & Sync" section. Community edition is opensourced and can be installed on the private server. Great advantage is an official andriod app for Seafile.

**Comment by pietsch** [comment]
I believe there was a mistake. The Seafile community edition is Free Software, full stop. It is not crippleware compared to the enterprise edition. Please add it to the list.
