### ISSUE TITLE
New Alternative Email Protocol: Freemail

### ISSUE THREAD

**Issue by rodneyrod** [nylira/prism-break#958]
https://freenetproject.org/freemail.html

Freemail uses the Freenet network to distribute mail between users in a secure fashion with a user's existing email client.

It could be listed as an alternative to email.

**Comment by yegortimoshenko** [comment]
Hasn't been active since 2015: https://github.com/freenet/plugin-Freemail/commits/master

Link is defunct. Safe to close.
