### ISSUE TITLE
Suggestion: Keybase - simplified GPG discovery and use

### ISSUE THREAD

**Issue by alebcay** [nylira/prism-break#959]
[Keybase](http://keybase.io) is an online service that allows people to associate GPG keys with existing Twitter and GitHub accounts. Others can then search for your online profile, find your public key, and use it.

Pros:
- Easy (but a little less secure) setup for beginners - makes key for you in-browser with client-side Javascript
- Advanced setup for experienced users - generate keys offline, and upload public keys
- Command line client (open source)!

```
npm install -g keybase-installer
```
- Tracking feature - allows people to publicly sign and affirm others' identities, and then be notified if their key changes
- Proof system - procedures in place to prove ownership of a domain, website, Twitter, or GitHub accounts

Cons:
- AFAIK, the actual website is closed-source
- By default, the in-browser setup stores an encrypted version of your private key on server for decrypting and signing - the user can manually opt out, but users can then only decrypt and sign messages offline.
- Currently in closed alpha, with a pretty long waiting list (14000 or so), but invites available

**Comment by respel** [comment]
It has a pretty bad privacy policy though.

> Information collected automatically:
> 
> Usage Information. When you access or use the Service, we automatically collect and store information about your browsing habits and your use of the Service (“Usage Information”), including:
> 
>     a. Your computer’s IP address
>     b. Your preferences and settings (time zone, language, privacy preferences, application preferences, etc.)
>     c. The URL of the site that referred you to the Service
>     d. The buttons and controls you clicked on (if any) within the Service
>     e. How long you used the Service and which parts and features you used
>     f. Session times and lengths
> 
> Logs of this information may persist for an indefinite period.

**Comment by yegortimoshenko** [comment]
Website is proprietary, privacy policy is still as bad as mentioned before, service exclusively supports other proprietary services that we're trying to replace (Facebook, GitHub, Reddit, Twitter), these services are relied upon to prove identity which is ultimately broken, and reliance upon this service would significantly weaken web of trust which is the only state adversary proof way to prove someone's identity, and additionally the only truly decentralized way.

I ask to apply "waiting for objections" based on unfriendly privacy policy and lack of source code for the backend and frontend (the latter includes non-trivial compressed JavaScript without source code).

**Comment by jinformatique** [comment]
@yegortimoshenko @respel yes privacy policy is that bad. In the meantime, is there any better recommandation that have all the advantages of keybase?

**Comment by yegortimoshenko** [comment]
Keybase doesn't have any advantages over web of trust, only disadvantages. It's literally not any better than posting something signed by your key here, and in several other places. Just ask someone you casually know to sign your key, if you can't meet, do so with low level of trust.

**Comment by Hillside502** [comment]
Open Source Keybase Alternatives - AlternativeTo.net
https://alternativeto.net/software/keybase/?license=opensource
