### ISSUE TITLE
Android -> Droidwall

### ISSUE THREAD

**Issue by TheCherry** [nylira/prism-break#963]
Have found that awesome Android APP:
https://play.google.com/store/apps/details?id=com.googlecode.droidwall.free&hl=de
source is avarible too: https://code.google.com/p/droidwall/

Its a very simple and nice Firewall, now I did forbid any google service to internet, ahjo! :)

**Comment by yegortimoshenko** [comment]
The application is not maintained anymore, safe to close.

For reference: https://github.com/chr4/droidwall

> A fork of the latest GPL version of droidwall (v1.5.7). The original owner and creator Rodrigo Rosauro sold droidwall to AVAST in december 2011.

**Comment by strugee** [comment]
Agreed.
