### ISSUE TITLE
Firefox plugins for video downloading?

### ISSUE THREAD

**Issue by vitruvianjew** [nylira/prism-break#967]
What is known about the various firefox plugins for video downloading?  Are there any open source plugins?  If there are, please add info on these plugins to this section:

https://prism-break.org/en/subcategories/gnu-linux-web-browser-addons

This is relevant, I think, because the NSA does track your porn browsing habits so this information can be used against you later.

**Comment by yegortimoshenko** [comment]
I agree with @Zegnat, video download addons are not privacy-related.
