### ISSUE TITLE
more programs

### ISSUE THREAD

**Issue by blackhold** [nylira/prism-break#976]
instant messaging: irssi, qwebirc, ircd, bittlebee
irc: irssi, qwebirc, ircd
mail: zimbra, zarafa
mesh: libremesh
editing: inkscape, gimp, scribus
email clients: mutt
audio players: mocp
media publishing: archive.org, dmdb (giss.tv)
streaming: adtlantida.tv, giss.tv, gstreamer, vlc (under development)
office: libreoffice

**Comment by nodiscc** [comment]
@Zegnat @nylira I think this can be closed. @blackhold has not responded since 1 May 2014. Please let me know if you need help maintaining the issue tracker, I'll be glad to help.
