### ISSUE TITLE
Self-destruct mail

### ISSUE THREAD

**Issue by purezza** [nylira/prism-break#980]
I read about trashmail in another issue, so what about a similar mail service: self-destructing email?
As far as I found there are:
 https://oneshar.es/
 http://email.about.com/od/anonymousemailservices/gr/will_self_destr.htm http://www.destructingmessage.com/

**Comment by yegortimoshenko** [comment]
Agree with @strugee, this should be closed. All proposed services are either proprietary or defunct.
