### ISSUE TITLE
Linux Mint Debian Edition removed?

### ISSUE THREAD

**Issue by radiorapido** [nylira/prism-break#982]
Just noticed that LMDE seems not to be on the list of recommended operating systems.

I am just wondering why this might have been removed.

I currently use Linux Mint Maya MATE edition, but was thinking of moving to LMDE... now I'm confused.

thanks in advance

**Comment by yegortimoshenko** [comment]
Closing as duplicate of #805 (see f66bfb6cdd3904ce51ba0bf28d3f0255838e8286).
