### ISSUE TITLE
Add Sipdroid

### ISSUE THREAD

**Issue by Oxeda** [nylira/prism-break#990]
https://code.google.com/p/sipdroid/

It's a simple, light and open-source VoIP android application that supports audio and video calls.

**Comment by yegortimoshenko** [comment]
New site: http://sipdroid.org/

**Comment by Hillside502** [comment]
Source
https://github.com/i-p-tel/sipdroid

**Comment by yegortimoshenko** [comment]
I don't see the point, considering that new Android versions have a built-in SIP client.

**Comment by Oxeda** [comment]
This request is so old I had to recover my password to reply, 2014 wow back then the privacy war had hope, not anymore it seems.

**Comment by yegortimoshenko** [comment]
We're doing pretty good :-)

**Comment by yegortimoshenko** [comment]
Closing, because release hasn't been updated since forever (2013) and SIP client is integrated into Android itself.
