### ISSUE TITLE
Adblock Edge BSD Doesn't work

### ISSUE THREAD

**Issue by zennix** [nylira/prism-break#994]
Firefox's addons site states that Adblock Edge can't be installed for my operating system. I have tested this on FreeBSD and OpenBSD. I currently use Adblock Plus, with the "Allow Unobtrusive Advertising" unchecked, on BSD systems.

**Comment by yegortimoshenko** [comment]
This is a support ticket for software that we don't list (at least, not anymore). Safe to close.
